### ISSUE TITLE
CLAHub

### ISSUE THREAD

**Issue by dmodoomsirius** [cla-assistant/cla-assistant#100]
Is there a away to import users who have singed a cla from CLA hub over git cla-assistant?

**Comment by thojansen** [comment]
In CLAHub you can download the **users who have signed** as a csv file and then upload it again in CLA assistant. Note however that only the GitHub username is imported.

<img width="1014" alt="screen shot 2016-02-13 at 12 57 05" src="https://cloud.githubusercontent.com/assets/5912220/13027462/9532c512-d251-11e5-8541-d455a91b9473.png">
