### ISSUE TITLE
Share a single cla for all projects in an organization

### ISSUE THREAD

**Issue by niemyjski** [cla-assistant/cla-assistant#101]
We have like 15 open source projects under a single organization and we'd like to share a single cla link.. Is this possible?

**Comment by thojansen** [comment]
Any contributor needs to sign the CLA per repository, but you can use the same CLA stored as a gist file for all repositories.

**Comment by niemyjski** [comment]
but I don't want it per repository, I want the database to be per github organization. It's kind of redundant to have them sign the same exact cla for every project esp in a micro service era...

**Comment by thojansen** [comment]
understood.. then this should be the same as #66

**Comment by gollogly** [comment]
I was just wondering if there is the capability for a user only to sign the cla once for a repository and not each time a PR needs to be contributed. (how does this work so once the sign on the first pull request, it is remembered for future PRS ?)

I wasn't clear from the comments and looking at the main web site. This was my only reservation and the tools looks very useful to me.

**Comment by KharitonOff** [comment]
please see #107
