### ISSUE TITLE
CLA Assistant Unlinked -- All Data Missing

### ISSUE THREAD

**Issue by prestonvanloon** [cla-assistant/cla-assistant#1011]
## URL to the linked Repository or Organization

https://github.com/prysmaticlabs/prysm

## Steps to reproduce the problem

1. Wake up one day (I'm not sure when this started)
2. Hear reports that CLA Assistant is no longer linked with the Prysm project
3. Log into cla-assistant.io, no data is present. The branch protection checks for CLA assistant are gone in Github.

## What is the expected result?

CLA assistant is linked to the prysm project with hundreds of contributors previously signed.

## What happens instead?

Nothing is there :(

## Any other information? (attach screenshot if possible)

![Screenshot from 2023-07-24 09-46-50](https://github.com/cla-assistant/cla-assistant/assets/7246818/696729cd-c71f-4ac2-b637-e9513cc05973)

## Used browser and browser version?

Chrome

**Comment by prestonvanloon** [comment]
Here's a link to a CLA assistant comment from a PR: https://github.com/prysmaticlabs/prysm/pull/11698#issuecomment-1329253188

Clicking the CLA button shows an error of "Bad credentials"

![Screenshot from 2023-07-24 09-54-09](https://github.com/cla-assistant/cla-assistant/assets/7246818/8b7da4e7-9ce8-4bea-9fcb-059400582943)

**Comment by prestonvanloon** [comment]
@Shegox Thank you!!! That resolved my problem. Is there anything we could do to prevent this from happening again or receive notification that it has become unlinked? We just happened to notice that it wasn't a requirement one day, but not sure how long it has been broken.

**Comment by Shegox** [comment]
At the moment not really, however a colleague is currently working on adding better support for GitHub App based authentification, which will make the authentification independent of an user account/permissions. 

In addition to more quickly notice this, would be making the CLA-check a "[required status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)". This way you would see directly when it fails and ensures that you can't merge a PR without a CLA-check.
