### ISSUE TITLE
Recheck PRs doesn't check all pull requests

### ISSUE THREAD

**Issue by JeromSar** [cla-assistant/cla-assistant#102]
Hello,

Thanks for providing CLA assistant to the public for free. I found it incredibly handy.

The recheck PR feature is incredibly handy for repositories where the CLA is added afterwards, but it does not check all PRs, as can be seen in this picture:

![TotalFreedom Repository](https://www.screenshottr.us/v/00f0353f4b2ac52411e9f9aedb2d3981/577cc43d0766d0d8e5129617eb37b02e.png)

**Comment by KharitonOff** [comment]
Is this issue already solved for you? I couldn't find any open PR without status from CLA assistant in your repo...

**Comment by JeromSar** [comment]
@KharitonOff I accidentally deleted a branch which the PRs in question were based on, thus closing those PRs. By reopening the PRs one by one, cla-assistant was triggered and the status appears again.

As far as I am aware, this is still a bug.

**Comment by JeromSar** [comment]
@KharitonOff Thanks for the fix! :)
