### ISSUE TITLE
Status: webhook missing

### ISSUE THREAD

**Issue by urbanhusky** [cla-assistant/cla-assistant#103]
I'm trying to set up cla-assistant for our BudgetFirst/BudgetFirst organisational repository. 
After linking it and approving access, the status shows ok for gist, but not okay for webhook. I also don't think that the integration works properly.

What am I missing?

**Comment by KharitonOff** [comment]
I assume you heave push rights for this repo and you are one of the owners in this organisation, aren't you? Could you check the repo settings please, whether the webhook for CLA assistant was set and it is inactive or it wasn't set at all?

You could also try to remove and re-add your repo in CLA assistant.

**Comment by urbanhusky** [comment]
Okay, my mistake was that I used another account purely for managing that and that account was not also an owner. So this doesn't work if you don't have owner privileges?

**Comment by KharitonOff** [comment]
Yes, CLA assistant needs certain rights, e.g. to create a webhook. If a user isn't allowed to do it on its own, he/she can't provide this right to CLA assistant.
As I understand it works for you now and I may close this issue, if not feel free to reopen it :)
