### ISSUE TITLE
Contributors report signing CLA multiple times and CLA dashboard is blank

### ISSUE THREAD

**Issue by mc-hamster** [cla-assistant/cla-assistant#1035]
Hi,

We have had a report of contributors signing the CLA multiple times and the CLA Assistant not recording the digital signature. When I logged into to the CLA Assistant dashboard, the dashboard comes up blank.

<img width="1038" alt="image" src="https://github.com/cla-assistant/cla-assistant/assets/12804989/5af02f95-161a-447c-92fb-350ffa794007">

Additionally, I am unable to view the list of signed CLAs. That also comes up blank.

Looking for help here.

Thanks!

**Comment by mc-hamster** [comment]
There should be about a dozen repos on that list.

**Comment by OpenSource-For-Freedom** [comment]
Yes, as above we are supporting this mission and need access. One other and I are on standby, thank you.

**Comment by Shegox** [comment]
@mc-hamster please excuse the super long wait. 

I had today some time to check it and I couldn't find any CLAs configured with with https://github.com/mc-hamster

- Could it be that your user was previously called something else? Did you rename it?
- Can you link me a repository where you have enabled CLA-Assistant?

**Comment by mc-hamster** [comment]
> @mc-hamster please excuse the super long wait.
> 
> I had today some time to check it and I couldn't find any CLAs configured with with https://github.com/mc-hamster
> 
> * Could it be that your user was previously called something else? Did you rename it?
> * Can you link me a repository where you have enabled CLA-Assistant?

Thank you so much for replying!

I have enabled cla assistant in most of the repos on the meshtastic project, here's one:

https://github.com/meshtastic/firmware

Here's a screen shot of the configuration from 5/12/2022. We did rename some of the repos at some point.

![image](https://github.com/cla-assistant/cla-assistant/assets/12804989/055ff960-a8e3-4ecc-b59d-37bd6a7a96ea)

**Comment by Shegox** [comment]
Okay, so it is about the repositories in the `meshtastic` organization, right? 

The good news is that I'm able to confirm, that indeed the repositories and config still exist. The weird thing is why you can't see them. 

Are you a GitHub organization owner of the `meshtastic` and can you check if `CLA assistant` has third-party access rights under https://github.com/organizations/meshtastic/settings/oauth_application_policy ?

**Comment by mc-hamster** [comment]
Looks like CLA Assistant is no longer there.

<img width="1298" alt="image" src="https://github.com/cla-assistant/cla-assistant/assets/12804989/a53b1219-59bc-462c-a4b9-f4e816a6b0fa">

**Comment by Shegox** [comment]
Can you try granting CLA Assistant access again via https://github.com/orgs/meshtastic/policies/applications/160438 and then try logging into CLA-Assistant again?

**Comment by mc-hamster** [comment]
Yes! It works again! Thank you so much for the assistance!!!

Are there any indicators of how the integration stopped working?

<img width="935" alt="image" src="https://github.com/cla-assistant/cla-assistant/assets/12804989/4d913533-d4e5-4f94-b605-1474192cc745">

**Comment by Shegox** [comment]
I don't have a clear reason why, but I could imagine that either:
- somebody removed the third-party authorization from the CLA-Assistant app in your organization
- somebody enabled third-party authorization alltogether and it wasn't enabled previously and forgot to add the CLA-Assistant app.

**Comment by mc-hamster** [comment]
> I don't have a clear reason why, but I could imagine that either:
> 
> * somebody removed the third-party authorization from the CLA-Assistant app in your organization
> * somebody enabled third-party authorization alltogether and it wasn't enabled previously and forgot to add the CLA-Assistant app.

MMMmmmm... I'll remind the team to keep it in place.

Thanks for the help mate!

Cheers!
