### ISSUE TITLE
Problems with the port on Cloud Foundry

### ISSUE THREAD

**Issue by mpierre0220** [cla-assistant/cla-assistant#104]
I am trying to test cla-assistant deployed on Cloud Foundry. Clound Foundry apps listen to a port that is set up automatically for you but but in accessing the app's URL you don't use that port. Seems like Cloud foundry router does the magic for you.

In setting by app's credentials for Cla-assistant on Github, at first I did not use that port, did not think of that. But I did provide that port to the Cla-assistant app in the environment. Cloud foundry supplies the port in environment variable VCAP_APP_PORT. App.js will listen on that port too. Because I did not supply that port to Github, when Githud calls the callback url, the Cla-assistant application will fail the call with error AuthorizationError: The redirect_uri MUST match the registered callback URL for this application. 

I debugged this to strategy.js where the callback URL is parsed and I saw that the port is being used and the Github URL did not have a port. When I use the port in the Github URL, the calls times out. 

Indeed the Cloud Foundry does not expect the port to be used in the URLs. So when I modify the http object in confi.js not to use a port (I comment port out)
     http: {
            protocol: process.env.PROTOCOL || 'http',
            host: process.env.HOST || 'cla-assistant.io',
            //port: process.env.HOST_PORT
        },
when I login now, the callback works but I don't get the cla-assistant user interface to go process the CLA documents. Instead I get this:

Hey, {{ user.value.login }}!
 
Then I get an icon to logout.

Can someone help me figure out what is going here, please?

**Comment by KharitonOff** [comment]
skipping the HOST_PORT variable was the right decision if you have no port in the destination url (you can also just unset HOST_PORT env. variable, no need to comment it out).
Regarding the second problem: could you check/provide the browser console output, please.

**Comment by mpierre0220** [comment]
Thanks for your quick reply.

Regarding the port, I have uncommented config.js and did not set the environment variable HOST_PORT
For the 2nd problem, here is the screenshot of my browser ... ![cla-mgr](https://cloud.githubusercontent.com/assets/6641778/13575352/781cc83a-e456-11e5-81dc-0d524c9b5d99.PNG)

Here is the screenshot of the console

![console](https://cloud.githubusercontent.com/assets/6641778/13576074/d32ac4b8-e459-11e5-8d62-49a79eb19042.png)

On my local machine app.min.js resides on src/client/app.min.js while on the remote machine the file resides on Scripts/app.min.js, I don't know if they're the same.

Here is the content of the file on the remote machine 

<!DOCTYPE html>
<html>

<head>
  <title>CLA assistant</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base href="/">
  
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-animate.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-route.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.13/angular-ui-router.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.4/ui-bootstrap-tpls.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-select/0.11.2/select.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-utils/0.1.1/angular-ui-utils.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-sanitize.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-scroll/0.6.5/angular-scroll.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/ng-csv/0.3.3/ng-csv.min.js"></script>
  <script src="//www.google-analytics.com/analytics.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angulartics/0.17.2/angulartics.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angulartics/0.17.2/angulartics-ga.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/PapaParse/4.1.2/papaparse.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.5/clipboard.min.js"></script>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  </script>
  
  <script src="app.min.js"></script>

  
  

  
  <link href="//cdnjs.cloudflare.com/ajax/libs/angular-ui-select/0.11.2/select.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/css/selectize.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="//cdnjs.cloudflare.com/ajax/libs/octicons/2.0.2/octicons.min.css" rel="stylesheet">

  
  <link href="/assets/styles/app.css" rel="stylesheet">
</head>

<body>


  <div id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-home-left">
            <div ng-show="!!user.value.login">
              <a ng-href="{{user.value.html_url}}" target="spcae">
                <img ng-src="{{ user.value.avatar_url }}" style="height:25px;" />
                <a class="navbar-text-hide">&nbsp; Hey, <b>{{ user.value.login }}</b>!</a>
              </a>
            </div>
        </div>
        <div class="nav navbar-home-right">
            <a ng-hide="!user.value.login" href="/logout" target="_self" class="octicon octicon-sign-out" style="font-size:19px" tooltip-placement="left"
            tooltip="Sign out"></a>
        </div>
        <div class="navbar-center" style="">
            <a href="/">
              <img class="center-block img-responsive" src="/assets/images/logo_b.svg" style="width:55px;">
            </a>
        </div>
    </div>
  </div>

  <div class="container-fluid" style="margin-bottom:50px;">
    <div style="margin-left:15px; margin-right: 15px">
        <section ui-view class="col-md-8 col-md-offset-2"></section>
    </div>
  </div>

  <div class="navbar navbar-default navbar-fixed-bottom">
      <div class="navbar-top-border">
          <div class="container-fluid">
               <div class="navbar-text navbar-left">
                  <p style="margin-bottom:0px">© 2015 SAP SE</p>
              </div>
              <div class="navbar-text navbar-center" style="z-index:-1;">
                <p class="hidden-xs hidden-sm" style="margin-bottom: 0px;">
                  Made with <span class="octicon octicon-heart"></span> from the GitHub team at SAP
                </p>
              </div>
              <div class="center-block">
                <div class="navbar-text navbar-right">
                  <a href="https://github.com/cla-assistant/cla-assistant/issues/new" target="space">
                    <span class="octicon octicon-mark-github"></span> Open an issue
                  </a>
                </div>
              </div>
              <div class="center-block">
                <div class="navbar-text navbar-right">
                  <a href="https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30" target="space" style="margin-right: 10px">
                    Terms of Service &amp Privacy Policy
                  </a>
                </div>
              </div>
          </div>
      </div>
  </div>
</body>

</html>

**Comment by mpierre0220** [comment]
Github did process the file that I cut and pasted above. Here is the zipped version of the same

[app.min.zip](https://github.com/cla-assistant/cla-assistant/files/161709/app.min.zip)

**Comment by KharitonOff** [comment]
ok, probably you missed the build step. Could you run ` ./node_modules/grunt-cli/bin/grunt build` on your server or run the build task on your local machine and push all sources to CF (that should also work). 
The build step minifies and uglifies the client code. The server should have the src/client/app.min.js

**Comment by mpierre0220** [comment]
Yeah, I have been building and pushing stuff to the server....in setting up the environment variables you have to restage...perhaps that restaging has erased the built files on the server. I have pushed again and it is working now. Thanks for your help.

**Comment by mpierre0220** [comment]
Closing the issue.
