### ISSUE TITLE
CLA bot doesn't appear and status is stuck on "Expected — Waiting for status to be reported"

### ISSUE THREAD

**Issue by aytey** [cla-assistant/cla-assistant#1052]
## URL to the linked Repository or Organization

https://github.com/microsoft/ifc/pull/64

## Steps to reproduce the problem

1. Opened-up PR against https://github.com/microsoft/ifc/pull/64
2. CLA bot doesn't appear
3. Sadness

## What is the expected result?

1. CLA bot to appear and to allow me sign

## What happens instead?

1. Nothing, CLA bot doesn't appear and the status in the action is "Expected — Waiting for status to be reported"

## Any other information? (attach screenshot if possible)

I *possibly* signed the CLA for [https://github.com/Z3Prover/z3](https://github.com/Z3Prover/z3) (which is a Microsoft CLA); however, if I did this, it would have been before:

1. I changed my legal name (Andrew V. Jones -> Andrew V. Teylu)
2. I changed my email (I actually don't know which email I signed the CLA with; I may have even signed it with the email before the company I was working for got acquired)
3. I changed my GitHub user-name ([andrewvaughanj](https://github.com/andrewvaughanj) -> [aytey](https://github.com/aytey))

**Comment by KharitonOff** [comment]
@aytey microsoft/ifc doesn't use CLA assistant for their PRs. Looking at the PR https://github.com/microsoft/ifc/pull/52 it seems that they use another GitHub App: https://github.com/apps/microsoft-github-policy-service.

**Comment by aytey** [comment]
Haha, oops!
