### ISSUE TITLE
Does the CLA need to be signed per PR if already accepted for a repo

### ISSUE THREAD

**Issue by martingollogly** [cla-assistant/cla-assistant#107]
I have seen other issues related to this #66 but was just wondering if there is the capability for a user only to sign the cla once for a repository and **not each time a PR needs to be contributed**. (how does this work so once they sign the agreement on the first pull request, it is remembered for future PRS for the user?)

I wasn't clear from the comments and looking at the main web site. This was my only reservation as it could be more intrusive, apart from that this tools looks very useful to me.

**Comment by KharitonOff** [comment]
Sorry for the unclear description. CLA assistant comments only once in the first PR of a user who hasn't signed a CLA yet. If the user signs the given CLA all his further PRs get only the green status from CLA assistant but no comments anymore (as long the linked CLA remains the same).

**Comment by gollogly** [comment]
Excellent, thanks for this

Martin
