### ISSUE TITLE
Add contributors to GitHub team

### ISSUE THREAD

**Issue by jenlampton** [cla-assistant/cla-assistant#108]
This is a fantastic tool, thanks for building it (and giving it back!).

I wonder if there is interest from anyone else to add support for adding people to organizations after signing a CLA?

**Comment by thojansen** [comment]
I like the idea. We could even evaluate the option to only use a GitHub team to track people having signed the CLA (although this conflicts with another requirement to store more information on users like their E-Mail address). I think the fact that we currently store this in our database is not ideal (and most likely the reason why a few have opted to setup their own instance). Would love to get some more feedback on this.

**Comment by KharitonOff** [comment]
Interesting Idea.
But in this case we won't be able to determine the version of signed CLA.

**Comment by thojansen** [comment]
I have just added https://probot.github.io/apps/invite-contributors/ for this repo. Seems to be reasonable to do this as a separate app, therefore closing this right now.
