### ISSUE TITLE
CLA won't check off for esp-extra-components PR #432

### ISSUE THREAD

**Issue by Teesmo** [cla-assistant/cla-assistant#1084]
I tried contributing to the esp-extra-components repository, but my changes won't be effected because the CLA I signed won't check off. The guys at espressif tell me I signed in with an incomplete email "xxxx@gmail.**co**", which does not match with my github email "xxxx@gmail.**com** ". How do I fix that? 
The PR link is [here](https://github.com/espressif/idf-extra-components/pull/432#issue-2592041870)

**Comment by KharitonOff** [comment]
@Teesmo the easiest way to solve the issue, is to add the "wrong" email address to your GitHub Profile https://github.com/settings/emails  and click the "recheck" link in the CLA assistant's comment on your PR

**Comment by Teesmo** [comment]
Thanks, it worked.
