### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by UniquePixels** [cla-assistant/cla-assistant#1086]
What is the status of this project?  Is it still being supported and maintained?

I really like the system, but before I start using it in my orgs repos I need to make sure I am not setting up something that is going to break and not be fixed.

It is concerning that many of the issues have a response from an individual who says they not longer have access so cant help, but no responses from anyone else.

**Comment by Shegox** [comment]
Hey 👋 

CLA-assistant and cla-assistant.io is still supported and maintained. We also don't have any plan to sunset it and are actively using it ourselves for our open source projects in github.com/SAP. 

There has been a bit lack of active maintainership over the last while, but I hope to have some more time soonish to tackle outstanding issues and perform a few needed improvements.

**Comment by UniquePixels** [comment]
@Shegox Thank you so much for the reply, this is great to hear!
