### ISSUE TITLE
Add a handler for a ping event in web hooks

### ISSUE THREAD

**Issue by brbmi** [cla-assistant/cla-assistant#109]
There needs to be a handler for the ping event in web hooks. It should simply a status of 200. Currently when installing a web hook, it does a ping but since there is not a handler as there is one for the pull request event, file pull_request.js in src/server/webhooks, the call fails. I will do a Pull request for the fix and close this issue.

**Comment by thojansen** [comment]
v1.4 is released now to production with the ping event :shipit:
