### ISSUE TITLE
Option to not require people to sign CLA all over again

### ISSUE THREAD

**Issue by laughinghan** [cla-assistant/cla-assistant#111]
Feature Request: When updating a CLA, be able to mark it as "compatible" with previous versions or something so that contributors who've signed a previous version don't have to all re-sign the new, completely equivalent one.

Rationale: While it makes sense in general that just because a contributor has signed a past version of a CLA, it shouldn't be assumed they agree to the current one too, it's really annoying that the tiniest formatting or typo-fixing edit forces everyone to have to re-sign the CLA.

Ideas:
- The simplest thing to do would be to only invalidate signatures if people unlink and re-link a CLA and a repo, but you probably don't want to do this because you want the default to be to invalidate signatures (also, backwards compatibility).
- The second-simplest thing I can think of is, when linking a CLA to a repo, have an opt-in checkbox that says that updates to the CLA are assumed to be compatible, and to invalidate signatures you have to come here and click a "incompatible update to CLA" button (or unlink and re-link the CLA).
- One fine-grained opt-in idea would be to have a version tag in the CLA (like, a line whose sole contents is "Version 1.0" or whatever): changes to the minor version (or no changes to the version number) are assumed to be compatible, whereas a change to the major version means an incompatible update to the CLA has occurred.
- You probably super don't want to define a version tag format. What if the opt-in checkbox says that updates to the CLA body are assumed to be compatible, but if the filename of the Gist changes, then it's assumed to be incompatible? Then you just put the version number in the Gist filename ("MathQuill_CLA_v1.md") and the body can be updated and it's assumed to be compatible until the filename is updated (to "MathQuill_CLA_v2.md", in this case).

**Comment by KharitonOff** [comment]
Nice Idea :+1: 
Currently you could export and import the list of contributors in case you don't want that your contributors have to sign the new version again. So it is some kind of workaround, but the question is whether it is sufficient for the rare cases of doing minor changes on the linked CLA?

**Comment by thojansen** [comment]
We could offer a button "take over from previous version" which would mimic export/ import. Not a big fan of the implicit behaviours, but it is a very valid request. The other option would be to activate new versions in CLA assistant (and not take the latest gist) explicitly (with some options). Any other thoughts?

**Comment by laughinghan** [comment]
> Currently you could export and import the list of contributors in case you don't want that your contributors have to sign the new version again.

I didn't think of that, useful workaround, I will go do that.

> The other option would be to activate new versions in CLA assistant (and not take the latest gist) explicitly (with some options).

Oh! I like that.

**Comment by torkelo** [comment]
so I did a minor change to the CLA, and now seems to have lost all the previous signatories, how can I get them back, export / import them?

**Comment by OozmaKappa** [comment]
you can view the list of signers (by clicking on the number, probably "0") and select the previous version of the CLA in the popup

**Comment by KharitonOff** [comment]
you can view the list of signers (by clicking on the number, probably "0") and select the previous version of the CLA in the popup

**Comment by torkelo** [comment]
@OozmaKappa thanks!
