### ISSUE TITLE
Loading indicator while loading your "Linked CLAs"

### ISSUE THREAD

**Issue by laughinghan** [cla-assistant/cla-assistant#112]
The first few times I was def worried that you'd lost all my CLAs

![image](https://cloud.githubusercontent.com/assets/225809/13888375/5ee37d40-ecfe-11e5-9319-2094c20886c5.png)

(Note: I really appreciate this service you're providing, I'll probably try to submit a PR for this)

**Comment by thojansen** [comment]
@laughinghan thanks for your valuable feedback. Please let us know in case you need any help to get this PR done.
