### ISSUE TITLE
Status not updated after adopting commit email

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#113]
There seems to be some issue which happened in this PR:
https://github.com/SAP/openui5/pull/874

As far as I understand, it was like this:
- Opened PR with a commit author email which is not liked to user account
- Signed CLA (user is showing up the list with date of PR)
- Amend commit to change mail
- Status is still "not signed yet" even after running "Recheck PRs"

Might be related to #102 (regarding "Recheck PRs")

**Comment by kfitzpatrick** [comment]
I believe I'm still having the same issue ref: #114

**Comment by KharitonOff** [comment]
indeed it seems to be related to #102 and thus fixed.
