### ISSUE TITLE
"not signed yet." when I've clicked the link multiple times

### ISSUE THREAD

**Issue by kfitzpatrick** [cla-assistant/cla-assistant#114]
For https://github.com/grafana/grafana/pull/4675

I suspect there was an issue because the original commit may have had the wrong email address. I've since fixed the commit, but I still get the error message.

**Comment by maniankara** [comment]
Same here. In my case, I used two different email address when I did my commits. Tried:
 - Adding the email to github account, still "not signed yet" 
 - Modified the commit's email with `rebase`, same, no luck.

**Comment by KharitonOff** [comment]
CLA assistant needs to be triggered after you change the author of the commit. It happens normally via pull request webhook (e.g. if you do a further commit on the PR). The repository owner can also trigger it manually by pushing the "Recheck PRs" button in CLA assistant. 
Unfortunately we had some problems with this "recheck"-functionality (see #102 ). But now it should be fixed.
