### ISSUE TITLE
as collaborator, signing the CLA does not get tracked

### ISSUE THREAD

**Issue by wmark** [cla-assistant/cla-assistant#116]
I am a collaborator with https://github.com/mholt/caddy. I have signed the CLA for a PR, and then for the entire project and I still cannot push to *master* due to:

```
$ git push mholt master

# …
remote: error: Required status check "licence/cla" is expected
To git@github.com:mholt/caddy.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:mholt/caddy.git'
```

I suspect that this is due to me being collaborator number 75 (due to paging?) and/or **cla-assistant** not having copied me to its database.

My expectation is that my *git pushes* don't get rejected by *status check "licence/cla"*.

**Comment by KharitonOff** [comment]
this issue seems not to be related to CLA assistant but to the GitHub feature "protected branches"
https://help.github.com/articles/about-protected-branches/ 
It looks for me like you have no push rights for master yet... could it be the reason?

**Comment by thojansen** [comment]
CLA assistant only sets a status on commits of PRs. Even if we would set the status on commits of a given branch (e.g. like travis), you could only push to a protected branch once that commit was already pushed to another branch and the status has passed.

**Comment by wmark** [comment]
Thanks for looking into this!
