### ISSUE TITLE
Do not present CLA form if consent is already granted

### ISSUE THREAD

**Issue by mmoayyed** [cla-assistant/cla-assistant#120]
I have:

- Logged into Github. Signed in.
- Have already accepted the CLA for a given project

If I then browse to: https://cla-assistant.io/org/projectname I am presented with the CLA form again. This should not happen, as I have already done so. Some form of confirmation would be better to indicate there is nothing to be done.

**Comment by thojansen** [comment]
We are now showing the signed CLA without the sign button as part of v1.4 which is released now to production :shipit: 🎉 .

**Comment by mmoayyed** [comment]
Excellent
