### ISSUE TITLE
Sign the agreement (multiple times) but project says it still is not signed

### ISSUE THREAD

**Issue by rstradling** [cla-assistant/cla-assistant#123]
https://github.com/ensime/ensime-sbt/pull/212 is the pull request where I am trying to sign the CLA.  It comes up.  I say sign it.  It says thank your for signing and now will take you back to github.  It still has that I have not signed it (and this is after multiple refreshes of the UI)

**Comment by KharitonOff** [comment]
the reason is that you have signed the CLA as @rstradling but commits are done by @ryanstradling - these are two different users 😉  
So, as soon you as @ryanstradling sign the CLA it will set the status of the PR to green.
