### ISSUE TITLE
licence/cla — Waiting for status to be reported (https://github.com/PBSPro/pbspro/pull/68)

### ISSUE THREAD

**Issue by subhasisb** [cla-assistant/cla-assistant#124]
For a pull request we have on our repository: https://github.com/PBSPro/pbspro/pull/68 the contributor has actually signed the CLA, but still the status check is showing as waiting for status. Am not able to merge the PR since this is mandatory status check.

Do you know whats wrong? And how I can fix this and go ahead.

**Comment by KharitonOff** [comment]
You can "recheck" the PR of your repository by pushing the "Recheck PRs" button in CLA assistant
<img width="498" alt="bildschirmfoto 2016-06-21 um 20 27 37" src="https://cloud.githubusercontent.com/assets/8480657/16241722/4c2cef10-37ef-11e6-89c3-9264e325548d.png">

**Comment by subhasisb** [comment]
Thanks - it worked. Closing the ticket
