### ISSUE TITLE
CLA-Assistant not detecting full github name with dash in it

### ISSUE THREAD

**Issue by phantom-voltage** [cla-assistant/cla-assistant#128]
I tried to sign a CLA from the cla-assistant in the Emby Repository. It's not detecting my full username with the dash.

https://github.com/MediaBrowser/Emby/pull/1918

**Comment by JNKielmann** [comment]
Hello phantom-voltage,
thank you very much for reporting this issue.
I do not think the problem you are having is related to the dash in your name. The commit in your pull request is actually not linked to your github account.
https://github.com/MediaBrowser/Emby/pull/1918/commits 
(Notice it only shows "phantom" as committer and your profile picture is not shown.)
To fix this you can add the email address, which you used for the commit (phantom@blackbullet.lan), to your github account( Settings -> Emails -> Add email address ) or change the email address you use to your github mail. ( git config --global user.email "your_email@example.com" )


Nevertheless, we should check if it is possible to avoid this issue somehow.
