### ISSUE TITLE
cla-assistant does not find one of my repositories

### ISSUE THREAD

**Issue by cvogt** [cla-assistant/cla-assistant#130]
it does not show xdotai/play-json-extensions for me

**Comment by KharitonOff** [comment]
could you check your rights on this repository, please. You should have "owner" rights there in order to be able to link the repo in CLA assistant.
You can see it in settings of your repository -> Collaborators & teams

**Comment by cvogt** [comment]
@KharitonOff it's an org repository, so I am not the owner, but I am Admin. It's exactly the same as for xdotai/lens and that one can be found and I am using cla-assistant for it. The only difference I know of is that xdotai/play-json-extensions used to be cvogt/play-json-extensions but I moved it to the xdotai org at some point.

**Comment by thojansen** [comment]
Can you check the organisational access in your settings for CLA assistant?

![screen shot 2016-07-13 at 10 32 43](https://cloud.githubusercontent.com/assets/5912220/16796890/3d21103a-48e5-11e6-832e-8c74a8f721ad.png)

**Comment by KharitonOff** [comment]
@cvogt could you go through the steps here https://help.github.com/articles/managing-an-individual-s-access-to-an-organization-repository/ and check your access rights for the repo, please?

**Comment by cvogt** [comment]
@thojansen @KharitonOff Please mind that cla-assistant works fine for me for other repos in that same organization. It needs to be something repository specific, not organization specific. I am not an owner of the organization, but I have Admin rights in all repositories we use cla-assistant for including play-json-extensions for which I fail to use it.

@KharitonOff @thojansen I cannot click "manage access" or check the OAuth settings because I am not an owner. I will ask an owner to check, but I am failing to see how that would help, if other repos in that org work fine.

Sure it's nothing regarding having move the repo previously :)?

**Comment by cvogt** [comment]
@thojansen actually I can see "manage access". Looks all good.

![image](https://cloud.githubusercontent.com/assets/274947/16807083/237b7af8-48e5-11e6-8889-4d1e65abe81e.png)


![image](https://cloud.githubusercontent.com/assets/274947/16807060/0dcb72da-48e5-11e6-857c-d586682583aa.png)

**Comment by KharitonOff** [comment]
@cvogt the point is: CLA assistant uses following GitHub-Api to read your repositories https://developer.github.com/v3/repos/#list-your-repositories and it calls this api with parameter affiliation=owner, organization_member the result of this call is represented in the drop-down list. We use this parameter to sort repos out where the user has not enough rights (e.g. setting web hooks)
You can try to call this api with your user credentials and check whether this repo is in the list or not.
https://api.github.com/user/repos?per_page=100&affiliation=owner,organization_member (if you have more than 100 repos, add parameter page=2 to see next ones).

**Comment by cvogt** [comment]
none of my xdotai/ repositories show up using that api route. Not even the ones I successfully added via cla-assistant. However, they all show through https://api.github.com/user/repos?per_page=100&affiliation=collaborator

**Comment by cvogt** [comment]
Neither of the repositories I added (xdotai/lens xdotai/diff), nor the one I am failing to add (xdotai/play-json-extensions) show up using that api route. Some other unrelated xdotai/* repositories do.

However all the ones I care about (including xdotai/play-json-extensions) show up through https://api.github.com/user/repos?per_page=100&affiliation=collaborator

**Comment by KharitonOff** [comment]
@cvogt could you check this api: https://api.github.com/user/repos?per_page=100&affiliation=owner,organization_member&page=2 , please, whether you can find your repos there (excepting xdotai/play-json-extensions)?
We restrict the afflilation to owner and organization_member in order to select those repos, where the user has enough rights (e.g. setting webhook). Only if the user has this rights he/she can provide CLA assistant with them, otherwise CLA assistant would not work properly...

**Comment by KharitonOff** [comment]
please reopen if you still need some help from our side

**Comment by cvogt** [comment]
@KharitonOff Hi, I'd like to re-open this please. Can't see the button though.

So I finally went through this with github support. 

The repository I would like to use cla-assistant for does not show up in

https://api.github.com/user/repos?per_page=100&affiliation=owner,organization_member 

but it does show in

https://api.github.com/user/repos?per_page=100&affiliation=owner,organization_member&page=3

Github support made me aware of the following header being sent back by the REST server:

```
Link: <https://api.github.com/user/repos?per_page=100&affiliation=owner%2Corganization_member&page=2>; rel="next", <https://api.github.com/user/repos?per_page=100&affiliation=owner%2Corganization_member&page=4>; rel="last"
```

Looking at cla-assistant's source code, I assume the relevant code is here: https://github.com/cla-assistant/cla-assistant/blob/84bc9a206d5034ae175b8a741a908f96143672bf/src/server/services/repo.js#L297

Is this code taking the pagination into account? The maximum number of entries per page are limited to 100 btw.

**Comment by KharitonOff** [comment]
@cvogt ok, very strange :( 
Could you send me the screenshot of all xdotai/* repos from the list (in CLA assistant), please? I would like to compare the GitHub API response with the output of CLA assistant.
We collect data from all pages (here are the relevant code lines: https://github.com/cla-assistant/cla-assistant/blob/master/src/client/controller/home.js#L130 -> https://github.com/cla-assistant/cla-assistant/blob/master/src/client/api.js#L126)

**Comment by cvogt** [comment]
I just tried it again, this time logging out first then logging in and now it shows up. Maybe a caching issue somewhere. Should have tried it before. Thank you in any case :). Sorry for the noise.

**Comment by KharitonOff** [comment]
No problem, glad your problem is solved now 😃
