### ISSUE TITLE
Cannot sign CLA, but I've signed it before and it has worked

### ISSUE THREAD

**Issue by ajpevers** [cla-assistant/cla-assistant#133]
I want to sign the CLA on pull request https://github.com/magento/magento2/pull/5496
and on https://github.com/magento/magento2/pull/5625

I've committed pull requests (https://github.com/magento/magento2/pull/4897) that have signed CLA's with the same github user and the same commit email address.

What's going wrong here?

**Comment by thojansen** [comment]
@KharitonOff It seems that they are running a modified version of CLA assistant and hosting it themselves.

**Comment by ajpevers** [comment]
Okay, so I need to let them fix it?

**Comment by ajpevers** [comment]
And if they would not run a modified version, would it work correctly?

**Comment by KharitonOff** [comment]
We can hardly analyze the problem without access to the system/logs. 
You can ask the repository owner (someone who has admin/owner rights on this repo) to push "Recheck PRs" button in the admin view of the CLA assistant. Maybe that will solve the problem.
