### ISSUE TITLE
Can't link after unlink-ing once

### ISSUE THREAD

**Issue by TamalSaha** [cla-assistant/cla-assistant#134]
Hi,
I created cla link for a repo once. Then deleted the git repo and recreated it under the same organization. Now, I can't create cla links anymore. How do I fix this issue?

Thanks.

**Comment by KharitonOff** [comment]
@TamalSaha could you give me the name of the repository?

**Comment by TamalSaha** [comment]
https://github.com/appscode/data is the repository. I see the name of the repository in the dropdown list. After I click the "Let's go" green button, I see the following animation and nothing happens. I have waited more 5 mins and then closed the tab
![cla-nothin](https://cloud.githubusercontent.com/assets/94814/16862216/c2635efc-49fc-11e6-8874-ef0432a56445.png)
.

**Comment by KharitonOff** [comment]
Could you try it again, please?

**Comment by TamalSaha** [comment]
Thanks @KharitonOff. It worked this time. Did you fix any bug or was this some one-off manual thing?

**Comment by KharitonOff** [comment]
@TamalSaha This was a special, exclusive fix only for you 😏 
We will fix this bug too, but it will take some time... so it would be great if you unlink your repo in CLA assistant first before you delete and recreate it in GitHub 😄

**Comment by TamalSaha** [comment]
:) Thanks for the info. I have another repo in similar situation. I was just testing to make sure it was really a bug. I am going to file another issue if the bug is not fixed by the time we are ready to make it public, again.
