### ISSUE TITLE
Let contributor accept one of several CLAs

### ISSUE THREAD

**Issue by ttmc** [cla-assistant/cla-assistant#136]
This project has the right idea, but before we can use it, we need contributors to be able to choose between accepting our "Individual CLA" (which covers just their contributions) or our "Entity CLA" (which covers everyone in their team/company/organization). See our current CLA page to see what I mean:

https://www.bigchaindb.com/cla/

**Comment by thojansen** [comment]
Right now we do not support _Corporate CLAs_ within the tool. We had some discussions around this topic (see #15) and decided against a tool support for this case. Right now this is rather handled manually and on a case-by-case basis. Having said that, I would suggest that you make it clear in the CLA itself that only individual CLAs are covered (maybe you can even add a custom checkbox in the future to make this more explicit when this functionality is released) and handle corporate CLAs manually. In case you get a list of github usernames from a given company, you can still upload this list in CLA assistant manually to have the same workflow.

There are a couple of reasons for this decision. One is the additional complexity of handling corporate CLAs and the other the process itself. How could you be sure that a given user is authorised to give you a corporate CLA for a given company?
