### ISSUE TITLE
Save also the GitHub id, email and name if provided.

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#137]
Right now I can see that only the username is being saved (or exported) but the username can change and sometimes we need more info.. The only thing that is not changeable is the GitHub `id` and that should be definitely saved and maybe storing the extra things like email and name.

- id
- name
- email

https://api.github.com/users/lipis

**Comment by KharitonOff** [comment]
this issue is related to #64 
we are working on it and we are going to roll out this feature soon 😃 
would you like to test it as soon we are ready?

**Comment by lipis** [comment]
of course..!! that would save the world..

**Comment by thojansen** [comment]
The id field is already supported, but we would like to have the option to mark a custom field as _hidden_ in order to not be able to change it 😄 . Tracking under #143
