### ISSUE TITLE
What is the suggested setup to run cla-assistant on our own instance?

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#140]
We will have to host our own version. What would be the suggested way of achieving this to fulfill most of the following requirements:

- Preferable running on AWS (we could check alternatives, so don't hesitate to suggest if not)
- Minimal effort for setup/maintain/sync with the master project
- Detailed instructions for setting up tools on the suggested platform
- Backup support
- Paid services are not an issue

**Comment by thojansen** [comment]
In general there are not many requirements and AWS should be fine for hosting (we use a cloud foundry based provider for hosting/ might be less effort on your side). Apart from the application, you also need a mongoDB, which we are hosting on mLab (automatic backup, SSL, ..). In terms of the overall stack, the db would be the most important part as the CLAs are stored there. The app just connects to it.

Other than that, maybe you want to create a fork of the `cla-assistant` repo and set up your own deployment pipeline from there. We are using travis to build and test and then `cf push` the application. There is also an option to route log messages to a slack channel (in case you are using it).

Also it would be interesting to know why you need to run your own instance and if there is anything we could change on our side such that you would not need to do it anymore 😄 .

**Comment by lipis** [comment]
Thanks @thojansen!

We are "forced" to run our own instance because of the #141.. if you can change that part we can send a small thank you basket to your offices in Berlin :) It's right next to ours..

**Comment by thojansen** [comment]
Ok, understood. Please let us check if we can change that.

**Comment by thojansen** [comment]
Closing this issue now in favour of changing our TOS, which is tracked under #141. Still waiting for feedback from our colleagues.

**Comment by lipis** [comment]
🏇 🎆 🌾 🌴 👍
