### ISSUE TITLE
Term of Use

### ISSUE THREAD

**Issue by raphaelrobert** [cla-assistant/cla-assistant#141]
We would like to use your service, but unfortunately the Terms of Use are not very user friendly (https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30).

Particularly section 4:
*By transmitting or uploading any Content (defined below) to the Website, You grant to SAP a perpetual, irrevocable, nonexclusive, worldwide, fully paid up and royalty free, unlimited license to use such Content without restrictions of any kind and without any payment or other consideration of any kind, or permission or notification to You or any third party.
The license includes, without limitation, the irrevocable right to reproduce, prepare derivative works, combine with other works, alter, translate, distribute copies, display, perform, license the Content, and all rights therein; to make, have made, offer to sell, sell, lease, or otherwise distribute any Content or product; and to practice any method, embodying such Content (including the right to sublicense any of the foregoing).*

When contributors submit personal information such as name, email, address, phone number, etc. in good faith the information submitted will remain private, these Terms of Use in fact allow SAP SE to publish them (among other things).

Do you have any plans to change this?
It would be great, as CLA assistant is otherwise a great tool.

**Comment by thojansen** [comment]
We have reached out to our legal team to check this. Thanks for mentioning that.

**Comment by bennyn** [comment]
Any update on this?

**Comment by thojansen** [comment]
Not yet.. vacation time.

**Comment by thojansen** [comment]
We have now updated our TOS according to your feedback. We hope that you are now able to use our service.
https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30

**Comment by lipis** [comment]
That's awesome! Thanks @thojansen :) Once we are going to verify it with our legal team.. we'll let you know..
