### ISSUE TITLE
hidden custom fields

### ISSUE THREAD

**Issue by thojansen** [cla-assistant/cla-assistant#143]
Make it possible to create hidden custom fields (e.g. the Github id).

**Comment by mickaelandrieu** [comment]
Hello @thojansen isn't already the case? See https://github.com/cla-assistant/cla-assistant/blob/master/src/client/templates/customField.html#L1

Except if I'm wrong, every HTML5 types can be generated by this directive, so "hidden" fields can already be generated.

Mickaël

**Comment by thojansen** [comment]
@KharitonOff can you check if we can close this and if not provide some points on what is currently missing?

**Comment by mickaelandrieu** [comment]
@thojansen / @KharitonOff , see https://github.com/cla-assistant/cla-assistant/pull/204
