### ISSUE TITLE
Asking people to sign CLA again

### ISSUE THREAD

**Issue by bdarnell** [cla-assistant/cla-assistant#144]
In the last day or two cla-assistant has starting asking people who have already accepted the CLA for cockroachdb/cockroach to sign it again. Users who do so show up a second time in the exported report twice. For example, it says I signed twice on the following days:

    bdarnell    Aug 5, 2016 2:23:54 PM
    bdarnell    Jul 21, 2015 1:26:39 PM

**Comment by KharitonOff** [comment]
@bdarnell sorry for that! We have released v1.4 last Friday and there was a bug. This problem should be solved since Aug 6. Could you check/keep your eyes on it, please.

Thank you very much for reporting this issue!
