### ISSUE TITLE
Linked repositories list is blank (it used to contain ~6 entries)

### ISSUE THREAD

**Issue by tomdee** [cla-assistant/cla-assistant#145]
I use CLA assistant on a number of repos under `projectcalico` org. The list of linked repos has been blanked at some point in the last few weeks and I'm not sure why.

**Comment by KharitonOff** [comment]
Do you see this repositories in the drop down list on the "Create new link" view?
This issue could be related to #130 
Do you have admin rights in this organization?

**Comment by tomdee** [comment]
I think the app had become unauthorized. It's now working OK so closing.
