### ISSUE TITLE
corporate CLAs

### ISSUE THREAD

**Issue by thojansen** [cla-assistant/cla-assistant#15]
Support the notion of Corporate and Individual CLAs. Ensure that a Corporate CLA is in place before presenting individual CLAs for signing. Periodically (or on a per project basis!) validate the affiliation of the individuals with their employers.

**Comment by KharitonOff** [comment]
Comments from Chris:
Support for Corporate CLA.
  - This would require a user to indicate whether they are participating in the project as an individual or on behalf of a corporation (for example, see ubuntu’s process here: http://www.ubuntu.com/legal/contributors/submit.
  - This would also require the system to maintain a CCLA with a list of authorized contributors (with list of GitHub IDs). Some organizations provide the ability to update this list online (see OpenStack https://wiki.openstack.org/wiki/HowToUpdateCorporateCLA) .

**Comment by thojansen** [comment]
As per discussions with legal, CCLA handling will be an exceptional case not covered by our tool.
