### ISSUE TITLE
CLA status shows up as Pending incorrectly

### ISSUE THREAD

**Issue by d4l3k** [cla-assistant/cla-assistant#150]
https://github.com/cockroachdb/cockroach has been encountering a lot of "Pending" statuses for people who have already signed the CLA.

This seems to have been a issue since at least July 18th. It's a common enough problem that we have documentation on how to fix it: https://github.com/cockroachdb/cockroach/wiki/licence-cla-PR-glitch.

For instance, it just happened again to https://github.com/cockroachdb/cockroach/pull/8572.

Might be related to https://github.com/cla-assistant/cla-assistant/issues/144.

**Comment by KharitonOff** [comment]
Thank's for reporting this! The problem is that github api needs some time (sometimes more than 3 seconds) to respond with appropriate payload after a new PR was created. I'll try to fix it on our side.

**Comment by KharitonOff** [comment]
I've increased the number of retries to 10. Have you experienced this issue since end of August again?
