### ISSUE TITLE
Contributor Covenant Code of Conduct as the CLA

### ISSUE THREAD

**Issue by nuno-agostinho** [cla-assistant/cla-assistant#152]
It would be great if in the license selection you could allow people to choose the latest version of the [Contributor Covenant Code of Conduct](http://contributor-covenant.org/) and easily update it when new versions are released.

**Comment by KharitonOff** [comment]
ok, that sounds interesting, but wouldn't it be a bit confusing for users to sign Code of Conduct in a CLA tool? There is also at least one placeholder ([INSERT EMAIL ADDRESS]) in the document, which should be filled...
I think CLA assistant is not the right tool for that. Nevertheless I could imagine that a modified version of CLA assistant would meet your requirement well.

**Comment by thojansen** [comment]
Right now CLA assistant is not the right tool for this, so we are closing this issue. However the current code base would be a good starting point if you want to enforce signing a code of conduct. The workflow would be different as a user would sign a code of conduct once globally and not per repo or organisation, but an opt-in could be also per repo or org. We have discussed this workflow for CLAs and generally decided against it. I also agree that this would deserve a new name, branding etc.
