### ISSUE TITLE
CLAassistant is posting twice for new contributors

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#154]
https://github.com/lipis/cla/pull/18

Not sure if it's because if it's because I was linking and unlinking this project a few times in the past.. 

Feel free to submit random PRs if you want to debug it somehow to that project as it serves only as a test..

**Comment by KharitonOff** [comment]
@lipis you've linked this repo on both instances: preview.cla-assistant.io and cla-assistant.io
That's why there are two comments from CLA assistant 😏

**Comment by lipis** [comment]
I had this feeling that it was my fault :) Thanks..
