### ISSUE TITLE
Provide a link to add to CONTRIBUTING.md

### ISSUE THREAD

**Issue by waldyrious** [cla-assistant/cla-assistant#156]
After setting up cla-assistant for a project I help maintain ([tldr-pages](https://github.com/tldr-pages/tldr)), at no step I could find a link to the CLA page (i.e. not the gist, but the actual page at cla-assistant.io).

Eventually, by clicking in the "Details" link in [a pull request](https://github.com/tldr-pages/tldr/pull/1048), I figured out that a link in the form https://cla-assistant.io/tldr-pages/tldr would work. It would be nice if this was pointed out during the initial setup.

**Comment by waldyrious** [comment]
I'm still interested in this.

**Comment by waldyrious** [comment]
I'm *still* interested in this.

**Comment by nothingismagick** [comment]
I would like to know about this too.

**Comment by KharitonOff** [comment]
I linked the name of the CLA file with the CLA page. You can easily navigate to this page by clicking on the link. I hope it is sufficient for your use case.
![screen shot 2018-07-09 at 14 43 52](https://user-images.githubusercontent.com/8480657/42451239-e8491196-8386-11e8-9783-5766b18f2b7f.png)
