### ISSUE TITLE
Option to exclude repositories if organization is linked

### ISSUE THREAD

**Issue by dennisoelkers** [cla-assistant/cla-assistant#157]
When you link an organization, a github orga webhook is installed which adds the PR check for every PR of every repository. It is desirable though, to be able to exclude repositories from this, so all repositories from orga n _excluding_ repos x, y & z are linked. In certain scenarios it is much less effort to link an orga and exclude some repositories than selectively including only the desired repositories (and take care that future repositories get added too).

One idea (UI-wise) might be the option to supply a repo pattern for a linked orga which is used to match repository names against.

**Comment by matz3** [comment]
Seems to be related to my comment (2.) here: https://github.com/cla-assistant/cla-assistant/issues/62#issuecomment-236983994
