### ISSUE TITLE
Linked organizations aren't visible to other users

### ISSUE THREAD

**Issue by tomdee** [cla-assistant/cla-assistant#158]
I set up a linked organisation but other people in my github org can't see it. They can only see the linked repositories that I previously set up. I've made people "owners" and given them admin rights but they still can't see the linked orgs in the cla-assistant UI. What am I doing wrong?

**Comment by KharitonOff** [comment]
Did the other users provided CLA assistant with extended scope ("admin:org_hook")? To do so, they need to click the "Create new link" button and click on the link "want to link an org?" under point "2 Choose a repository". After that they should see the linked org too.

**Comment by tomdee** [comment]
Yes that work! Thanks. Quite a non-intuitive UX though - can it be made easier/more obvious?

**Comment by lipis** [comment]
If I link an org.. how can I invite (or what's the procedure) so other admins can see the activities of that org?

**Comment by KharitonOff** [comment]
Everybody sees the linked repos/orgs for which he/she has owner rights (even if another person has linked the repo/org). For the linked orgs there is the only extra step to do is to provide CLA assistant with extended scope as described above.

**Comment by lipis** [comment]
@KharitonOff Thanks.. we'll check that out..
