### ISSUE TITLE
Is it possible to ask for a recheck a specific PR 

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#159]
Instead of rechecking them all in one organization?

**Comment by KharitonOff** [comment]
unfortunately not. A recheck on a specific PR happens only if the webhook is triggered (e.g. by a new commit on the PR)

**Comment by thojansen** [comment]
@KharitonOff via an API call 😄 ?

**Comment by KharitonOff** [comment]
Ok, there is no API on CLA assistant side for that. The only thing I could imagine is to 'redeliver' the webhook from GitHub (go to repo settings -> webhooks -> find under 'Recent Deliveries' the call for the given PR and click on 'Redeliver'-button) 😏 

OR 

create an API call with similar payload 😄 
 - "action" (open, reopen or synchronize)
 - "number"
 - "repository" with "id", "name", "owner"."login"
 - "organisation" (if it is an organisation webhook) with "id"
and Header "X-GitHub-Event: pull_request"

OR

contribute to cla-assistant and create an API/ this function 😄
