### ISSUE TITLE
Is it enough to have only the username in the CSV file when importing?

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#160]
Or what's the general suggestion if we want to exclude all the members of our organization?

**Comment by thojansen** [comment]
this is currently the only way to do it and yes, the username is the only thing which is needed

**Comment by lipis** [comment]
Thanks!

**Comment by aoberoi** [comment]
if the CSV i am providing for import has the other metadata, is there a way we can support importing that all too?

my use case is i started with a CLA attached to a repo, but then i wanted to link that CLA to the whole owning org. i exported the list from the repo (which includes my metadata) and when i import it to the org i only have github username. i think this would be a common pattern among users.
