### ISSUE TITLE
[Question] Proof of CLA

### ISSUE THREAD

**Issue by elbenfreund** [cla-assistant/cla-assistant#164]
hello community,

please excuse if this is the wrong place to raise the issue, but I was wondering what sort of actual proof cla-assistent provides to be presented in front a court of law if it ever comes down to it. Is there any actual signing procedure and/or a way to extract a signed document (pdf)?
I am aware of the (lovely) possibility to export contributors that signed via csv, but I somehow doubt this will hold up at court.

Thank you for your effort and contributions: Eric.

**Comment by thojansen** [comment]
To our current knowledge our current measures are sufficient and our legal team was fine with the taken approach (electronically stored documents in a systems as a record). We had a discussion with Microsoft and they are using DocuSign to go one step further, but so far we have decided to keep this more lightweight. Having said that, we would be happy to see how an integration into DocuSign (or s.th. similar) could look like and check if that is something needed by the community (formally needed by lawyers).
