### ISSUE TITLE
Export API / Periodic Export?

### ISSUE THREAD

**Issue by imbriaco** [cla-assistant/cla-assistant#166]
First of all, thank you for creating the cla-assistant. I've evaluated many of these tools and this is definitely the best available option in my experience.

I'm wondering if there is any way to periodically export the contributor CSV other than manually logging in through the web UI? It seems like exposing an API endpoint that I could fetch an export from would be the easiest path, but I wasn't able to find anything that like that from a quick look through the code.

**Comment by KharitonOff** [comment]
Thank you for your positive feedback!
There is an API that gives you the list of signed CLAs (not in csv format, but as JSON). The only Problem is: you need a Session ID.
I'll rewrite the authentication part to provide the possibility to access APIs with username and github token.

**Comment by KharitonOff** [comment]
Now you can use the POST API `/api/cla/getAll` to collect all signed CLAs for your repo. You have to provide following parameters in the request body:
`repoId` and `gist.gist_url` as json e.g.:
```
{
"repoId":"51002973",
"gist":{
		"gist_url": "https://gist.github.com/96ef0a16f11c8f11b41c"
	   }
}
```
For authentication you can use a valid github token. You can provide it either as a body-field `token` or as a header-field `x-token`.
Would this solution help you?

**Comment by imbriaco** [comment]
The API request makes sense, though I'm not sure how I would go about getting the GitHub token. I'm assuming that you specifically mean a token for the cla-assistant OAuth application? Could the cla-assistant web UI expose that somewhere?

**Comment by KharitonOff** [comment]
You can use your "personal github token". If you go to settings in your github profile you can generate a github token under "Developer settings -> Personal access token". We use it only for identification towards GitHub.

**Comment by imbriaco** [comment]
I didn't even realize you could choose the scopes when you created a personal access token and I used to work at GitHub. Derp! Yes, this will work great. Thanks so much!

**Comment by imbriaco** [comment]
Actually, one more question @KharitonOff -- can I use `orgId` instead of `repoId`?

**Comment by imbriaco** [comment]
Nevermind, tested it for myself and it works great. I really appreciate it!
