### ISSUE TITLE
Not checking the full commit range

### ISSUE THREAD

**Issue by Kostronor** [cla-assistant/cla-assistant#168]
It seems that cla assistant is missing commits in fairly long prs, like this one f.e.:
https://github.com/Minecolonies/minecolonies/pull/238

After more then 250 commits it misses the newest ones and so misses some contributors (only found 4 out of at least 6).

Will it be possible to bump this limit up somehow?

**Comment by KharitonOff** [comment]
@Kostronor can you click on "Recheck PRs" in CLA assistant please and check wether it is working now

**Comment by Kostronor** [comment]
@KharitonOff I clicked it, waited 2 minutes and clicked it again. So far no update for the pr as it seems.

**Comment by KharitonOff** [comment]
@Kostronor ok, thank you! I'll keep on searching ...

**Comment by Kostronor** [comment]
@KharitonOff If there is any more Info I can supply please tell!

**Comment by KharitonOff** [comment]
now it should work with large commit ranges. I was looking for the root cause on the wrong side. The threshold of 250 is set by GitHub...
Now we take all commits pushed to the PR-branch since the date of the PR base commit.

**Comment by Kostronor** [comment]
@KharitonOff I kicked off a new recheck and now 13 contributors are found. That looks like a solid number so I'd say it is done.

Thanks a lot for the fix!
