### ISSUE TITLE
Recheck PRs on newly added org are all pending

### ISSUE THREAD

**Issue by kborchers** [cla-assistant/cla-assistant#169]
After adding an org and clicking "Recheck PRs", all open PRs are checked but all come back as pending and are stuck that way.

This may be related to #150 but is a bit different in that because the org is new, there isn't even a workaround because there is no webhook payload to resend. Any thoughts appreciated. I'm also happy to help work on the solution to this and #150 but I'm new to this code base so some theories on the cause and direction where to look would be helpful.

Thanks!

**Comment by KharitonOff** [comment]
Do I understand you correctly: the status of all PRs in the org remains "pending" even if all committers of the PRs have signed the CLA?

The workaround mentioned in #150 is actually an "old" one - "Recheck PRs" does the same. But if you wisch you can resend the webhooks also for the org. You have to just navigate into org settings and select "Webhooks" there
![bildschirmfoto 2016-11-02 um 10 55 56](https://cloud.githubusercontent.com/assets/8480657/19924165/10705aa6-a0eb-11e6-8d3f-7fd08477dd31.png)

**Comment by kborchers** [comment]
Sorry, I believe this issue was filed before I fully understood how things work. I was not expecting the unsigned CLA to leave the status as pending but expected it to fail the check. If the expected outcome is for the check to always be pending until the CLA is signed, this is working properly and you can close this issue. If it should actually fail the check, then it is not doing that.

**Comment by KharitonOff** [comment]
No problem. CLA assistant check has indeed only two statuses: pending and success.
