### ISSUE TITLE
Automatically ignore bot users

### ISSUE THREAD

**Issue by finnp** [cla-assistant/cla-assistant#173]
Hey,

GitHub recently introduced bot users (aka integrations). It would be nice if bots would be automatically white-listed, since they can't sign any CLA. They always include the tag `[bot]` in their committer name, e.g.  `greenkeeper[bot]`, which users are not allowed to use.

Also if there is a full user object, the `type` key can be checked, which is set to `"Bot"`.

So It would be rather easy to filter them.

Have look at this example: https://api.github.com/repos/wireapp/wire-webapp/pulls/422/commits

This is related to this issue https://github.com/greenkeeperio/greenkeeper/issues/236

**Comment by Arcanemagus** [comment]
I absolutely love the irony of a `bot` commenting on an issue about `bot` users not being supported. (Also: Bump so this doesn't get closed as stale.)

**Comment by lipis** [comment]
Can we do something about it? https://github.com/wireapp/wire-web-packages/pull/21#issuecomment-345163601 how can we whitelist that one?

**Comment by lipis** [comment]
Or just implement them.. or a way to whitelist through the UI..

**Comment by pethers** [comment]
Just started using cla-assistant and have the same issue, any progress or workaround ?

**Comment by KharitonOff** [comment]
This feature is finally live! 😃  You can use a whitelist of contributors (also with wildcard \*) for your repo/org. To do so you just need to click "Edit" button and type `*[bot]` or a comma separated list of user names into whitelist field
![screen shot 2018-07-06 at 10 36 16](https://user-images.githubusercontent.com/8480657/42368999-ea3b6fc4-8108-11e8-918f-732a328a39b2.png)
![screen shot 2018-07-06 at 10 36 38](https://user-images.githubusercontent.com/8480657/42369016-f241621e-8108-11e8-9dd5-47e9d8b1ed4d.png)
It would be great if you could test it and give us your feedback, whether it works as expected!

**Comment by pethers** [comment]
Thanks @KharitonOff have updated the settings with codacy-badger,*-bot . After a recheck it's all green for bots now, used https://github.com/Hack23/cia/pull/51 for test and all looks good :)

**Comment by KharitonOff** [comment]
@pethers great! Thank you for testing and letting us know that it works for you!
