### ISSUE TITLE
Seems to fail when trying to retrieve repositories/organizations

### ISSUE THREAD

**Issue by mookid8000** [cla-assistant/cla-assistant#174]
When creating a new link, nothing shows up in the "Choose an org or a repo" select box.

The console reveals that the server experienced something bad:

<img width="534" alt="skaermbillede 2016-11-07 kl 10 18 00" src="https://cloud.githubusercontent.com/assets/32968/20052269/9db83122-a4d3-11e6-858f-b05e05f4780a.png">

**Comment by KharitonOff** [comment]
Thank you for reporting this issue! I've just pushed the possible bugfix...
Could you retry please and let me know, whether it works for you now or still fails?

**Comment by mookid8000** [comment]
I just tried.... but still nothing shows up in the box.

I also get these periodically – don't know if it's related:

<img width="625" alt="skaermbillede 2016-11-07 kl 10 25 08" src="https://cloud.githubusercontent.com/assets/32968/20052527/a60bcfb8-a4d4-11e6-93b1-b6c516c52914.png">

**Comment by KharitonOff** [comment]
Yes, the 404 was related... 😞  The app was crashing
Now it should be solved. Can you confirm it?

**Comment by mookid8000** [comment]
🎉 

<img width="962" alt="skaermbillede 2016-11-07 kl 11 20 23" src="https://cloud.githubusercontent.com/assets/32968/20054218/3aeeb616-a4dc-11e6-90e8-0899b66c1c09.png">

Thank you for the super-quick response and subsequent fix! 😄
