### ISSUE TITLE
Can I revoke access for a specific organization?

### ISSUE THREAD

**Issue by bseddon** [cla-assistant/cla-assistant#177]
I have granted access for two organizations to cla-assistant.  I really only want/need one to be granted access.  I can see I am able to revoke the whole cla-assistant application but is it possible to revoke access to just one of the organizations?

In the Authorized Applications screen for cla-assistant there was a button to allow/grant access to a specific organization but there seem to be no equivalent option to revoke access.  I appreciate this is not a killer issue but it would be nice to know or know why its not needed.

**Comment by KharitonOff** [comment]
Yes you can do it 🎉   

For that you have to go into settings of your organization...
https://help.github.com/articles/denying-access-to-a-previously-approved-application-for-your-organization/
