### ISSUE TITLE
Capture email address, address etc

### ISSUE THREAD

**Issue by purplefox** [cla-assistant/cla-assistant#178]
Hi,

We're looking for something like cla assistant to manage CLAs for our projects.

I took a look and it only seems to captire github username. I'm not sure this is really enough information in order to identify a signer as anyone can just create a github account.

Is there any way of exposing, at the least email address too? It would also be great if the user could input extra fields such as address when signing the CLA.

**Comment by KharitonOff** [comment]
Hi,

can you take a look on the issue #64 
You can use "custom fields" for requesting users to enter their e-mail-address and others.

**Comment by purplefox** [comment]
Thanks. Is there any documentation / guide that explains how to setup these extra fields?

**Comment by KharitonOff** [comment]
yes, our README.md 😄 
check the "Request more information from the CLA signer" section 
If something is still unclear feel free to raise your questions here

**Comment by purplefox** [comment]
Thanks. I have created a gist here:
https://gist.github.com/purplefox/9e9ce33631d631ac3b7af6ff8cc730c1

But I get an error when trying to sign the CLA:

====
There is no CLA to sign for Tesco/mewbase

(Unexpected string in JSON at position 103)
====

Seems like something wrong with the JSON, but not sure what. Any ideas?

**Comment by KharitonOff** [comment]
yes, there is a comma missing after first "githubKey": "name"

**Comment by purplefox** [comment]
Thanks I corrected that and now get:

(Unexpected token < in JSON at position 250)

**Comment by purplefox** [comment]
So.. I replaced the JSON with the exact same one from your README and it works, then I tried removing the "category" field as we don't want it, and get the same error again.

So it seems that a field called "category" is mandatory. Is there any way around this as we don't want to give users this choice?

**Comment by KharitonOff** [comment]
hmm... it works for me also without category
here is the gist, i forked from yours:
https://gist.github.com/KharitonOff/3cc2554f1b5da6659911022642909ec2

and the linked repo:
https://cla-assistant.io/kharitonoff/cla1

**Comment by KharitonOff** [comment]
I assume everything is working fine for you now...

**Comment by purplefox** [comment]
Still can't get it to work without category.... but I can live with that
for now.
