### ISSUE TITLE
Just can't get a check to pass

### ISSUE THREAD

**Issue by dschaper** [cla-assistant/cla-assistant#179]
https://github.com/pi-hole/testRepo/pull/14

Clicking on the CLA link shows that I've signed it, but coming back to the webpage shows no sign. Checked webhooks and all are green. No clue where we are going wrong.

**Comment by KharitonOff** [comment]
Hi, did @PromoFaux signed the CLA?

**Comment by dschaper** [comment]
That would be a problem, thanks for the quick reply, PEBCAK...
