### ISSUE TITLE
provide option to view and revoke CLAs

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#18]
Provide an option to view all signed CLAs and to revoke CLAs for future pull requests.

**Comment by mierschp** [comment]
@KharitonOff I think we should rename this topic to "revoke CLAs" only,  because the option to provide a view of all signed CLAs is already treated in #35

**Comment by KharitonOff** [comment]
@mierschp let's create a new issue for revoking and close this one as soon the we have linked the new view on the landing page

**Comment by JeromSar** [comment]
Keep in mind that some CLAs can not be revoked be definition. I think the CLA provider should be able to toggle this feature on and off per CLA.

**Comment by thojansen** [comment]
Thanks. This would be rather a "revoke for future (not yet opened) PRs". It does not make sense to do this for merged/ open PRs.

**Comment by thojansen** [comment]
Also: It is unclear if we enable this feature at all.

**Comment by thojansen** [comment]
For now, we will not enable this feature.
