### ISSUE TITLE
Page says I've accepted, badge on Github says I haven't

### ISSUE THREAD

**Issue by christoffer** [cla-assistant/cla-assistant#181]
I've signed the CLA (using this account which is github.com/christoffer): https://cla-assistant.io/dequelabs/axe-core?pullRequest=256
but on the pull request, the CLA is still unaccepted: https://github.com/dequelabs/axe-core/pull/256

I've tried clearing cookes, incognito mode and revoking + re-authing the CLA application.

Just let me know if there's any more information I can provide that's useful :)

**Comment by KharitonOff** [comment]
@christoffer-dropbox is the committer of this PR. He/she has to sign the CLA.
So did you sign it in name of the "christoffer-dropbox" ?

**Comment by christoffer** [comment]
Oh, that's interesting! It's on the committer basis, and not the PR basis! That makes sense, thanks for figuring this out!
