### ISSUE TITLE
Sign CLA for entire organization 

### ISSUE THREAD

**Issue by Infra-Red** [cla-assistant/cla-assistant#184]
Hi!
Is there any way to sign CLA for entire organization with cla-assistant bot?

**Comment by thojansen** [comment]
Yes, CLA assistant can be either activated/ linked to a repo or an entire org.

**Comment by Infra-Red** [comment]
@thojansen Sorry, but can you clarify how it can be done? When i exported csv with list of users for repository i observed `Signed for Organisation: FALSE`, which option configure this parameter.

**Comment by KharitonOff** [comment]
@Infra-Red If you link not only a repo but your organization in CLA assistant then each signature is valid for the whole organization.
If you don't see a list of your orgnizations in the dropdown then you should provide CLA assistant with additional rights first. To do so just click on the "(want to link an org?)" link
<img width="392" alt="bildschirmfoto 2016-12-12 um 09 38 05" src="https://cloud.githubusercontent.com/assets/8480657/21092789/bcc9c828-c04e-11e6-8588-a44486de3c91.png">

Let us know if you have any further questions.
