### ISSUE TITLE
Problem with signing CLA after changing username/email

### ISSUE THREAD

**Issue by xlttj** [cla-assistant/cla-assistant#186]
https://github.com/pimcore/pimcore/pull/1145 says I'd have to sign the CLA for pimcore/pimcore.

I've done that before for that repository but **changed username and email address** since then. Now when I try to sign again as requested on https://cla-assistant.io/pimcore/pimcore?pullRequest=1145 it reads „You have signed the CLA for pimcore/pimcore“. 

I contacted GitHub support and they said that this sounds like a bug with CLA Assistant and recommended to open an issue her.

**Comment by KharitonOff** [comment]
That sounds for me like a Problem with session cookies... Could you try to sign out from Github, logout from CLA assistant (https://cla-assistant.io/logout) and call the url again https://cla-assistant.io/pimcore/pimcore?pullRequest=1145. Or call this url from another browser.

If this won't help, I'll be able to look in it next week first 😄 (sorry for that)

**Comment by xlttj** [comment]
Signing out and back in helped. Thanks!
