### ISSUE TITLE
Unable to import csv file containing github usernames of contributers who have already signed the CLA. 

### ISSUE THREAD

**Issue by jilvin** [cla-assistant/cla-assistant#188]
Tried in Mozilla Firefox Developer Edition 51.0a2 (2016-10-17) (64-bit).

**Comment by jilvin** [comment]
Also correct the spelling "contributer" to "contributor" in the front-end of the software.

**Comment by thojansen** [comment]
Does it work for you in another browser?

**Comment by david-wire** [comment]
I am also unable to import the csv file on Mozilla Firefox 51 on MacOS (I also tried on Chrome and Opera). The 'Import' button is not clickable. Do I have to unlink the csv file that was previously imported?

**Comment by KharitonOff** [comment]
In Chrome 57, Firefox 52, Safari 10.1 and IE 11 import feature is working as expected
