### ISSUE TITLE
I'm getting checks on an unadded repository

### ISSUE THREAD

**Issue by camlorn** [cla-assistant/cla-assistant#189]
Hi,
https://github.com/libaudioverse/libaudioverse shouldn't be on my CLA assistant account, but I'm getting a check saying that all contributors have signed a test CLA anyway.  What do I need to do about fixing this?

I did try it briefly for experimentation and figured I forgot to turn it off, but I'm not seeing the repository listed and I really need it gone.

**Comment by KharitonOff** [comment]
hi, it seems that you have transferred your repo... so you can't unlink the repo in CLA assistant now... To stop CLA assistant reacting on new PRs you can delete the webhook in github: go to https://github.com/libaudioverse/libaudioverse -> settings -> webhooks
