### ISSUE TITLE
cla assistant is not working

### ISSUE THREAD

**Issue by opichon** [cla-assistant/cla-assistant#191]
https://github.com/tecnickcom/TCPDF/pull/49

This PR says that I haven't signed the CLA. 
In fact, I have signed the CLA for tecnickcom/TCPDF several times. If I try to sign it again, CLA tells me I have already signed it.

**Comment by KharitonOff** [comment]
the PR you mentioned says that @meroshan (the committer of the PR) haven't signed the CLA ;)
As soon @meroshan signs it the PR will get green status from CLA assistant
