### ISSUE TITLE
I have signed agreement many time still it shows it is not signed. 

### ISSUE THREAD

**Issue by drcsystems2** [cla-assistant/cla-assistant#194]
Hello
for my pull request I have signed agreement but still it shows agreement is not signed. My pull request is https://github.com/magento/magento2/pull/8249 
please let me know what is issue with it ? 

Thanks.

**Comment by KharitonOff** [comment]
hi,
the committer should sign the CLA. In your case it's @dhavalsolankidrc :)

Regards

**Comment by dhavalsolankidrc** [comment]
Okay thanks it was my mistake in push. :) 
let me try again.
