### ISSUE TITLE
Sync signers lists across repos and/or orgs

### ISSUE THREAD

**Issue by aoberoi** [cla-assistant/cla-assistant#196]
Currently, my company has more than one Org on github, yet we have just one CLA. I've synced a CLA to one of the orgs, but if I add it to the others then the lists are not in sync. It would be great to have a way to link bucket together both orgs and repos so that they can all be under the same CLA.

**Comment by MichaelTsengLZ** [comment]
It would be great if cla-assistant has this feature.

**Comment by walmartlabs-cla-admin** [comment]
We are already at 4 orgs at least with hundreds of repositories. This feature would certainly help a lot.

**Comment by MichaelTsengLZ** [comment]
We are Open Source Program Office at Microsoft. We've already made [contribution]( https://github.com/cla-assistant/cla-assistant/pull/250) back to the CLA-Assistant to support the scenario. Thank CLA-Assistant team again to have this awesome project. 👍 👍 👍
