### ISSUE TITLE
Repository owners being asked to sign CLA

### ISSUE THREAD

**Issue by PaulStovell** [cla-assistant/cla-assistant#197]
Is there a way to prevent CLA Assistant asking owners of the repository to sign the CLA?

E.g., I have 10 team members who contribute to the repository. I want CLA Assistant to ask the general public to sign the CLA, but not my team members.

**Comment by KharitonOff** [comment]
Unfortunately not. The workaround you can do: is to import the github names of your team members  into CLA assistant.

**Comment by sawilde** [comment]
@PaulStovell I just signed it myself for my own open source repo - I am not sure if there was an import functions then - not much details about the format though - I assume the first column is the github username

![image](https://cloud.githubusercontent.com/assets/297165/25925088/abd9aa50-3629-11e7-9926-ee420d8e8b68.png)

**Comment by MichaelTsengLZ** [comment]
I have a microservice to tell cla-assistant who need to sign a CLA and who don't need to. For example, we don't need employees to sign CLAs but need vendors to sign. What's the best generic design?

**Comment by thojansen** [comment]
As mentioned in #232, i think the question is if this is a specific services only relevant for you or if this is something CLA assistant should provide to everyone.

- If this is a simple pattern, I guess we should make this part of CLA assistant itself.
- If you need to hook up your IdP system, maybe we can specify an interface for a "validation/ whitelist endpoint".

Can you share some insights in how these "custom checks" would look like?

**Comment by MichaelTsengLZ** [comment]
Sure. The custom check is based on the user's company email. However, not all employee provide their company email on GitHub.  We have a microservice that already linked Github accounts with employee info(including company email). So I think that specifing an interface for a "validation/whitelist endpoint" is the right way to go.

**Comment by MichaelTsengLZ** [comment]
Could you give me some guidance on how to specify an interface for a "validation/whitelist endpoint" please?

**Comment by MichaelTsengLZ** [comment]
Discussed the problem with my tech lead. He thought the hookup solution may not be a good solution because cla-assistant may not work properly when IdP system has some problems. What's more, maintain a whitelist is hard in a complicated situation. He prefers to insert CLA record with some specific field into the CLA table.
We are planning to do this:
```
// 1. Open add/update CLA endpoint.
// 2. Add  'type' and 'reason' property in a CLA document. 
```
Any thought?

**Comment by thojansen** [comment]
So you are looking into an API to add users to a whitelist? Or maintain it separately?

**Comment by MichaelTsengLZ** [comment]
A record in the whitelist may simply be a CLA record in CLA collection marked with `type=employee`. I want to add an API endpoint for third party system or use the current /api/cla/sign API to create the record. Is that OK?

**Comment by MichaelTsengLZ** [comment]
And I want to contribute back to the cla-assistant.

**Comment by thojansen** [comment]
Sure, that sounds good.

**Comment by sschuberth** [comment]
For reference, the discussion in #61 is also related.
