### ISSUE TITLE
Added email to github but still says that it is not signed. 

### ISSUE THREAD

**Issue by bosstjann** [cla-assistant/cla-assistant#198]
I have a problem that I have accepted CLA with my primary GitHub account. 

It says Name SurName seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

I have added my email which was used for commit but nothing changed.

**Comment by cwoodwar6** [comment]
I am having this same issue. The commit shows my profile picture now instead of the default image when a commit is not associated, so I know GitHub has associated my account.

**Comment by thojansen** [comment]
Can you post links to your PRs?

**Comment by bosstjann** [comment]
https://github.com/eclipsesource/jsonforms/pull/487

**Comment by cwoodwar6** [comment]
https://github.com/uber/okbuck/pull/382

**Comment by Helias-Criouet** [comment]
Same problem on appium/appium-ios-simulator#138

**Comment by PatrickSchuster** [comment]
In case some people still have difficulties with this.
What helped me was to make sure that my author-email-address in my Sourcetree installation (which I used to commit changes) was added to my Github account as well. I missed checking that and thus wrongly assumed I was using an already added e-mail-address.

**Comment by akashgangrade** [comment]
I am facing the same problem. Kindly check it.
https://github.com/firebase/firebase-tools/pull/1762

**Comment by KharitonOff** [comment]
@akashgangrade please make sure that your email address "akash.gangrade@webdunia.net" is assigned to your github account.
