### ISSUE TITLE
Status check not working

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#200]
PR: https://github.com/SAP/openui5/pull/1363

CLA has been signed, but the status is still `not signed yet`. Re-check from PR comment and from admin UI didn't work.

Redirect seems to be broken aswell, see https://github.com/SAP/openui5/pull/1363#issuecomment-284247309.

**Comment by KharitonOff** [comment]
Hi Matthias,

CLA assistant checks the signatures of the committers of the PR, so @sbell-bluefin and not @stu-b-doo should sign the CLA.

**Comment by stu-b-doo** [comment]
ah, that's my old account. Need to change my git email address. Successfully signed - thanks!

**Comment by matz3** [comment]
@KharitonOff thanks! I missed that. Would be helpful to show the username if it differs from the one opening the PR.

**Comment by sbell-bluefin** [comment]
Also worth pointing out that the first time I tried signing this from the committer's github account - I accessed the PR while logged in as the committer but the assistant's 'sign me in with github' was picking up the other account, which was also logged in in a different tab, same browser session. 

Not saying this is something that needs fixing as such, just something to be aware of in case of similar issues.
