### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by hrj** [cla-assistant/cla-assistant#21]
I have been watching this repo for a while now, hoping for a public announcement.

It's not clear to me whether you plan to roll this out as a service. Or is it supposed to be a Bring-Your-Own-Server project?

If it's the latter, a few words on how to run and configure this would be appreciated.

Thanks!

**Comment by thojansen** [comment]
Thanks for your interest in the project @hrj. We plan to have a service up and running for SAPs open source projects very soon. Right now we would recommend to set up your own server. For this you need to set up a mongo database, set the environment variables (see .env.example) and then run the app via npm install/ npm start.

**Comment by thojansen** [comment]
see #26
