### ISSUE TITLE
Suddenly all our cla-assistant related tasks are not completing

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#211]
We didn't change anything and it looks like everything is green from the our dashboard. Any clues?

https://github.com/wireapp/wire-webapp/pulls

**Comment by bennyn** [comment]
**Screenshot of the issue:**

![capture](https://cloud.githubusercontent.com/assets/469989/24757128/90f71698-1ade-11e7-9a43-32b627b34137.PNG)

Problem exists since yesterday.

**Comment by KharitonOff** [comment]
Sorry for this! 
We changed the status context from licenCe/cla to licenSe/cla. This caused problems in repositories which have licenCe/cla as required status on protected branch. If you change your repo settings requiring the "new" status, this should be fixed.

**Comment by lipis** [comment]
Awesome! Typos are evil.. 👹
