### ISSUE TITLE
Am I an affiliate for using this?

### ISSUE THREAD

**Issue by franciscop** [cla-assistant/cla-assistant#212]
I have read the CLA and while I am not a lawyer, the main doubt I had was this:

> "Thank you for your interest in contributing to open source software projects (“Projects”) made available by SAP SE or its affiliates (“SAP”)"

Am I supposed to copy that file in a new gist and change that for my company? Or am I supposed to keep it as-is? In the last case I'd need to be an affiliate of SAP SE, am I an affiliate of SAP SE for using this project?

**Comment by thojansen** [comment]
You would either create your own or copy and paste and remove SAP with s.th. else. For more context, see https://opensource.guide/legal/
