### ISSUE TITLE
CLA Stopped working, error: Unexpected token in JSON

### ISSUE THREAD

**Issue by slvnperron** [cla-assistant/cla-assistant#213]
Hello,

We haven't changed the Gist recently but the CLA Assistant page stopped taking submissions. Here's our page: https://cla-assistant.io/botpress/botpress?pullRequest=136

The gist: https://gist.github.com/slvnperron/78043257a9b5bd8910f6ea779ad58f90

Error:
> Unexpected token Y in JSON at position 811

**Comment by KharitonOff** [comment]
@slvnperron It looks good to me. Have you already found the problem/solution ?

**Comment by slvnperron** [comment]
@KharitonOff thanks for the quick reply, we found the issue. Escaping double quotes using `\"` in our gist JSON used to work fine but now it seems like it is not supported. Not sure is escaping is valid JSON though.

**Comment by KharitonOff** [comment]
Great!
The .md file should support `\"` but the metadata file, which has JSON format and is parsed in javascript, needs two backslashes `\\"`. It's pretty weird :)
