### ISSUE TITLE
cla email invalid

### ISSUE THREAD

**Issue by huneau** [cla-assistant/cla-assistant#214]
I've got that 
![cla](https://cloud.githubusercontent.com/assets/9199240/25231089/bdde9494-25d6-11e7-8517-830dd1f57eeb.png)

I can't see where I should verify my email.

**Comment by KharitonOff** [comment]
This message says that there are some commits in your PullRequest which were done with another e-mail address than the one you have assigned to your profile. If you add the e-mail address (the invalid one) to your Profile then GitHub and CLA assistant will recognise you.

**Comment by KharitonOff** [comment]
oh... moment, it looks like "invalid-email-adress" is a github user, isn't it? Could you provide a link to the PR?

**Comment by huneau** [comment]
https://github.com/wekan/wekan/pull/1003

I think you right... I forget to set a user.email in my git config -_-'

**Comment by huneau** [comment]
think, I rework my branch here https://help.github.com/articles/changing-author-info/ and certificate is validate

**Comment by huneau** [comment]
Maybe a better explicit message, or clicable something :/

**Comment by KharitonOff** [comment]
normally there is a better message, assuming user has used a valid (but not assigned to his/her github profile) email address for the commit. We haven't had such constellation like yours so far.
