### ISSUE TITLE
Change license 

### ISSUE THREAD

**Issue by pavolloffay** [cla-assistant/cla-assistant#215]
Hello,

I have signed https://cla-assistant.io/uber/jaeger-client-java with my personal details and now I would like to change it and sign with company details.

**Comment by KharitonOff** [comment]
@pavolloffay unfortunately it is not possible yet to change the signature. 
CLA assistant does "basic" verification of signatures based on github user accounts. So we do not support differentiation between private and corporate CLAs. Some repositories/organisations (like uber) use so called "custom fields" as workaround to collect different data, but there is no functional support on our side to handle this data.
Sorry for that :(
I would suggest to contact uber directly and provide your agreement with company details on an informal way.
