### ISSUE TITLE
CLA appears as not signed

### ISSUE THREAD

**Issue by mstrelex** [cla-assistant/cla-assistant#217]
I added additional email to my account and CLA still appears as not signed:
https://github.com/appium/appium-uiautomator2-driver/pull/70

**Comment by KharitonOff** [comment]
CLA assistant needs to be triggered again to recheck the PR. This happens: 
 - as soon you add a commit to your PR
 - when the repository owner clicks the "Recheck PR" in CLA assistant UI

**Comment by mstrelex** [comment]
Thanks.
