### ISSUE TITLE
Changing the URL of the gist containing the CLA

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [cla-assistant/cla-assistant#223]
Is it possible to change  the URL of the gist containing the CLA (without having to export the  list of users who signed the CLA, unlink the repository, relink the repository with a a new gist URL and import the user list)?

![image](https://cloud.githubusercontent.com/assets/15331/26525096/6c79081c-431a-11e7-94a6-326dcc77b685.png)

**Comment by KharitonOff** [comment]
unfortunately not. It works only the (long) way you have described.
