### ISSUE TITLE
The way of generating the redirect url is not working properly on windows server

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#224]
I deployed cla-assistant on azure app service. It works pretty well except the redirects. 

https://github.com/cla-assistant/cla-assistant/blob/master/src/server/controller/default.js#L23
https://github.com/cla-assistant/cla-assistant/blob/master/src/server/controller/default.js#L35

**Comment by thojansen** [comment]
Can you provide some examples on how this breaks on azure? Also, you are always welcome to create a PR to fix this.

**Comment by KharitonOff** [comment]
I'm working on it.. The problem is using path.join for url was not a good idea ;P

**Comment by MichaelTsengLZ** [comment]
Thank you so much. I will send a pull request instead of just pointing that out next time.
