### ISSUE TITLE
How to implement the feature of showing custom field based on other custom fields

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#225]
I have a scenario that person can sign a CLA on behave of the employer or himself/herself. Based on the person's choice, I need to collection different information about the user. Is there any convenient way to implement that? Thank you so much.

**Comment by KharitonOff** [comment]
unfortunately not. We support only the "personal" CLAs. For corporate CLAs there is a workaround with custom fields, but you have no option to show/hide any fields depending on user input.
But we are open for contribution :)
