### ISSUE TITLE
"Status waiting to be reported" never completes

### ISSUE THREAD

**Issue by vivekrsharma** [cla-assistant/cla-assistant#228]
Already signed CLA for repo https://github.com/yarpc/yarpc-java and yet
I can't merge this PR (https://github.com/yarpc/yarpc-java/pull/323). It is 
blocked stating that waiting for the status to be reported.

I've tried unlinking and reimporting the repo under https://cla-assistant.io/ but
it didn't help either.

**Comment by KharitonOff** [comment]
Sorry for that! Please check the issue #211

**Comment by vivekrsharma** [comment]
No problem. How do I change that from licence/cla => license/cla? Is that going to be under .git directory?

**Comment by vivekrsharma** [comment]
I got it. For posterity, https://help.github.com/articles/about-required-status-checks/ this needs to be done. Also, this needs administrative access on the branch.
