### ISSUE TITLE
mention all committers who have not signed CLA yet

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#23]
If there are multiple committers in pull request all of them should sign the CLA. It is not transparent yet who has already signed the CLA and who not.
The possible solution could be: write names of all committers into comment who has not signed the CLA and update it after each signature.

**Comment by thojansen** [comment]
**1** out of **2** committers have signed the Contributor License Agreement (CLA).
- mail1@domain.com :white_check_mark: 
- mail2@domain.com :x: 

..something like this @KharitonOff ?

**Comment by KharitonOff** [comment]
yes, or like this:
1 more committer has to sign the CLA:
- mal2@domain.com

**Comment by KharitonOff** [comment]
only one committer in PR:
![bildschirmfoto 2015-06-05 um 13 53 45](https://cloud.githubusercontent.com/assets/8480657/8005531/6daafda8-0b8b-11e5-9d7a-9e16514fc7d5.png)

two committers in PR:
![bildschirmfoto 2015-06-05 um 13 58 13](https://cloud.githubusercontent.com/assets/8480657/8005535/70d35066-0b8b-11e5-8fac-734b35ffe5aa.png)
