### ISSUE TITLE
Enable certain people NOT to sign a CLA

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#232]
I extend the problem(https://github.com/cla-assistant/cla-assistant/issues/197) further. 

Not everyone needs to sign a CLA in our company. For example, employees don't need to sign while vendors do need. There are two designs to achieve it. 

First, develop a microservice which tells the cla-assistant whether the committer needs to sign a CLA or not. 

Second, develop a microservice to sign a CLA for employees automatically and delete the CLA record when he/she leave the company.

Any suggestions for the two methods? Currently, I prefer the first one.

**Comment by KharitonOff** [comment]
Great idea 👍 Like the first one better too.
I could imagine some kind of "white list" where you can enter login names and emails of users (and bots, this would solve the issue #173 too). Using some kind of regex pattern could be helpful to include larger user groups, like employees of your company.

**Comment by MichaelTsengLZ** [comment]
@thojansen and I discuss the problem a little bit.(https://github.com/cla-assistant/cla-assistant/issues/197)
Regex pattern cannot solve my problem. Because not all employee provide their company info(e.g company email) on their Github account. And currently, our team have an internal microservice that already linked employee Github account with their company info. So I think that specifying an interface for a "validation/whitelist endpoint" is the right way to go. Some guidance would be really helpful. Thank you so much.

**Comment by MichaelTsengLZ** [comment]
Close this issue and refer this to https://github.com/cla-assistant/cla-assistant/issues/197

**Comment by MichaelTsengLZ** [comment]
Right now, we use an API to create/delete a 'fake' CLA signature in the DB. So you could have a custom microservice to update the whitelist on the fly. Does this meet your requirement?
