### ISSUE TITLE
Minor formatting issue in SAP's own CLA

### ISSUE THREAD

**Issue by sschuberth** [cla-assistant/cla-assistant#238]
SAP's [own CLA](https://gist.github.com/CLAassistant/bd1ea8ec8aa0357414e8) has `###SAP Individual Contributor License Agreement` which actually should be `### SAP Individual Contributor License Agreement` (add space after `###`).

**Comment by thojansen** [comment]
Yes, thanks for reporting. This is due to the recent changes in the markdown format.

**Comment by sschuberth** [comment]
@thojansen, since this is trivial to fix, mind simply doing it?

**Comment by thojansen** [comment]
Well, we would like to avoid creating a new CLA version invalidating all existing signed CLAs. So we need to implement a functionality to create a new “patch version” of a CLA first.

**Comment by sschuberth** [comment]
Oh, I wasn't aware that CLAs get invalidated automatically when changed, and even so for very minor changes. Is implementing a “patch version” actually something you have on your roadmap?

**Comment by thojansen** [comment]
Yes, and we want to implement this first and then change the formatting.

**Comment by sschuberth** [comment]
@thojansen, any progress on implementing a “patch version”?

**Comment by wsdjeg** [comment]
I use this gist as my project's cla, can I change the url to my own gist?

**Comment by KharitonOff** [comment]
You have to unlink and link you repo with your own gist again (you'll find your gist file in the dropdown list). Everyone who signed you current CLA will have to sign the new one again.

**Comment by wsdjeg** [comment]
sign again? that is too bother, maybe use `patch version` is better.

**Comment by KharitonOff** [comment]
we have not implemented the possibility to use the "patch version" yet.
As a workaround you can export the list of your contributors and import it after relinking again - from the legal perspective I consider it questionable, since your contributors have signed an another document (SAPs CLA and not your own CLA).

**Comment by wsdjeg** [comment]
yeah, I know, it just like change the content of a contract. but I found cla may stop user contribute to my project. 

https://github.com/SpaceVim/SpaceVim/pull/1404

**Comment by KharitonOff** [comment]
Your users are right, the CLA file, you linked your repo with is only for SAP projects, so it doesn't help you at all to use it. You need an own CLA. Maybe you can take a look on this "CLA-generator" http://selector.harmonyagreements.org/

**Comment by KharitonOff** [comment]
also as @OvermindDL1 mentioned, usually contributors don't have any concerns to sign a CLA (with CLA Assistant we make it even easier to do it). The Agreement should happen between you and your contributor, not between SAP and your contributors ;)

**Comment by wsdjeg** [comment]
So, what should I do?

1. use cla-generator to create a agreement page
2. update cla url
3. request new contributer sign cla?

**Comment by OvermindDL1** [comment]
@wsdjeg 

And 4:  request old contributors to sign cla as well (else it is not that useful either, *everyone* needs to sign it, or you need to replace the code they gave).

**Comment by KharitonOff** [comment]
@wsdjeg yes, you should do the steps you've described.

**Comment by thojansen** [comment]
Still relevant.
