### ISSUE TITLE
Differentiate between employees and external contributors 

### ISSUE THREAD

**Issue by tessr** [cla-assistant/cla-assistant#239]
We don't currently require employees to sign the CLA, but in order for CLA Assistant to pass they need to "sign" it (or otherwise be added to the list of people who have signed the CLA). 

Is there a way to differentiate between employees (whom CLA Assistant can ignore) and people who have actually signed the CLA?

**Comment by KharitonOff** [comment]
I'm closing this issue as it is related to #197
