### ISSUE TITLE
Allow any org admin to see / export the list of signers

### ISSUE THREAD

**Issue by sschuberth** [cla-assistant/cla-assistant#240]
If CLA assistant was configured for an org, it would be nice if *any* admin of that org would be able to see and export the list of signers from the CLA assistant web interface. Currently, you have to login as exactly that admin of the org who has initially configured CLA assistant for the org.

**Comment by KharitonOff** [comment]
@sschuberth could you check the issue #158

**Comment by sschuberth** [comment]
Thanks for pointing that out. Indeed, pretending that I'd like to create a new link (without actually doing that) by clicking on `Create new link` -> `want to link an org?` -> `Yes, let's go for it!` worked to make the linked organization show up.
