### ISSUE TITLE
CLA signed but assistant still says not signed 

### ISSUE THREAD

**Issue by loewenstein** [cla-assistant/cla-assistant#241]
I have got a PR on my repo https://github.com/SAP/bosh-kubernetes-cpi-release/pull/1

The author has two github users. He committed with one, opened the PR with another. In the cla assistant I only see one of his users. @amitkgupta claims (and sent me a screenshot) that he gets a already signed screen when trying to sign with his second user. 

Any idea what could be wrong here?

**Comment by matz3** [comment]
It seems that one user is still not signed. See [my comment in the PR](https://github.com/SAP/bosh-kubernetes-cpi-release/pull/1#issuecomment-314680324).

**Comment by KharitonOff** [comment]
there is no entry with @amitkgupta in the DB. He should Sign out from github and try to sign the CLA. CLA navigates him to the Sign In-page where he should use credentials of @amitkgupta

**Comment by loewenstein** [comment]
Discussing that with Matthias we might have found the root of the confusion.

I suppose the PR author signed in with the correct user in github, however he was still signed in with his other account with @CLAassistant.

**Comment by loewenstein** [comment]
@KharitonOff no matter if the proposed workaround actually works or not, I would consider the status quo a UX issue that should be properly fixed. Could be done by:
1. Showing the current user on CLA sign up page
2. Provide a way to switch user or logout on CLA sign up page

WDYT?

**Comment by loewenstein** [comment]
@KharitonOff bump

**Comment by KharitonOff** [comment]
@loewenstein, will consider your proposal by the next release

**Comment by loewenstein** [comment]
Is there any update on this one?

stale[bot] <notifications@github.com> schrieb am Mo., 29. Jan. 2018, 23:11:

**Comment by loewenstein** [comment]
@KharitonOff any news?
