### ISSUE TITLE
why so many permissions?

### ISSUE THREAD

**Issue by giladgray** [cla-assistant/cla-assistant#243]
Why does a CLA assistant need to be able to write to my public repositories?
Any chance of slimming the required permissions?

<img width="515" alt="cla-assistant-permissions" src="https://user-images.githubusercontent.com/464822/28117791-77e7a67e-6717-11e7-9c15-ba770eae6903.png">

**Comment by KharitonOff** [comment]
CLA assistant needs this permissions to set webhooks and to be able to react on new PRs in your repository.

**Comment by giladgray** [comment]
ok but if i just want to sign someone else's CLA? not actually use it myself.

**Comment by giladgray** [comment]
makes sense to need more permissions if i'm going to actually create a CLA, but this is way too much friction for a simple contribution to someone else's project that happens to use this tool.

**Comment by KharitonOff** [comment]
for that, you needn't sign in to CLA assistant via the landing page. Just navigate to the appropriate CLA (link on the comment in the PR) and click "Sign in with GitHub to agree"

**Comment by giladgray** [comment]
hmm i did do that the first time but it didn't work on the PR (https://github.com/FezVrasta/popper.js/pull/351 says unsigned CLA). now it takes me to the full sign-in page.

glad to hear it's _supposed_ to work how i expected. not sure what's wrong here though.

**Comment by KharitonOff** [comment]
ok, if I click on "Contributor Licence Agreement" or on the "CLA not signed"-badge than I land on "https://cla-assistant.io/FezVrasta/popper.js?pullRequest=351" where you can sign the CLA

**Comment by giladgray** [comment]
yep i did that, and i clicked the button, and then it reloads me to the main page with the permission-full sign in button. i think i've done my part, but the PR still thinks it's unsigned.

**Comment by KharitonOff** [comment]
oh, ok.... there is something wrong

**Comment by KharitonOff** [comment]
could you try to access and sign the CLA via https://cla-assistant.io/FezVrasta/popper.js please ?

**Comment by giladgray** [comment]
🎉 that worked! thanks!
