### ISSUE TITLE
Sign only once when multiple orgs or repos lined with the same gist

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#246]
The same problem as the [issue196](https://github.com/cla-assistant/cla-assistant/issues/196), Microsoft has multiple orgs and thousands of repos, we'd like the contributors to sign the same CLA only once. Are there any reasons why we cannot add this feature? 

I'd like to change the code in [cla.sign()](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/api/cla.js#L342) and [cla.check()](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/services/cla.js#L117). What's more, I would add a function called getByGist() for both repo and org services.
```
sign = function (...) {
  ...
  // Sign the cla
  // Get linked items with the same gist
  // For each linked items validate pull requests. 
  ...
})
```
```
check = function (...) {
  ...
  // Call claService.get() without repo, owner, repoId or orgId
  ...
}
```

Any suggestions? 
cc: @jeffmcaffer

**Comment by KharitonOff** [comment]
@MichaelTsengLZ good point, we had this idea already in mind (see #118) but user feedback wasn't very supportive 😏

**Comment by MichaelTsengLZ** [comment]
Sounds like those don't support the feature have relatively simple organizations and CLA settings. In Microsoft, we have multiple orgs and each org has it's own CLA. What's more, there are some repos even have different CLA from its org CLA. So contributors may need to sign the same CLA for multiple times. 
I'm really interested in the idea of @thojansen which enables the contributors to decide what's the scope of the CLA (e.g. pull request, repo, org or all). Another simpler implementation option is to add a config setting to enable the feature and let the people who deploy the cla-assistant decide. Any suggestions?
The cla-assistant is really a great CLA tool. We are willing to adopt it and also contribute back to make it cover more scenarios.

**Comment by KharitonOff** [comment]
Ok, I think your second proposal could be indeed easily done. We can add a checkbox on the "create new link" view, which decides whether signatures should be on CLA-basis or not (default "not" - means the current implementation works as it is). If it is checked, we use the check function as you've suggested above.

**Comment by MichaelTsengLZ** [comment]
Thank you so much for your guidance. I will send a PR soon it. 👍 👍 👍

**Comment by MichaelTsengLZ** [comment]
Here is the PR and I also want to discuss the concerns in the PR.
https://github.com/cla-assistant/cla-assistant/pull/250
