### ISSUE TITLE
Can't sign CLA?

### ISSUE THREAD

**Issue by joekrill** [cla-assistant/cla-assistant#247]
I'm trying to sign the CLA for this PR: https://github.com/FezVrasta/popper.js/pull/356. I follow the [link](https://cla-assistant.io/FezVrasta/popper.js?pullRequest=356) and clicked "Sign in with Github to agree", and ultimately just get redirected to the [CLA assistant homepage](https://cla-assistant.io/) -- no message or anything else indicating success or failure. 

I've tried revoking and reauthorizing CLA assistant with Github, but with the same results. I've even tried to the whole process in an Chrome incognito window, to no avail. And using the "recheck" link doesn't seem to help.

I do have multiple email addresses associated to my github account -- could this have something to do with it perhaps?

**Comment by KharitonOff** [comment]
can you try to sign the CLA via this link (https://cla-assistant.io/FezVrasta/popper.js), please?

**Comment by joekrill** [comment]
That seemed to do it -- thanks so much @KharitonOff!

**Comment by giladgray** [comment]
@KharitonOff sounds like #243... perhaps there's really a bug in the software?

**Comment by KharitonOff** [comment]
@giladgray Yes, sure. I have this problem in mind, will take a look on it as soon I have some time for it. 
I suppose there is an issue because of "." in the repo name 😕

**Comment by FezVrasta** [comment]
Any news on this? My users are still having this problem.

**Comment by KharitonOff** [comment]
@FezVrasta now it should work again. Could you let me know, please if it doesn't?

**Comment by FezVrasta** [comment]
it seems to work now, thanks!

**Comment by KharitonOff** [comment]
Great! Thank you!
