### ISSUE TITLE
Enable link repo with a different CLA from its org CLA if exists

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#251]
As I mentioned earlier in issue #246, Microsoft has a more complex CLA configuration. One scenario is that we may need to override the org CLA with a different CLA. We are planning for the following changes.

1. We'd like to change the code that tries to get org CLA first and if not exists then get repo CLA. We will flip the order. 
2. Since we allow overridden CLAs, we will delete the repo webhook when its org linked and create webhook when its org is unlinked.
3. Because exclude repo list of an org is not that easy to maintain. We add a null type CLA only for repos to achieve the same goal. (Leave the exclude repo list as it is for a compatible reason.)  

Any guidance?

**Comment by KharitonOff** [comment]
@MichaelTsengLZ I found one minor issue:
<img width="632" alt="screen shot 2017-09-06 at 14 35 25" src="https://user-images.githubusercontent.com/8480657/30112299-24b32aca-9311-11e7-97e6-bbf9371c8f3c.png">
this happens if I "relink" the repo/org to use the same gist as shared one and the user signs the shared gist for another repo.

**Comment by MichaelTsengLZ** [comment]
Do you expect to filter out the same contributors and just show the latest signature?

**Comment by jeffmcaffer** [comment]
@KharitonOff is this when the user first signed CLA when the gist was NOT shared and then, after relinking as shared, signed again?

**Comment by KharitonOff** [comment]
@jeffmcaffer exactly. 
@MichaelTsengLZ yes, I would prefer to see only the last signature, then it wouldn't show my user as "2 contributers"

**Comment by MichaelTsengLZ** [comment]
@KharitonOff All right, I will send a pull request today.
