### ISSUE TITLE
garbage prepended to all headings

### ISSUE THREAD

**Issue by kusma** [cla-assistant/cla-assistant#259]
Things like `{:"aria-hidden"=>"true", :class=>"octicon octicon-link"}` gets prepended to all headings in the CLA for our project. This seems to be after a recent change.

This is what it looks like:
![image](https://user-images.githubusercontent.com/47073/30802184-f5f25bb4-a1e5-11e7-878a-c892103bdf94.png)

[Here's an affected link](https://cla-assistant.io/fusetools/fuselibs-public?pullRequest=488).

[Here's the gist that provides the markdown](https://gist.github.com/kusma/2348c1d8e1ab31bcd2d657a5bdb8a1f6)

**Comment by KharitonOff** [comment]
@kusma which browser do you use? 
I see your CLA (in Chrome, Firefox and Safari) as follows:
<img width="717" alt="screen shot 2017-09-25 at 13 42 30" src="https://user-images.githubusercontent.com/8480657/30806832-97c3ea96-a1f7-11e7-8b76-3ed88053b1a8.png">

Still, don't like the added anchor links, but it is an old issue. I'll try to find a quick fix for the link icons.
Sorry, but I could not reproduce your view.

**Comment by kusma** [comment]
@KharitonOff: I experienced this using Chrome. However, it seems the problem has been resolved now. Perhaps it was something in github's end?
