### ISSUE TITLE
documentation on how to run own instance of cla assistant

### ISSUE THREAD

**Issue by thojansen** [cla-assistant/cla-assistant#26]
provide a documentation on how to run a custom instance

**Comment by kevinsmeets** [comment]
Hi Guy's,


I'm trying to setup cla-assistant on a dedicated server running a CentOS 6.6 (Final) installation.

I've installed NodeJS v0.10.36, NPM v1.3.6 and MongoDB 3.0.3 and downloaded the cla-assistant repo (master branch). Then I proceeded to setup MongoDB (creating user and database) and to set some environment variables as shown by the .env.example. I set PORT to 3000, PROTOCOL to http, HOST to <my server IP address>. I created a random string and set it as SESSION_SECRET (I don't know if this is correct). The variable MONGODB is set to the connection-string for the MongoDB instance. I assume that cla-assistant needs the GITHUB_CLIENT (Client ID) and GITHUB_SECRET (Client Secret) from a GitHub Developer Application. I have no idea what SLACK_URL is supposed to contain, so I set it to 'https://api.slack.com/' (probably not correct). 

Then I proceeded by running 'npm install' followed by 'npm start'. There was a problem with Mongoose, so I updated Mongoose to version 4.0.0 which seems to have solved the issue (see https://github.com/Automattic/mongoose/issues/2757).

After running 'npm install' again and starting cla-assistant again using 'npm start', everything seems to be OK. The web interface is showing up when I open it using a browser.

However, clicking on the 'Sign in with GitHub' button does nothing. There are no errors logged in the terminal which is running cla-assistant (it does log: 'bootstrapped, app listening on localhost' and '/app.min.js'). In the browser there is an error logged to the console: app.min.js is filled with HTML?? So I installed grunt and built the AngularJS app. Now when the 'Sign in with GitHub' button is clicked, it does something.

When clicking on the 'Sign in with GitHub' button or the 'Sign in' link in the upper right corner, I get to see 'Unauthorized' and I see a 401 in the network traffic: http://<my server IP address>/auth/github/callback/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch.

The 'Authorization callback URL' for the GitHub Developer Application is specified as follows: http://<my server IP address>/auth/github/callback.


@Thojansen: For me, this is not enough information: 'set up a mongo database, set the environment variables (see .env.example) and then run the app via npm install/ npm start'. Obviously this doesn't mention that the AngularJS app has to be built using grunt, and it doesn't explain how to set up  cla-assistant.


So, I'm stuck. Can one of you please describe how to configure cla-assistant? 


Thanks, Kevin

**Comment by kevinsmeets** [comment]
I see that most URL's in my text are not shown as I hoped.
Just to clarify, the callback URL is: http://my-server/auth/github/callback
I should have remembered that certain brackets are not allowed/shown on GitHub, doh!

Thanks, Kevin

**Comment by KharitonOff** [comment]
Hi Kevin,

thank you very much for your Interest on CLA assistant! And so sorry for the spare info on how to set up CLA assistant. We are still working on the app and lot of things are changing continuously, so the short description you had is a bit outdated now. We have describe it again in more detail, see README.md.  

It would be great if you could review the description and validate, whether it works for you now. And please, let us know if you still have open questions or problems with set up.

Thanks and regards
Anton

P.S.: Feel free to reopen the issue in case anything is unclear.

**Comment by kevinsmeets** [comment]
Hi Guys,

Thank you for your quick reply and the updated README.md
I have cla-assistent running and properly configured and it works like a charm :+1: 

Thanks, Kevin

**Comment by thojansen** [comment]
awesome :shipit:
