### ISSUE TITLE
Inconsistent signed status

### ISSUE THREAD

**Issue by nerdlem** [cla-assistant/cla-assistant#260]
I'm being told by cla-assistant that I've not signed the CLA, but when I click on the "Details" link, the page tells me I've already signed it.

Example: https://cla-assistant.io/spf13/cobra?pullRequest=531

Am I doing something wrong?

Thanks

**Comment by KharitonOff** [comment]
HI @nerdlem, @uniregistry should sign this CLA, because @uniregistry made commits in this PR
