### ISSUE TITLE
How can I add another admin to the linked organization?

### ISSUE THREAD

**Issue by lipis** [cla-assistant/cla-assistant#263]
We are both owners of an organization but when he signing in into the `cla-assistant.io` there is nothing on his side.. so the question is how two people can admin the same organization?

**Comment by KharitonOff** [comment]
@lipis nice to see you here again ;)
your colleague should click the "Link" button first and then under point 2 select "want to link an org?" and provide additional auth-rights to CLA assistant

<img width="327" alt="screen shot 2017-10-05 at 11 06 09" src="https://user-images.githubusercontent.com/8480657/31219388-62f41430-a9bd-11e7-8869-d5ce661559cf.png">

If he has already done this and still can not see the org, check this answer: https://github.com/cla-assistant/cla-assistant/issues/176#issuecomment-259924887

**Comment by lipis** [comment]
Awesome! Thanks @KharitonOff.. nice to see that this project is still alive and kicking :)
