### ISSUE TITLE
Sign in with github to agree just reloads page 

### ISSUE THREAD

**Issue by SpadarShut** [cla-assistant/cla-assistant#264]
For this PR https://cla-assistant.io/FezVrasta/popper.js?pullRequest=454 I click `Sign in with github to agree` but it just reloads page. First time it showed github authorization, I allowed, but still I can't et this page to show I agreed.

**Comment by KharitonOff** [comment]
Sorry for this! Unfortunately I could not reproduce this issue or find the bug till now... We experience it only with this repository.
I'll work on this issue so far I have enough time again.

**Comment by tapdancemobile** [comment]
bump on this for me. I have tried it on two separate computers and two browsers...

**Comment by splix** [comment]
more context to @tapdancemobile issue:

- PR is here https://github.com/ethereumproject/emerald-mobile-wallet/pull/1
- there were same repo with that name, and @tapdancemobile already signed CLA for previous repo

**Comment by KharitonOff** [comment]
@tapdancemobile  @splix thanks, for reporting this. I think I can solve your problem by the end of the next week. Sorry for long delay. I hope it's ok for you.

**Comment by splix** [comment]
@KharitonOff sure, take your time. let us know if you'll need more information. thank you

**Comment by KharitonOff** [comment]
@tapdancemobile @splix we've done some fixes. Could you check please, whether your problem is solved now or not.

**Comment by splix** [comment]
I can confirm it was fixed
