### ISSUE TITLE
Commit blamed to generic email

### ISSUE THREAD

**Issue by chasehainsworth** [cla-assistant/cla-assistant#266]
After setting up Git on a new machine, I forgot to set my actual email to user.email. I made a commit, and it was blamed to: name@computername.local. Now, I am unable to [sign the CLA](https://github.com/sendgrid/docs/pull/3159) in a PR, since some of my commits aren't blamed to my actual email.

Adding the generic email to my account hasn't fixed it.

**Comment by KharitonOff** [comment]
it looks like you solved this issue on your own, should we close it?

**Comment by janainaCoelhoRocketchat** [comment]
how You solve this?
