### ISSUE TITLE
Export CSV only shows invalid characters

### ISSUE THREAD

**Issue by mosabua** [cla-assistant/cla-assistant#267]
We are using a metadata setup and I would like to be able to export the list now and then for our own records. However it seems that only invalid data (character encoding shows up). Is this feature supposed to work?

**Comment by KharitonOff** [comment]
@mosabua, yes it is. It works for me as expected. Could you provide more information, please? For which repo and gist are you trying to export signatures? Can you send me also an example of invalid data you get, please.

**Comment by mosabua** [comment]
Anton, can I email you that info please? You can contact me via the email in my profile. https://github.com/mosabua

**Comment by walmartlabs-cla-admin** [comment]
Thanks for reaching out. Turns out that the file is not comma but semicolon separated. In addition I found that the encoding was just picked up wrongly by my csv import tools (LibreOffice) and when playing around with different encodings it ended working just fine with ISO8859.

**Comment by mosabua** [comment]
Thanks for reaching out. Turns out that the file is not comma but semicolon separated. In addition I found that the encoding was just picked up wrongly by my csv import tool (LibreOffice) and when playing around with different encodings it ended working just fine with ISO8859.
