### ISSUE TITLE
Incorrect port environment variable in the documentation

### ISSUE THREAD

**Issue by Cry-Juan** [cla-assistant/cla-assistant#273]
Hi,

We are trying to host our own instance of cla-assistant. During the process we found out that the port is read from the environment variable HOST_PORT (at least for http), while the documentation says that the port number is read from PORT.

**Comment by KharitonOff** [comment]
@Cry-Juan thank you for pointing out this issue. I'll update the documentation. Actually PORT is used for the node server to start on and HOST_PORT is the port of the hosted instance (usually 443 or 80)
