### ISSUE TITLE
cla-assistant.io responds with 404 Not Found

### ISSUE THREAD

**Issue by tmbo** [cla-assistant/cla-assistant#276]
The webpage https://cla-assistant.io/ is not reachable, it responds with 

```404 Not Found: Requested route ('cla-assistant.io') does not exist.```

**Comment by KharitonOff** [comment]
sorry for that! Now it should be up again

**Comment by tmbo** [comment]
@KharitonOff It does, but now the repository doesn't show up any more (https://github.com/rasahq/rasa_core)

**Comment by KharitonOff** [comment]
sorry again, as described in #277 we have had some problems on our instance. Now it should work again. Could you confirm it?

**Comment by tmbo** [comment]
Yes looking good - thanks a lot for your effort :+1:
