### ISSUE TITLE
Does not report status

### ISSUE THREAD

**Issue by auchri** [cla-assistant/cla-assistant#279]
Hi!

In [this PR](https://github.com/telegramdesktop/tdesktop/pull/4068) it seems that the cla-assistant has not reported an status?

**Comment by KharitonOff** [comment]
@auchri has the user @PeterDaveHello already signed the cla?

**Comment by auchri** [comment]
No, he didn't sign the cla.
So the comment to sign the cla is missing too 🙈

**Comment by KharitonOff** [comment]
oh, i see, you're right. It seems that this PR was opened at the same time as CLA assistant has experienced some operational issues... I suppose that this is the reason why this PR didn't get any comment from CLA assistant.
I'll take this issue into consideration for further development, to find the way how we could solve it in future.
Sorry about that!

**Comment by auchri** [comment]
No problem! ☺

I think an easy solution would be to manually trigger cla assistant for an single PR via some button in the ui.

**Comment by Shegox** [comment]
Currently there exists a "Recheck PR" button from within the CLA-assistant, which triggers a recheck on all PRs to an associated repostiory/organization: 
![image](https://user-images.githubusercontent.com/16856448/128989689-ab541ebb-92e8-4813-8903-0ba2161fcd88.png)

Additionally you can force a manual recheck via manually navigating to following URL: 
```
https://cla-assistant.io/check/$ORG/$REPO?pullRequest=$PR_NUBER
# For example
https://cla-assistant.io/check/cla-assistant/cla-assistant?pullRequest=603
```

I think this should cover this quite good. In the future we could as well think about a more resilient and automatic recheck, but this should give people enough options to recheck in case the system has a hiccup.
