### ISSUE TITLE
Copyright notice on cla-assist.io

### ISSUE THREAD

**Issue by fabianschwarzfritz** [cla-assistant/cla-assistant#280]
Hi,
the copyright notice on [cla-assist.io](cla-assist.io) says "2015 SAP SE". 
Shouldn't this be 2017? 
Cheers

**Comment by thojansen** [comment]
Nope, I think this should not be updated yearly according to wikipedia. Please let me know if you find information that states the opposite.

**Comment by fabianschwarzfritz** [comment]
Yup, you're right. Interesting, I didn't know 👍
