### ISSUE TITLE
What is "org_cla" and why does it mean "Signed for Organization"

### ISSUE THREAD

**Issue by AlexEvanczuk** [cla-assistant/cla-assistant#283]
Trying to figure this out -- what does it mean that someone signed for an organization?  This is coming up as false for us, but I'm not sure what it means or why it is showing up.

**Comment by KharitonOff** [comment]
this flag indicates, whether the signature relates to the linked Repo or Org. 
In CLA assistant you can link an organization (with all repositories in it) as well as a single repository. If you link your org. and a user signs the CLA, this signature becomes valid for every repo in your organization and there is no need to sign CLA again if the user contributes to another repo of the org.
