### ISSUE TITLE
Append .md file extension to the file containing SAP Individual Contributor License Agreement

### ISSUE THREAD

**Issue by msohn** [cla-assistant/cla-assistant#293]
Could you add the .md file extension to the file "SAP_CLA" containing the SAP Individual Contributor License Agreement so that the page's [1] markdown content is rendered properly ? See e.g. the link from openui5's contributor guide [2] which is showing the raw file content instead of rendering the markdown.

[1] https://gist.github.com/CLAassistant/bd1ea8ec8aa0357414e8
[2] https://github.com/SAP/openui5/blob/master/CONTRIBUTING.md#contributor-license-agreement

**Comment by KharitonOff** [comment]
this issue relates to the #238
