### ISSUE TITLE
CLA Assistant was unlinked and removed but still haunts old pull requests

### ISSUE THREAD

**Issue by ttmc** [cla-assistant/cla-assistant#294]
Yesterday I did a trial with CLA Assistant on the bigchaindb/bigchaindb repository. It didn't work as expected so I unlinked it and removed it as best I could from all settings.

Unfortunately, it's still giving a warning (yellow dot) on all the pull requests that existed at the time of my experiment.

![screenshot from 2017-12-05 12-14-06](https://user-images.githubusercontent.com/1210951/33604343-e70d0434-d9b5-11e7-9596-15dcbd387069.png)

Clicking on "Details" leads to a page with:

![screenshot from 2017-12-05 12-14-24](https://user-images.githubusercontent.com/1210951/33604331-dcd65948-d9b5-11e7-97c8-151117918f8b.png)

New pull requests aren't affected.

There are more details in the comments of issue https://github.com/bigchaindb/org/issues/34

**Comment by KharitonOff** [comment]
I'm sorry for that, but we don't have any "roll back"-mechanism for statuses. So far I know, there is no way (no GitHub-APIs) to delete existing status at all.
