### ISSUE TITLE
Added email to github but still says that it is not signed.

### ISSUE THREAD

**Issue by Helias-Criouet** [cla-assistant/cla-assistant#295]
I have a problem that I have accepted CLA with my primary GitHub account.

It says `Name seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.`

I have added my email which was used for commit but nothing changed. PR is here: appium/appium-ios-simulator#138

**Comment by KharitonOff** [comment]
Now CLA assistant has to be triggered in order to check this PR again. There are two ways: a new commit on this PR or an admin of the repo has to click „Recheck PRs“ in CLA assistant‘s admin view.

**Comment by Helias-Criouet** [comment]
Thank you for the quick answer :)
