### ISSUE TITLE
Could I let CLA assistant handle private repo?

### ISSUE THREAD

**Issue by LinuxGit** [cla-assistant/cla-assistant#296]
I run a private docker instance and linked to a org, but only listed public repos. Could I let CLA assistant handle private repo? Thanks.

**Comment by KharitonOff** [comment]
@LinuxGit sorry for late response.
As far I know you can include private repos by changing the Auth scope of the App. That means, you have to add scope `'repo'` to the `admin_scope` in `src/config.js`
Restart your CLA assistant, sign out and sign in again.

**Comment by LinuxGit** [comment]
@KharitonOff Thanks for your reply. I tried it before, and `-v /home/pingcap/cla-assistant/src/config.js:/cla-assistant/src/config.js ` to docker instance. It didn't work.

**Comment by KharitonOff** [comment]
ok, maybe I was thinking in a wrong direction... You don't want to see the private repo in the list of linked repos / dropdown list to link it, but you are expecting CLA assistant reacting on PRs in the private repos of the linked Org. If it's so, then you can probably fix it by changing the if-statemnet here:
https://github.com/cla-assistant/cla-assistant/blob/43c801ec5b89bb0dde7e6b9795045969180d39ca/src/server/webhooks/pull_request.js#L105

**Comment by LinuxGit** [comment]
@KharitonOff I tried remove `req.args.repository.private == false` in the if-statement before and add scope 'repo' to the admin_scope in src/config.js.  But when I configure CLA, and Choose an org or a repo, I can't find any private repos in the dropdown list. So I can't linked it. Then I'm  expecting CLA assistant reacting on PRs in my private repo.

**Comment by MichaelTsengLZ** [comment]
We have set up the CLA-Assistant successfully for private repos. After adding the scope of 'repo', I think you need to revoke the previous OAuth app permission and then logout and login to grant the OAuth app different access. The tricky thing to support private repos is that you need to make sure the CLA bot has access to make comments in those private repos.

**Comment by LinuxGit** [comment]
@MichaelTsengLZ Thanks. After adding the scope of 'repo', revoke the previous OAuth app permission and grant again, I could find org's private repos in the dropdown list now. But when I use CLA bot GitHub account to login,  after linking the `CLA` column was empty, chrome tools reported:
```
http://IP:5000/api/repo/create` 
Request Method:POST
Status Code:404 Not Found
```
When I use my GitHub account to login, after linking org's private repo,  the `CLA` column was OK,  but When I access http://IP:5000/(repo name)?pullRequest=61, returned:
```
Error
There is no CLA to sign for `repo name`.
({"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"})
```
Linking my public repo, everything is OK.
