### ISSUE TITLE
Website: Authentication Error

### ISSUE THREAD

**Issue by JeromSar** [cla-assistant/cla-assistant#300]
The website currently spouts an internal server error. I've also noticed that some people who have previously signed our CLA do no longer appear to have done so.

**Comment by KharitonOff** [comment]
@JeromSar Thank you very much for reporting the issue! There seems to be a problem with a db-collection. Now it should work. Unfortunately the affected user have to sign the CLA again.

**Comment by JeromSar** [comment]
@KharitonOff I really hope you can restore a backup of the DB. Over 100 people signed our CLA, some of which can no longer be reached (Github account closed). Is there anything you can do?

**Comment by KharitonOff** [comment]
@JeromSar oh, no, I think you've misunderstood me. Our DB is ok, the problem was in a lost connection to it. It lasted about 2 hours. All signatures, done during this timeframe could not be saved. I'm sorry for that. But all other signatures happened before and after are available.

**Comment by JeromSar** [comment]
@KharitonOff I didn't see your last message until now. I see that the DB is okay. Thanks for your help! :)
