### ISSUE TITLE
Checker stuck on "Waiting for status to be reported"

### ISSUE THREAD

**Issue by decause** [cla-assistant/cla-assistant#303]
Thank you all for building and hosting such a useful tool for Open Source communities :)

One of our projects is having an issue where the check on the PR is stuck at "waiting for status to be reported."

When I look at my cla-assistant.io dashboard some of the UI elements are there, but some text columns are missing? 
When I mouse over the "link" icon, there is an 'x' next to the 'gist' item as well.
When I checked for the gist though, it is still there on our account.

Has anyone else reported anything like this, or is it isolated to our GitHub organization?

Thanks Much,
--RemyD.

**Comment by KharitonOff** [comment]
Thank you for reporting this issue and for your positive feedback!
No one has reported this issue yet. But this sounds like a bug, unfortunately I could not reproduce it yet. 
My assumption is that there is a conflict between the "old" link (twitter/reasonable-scala) and the new one (org twitter). CLA Assistant should handle both links properly and such constellation works fine in the test system. 
Another possible root cause could be a wrong token stored for the "old" link. This shouldn't happen too.
I'll let you know as soon I have any concrete findings/solution.

**Comment by decause** [comment]
@KharitonOff Thanks for getting back to us :)

So, your proposed fix would be to re-link the gist for our entire GitHub org? If that is the case then:

If we use the same gist text for the org-wide linked CLA, will CLA-Assistant be able to tell that people have already signed it, or will everyone have to re-sign it again?

**Comment by KharitonOff** [comment]
Maybe you can relink the repo, but not the whole organisation (org link seems to work properly).
If you relink your repo using the same gist (url) as before, then all previous signatures remain valid. Only if you change the Gist file itself or use another Gist file (url) everybody will have to sign the "new"/changed CLA again.

**Comment by decause** [comment]
![screenshot from 2018-01-09 14-11-36](https://user-images.githubusercontent.com/427420/34745942-1a80b728-f547-11e7-832a-9edc0bf020ee.png)

The dashboard no longer lists the URL to our gist, nor the number of signatories, and the export link is also missing.

When I click "configure cla" button at the top, it doesn't allow me to select the our org, or the repositories within that org (although it does allow me to select other repos/orgs I have access to in the dropdown.)

Please advise,
--RemyD.

**Comment by KharitonOff** [comment]
@decause thanks again for reporting the issue and providing us with further information! I strongly believe that we've found the route cause of your problem: we assumed a certain url style of the gist file (without hashtag and file name in it). In couple minutes it should work properly again. Could you confirm it, please?

**Comment by decause** [comment]
@KharitonOff Thanks again for all your help and support :)
![screenshot from 2018-01-10 12-39-30](https://user-images.githubusercontent.com/427420/34794431-772ce142-f603-11e7-8085-eb6bef30589b.png)

Though there is now the proper information populated for our org (yay!) the "repository" section where we were testing the service before turning it on for all repos seems to still be empty? We had two listed there previously? It's not a dealbreaker on our side necessarily, but it was useful to see on a per-repo basis, how many signatories there were.

SN: I know this is unrelated to this ticket, but it'd be *really* helpful/useful to include a mapping of who signed the CLA originating from which repository in the UI (even though in our case it applies to all of them.) It would seem there is a field for doing so in the exported .csv file, but it looks empty?

**Comment by KharitonOff** [comment]
Ok, I didn't realise that your repos disappeared too. I think I've found and fixed the route cause of this problem, but I'll be able to release the fix tomorrow first. I hope it's ok for you.

**Comment by decause** [comment]
Things look like they're back to normal 👌 

Thanks all for your support 💯
