### ISSUE TITLE
I have signed the CLA but the comment isn't updating

### ISSUE THREAD

**Issue by KyeMaloy97** [cla-assistant/cla-assistant#306]
URL to the linked Repo/Org: https://github.com/TestingCLA

Steps to reproduce the problem:

1. Open a PR
2. Comment says to sign it, when I have already signed (my GitHub ID is on the the dashboard at cla-assistant.io)
3. If I follow the link the page says "You have already signed the CLA"

What is the expected result?
The comment to go green and tell me I have signed.

What happens instead?
It remains yellow, even when I press recheck on the comment or Recheck PRs on the dashboard.

**Comment by KharitonOff** [comment]
Hi @KyeMaloy97 have you signed the CLA as @KyeMaloy97 or as @kyemaloythrowaway (the last one is the committer)

**Comment by KyeMaloy97** [comment]
Oops yea my mistake, I had FireFox open when my throwaway account was logged in on Safari. Would there be any way of opening a warning saying the PR contains a commit by <PERSON> and <PERSON> hasn't signed the PR?

**Comment by KharitonOff** [comment]
🤔  where and when would you show this warning?
