### ISSUE TITLE
Do I have to sign my own CLA?

### ISSUE THREAD

**Issue by LNFWebsite** [cla-assistant/cla-assistant#309]
This isn't a bug with CLA Assistant so much as it is a general question.

When submitting PRs to my own project (I make changes via commits to master and then merge them into the gh-pages branch), should I sign my own CLA?

I'm not savvy to the legalities of signing my own CLA but wanted to make sure that it is common practice before I do it...

Thanks!

**Comment by KharitonOff** [comment]
this is not really a common practice, but it is how CLA Assistant is designed now. Maybe we'll get a contribution which addresses this issue... (see #197 )
