### ISSUE TITLE
Error Boxes

### ISSUE THREAD

**Issue by yaseminc** [cla-assistant/cla-assistant#31]
**highlight error fields (=text boxes)**

- outline orange # ff803f
- box filling: #ffe5c9
- add orange text description beneath text box
![screen shot 2015-05-12 at 11 12 58 am](https://cloud.githubusercontent.com/assets/11296839/7583688/e058f960-f897-11e4-953a-76512c9c39bd.png)

**Error message if:**

1. repository is already linked with a CLA Gist file:
"Whoops! This repository is already linked. Try to choose another one :)"

2. User clicks on "Link them" w/o having chosen a repo and/or URL:
"Please enter a repository and a valid ~~Gist URL~~"  [ ~~Gist URL~~ is underlined and linked to Gist]
or: "Please choose a repository"
or: "Please enter a valid ~~Gist URL~~"

3. Gist URL is not correct:
"Oops, looks like this link isn't correct. The ~~Gist URL~~ should look like this: https://gist.github.com/..."

**Comment by yaseminc** [comment]
Feedback for "My Signed CLAs": "You have no signed CLAs so far."

**Comment by KharitonOff** [comment]
- [ ] user has no repos in github - let him know that cla-assistant doesn't make much sense without github repos

**Comment by thojansen** [comment]
closing for now
