### ISSUE TITLE
CLA as a gist: secret or public?

### ISSUE THREAD

**Issue by GuyPardon** [cla-assistant/cla-assistant#312]
Hi,

Quick question: if we configure our CLA as a gist for use with your product then can this be a "secret" gist or does it have to be a public one?

Thanks

**Comment by thojansen** [comment]
As anyone sees this gist when signing it and can kick off that workflow even without a PR, I do not see how a secret gist would make any sense.

**Comment by GuyPardon** [comment]
Thanks - but I read that secret gist instances are not private but just not searchable. Also see https://help.github.com/articles/about-gists/ 

I guess a secret one would do, no?

**Comment by KharitonOff** [comment]
It doesn’t matter for CLA Assistant. You can link both. So, a secret one is ok.
