### ISSUE TITLE
Timeout when configuring org

### ISSUE THREAD

**Issue by mosabua** [cla-assistant/cla-assistant#314]
I am trying to configure an organizations github.com/testarmada to use my cla-assitant configuration that already works in 3 other organizations on github with the same user. 

The user is an owner of the org but when I try to configure it the pop up dialog just shows a spinning wheel and it never finished. 

When I close the dialog the org is either not configure or it is configured but the webhooks config seem not complete since the status shows that.

**Comment by KharitonOff** [comment]
Unfortunately I could not find anything in the log entries. Could you send me the console output from your browser, please?

**Comment by mosabua** [comment]
I let it run for a while again and now have it configured but with the webhooks having an issue. Can I somehow kick of the config to be refreshed/updated? Or what could be the issues for this otherwise .. some user permissions or so?

**Comment by mosabua** [comment]
<img width="385" alt="screen shot 2018-03-13 at 08 21 55" src="https://user-images.githubusercontent.com/145658/37351235-d6ae4a6a-2697-11e8-95c3-d75f194386a2.png">

**Comment by KharitonOff** [comment]
The issue could be in permissions, but if you see this organization in the dropdown list, then all needed permissions should be provided to CLA Assistant.

Can you check whether there is a webhook in settings of your organization? (settings -> webhooks)
Can you also check your profile settings, please: settings->Applications->Authorized OAuth Apps->CLA assistant 
And can you also check one more place - whether CLA Assistant has access to your org: org settings->Third-Party access

**Comment by mosabua** [comment]
None of these were there. I am going to try recreating the config from CLA assistant

**Comment by mosabua** [comment]
I think I found the problem .. the org in which it is not working has Third Party access set to restricted ... but I cant take that off without loosing that config I think. How can I add CLA assistant now?

**Comment by KharitonOff** [comment]
If you go to your profile `settings->Applications->Authorized OAuth Apps->CLA assistant` you can grant there CLA Assistant access to the org again.

**Comment by mosabua** [comment]
Perfect. That did the trick. Thanks!
