### ISSUE TITLE
Slack integration possible on cla-assistant.io ?

### ISSUE THREAD

**Issue by gsaslis** [cla-assistant/cla-assistant#315]
Hi folks! 

Thanks for the amazing work on this!!  🤘 

I noticed your Readme mentions it is possible to self-host and setup Slack notifications, but i was wondering if this option is also available on cla-assistant.io somehow?

Thanks in advance!
Yorgos

**Comment by thojansen** [comment]
The current Slack integration is more focused on the operations part of cla-assistant itself. What would be your uses cases for a Slack integration? Do you want a notification each time a CLA is signed (might be too much) or do you have something else in mind?

**Comment by gsaslis** [comment]
@thojansen thanks for the prompt reply! 

yes, some kind of notification each time a CLA is signed, so i can keep track of the new contributors.

**Comment by KharitonOff** [comment]
Nice Idea!
@gsaslis as Thomas said, we use Slack for operational use cases. 
If you wish, you are very welcome to contribute and extend this integration. We would be glad to support you here if needed!

**Comment by gsaslis** [comment]
@KharitonOff awesome! thanks! 

your help will be much needed, as I'm very unfamiliar with the JS world. 
I started a PR, so I can get your feedback on whether i'm following the right approach with adding this logic in the right place. 

https://github.com/cla-assistant/cla-assistant/pull/325

Looking forward to your feedback  ; )
