### ISSUE TITLE
Company account gist?

### ISSUE THREAD

**Issue by GuyPardon** [cla-assistant/cla-assistant#318]
Hi,

While trying to create an account, I could login with my personal github account 'GuyPardon'. However, I would like to create a company gist. How do I create a company account?

Thanks
Guy

**Comment by KharitonOff** [comment]
Hi Guy, 
as far I know, this is not possible. You can create a personal account, create a gist with it and convert it to an organization (https://stackoverflow.com/questions/20647454/how-can-you-create-github-gists-that-live-under-an-organization-account-instead). But there is no way to create a gist for an org.

Regards
Anton

**Comment by GuyPardon** [comment]
OK so I have a "personal" gist in there for now. 

Questions: 

1. Why can't I just give any URL to a web page with the license? Why does it have to be a gist?

2. If it needs to be a gist: can you hide the gist URL when it shows up - so my github profile is not necessarily involved in all this?

Thanks

**Comment by KharitonOff** [comment]
1.: we use gist in order to 
 - handle different versions of a CLA
 - have a unified storage place, which everyone can access and easily use
 - have a standard format handling (provided by GitHub - no need to do it on our own)
2. Gist url doesn't show up for the contributors. Only repo/org-owners can see it in the admin ui of CLA Assistant - do you want to have it hidden there ??

**Comment by KharitonOff** [comment]
You can also create a dummy GitHub account and share the credentials with other org members (e.g. put it in a secret repo of your org if you have a payed account).

**Comment by GuyPardon** [comment]
OK seems to work so far - thanks!

Where can I see the "accept" history?

**Comment by KharitonOff** [comment]
just click on the number in the admin ui to see the list of contributors, who has signed the CLA
<img width="237" alt="screen shot 2018-03-22 at 15 12 09" src="https://user-images.githubusercontent.com/8480657/37775691-dfd8a10a-2de3-11e8-8c59-14cd2fe52c02.png">

**Comment by GuyPardon** [comment]
Perfect, thank you!

**Comment by GuyPardon** [comment]
Sorry for re-opening, but I can't seem to find the admin ui (to see the list of contributors) any more - can you help me find it?

Thanks

**Comment by KharitonOff** [comment]
@GuyPardon can you check the admin screen again, please? GitHub has recently experienced long time outage of some services, thats why CLA assistant could not display all data correctly.

**Comment by KharitonOff** [comment]
I assume you could find it again and close the issue, if not feel free to reopen it again 😄
