### ISSUE TITLE
Failed to configure CLA

### ISSUE THREAD

**Issue by uKL** [cla-assistant/cla-assistant#319]
Hi,

I'm a member of an organization and I'm trying to configure CLAs.

I'm getting issues & a webhook is not created.

Chrome Dev Tools is showing that there's a 404.

```
Request URL:https://cla-assistant.io/api/repo/create
Request Method:POST
Status Code:404 
Remote Address:104.31.73.128:443
```
Request Headers:
```
:authority:cla-assistant.io
:method:POST
:path:/api/repo/create
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, br
accept-language:pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
content-length:173
content-type:application/json;charset=UTF-8
cookie:__cfduid=XXX; _ga=GA1.2.1298856328.1517332313; _gid=GA1.2.389423634.1521541801; connect.sid=XXX
origin:https://cla-assistant.io
referer:https://cla-assistant.io/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
```
Payload:
```
{"repo":"FlutterBleLib","owner":"Polidea","repoId":121622800,"gist":"https://gist.github.com/6796564f4b8c9a769325bbe2f0bda241","sharedGist":true,"fork":false,"active":false}
```
Response:
```
"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/hooks/#list-hooks\"}"
```

Any thoughts? This may a permission issue but I'm not able to guess.

**Comment by KharitonOff** [comment]
Yes this sounds like a permission issue...
can you check your settings, please (see https://github.com/cla-assistant/cla-assistant/issues/314#issuecomment-372943242)

**Comment by uKL** [comment]
![zrzut ekranu 2018-03-23 o 08 39 46](https://user-images.githubusercontent.com/2377962/37817110-e2665484-2e75-11e8-9040-672667e06363.png)

It seems to be right. Projects I'm trying to add are withing the Polidea organization.

**Comment by uKL** [comment]
Maybe it's something about my personal permissions within the organization? I managed to add one project but I'm unable to add more.

**Comment by uKL** [comment]
I'm not an owner but the member. I'll check permissions to specific repositories.

**Comment by uKL** [comment]
It looks that I can configure project only if I have admin rights, write is not enough. I'll verify it by changing my permissions to admin.

**Comment by uKL** [comment]
This is the case. I need to have admin access to each repository.

It would be great to see some kind of error instead of a spinning chain cell.

**Comment by KharitonOff** [comment]
👍 You are right. I've created a separate issue for that

**Comment by uKL** [comment]
Thanks!
