### ISSUE TITLE
Options: Choose a CLA in Gist

### ISSUE THREAD

**Issue by yaseminc** [cla-assistant/cla-assistant#32]
We have **two options**:

- choose a CLA from the **drop-down menu**
- paste a URL from Gist in a **type-in box**

**drop-down menu:**
View default choice. If not acceptable,
- click on down-arrow to show choices
- scroll through list if necessary
- click on one option to select it.
-grouping options by repo owners?

e.g: **reviewninja**

            reviewninja/welcome
            reviewninja/dcode
            reviewninja/foo

like here:

![screen shot 2015-04-30 at 10 52 37 am](https://cloud.githubusercontent.com/assets/11296839/7409484/0bc02346-ef27-11e4-92dc-248b04866337.png)

One of the options could be blank.

What happens if I choose a stored CLA from drop-down menu?
- the paste/type option is not selectable
- Choose meta-option ("--") when I chose a a list item and decide to rather paste/type in a link?
[- Default value (= SAP CLA) ?]
[- what if there are too many options? --> start typing the name, auto-complete field (that can handle typos..)?]

- have it as a text field with auto-complete and option to drop down and search from the menu?

**type-in box:**
If I type/paste in a URL in the type-in box:
->Type in a response or leave the box blank.
- what happens to a preselected list item in the drop-down menu?
  __which one has priority? can we combine the choosing options?

*prompt text in italic gray and real text in normal dark primary color*

**Comment by KharitonOff** [comment]
@yaseminc could you review it again :)?

**Comment by yaseminc** [comment]
have a little less indent :)
![bildschirmfoto 2015-05-15 um 16 29 47](https://cloud.githubusercontent.com/assets/11296839/7654759/abd958bc-fb1f-11e4-84d9-a8adeafe2885.png)

**Comment by KharitonOff** [comment]
please reopen if something is missing
