### ISSUE TITLE
Status pending with my account

### ISSUE THREAD

**Issue by andrescolodrero** [cla-assistant/cla-assistant#321]
URL to the linked Repo/Org:

Steps to reproduce the problem:
1. SIgn in github with my account: andrescolodrero@gmail.com
2. Create Pull request: https://github.com/OctopusDeploy/Library/pull/667
3. Sign the CLA
4. Status pending

What is the expected result?
CLA Completed

What happens instead?
CLA assistant check 
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.

Andres Colodrero seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.
You have signed the CLA already but the status is still pending? Let us recheck it.

## Optional
I cant edit the agreement
![image](https://user-images.githubusercontent.com/4639270/38360418-a4587174-38b9-11e8-8c03-2be532623894.png)

Browser/version:

Any other tested browsers/devices(OK/FAIL):

**Comment by KharitonOff** [comment]
check the following link, please:
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user
