### ISSUE TITLE
CLA status mismatch

### ISSUE THREAD

**Issue by wavezhang** [cla-assistant/cla-assistant#322]
URL to the linked Repo/Org:
https://github.com/drone/drone

Steps to reproduce the problem:

1. open pull request https://github.com/drone/drone/pull/2324
2. Signed the CLA for drone/drone

![image](https://user-images.githubusercontent.com/832911/38779377-fcbdf3aa-40f9-11e8-82d1-c2c29268f822.png)

3. Check status of CLA
![image](https://user-images.githubusercontent.com/832911/38779383-205c483e-40fa-11e8-8f63-bfc44b2c27bf.png)

What is the expected result?
CLA signed
What happens instead?
CLA not signed
![image](https://user-images.githubusercontent.com/832911/38779383-205c483e-40fa-11e8-8f63-bfc44b2c27bf.png)

**Comment by KharitonOff** [comment]
@wavezhang , CLA Assistant checks the committers of the PR, whether they have signed the CLA or not. In your PR you have used an invalid email address, so GitHub can't recognise you as a committer and CLA Assistant won't change the status to green.
