### ISSUE TITLE
Link individual repositories in an organization

### ISSUE THREAD

**Issue by erickpeirson** [cla-assistant/cla-assistant#324]
I'm excited to start using cla-assistant! But I'm a bit puzzled by (apparent) limitation that one cannot use cla-assistant for individual repositories within an organization. 

Here's what I see when I click "want to link an org?" in the Configure CLA view:

![image](https://user-images.githubusercontent.com/3451594/39144197-117082e0-46fe-11e8-83cf-ed5c76175bdb.png)

Enabling cla-assistant for all repos in the organization is not acceptable for my use-case. Indeed, I would need to be able to configure CLAs separately for individual repos in the organization, and only for a small number of such repos (an exclusion feature, as suggested in #157 would not really be practical). 

The ideal situation would be if organization repositories were treated in precisely the same way as personally-owned repositories, similar to Travis-CI, Coveralls, and other such CI/CD platforms.

Can you provide any guidance about development plans around organization repositories? Thanks for your help!

**Comment by thojansen** [comment]
The "link to an org." feature is an optional step which you can ignore if you do not want to use it. Just follow the three steps for an individual repo and you should be good to go. It does not matter if this is a personal one or an org. one. You should see all repos where you are an owner in the dropdown list.

**Comment by erickpeirson** [comment]
On a hunch, I checked the OAuth application settings on GitHub, and it looks like org access hadn't been granted. Granting it did the trick. Sorry for the false alarm. Perhaps this is a feature request for a tooltip or help text describing this scenario?

Thanks for putting together a great project!
