### ISSUE TITLE
Sign the agreement (multiple times) but project says it still is not signed

### ISSUE THREAD

**Issue by wyy912** [cla-assistant/cla-assistant#326]
https://github.com/alibaba/freeline/pull/985
I sign multiple times, but the second still not work

**Comment by KharitonOff** [comment]
@wyy912 you can ignore the second comment. Since the status of the PR is green, everything is ok.
Actually there should be only one comment from CLA assistant. I'll take into consideration that there is probably a bug on our side.

**Comment by wyy912** [comment]
thank you so much
