### ISSUE TITLE
user consent to privacy policy

### ISSUE THREAD

**Issue by thojansen** [cla-assistant/cla-assistant#329]
Until May 25th, we need to check for user consent.
> The person whose personal data should be processed (data subject) has explicitly consented to the processing for one or more specific purposes, e.g. by accepting a privacy policy before personal data is provided.

**Comment by thojansen** [comment]
Currently checking with Legal if we need explicit consent of if the current terms are sufficient.

**Comment by KharitonOff** [comment]
no need for explicit consent on our side, but a possibility for project owners to get a user consent to the processing the data in accordance to the project owner's privacy policy
