### ISSUE TITLE
Setup your own instance of CLA assistant Docs

### ISSUE THREAD

**Issue by nac2791** [cla-assistant/cla-assistant#334]
I am having trouble getting my instance up and running. I am trying to get a test instance going for my company internally on a GHE instance. I was able to find the overrides in [src/config.js](https://github.com/cla-assistant/cla-assistant/blob/master/src/config.js#L11) to get the API calls working to the GHE instance but I am having problems when the application is hitting the `/count/stars` endpoint. The application crashes with a 404 with the response.

Is there any additional configuration needed to get cla-assistant working with a GHE instance? Also, what permissions need to exist on the cla-assistant GitHub app. The only documentation I see for perms is on the user and thats `repo-only`

```
✓ bootstrapped, app listening on localhost:5000
{"name":"localhost","hostname":"565b43154af8","pid":18,"level":30,"msg":"✓ bootstrapped !!! App listening on localhost:undefined","time":"2018-06-04T16:55:58.927Z","src":{"file":"/cla-assistant/src/server/app.js","line":195},"v":0}
{"name":"localhost","hostname":"565b43154af8","pid":18,"level":30,"err":{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.13/v3/repos/#get\"}"},"msg":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/enterprise/2.13/v3/repos/#get\"}","time":"2018-06-04T16:56:07.443Z","src":{"file":"/cla-assistant/src/server/controller/counts.js","line":146},"v":0}
/cla-assistant/src/server/controller/counts.js:149
            count: resp.stargazers_count
                       ^

TypeError: Cannot read property 'stargazers_count' of null
    at /cla-assistant/src/server/controller/counts.js:149:24
    at collectData (/cla-assistant/src/server/services/github.js:112:21)
    at /cla-assistant/src/server/services/github.js:34:13
    at __dirname.sendError (/cla-assistant/node_modules/github/lib/index.js:801:7)
    at /cla-assistant/node_modules/github/lib/index.js:809:21
    at callCallback (/cla-assistant/node_modules/github/lib/index.js:685:9)
    at IncomingMessage.<anonymous> (/cla-assistant/node_modules/github/lib/index.js:749:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by KharitonOff** [comment]
@nac2791 sorry for long delay.
This is definitely a buggy implementation of the start screen! We will fix it in the next release.
If you wisch you can just comment the activity block in the login.html https://github.com/cla-assistant/cla-assistant/blob/48ac830ed81e2c764f4d297be63cb74f180644c5/src/client/login.html#L123-L135
 
and the api call in the controller/home.js
https://github.com/cla-assistant/cla-assistant/blob/48ac830ed81e2c764f4d297be63cb74f180644c5/src/client/controller/home.js#L295-L305
