### ISSUE TITLE
Update CLA without losing current signatories or keep records across versions

### ISSUE THREAD

**Issue by mfreed** [cla-assistant/cla-assistant#337]
My understanding/experience has been if we change the CLA, it effectively looks like a new document from the perspective of the system, so requires that we get new signatures.  I understand the purpose of this to avoid projects changing the terms of the CLA without appropriate acceptance by users.

In our case, we recently changed the legal name of our company, and prefer that our CLA reflects the current corporate name.  That's the sole change we want to do to the CLA. Is there any way to do this or do you have any suggestions?

Alternatively, does the CLA-assistant service provide a good way to support (or at least report) multiple versions of the CLA document?  If I post a new CLA document, it would be great if you'd be able to still keep a record of those signatures on the old version of the document, to be able to match a particular PR/contribution to the CLA at the time of consent.

(While not needed for this request, our agreement for reference: https://cla-assistant.io/timescale/timescaledb )

**Comment by KharitonOff** [comment]
If I understand you right, this feature is already available. All signatures remain untouched for each version of your CLA. If you click on the number of signatures for a linked repo, you'll see the list of signees for the current CLA version. There is also a dropdown list, where you can switch between the versions of your document or take a view on the list of all signees of all versions. 

![screen shot 2018-06-11 at 09 59 42](https://user-images.githubusercontent.com/8480657/41219331-3e6bd00c-6d5e-11e8-9966-e96dca8e7a71.png)
