### ISSUE TITLE
Allow selecting single repos for new type of Orgs

### ISSUE THREAD

**Issue by mastrolinux** [cla-assistant/cla-assistant#338]
No way to select single repo on new orgs. The single repo feature is only available for old type of orgs.

URL to the linked Repo/Org:
https://github.com/bcmi-labs

Steps to reproduce the problem:

1. Link your org by granting access
2. Try to select single repo
3. You will only see forked repos but not all the repositories the organization has:
![image](https://user-images.githubusercontent.com/1333971/41401393-07fae4d6-6fc0-11e8-99f1-0ca226cb6724.png)

What is the expected result?
I would like to have the same behavior as old type of orgs where I can see all the repos.
![image](https://user-images.githubusercontent.com/1333971/41401443-2ccd4dd0-6fc0-11e8-80a7-c7f15e6204a7.png)

What happens instead?
Only forked repos are visbile, maybe it is just a limit on the number of repos, consider Arduino has more than 100 repos and bcmi-labs more than 250.

**Comment by KharitonOff** [comment]
@mastrolinux could it be that the repos, you can't find for bcmi-labs are private? If I go to the provided url GitHub says, there are only 10 Repositories.
![screen shot 2018-06-14 at 16 19 46](https://user-images.githubusercontent.com/8480657/41418039-362b3098-6fef-11e8-9d82-5a5b45c498a1.png)

**Comment by KharitonOff** [comment]
@mastrolinux could you solve this problem?

**Comment by mastrolinux** [comment]
Yes, looks like the app does not work with private repos, I think it should be documented, it would be useful for testing.

**Comment by KharitonOff** [comment]
Good idea, you are welcome to help us here and update the description in the way you would expect it 👍
