### ISSUE TITLE
CLA assistant is down

### ISSUE THREAD

**Issue by alonsocamaro-test** [cla-assistant/cla-assistant#341]
## Required

URL to the linked Repo/Org: https://cla-assistant.io/accept/f5devcentral/f5-tmsh2iapp?pullRequest=5

Steps to reproduce the problem:

1. Send a pull request
2. Try accepting it

What is the expected result?

The site to be up

What happens instead?

Please see attached screenshot

**Comment by alonsocamaro-test** [comment]
Attached screenshot of the issue:

<img width="1497" alt="screen shot 2018-06-18 at 17 02 37" src="https://user-images.githubusercontent.com/40360012/41544600-72da4b32-7319-11e8-8f3d-e4135967505c.png">

**Comment by KharitonOff** [comment]
Now it should be solved. Can you test it again, please?

**Comment by alonsocamaro-test** [comment]
Yep, working like a charm.

Thanks! :-)
