### ISSUE TITLE
feature request: non overridable prefills of GitHub data

### ISSUE THREAD

**Issue by alonsocamaro** [cla-assistant/cla-assistant#344]
First of all thanks very much CLA assistant and running it

I wonder if it could be possible to make githubKey's not overridable, maybe by pulling them directly from github rather than from the form?

Many thanks

        Ulises

**Comment by KharitonOff** [comment]
Glad that you like and use CLA assistant!
There are a lot of GitHub accounts with fake names and other data. I think we should keep the possibility to override this data. 

A workaround could be in your case to create a form with 'hidden' fields, such fields are not presented to the user and could be filled with github data.

**Comment by alonsocamaro** [comment]
Thanks for the suggestion! 

I didn't realize of the hidden data. I will start using it straight away. Feel free to close this request if what I'm proposing is not doable.

With respect of the fake names and data I agree. I guess the solution is [https://github.com/cla-assistant/cla-assistant/issues/336](https://github.com/cla-assistant/cla-assistant/issues/336
) which I understand does not only apply when exporting the signatories.

From my part I'm advocating for the use of CLA assistant in my company and hopefully this will help you in the future.

Many thanks

**Comment by KharitonOff** [comment]
Ok, I'm happy that we could find a solution for your use case! And thank you very much for your support and advocating in your company!

**Comment by KharitonOff** [comment]
@alonsocamaro I think this feature is already implemented. Sorry for not letting you know it strait at the beginning and not having documented it properly (any help here would be appreciated 😄)... There is a type **'readonly'**. The only problem here is, these fields won't have a label. Is it what you needed?

**Comment by alonsocamaro** [comment]
@KharitonOff 

Ummm I'm not finding "readonly" in the JSON schema... what am I missing here?

Also, does this 'readonly' means that that data field cannot be tampered?

**Comment by KharitonOff** [comment]
Yes, as I said, it is not documented properly (even the JSON schema doesn't contain it) but it should work. And yes, 'readonly' means that the data field cannot be tampered. In combination with github_key it should work, like required from your side.

**Comment by alonsocamaro** [comment]
Thanks @KharitonOff !!! 

I gave it a try and it is working. I see that the fields are displayed in the form just not an editable text field. See attached a screenshot of:

```
    "name": {
        "title": "Full Name",
        "description": "(if contributing as individual)",
        "type": "string",
        "githubKey": "name"
    },
    "githubname": {
        "title": "GitHub name",
        "description": "(readonly)",
        "githubKey": "name",
        "type": "readonly"
    },
```

<img width="404" alt="screen shot 2018-06-21 at 18 55 52" src="https://user-images.githubusercontent.com/16683733/41733661-d3181be2-7584-11e8-93b8-621dc1d6ee99.png">

I will be glad adding this to the CLA-assist page. 

For documentation purposes, how is it assured that the "readonly" fields are not modified when sending the POST of the form?

Thanks again!

**Comment by KharitonOff** [comment]
> how is it assured that the "readonly" fields are not modified when sending the POST of the form?

It is not assured at all... At the end we just present this field as a label on the UI, so the normal user has no possibility to edit it. But the POST request can still be manipulated...

**Comment by alonsocamaro** [comment]
Thanks for the clarification @KharitonOff !

Talking with legal from my company they say that e-mail verification  would be a defense in the case "there was some enforcement action against us based on someone fraudulently submitting code that we redistributed".

Given that github does e-mail verification I believe it would be very interesting if this data is pulled by CLA-assistant server directly from github before storing it in the database.

Would it be possible? Could we reopen this issue for implementing this feature? Should I open a new issue?

Regards

**Comment by KharitonOff** [comment]
@alonsocamaro sure,  feel free to reopen the issue.
You are also very welcome to create a PR and propose your solution there 👍 
Isn't it enough from your legals point of view to identify the committer with his GitHub user name?

**Comment by alonsocamaro** [comment]
@KharitonOff let me get back to you next week
