### ISSUE TITLE
cla-assistant.io not functioning

### ISSUE THREAD

**Issue by lorensr** [cla-assistant/cla-assistant#345]
**URL to the linked Repo/Org:** https://github.com/GraphQLGuide/book/

### Steps to reproduce the problem:

1. Create a PR

### What is the expected result?

A comment should appear saying to sign

### What happens instead?

Nothing. For example: https://github.com/GraphQLGuide/book/pull/10

**Comment by KharitonOff** [comment]
@lorensr sounds strange. According to our logs, the GitHub API responded with no committers for both PRs. I can imagine that something went wrong during the setup and now, the communication between CLA Assistant and GitHub doesn't work properly... Could you relink your repository (remove the current link and create it again) in CLA Assistant, please?

**Comment by lorensr** [comment]
Fixed, thanks!
