### ISSUE TITLE
Redirects after signing end up with GitHub abuse detection mechanism when signing CLA

### ISSUE THREAD

**Issue by pelsasser** [cla-assistant/cla-assistant#348]
URL to the linked Repo/Org:
https://github.com/MARKETProtocol/MARKET.js

Steps to reproduce the problem:

1. Open a PR
2. Attempt to sign CLA

Here is an example where one contributor receiving the error - https://github.com/MARKETProtocol/MARKET.js/pull/57#issuecomment-401833531

What is the expected result?
signing is successful 

What happens instead?
Several redirects looping until GitHub complains

**Comment by pelsasser** [comment]
Also have seen this as well when trying to sign CLA for same repo 

![image](https://user-images.githubusercontent.com/15096737/42177936-ca92df1a-7deb-11e8-9ca1-01c89a5ebe55.png)

**Comment by KharitonOff** [comment]
Thanks for reporting this issue. I'm looking into it...

**Comment by KharitonOff** [comment]
@pelsasser now it should be solved. The problem was caused by browser caching mechanism, since your repo name ends with .js the http responses were cached in a different way than for other repos 😕 
Could you try it again and close the issue if it is working for you now, please?

**Comment by pelsasser** [comment]
@KharitonOff - issue looks to be resolved! Thanks so much for the quick response!
