### ISSUE TITLE
Requires JavaScript

### ISSUE THREAD

**Issue by dotlambda** [cla-assistant/cla-assistant#349]
Cla-assistant requires users to enable JavaScript in their browsers. I prefer not to do that for random sites.
Would it possible to implement it in such a way that basic functionality works without JS?

**Comment by KharitonOff** [comment]
@dotlambda CLA Assistant is an angular app. The whole logic is in javascript implemented. I can hardly imagine how to do this without JS. But we are always open for contributions from the OS community so you are very welcome to help us and improve CLA Assistant in this point 😃
