### ISSUE TITLE
List of my signed CLAs

### ISSUE THREAD

**Issue by yaseminc** [cla-assistant/cla-assistant#35]
- [ ] extra site for 'my signed CLAs': **Where?**

- [ ] Link on Landingpage 
- [ ] Link in footer of CLA assistant to view own contributions with signed CLAs

**Comment by KharitonOff** [comment]
related to #18

**Comment by KharitonOff** [comment]
further ideas:
 - provide ordering function on columns
 - don't show the gist url, but a button for modal view with CLA content

**Comment by mierschp** [comment]
so far every signed CLA of the user will be shown in the list, even the older versions. That means that the same repo will be listed several times. These entries should not be shown in the list, so that only the actual signed version of the CLA is listed

**Comment by mierschp** [comment]
@yaseminc I'm currently working at a solution to show the version-status of a CLA and could use your help as designer,  because currently I'm using the link-icons of the "Linked-CLA's", but in this context I don't think we should use them.

These icons should have two states:
- inactive/failure
-ok 

Do you maybe have some ideas?

**Comment by KharitonOff** [comment]
@yaseminc  in case you would like to see how it looks right now, you can go to https://preview.cla-assistant.io login and then go to https://preview.cla-assistant.io/my-cla ;)

**Comment by yaseminc** [comment]
hi @mierschp and @KharitonOff, so you want to indicate the status of the version of each CLA, do I get this right? I'd say take a grey filled circle and a white " ! " (like the current icon for inactive link) for inactive/failure and a check-icon in a circle for OK (green, and only the outline like in the icon for active link). can you do this by programming/ taking the icons from fontawesome or would you prefer me sending you svgs? this could take some time, probably until tomorrow night though.

**Comment by yaseminc** [comment]
like those: 

(those are just screenshots, please don't use them ;) )
![bildschirmfoto 2015-06-22 um 15 11 03](https://cloud.githubusercontent.com/assets/11296839/8282426/fc5115d4-18f0-11e5-8b5a-b372bc8021ee.png)

![bildschirmfoto 2015-06-22 um 15 11 18](https://cloud.githubusercontent.com/assets/11296839/8282427/fc68ab2c-18f0-11e5-829c-ca2a1410a6a6.png)

**Comment by mierschp** [comment]
hey @yaseminc we were trying around to do this by programming and some online tools, but it doesn't look that well... ^^
It would be really awesome, if you could send us some svgs :)

We really liked your idea with the "!" in a  filled circle and the check-icon in a green circle. 
But we didn't dicide yet, which color to choose for the "!"-icon, whether red or grey. Maybe you could decide, which one looks better? :)

**Comment by yaseminc** [comment]
sure, I'll send it to you ;)

2015-06-23 10:06 GMT+02:00 mierschp <notifications@github.com>:

**Comment by yaseminc** [comment]
sorry guys, I'll do it on the weekend!

**Comment by KharitonOff** [comment]
no problem, just take your time :smiley:

**Comment by mquandalle** [comment]
Any news on that?

**Comment by thojansen** [comment]
skipping this for now.. we will however fix #120 and make it possible to view an already signed CLA
