### ISSUE TITLE
Deleting hosted data?

### ISSUE THREAD

**Issue by robertDurst** [cla-assistant/cla-assistant#350]
Hey, sorry if a) this has already been answered and b) for not following the template.

If we want to delete the hosted data, can we? How does this process work?

**Comment by KharitonOff** [comment]
@robertDurst no Problem, the template is only for bug reporting there...
If you want to delete all signatures related to your repo/org you need to contact us via an issue or an email and provide the name of your repo/org. We'll do it for you.
