### ISSUE TITLE
List of signed contributors gone after adding whitelisted user

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#351]
URL to the linked Repo/Org: https://github.com/SAP/ui5-fs, https://github.com/SAP/ui5-tooling

Steps to reproduce the problem:

1. Click new "Edit" button
2. Add whitelisted user (e.g. "dependabot")
3. Refresh project list

What is the expected result?
List of signed contributors is still there as before

What happens instead?
List of signed contributors is empty. Even after logoff and logon again.

**Comment by KharitonOff** [comment]
@matz3 could you look into browser log, please? Do you see any errors there?

**Comment by KharitonOff** [comment]
I could reproduce this issue on my own now. I'll try to fix it as soon as possible. Thank you!

**Comment by KharitonOff** [comment]
@matz3 I found the problem and the fix is on it's way... You can get your contributors back by editing the repo and selecting the 'SAP individual CLA' again.
The problem was: there are different urls, leading to the CLA. On edit, the wrong url was taken for the default SAP's CLA (my fault).

**Comment by KharitonOff** [comment]
btw. the github name of dependabot is `dependabot[bot]`, so you have to whitelist either `dependabot[bot]` or `*[bot]` or `dependabot*`
