### ISSUE TITLE
Send email on new signatures.

### ISSUE THREAD

**Issue by kevincox** [cla-assistant/cla-assistant#353]
It would be good to have the option to send signature notifications, and copies of the provided information to an email address. This would allow easy archiving of the signatures.

I think the email should include at least:
- Signers name and email.
- Date
- Version/text of CLA signed.

**Comment by KharitonOff** [comment]
I like your idea! It corresponds to the issue #299 
It would be great to have the possibility to export/receive the content of the signed CLA in any possible form!

**Comment by kevincox** [comment]
Ping

**Comment by kevincox** [comment]
Bump

**Comment by Serg046** [comment]
As I understand the email is sent by GitHub, so we see there what we see in the PR.
But I am not sure if we want CLA text right there...
