### ISSUE TITLE
Way to remove personal information per GDPR

### ISSUE THREAD

**Issue by kristakhare** [cla-assistant/cla-assistant#362]
Have you considered the request for and storage of Full Name, a piece of PII and implications of GDPR for European contributors? It would be great if the tool offered a way to request removal of personal information. 

I also wonder if signature (assumed full name) could be replaced by GitHub username, and how would that affect recognition of signature?

**Comment by kristakhare** [comment]
Thank you for your response! I will close this issue for now, since I think we can customize our fields to address.

**Comment by glopesdev** [comment]
@kristakhare is there any chance you could describe in broad strokes what your approach to address this issue was? It would be really useful to have a sense of how other projects working with EU collaborators are dealing with this.
