### ISSUE TITLE
Customised landing page

### ISSUE THREAD

**Issue by hentisemmle** [cla-assistant/cla-assistant#363]
URL to the linked Repo/Org:

N/A

Steps to reproduce the problem:

1. Setup your own instance of CLA assistant
2. Go to landing page

What is the expected result?

See a custom landing page with branding that matches the owner of the instance

What happens instead?

See the default SAP CLA page. 

## Optional

Currently the default installation of CLA on your own instance will show you the default CLA landing page similar to https://cla-assistant.io/

This is inconsistent with some companies requiring domains to match corporate branding guidelines. 
Currently there seems to be no way to change this. 

Please add a way to customise the landing page.

**Comment by KharitonOff** [comment]
Thank you for your proposal. Some companies, which set up an own instance of CLA assistant have changed the html and css in order to match their branding. I can hardly imagine how we could make it customisable, but you are very welcome to create a PR
