### ISSUE TITLE
can't sign mark fleming -- which is same person as flemingm

### ISSUE THREAD

**Issue by flemingm** [cla-assistant/cla-assistant#364]
URL to the linked Repo/Org:

https://github.com/dlemstra/Magick.NET/pull/284

Steps to reproduce the problem:

1. add other email for me. And re-verifed. did not find me.

What is the expected result?

verify mark fleming and flemingm as the same person.

What happens instead?

Said one person was not verified.

**Comment by KharitonOff** [comment]
@flemingm it seems to be solved isn't it?

**Comment by flemingm** [comment]
yes --- it could have been a timing issue.
