### ISSUE TITLE
List of signed contributors gone after adding whitelisted user to linked organisation

### ISSUE THREAD

**Issue by ixalon** [cla-assistant/cla-assistant#366]
This is similar to https://github.com/cla-assistant/cla-assistant/issues/351 however it is against an Organisation CLA with a link to a gist so there appears to be no way to perform the fix to get the signed user list back.

Is there any way to recover the list?

URL to the linked Repo/Org: https://github.com/beamly

**Steps to reproduce the problem:**

1. Edit linked organisation
2. Modify "Provide user names, who doesn't need to sign the CLA"
3. Save

**What is the expected result?**

Contributor list is not lost

**What happens instead?**

Contributor list of all versions of the CLA is lost

**Comment by ixalon** [comment]
I've imported a CSV of those who I know have signed the CLA, but the bug still exists.

**Comment by KharitonOff** [comment]
@ixalon thank you very much for reporting this probmlem and please excuse the long delay in the response (due to vacation time it takes us longer to handle issues). 
It seems indeed to be the same problem like #351. I'll try to fix it soon.

**Comment by jmdh** [comment]
We were bitten by this problem on our self-hosted version of cla-assistant. The problem seemed to be that the edit operation changed the `gist` element of the `repos` document, replacing the correct working `https://gist.github.com/$USER/$ID` URL with `https://api.github.com/gists/$ID`.

In case this is helpful for someone else in a similar situation, before the bug can be fixed, the following worked for us (no warranty provided, please check this makes sense for your data!):

In the mongodb shell, connected to the correct database:

`db.repos.updateOne( { repoId: "<your-repo-id>" } , { $set: { gist: "https://gist.github.com/<your-user>/<your-gist-id>" } } )`

(replacing `<your-repo-id>`, `<your-user>`, `<your-gist-id>` of course).

**Comment by KharitonOff** [comment]
@ixalon I've found and fixed the bug. I'll ship the fix tomorrow to production. 
As soon the fix is productive you can just go to edit screen again, check whether the gist url is correct (https://gist.github.com/59e096256358ac91ec2a7760c63817b9) and click save.

**Comment by KharitonOff** [comment]
@jmdh sorry for the inconvenience and thank you for your comment
