### ISSUE TITLE
wording

### ISSUE THREAD

**Issue by yaseminc** [cla-assistant/cla-assistant#37]
We're happy to get some help with the wording:

- Pop Up "Contributors who signed a CLA" --> List of contributors?

**Comment by KharitonOff** [comment]
we need help from a native speaker to review all texts on:
- landing page
- administration view incl. all popups

**Comment by dfarr** [comment]
I can look at this tomorrow!

**Comment by yaseminc** [comment]
@dfarr thanks! Did you have a chance to look at it yet?

**Comment by dfarr** [comment]
Sorry guys! Looking now :)

**Comment by thojansen** [comment]
please check #50

**Comment by KharitonOff** [comment]
done with pr #50
