### ISSUE TITLE
Feature Request: Monitoring the CLA status of a whole repository / organization

### ISSUE THREAD

**Issue by bd82** [cla-assistant/cla-assistant#371]
Hello and thanks for CLA-assistant! 😄 

As I understand CLA-A helps ensure contributors signed the CLA by
adding a **status check** to **pull requests**.
That helps ensure **new** content added to a repository is compliant.

But what if I want to ensure all the **past** contributors have signed the CLA?
Basically compare the list of contributors on a github repo to the list of those that have signed the CLA. Such a monitor could also be relevant for a whole organization instead of a single repo.

Another concern is that not all contributions necessarily come in via a pull request.
So its not enough to verify all pull requests authors have signed the CLA, rather that all
commit authors have signed the CLA.

### Questions

* Would such a feature be considered in the scope of CLA-A?
* Can the list of CLA signatures and whitelisted user names be exported from CLA-A
   in an automated manner (e.g REST API)?
   * If such an export capability exists such a monitor could be implemented externally...

Cheers.
Shahar.

**Comment by KharitonOff** [comment]
Thank you for your comments!
> But what if I want to ensure all the past contributors have signed the CLA?

You can import an existing list of usernames into CLA assistant 
<img width="446" alt="screen shot 2018-09-11 at 09 59 52" src="https://user-images.githubusercontent.com/8480657/45346471-9513bf80-b5a9-11e8-92f0-78533c504daa.png">

> Such a monitor could also be relevant for a whole organization instead of a single repo.

You can also link a whole organization 
![screen shot 2018-09-10 at 15 14 56](https://user-images.githubusercontent.com/8480657/45345545-f0907e00-b5a6-11e8-8ca3-640102db14a5.png)

> So its not enough to verify all pull requests authors have signed the CLA, rather that all
commit authors have signed the CLA.

This is how CLA assistant is designed per default. It checks all committers of the PR. Usually you don't grant push rights to everyone but receive a contribution via a PR.

> Can the list of CLA signatures and whitelisted user names be exported from CLA-A
in an automated manner (e.g REST API)?

You can check this issue #166

**Comment by bd82** [comment]
Thanks @KharitonOff I play around with #166 
To see if I can build a script to run the logic I want.

> This is how CLA assistant is designed per default. It checks all committers of the PR. Usually you don't grant push rights to everyone but receive a contribution via a PR.

I am thinking about the scenario of ensuring that everyone with write access to a repo
signed the CLA rather than just that all contributions that went through a PR were signed.
Even with PRs status checks can be skipped so I wonder if a stronger verification can be
done.
