### ISSUE TITLE
Feature: Copyright Assignment Agreement (CAA)

### ISSUE THREAD

**Issue by ilyaigpetrov** [cla-assistant/cla-assistant#372]
Is it possible to use https://cla-assistant.io for [CAA], not CLA?
Is some special configuration required compared to CLA?

[CAA]: http://wiki.civiccommons.org/Contributor_Agreements/#how-to-accept-code-and-documentation-contributions-legally

**Comment by KharitonOff** [comment]
I think you should ask a legal person. CLA assistant requests a github authentication from the contributors, I don't think that this would be enough in the CAA use case.
