### ISSUE TITLE
Question: Isn't a Contribution Notice in README.md Enough?

### ISSUE THREAD

**Issue by ilyaigpetrov** [cla-assistant/cla-assistant#373]
Open source project rust-postgres-macros has [a contribution noitice](https://github.com/sfackler/rust-postgres-macros/blob/7d4cc509e5c96e062ba494ecd7fde020a5e91a21/README.md#contribution) in their README.md:

> Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any additional terms or conditions.

I want to do the same, but with a project dual-licensed under LGPL + proprietary licenses and Copyright Assignment Agreement (CAA) for contributions.
Isn't such notice enough for accepting pull requests and commits? Why to use https://cla-assistant.io ?

**Comment by KharitonOff** [comment]
Different companies and projects handle this topic with a different approach depending on the opinion of their legal department. With CLA assistant we try to reduce the pain for contributors in such projects which request a CLA. Maybe you can find an answer to you questions here: https://opensource.guide/legal/#does-my-project-need-an-additional-contributor-agreement
