### ISSUE TITLE
I can not login with my account

### ISSUE THREAD

**Issue by devonfw-core** [cla-assistant/cla-assistant#378]
URL to the linked Repo/Org:
[https://cla-assistant.io/](https://cla-assistant.io/)

Steps to reproduce the problem:

1. Navigate to [https://cla-assistant.io/](https://cla-assistant.io/)
2. Log in with my devonfw-core GitHub account.

What is the expected result?
I should log in

What happens instead?
I receive an error message: **Internal Server Error**. The status code was 500

Any other information? (attach screenshot if possible)
I can not enter into [https://cla-assistant.io/](https://cla-assistant.io/) to manage and add more CLA with my GitHub Account whose username is **devonfw-core**. But if I try to enter with other GitHub accounts I can do it.

When I tried to log in with devonfw-core account I recive an error response: **Internal Server Error**. If I open the web console I can see three network interactions, the first two are to request github to log in and return the Status Code 302 Found. The last one is to [https://cla-assistant.io/auth/github/callback?code=85a502171895a93507f4](https://cla-assistant.io/auth/github/callback?code=85a502171895a93507f4) and returns Status Code 500.

![image](https://user-images.githubusercontent.com/40631995/45997615-8694d000-c0a0-11e8-866f-b730ea09c62e.png)

I have tried it with different pcs in different places with different ips and also with different browsers.

Browser/version:
I tried it with Google Chrome version 69.0.3497.100

Any other tested browsers/devices(OK/FAIL):
Also I tried it with Internet Explorer version 11.1266.15063.0 and it fails.

**Comment by KharitonOff** [comment]
according to my logs, your user account has exceeded GitHub's API rate limit. Do you use this user account for any other tools, which access GitHub via API?

**Comment by KharitonOff** [comment]
Ok. I see. I'll try to find the root cause.
Regarding the multiple repositories with one gist: have you already considered to link the whole org instead of single repositories? You can also use an exception list for the repos in the org, which should be excluded. In this case you would have only one CLA link
