### ISSUE TITLE
Signature not taken into account

### ISSUE THREAD

**Issue by xadupre** [cla-assistant/cla-assistant#383]
Url: https://github.com/onnx/onnxmltools

I signed many times the required CLA with no effect. If I try to sign again, a new page opens telling me I already signed but the previous page associated to the PR https://github.com/onnx/onnxmltools/pull/144 tells me I did not.

I tried with Edge, Firefox. No difference.

Is it possible to unblock me?

Xavier Dupré

**Comment by KharitonOff** [comment]
Hi Xavier,
you should sign the CLA as @sdpython because you've committed to the PR with this account (email). To do so, sign out yourself from github and sign in to github as @sdpython, navigate to CLA assistant via the link in the PR and accept the agreement.
