### ISSUE TITLE
i have signed, but have no work , why ?

### ISSUE THREAD

**Issue by Jamlee** [cla-assistant/cla-assistant#384]
![image](https://user-images.githubusercontent.com/5196641/47965218-579a5280-e07f-11e8-9818-eea00918ac6c.png)

URL to the linked Repo/Org:
https://github.com/goproxyio/goproxy/pull/14

What is the expected result?
signed the pull
What happens instead?
not work, it is notify to me to sign again.

**Comment by KharitonOff** [comment]
Please make sure, that @webboy89860 signs the CLA too (this user has committed to the PR).

On 4. Nov 2018, at 15:19, jam lee <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/5196641/47965218-579a5280-e07f-11e8-9818-eea00918ac6c.png>

URL to the linked Repo/Org:
goproxyio/goproxy#14<https://github.com/goproxyio/goproxy/pull/14>

What is the expected result?
signed the pull
What happens instead?
not work, it is notify to me to sign again.

**Comment by Jamlee** [comment]
got it , thanks
