### ISSUE TITLE
Unable to link repository (Webhook API error)

### ISSUE THREAD

**Issue by sdirix** [cla-assistant/cla-assistant#386]
URL to the linked Repo/Org: https://github.com/eclipsesource/jsonforms-tooling

## Steps to reproduce the problem:

1. Login to CLA Assistant
2. Setting up CLA for a new repository (organization)

## What is the expected result?

CLA Assistant integration successful:
 - Webhook is created
 - CLA Assistant shows repository in list of linked repositories
 - CLA Assistant reacts to PRs 

## What happens instead?
CLA Assistant indicates in UI that linking was successful, however after reloading the page the repository is not shown anymore.

The console shows the following errors:
![selection_029](https://user-images.githubusercontent.com/8998368/47995815-dc748300-e0f6-11e8-92e4-f6a27815ee30.png)

## Additional information
1. It doesn't matter if choosing a predefined CLA or a gist, both don't work
2. The UI popup indicates linking was successful
3. The new repository shows up an in the list of linked repositories, however only the checkmark for ```gist``` is given but not for ```webhook```. After reloading the page, the repository no longer shows up in the list of linked repositories.
4. Retrying after log out / login in both Github and CLA assistant doesn't work
5. I have the required rights to the repository.
6. I tried setting up the webhook in the repository manually (copied the settings from another repository which was linked to CLA assistant before) and indeed the checkmark for ```webhook``` is then also shown when linking the repository. However CLA assistant still doesn't react to PRs and when reloading the page, the repository again vanishes from the list of linked repositories.

**Comment by KharitonOff** [comment]
@sdirix your repository is stored in the DB with wrong repository id (I don't know how this could happen). We crosscheck the data stored in our DB with 'real' data from GH, that's why cla assistant can't find it and list it as linked one.
I've removed the DB entry manually. Could you try to link the repo again, please?

**Comment by sdirix** [comment]
Thanks for looking into this issue! Yes, the linking now worked. Thanks for the efforts!

One more thing I don't understand, maybe this is related to the database issue so I will mentioned it here. If it's an own issue I'll open another issue if you prefer. 

We share the same gist for multiple repos, however it seems that a different number of people are actually linked.

For privacy reasons I will use ```A```,```B```,```C``` for numbers where ```A``` is the largest and ```C``` the lowest.

 * https://github.com/eclipsesource/jsonforms is signed by ```A``` people
 * https://github.com/eclipsesource/jsonforms-ui-schema-editor and four other repositories are signed by ```B``` people
 * https://github.com/eclipsesource/jsonforms-typescript-seed is signed by ```C``` people.
 * When linking the new repository https://github.com/eclipsesource/jsonforms-tooling the number of signed people is shown as ```C```.

All of these repositories are linked to the same gist and all of them have ```shared``` set to true. Also when looking at the signers, they form a subset relation: signers of C is a subset of signers of B which is a subset of signers of A. Is there a way to just sync them all to the list of ```A``` signers?

**Comment by KharitonOff** [comment]
This is possible in case the repo jsonforms and jsonforms-ui-schema-editor haven't had ```shared``` flag previously and had some contributors before you changed it to ```shared```. 
The only workaround to bring them to the same set of contributers is to export the set A and import it again for the repo jsonforms-tooling e.g.

**Comment by sdirix** [comment]
Thanks for the advice. I'll close this as the original issue was resolved. Thanks again!
