### ISSUE TITLE
Is it possible to trigger specific CLA's depending on content of PR?

### ISSUE THREAD

**Issue by capsulecorplab** [cla-assistant/cla-assistant#387]
If, say, a PR includes a png image, is it possible to trigger a CLA specific for handling image copyright? i.e., the CLA(s) triggered is contingent on the contents of the PR.

**Comment by KharitonOff** [comment]
No, the scenario you've described is currently not possible with CLA assistant. But we are always open for new contributions 😄

**Comment by capsulecorplab** [comment]
@KharitonOff Duly noted. Thanks for the response!
