### ISSUE TITLE
Keep getting prompted to sign the CLA

### ISSUE THREAD

**Issue by KateChuen** [cla-assistant/cla-assistant#391]
https://cla-assistant.io/SAP/cloud-commerce-spartacus-storefront

What happens instead?

I've signed the CLA multiple times, signing out and signing back in. Removing and adding email addresses, but no luck. It keeps saying "Pending" next to the CLA thing. But if I go to the CLA page, it tells me that I have already signed it. 

Any other information? (attach screenshot if possible)
![cla](https://user-images.githubusercontent.com/45409515/50009066-046fc580-ff84-11e8-8d8d-c8b5f925da14.png)

Browser/version:

Chrome, Safari ->Both fail

**Comment by KharitonOff** [comment]
@KateChuen have you also added `kate.chuen-cheong@hybris` to your github profile?
