### ISSUE TITLE
Gmail period and plus sign support

### ISSUE THREAD

**Issue by Ecsy** [cla-assistant/cla-assistant#393]
**Steps to reproduce the problem:**

1. Create a gmail email account. For example: claassistant@gmail.com
2. Create an github user with a verfied email of: claassistant+github@gmail.com
3. Use CLA Assistant in your repo.
4. Sign CLA.
5. Create PR.

**What is the expected result?**

CLA check should pass.

**What happens instead?**

CLA check fails. Only exact match will pass.

**Notes**

All the following email addresses work by default with Gmail with the registered claassistant@gmail.com email address:
claassistant+github@gmail.com, cla.assistant@gmail.com, claassistant+whatever@gmail.com

**Comment by KharitonOff** [comment]
@Ecsy I wonder how does GitHub handle email addresses with period and plus sign? If I make a commit with 'claassistant+github@gmail.com' and in my github account is 'claassistant@gmail.com' stored. Would GitHub assign this commit to my user?
