### ISSUE TITLE
 I signed the CLA already but the status is still pending.

### ISSUE THREAD

**Issue by zhouhesheng** [cla-assistant/cla-assistant#394]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by KharitonOff** [comment]
@zhouhesheng can you provide a link to your pull request?

**Comment by KharitonOff** [comment]
If this issue relates to this PR: https://github.com/zhuhaow/NEKit/pull/224 then you should ask @HansonZ to sign the CLA, because he is the committer of the PR.
