### ISSUE TITLE
Thin text a bit difficult to see on lower resolutions

### ISSUE THREAD

**Issue by casche** [cla-assistant/cla-assistant#40]
The thin text that is placed on the background image is a bit difficult to see when using a monitor with a low DPI. Not a problem for retina displays.. just old cheap monitors :)

I would suggest adjusting the font-weight to bit slightly bigger. 

![screen shot 2015-05-11 at 9 33 02 am](https://cloud.githubusercontent.com/assets/5832943/7564834/e34a02fe-f7c0-11e4-979d-cecd1865651c.png)

**Comment by yaseminc** [comment]
@mierschp @KharitonOff pls change to font-weight: 400 :)
thx @casche !

**Comment by KharitonOff** [comment]
We tried it out, but it doesn't look nice :(
We'll see wether we can set the font-weight depending on the user's DPI...

**Comment by thojansen** [comment]
Shall we close this one?

**Comment by yaseminc** [comment]
yeah, we don't want to change it..
