### ISSUE TITLE
Status check not working

### ISSUE THREAD

**Issue by maximdidenkoepam** [cla-assistant/cla-assistant#400]
Hello,

I can't merge my PR because of incorrect status of CLA. I have signed it several times, but result is the same. Could you help me to resolve the issue?

https://github.com/folio-org/ui-users/pull/637

![screenshot_1](https://user-images.githubusercontent.com/43472449/50896854-00b05100-1413-11e9-9f1a-58fd8f2af804.png)

Thanks,

**Comment by michael-spengler** [comment]
Hi.

Good news: There seems to be a simple solution for this. 
It seems that the user who committed the changes is slightly different from the username who signed the CLA --> maximdidenko vs maximdidenkoepam

Does this already solve this issue?
