### ISSUE TITLE
Add Optional Configuration to Ignore Contributions from GitHub Org Members

### ISSUE THREAD

**Issue by BenLloydPearson** [cla-assistant/cla-assistant#403]
CLA-Assistant is missing a fairly important feature: the ability to automatically ignore members of known organizations. I.e. it should be possible to tell CLA-Assistant to ignore members of specific GitHub organizations where my account is set to owner.

This would be useful because many GitHub organizations often already have some sort of agreement between members to assign copyright to the owner of the org. The most common example would be companies that invite their employees to be members of the organization and don't need them to sign.

Requirements:
- Should have an optional configuration in the edit menu for each linked repository/organization to ignore contributions from members of the organization the repository is hosted under.
- Should work across organizations when a shared CLA that spans multiple GitHub organizations is used.

**Comment by KharitonOff** [comment]
the PR #410 seems to address this issue.

**Comment by BenLloydPearson** [comment]
Based on the response I received from the developer, it doesn't seem to solve my problem. We need to automatically accept contributions from users of organizations we control. E.g. if a user is a member of the GitHu org the repo is hosted under (or one of the other organizations we control), their contributions should be automatically accepted. #410 is designed to accept contributions from other whitelisted organizations.

@KharitonOff this raises a question, does cla-assistant currently have enough privilege to read the member list for organizations its installed to? Or is this something that also needs to be implemented to make this request possible?

**Comment by KharitonOff** [comment]
You can also use the feature of #410 to whitelist your own organization. This would work if members of the Org open PRs not from own forks but from repository branches.

@BenLloydPearson yes, you can get the list of members for all organizations where you (a user who has linked the organization in CLA assistant) are a member too.

**Comment by BenLloydPearson** [comment]
This issue with that approach is that we often invite non-employees to be collaborators with write access to the repo, but they still need to sign the CLA. They would be capable of creating PR's from the organization and be able to bypass the CLA check.

**Comment by BenLloydPearson** [comment]
@KharitonOff I've given this some consideration and it's possible #410 might resolve our issue at least partially. For the use case I describe, I was hoping for a solution that doesn't require developers to follow specific practices (e.g. I will have to notify our developers make sure that all internal contributions come from a branch on our repo rather than forks of the developer's personal account), because I find that this results in inconsistent outcomes between developer teams. With that said, I think #410 does technically resolve our problem, so once it hits the SAP hosted version of CLA-Assistant, I'll see if I can make it work for us.

**Comment by KharitonOff** [comment]
@BenLloydPearson, sounds good. We are just waiting for all CLAs to be signed and then we'll be able to take over the changes. I see your point and I think this solution resolves the problem in a pretty simple way. But if it wont work in practice, we can still improve it.

**Comment by BenLloydPearson** [comment]
@KharitonOff , when will #410 make it into the hosted version of CLA-Assistant? It doesn't appear to be there yet.

**Comment by KharitonOff** [comment]
@BenLloydPearson thanks for asking :) I'll do it this week.

**Comment by KharitonOff** [comment]
@BenLloydPearson the feature is live 😃

**Comment by BenLloydPearson** [comment]
@KharitonOff Thanks! I've implemented it in our instance so I can test it out. Since this technically solves this issue, I'll go ahead and close it. With that said, I'm still hoping to get a developer to help me build this feature out a bit more so I'll hopefully have some additional improvements for you in the near future.

**Comment by ibakshay** [comment]
@BenLloydPearson Hi Ben, I am currently working on CLA Assistant. 
As you have mentioned that your team will work on developing additional improvements on this topic, Can you tell me if there is progress on this matter?
