### ISSUE TITLE
adding of new email addresses after cla alredy signed

### ISSUE THREAD

**Issue by cxcv** [cla-assistant/cla-assistant#405]
Hi there,

At https://github.com/grafana/grafana/pull/12765
I've already signed the CLA with my primary email address. 
Then I've updated the PR using an alternate email address.
Hence the CLA was not signed with this alternate address, I've added it to my github account.
Now the merge page at https://github.com/grafana/grafana/pull/12765 says the alternate email address did not sign the CLA, but at signing page at https://cla-assistant.io/grafana/grafana?pullRequest=12765 says I've already signed. 
How can I get a sign off here?

Cheers
Benjamin

**Comment by KharitonOff** [comment]
There was a tiny "recheck PR" url in the comment of CLA assistant. This was needed to be clicked to trigger CLA assistant and recheck the PR. Now everything looks good again
