### ISSUE TITLE
Unable to remove a user from CLA.

### ISSUE THREAD

**Issue by jefgen** [cla-assistant/cla-assistant#406]
It seems there is no way at all to **remove** a user from the list of users covered by the CLA.

(Aside: There was a previous issue filed here #201, but that was closed due to it being "stale", and then labeled as "wontfix".)

We have a real world case of a user leaving a team, and now we need to update the list of users covered under the CLA to remove the username. Unfortunately, it doesn't appear to be possible to do this.

I've tried exporting/import, but that doesn't work.

URL to the linked Repo/Org: https://github.com/unicode-org/icu

Steps to reproduce the problem:

1. Export list of users as `csv` file.
2. Edit the file to *remove* the entry/line for a single user.
3. Import the edited `csv` file.

What is the expected result?
The user should be removed from the list of users.

What happens instead?
The user is not removed.

**Comment by MichaelTsengLZ** [comment]
Try to hit this end-point `https://cla-assistant.io/api/cla/terminateSignature`
with header like this:
```
x-token: 'your-personal-token'
```

with body like this:
```
// if you link an repo
{
  user: abc,
  userId: 123,
  endDate: '2019-01-29T01:53:31.779Z',
  owner: 'my-repo-org-name',
  repo: 'my-repo'
}
// if you link an org
{
  user: abc,
  userId: 123,
  endDate: '2019-01-29T01:53:31.779Z',
  org: 'my-org'
}
```
[Here](https://github.com/cla-assistant/cla-assistant/blob/64edc29aad2c46896fb358bebde7e29d2234b7df/src/server/api/cla.js#L756) is the implementation details

**Comment by jefgen** [comment]
Thank you very much @MichaelTsengLZ !

I think it worked, as I now see an `end_at` associated with the user recorded.

Though there doesn't appear to be anything in the Web UI that indicates that the CLA no longer applies to that user...

I'm guessing that if they were to open a new pull-request then the CLA-Assistant would think that they are no longer covered? (Is that correct?)

**Comment by MichaelTsengLZ** [comment]
Correct, they will have to sign the CLA again when they submit a new pull request.

**Comment by jefgen** [comment]
Got it! -- Thank you again!

**Comment by jackkoenig** [comment]
In case anyone comes across this again. I tried this recently, and was able to successfully remove a user's signature. Unfortunately, now they cannot sign again. Clicking `I Agree` just doesn't seem to do anything. 

I know next to nothing about web programming so please forgive any abuse of terminology, using Chrome DevTools the response upon clicking `I Agree` appears to be:
```
"Empty value for parameter 'owner': undefined"
```

**Comment by opcfoundation-org** [comment]
Where does the "userId" come from? I see nothing in the export data or github that could tell me what to put in

**Comment by KharitonOff** [comment]
@opcfoundation-org you can get it via API https://api.github.com/user
