### ISSUE TITLE
Adding CLA to Org fails be is listed

### ISSUE THREAD

**Issue by hentisemmle** [cla-assistant/cla-assistant#411]
URL to the linked Repo/Org: https://github.com/Semmle

Steps to reproduce the problem:

1. Add CLA to org 
2. Opps! Something went wrong!
3.

What is the expected result?
Works 
What happens instead?
Opps! Something went wrong!

Screenshot of error.

![screenshot at 2019-02-05 16-57-02](https://user-images.githubusercontent.com/28868601/52291226-ca121b80-2969-11e9-9319-31102e3e24f0.png)

The org is listed as added, no PR's are detected in repos not linked, and linked repos behave according to contributors in their respective lists. 

Non linked repos do not get any PR integration and no CLA messages are displayed.

**Comment by KharitonOff** [comment]
@hentisemmle I think you have the same problem like the issue #404 describes... do you?

**Comment by hentisemmle** [comment]
Morning @KharitonOff 

Thank you for the link.Still received and error, but it seems to be functioning as expected now. 

Kind regards
Henti

**Comment by rianquinn** [comment]
I guess we had the same issue:
https://github.com/Bareflank/hypervisor/issues/753

Do we know what could cause this?

**Comment by KharitonOff** [comment]
@rianquinn did you try to link the whole organization @Bareflank in CLA assistant? If so, you probably need to request an approval for CLA assistant in GitHub to access the org (to do so, please follow the steps described here https://help.github.com/en/articles/requesting-organization-approval-for-oauth-apps )
