### ISSUE TITLE
Can the CLA assistant handle CLA signed by organisations

### ISSUE THREAD

**Issue by AloisReitbauer** [cla-assistant/cla-assistant#414]
Is there a way to add an entire organization as whitelisted for contribution. I understand how it will work for individual users. In case of corporate CLAs you will want the members of a Github group be able contribute. 

Is this currently supported? If not, where in the code would this be added ideally.

**Comment by KharitonOff** [comment]
There is a PR open, which already addresses your request: #410 
I hope it is ok for you to wait until we'll be able to merge it.

**Comment by KharitonOff** [comment]
@AloisReitbauer now you can test this feature on https://cla-assistant.io

**Comment by andschwa** [comment]
@KharitonOff I am trying to test this feature, but when I add my organization name to the whitelist, it just complains:

"Authentication required"

I am not sure what's up :/

**Comment by andschwa** [comment]
> @KharitonOff I am trying to test this feature, but when I add my organization name to the whitelist, it just complains:
> 
> "Authentication required"
> 
> I am not sure what's up :/

Well that's bizarre. I closed and re-opened and what do you know? It was some cache issue. So that worked.

**Comment by andschwa** [comment]
Well, that's unfortunate. I tried whitelisting the `openenclave` GitHub organization (of which I am the sole member) and opening a test here: https://github.com/openenclave/test-repo/pull/3 but that doesn't seem to work as I expected, it still wants me to sign the CLA.

**Comment by KharitonOff** [comment]
@andschwa sorry for long delay and thank you very much for pointing this issue out! The problem should be fixed now. Can you try and confirm, please?

**Comment by andschwa** [comment]
@KharitonOff Cool! Ok, it works as expected for users of some org making a PR to repos in the same org. Thank you!

However, my understanding of the implemented logic leads me to believe that it won't let me whitelist authors from some external org making contributions directly in m,y repo. Instead, the logic lets me whitelist PRs made _from_ some external org's fork. Is that right? If so, I can work with that, though it'd be nice to do a membership test 😄

**Comment by KharitonOff** [comment]
Yes, you are right, there is no membership check. I suppose you'd prefer to have a solution like @BenLloydPearson described in #403 
In case you'd like to become an active contributor to CLA assistant you can synch with Ben and jointly develop a possible solution 😄I will be happy to provide you with all information you may need.

**Comment by andschwa** [comment]
Thanks @KharitonOff! I will keep that in mind and let you know (I'd be doing it for work so I'd need to make sure I have time).

**Comment by ibakshay** [comment]
I will close this issue as the CLA Assistant can handle CLA signed by organisations now  and the [Membership Check](https://github.com/cla-assistant/cla-assistant/pull/462) functionality is also implemented.
