### ISSUE TITLE
I've singed the CLA agreement for repo but the check still doesn't pass

### ISSUE THREAD

**Issue by tendonstrength** [cla-assistant/cla-assistant#415]
URL to the linked Repo/Org: https://github.com/mochajs/mocha/pull/3738

Steps to reproduce the problem:

1. I opened the above-mentioned PR
2. I signed the CLA agreement with the email tendonstrength@gmail.com
3. It shows that I've signed it successfully on the CLA site (see screenshot below).

What is the expected result?

The check should pass and the PR should be mergeable 

What happens instead?

The PR check says that I have not signed the agreement. 

## Optional
Any other information? (attach screenshot if possible)

The CLA site shows that I've signed successfully:

<img width="1319" alt="screen shot 2019-02-17 at 9 18 39 am" src="https://user-images.githubusercontent.com/992991/52919533-f4989880-32c8-11e9-8ca9-26215de513aa.png">

Browser/version: Chrome 72

Any other tested browsers/devices(OK/FAIL):

**Comment by KharitonOff** [comment]
CLA assistant checks whether all **committers** of a PR have signed the CLA or not. In this case you (@tendonstrength) are the author of the PR but not a committer

![screen shot 2019-02-18 at 10 38 31](https://user-images.githubusercontent.com/8480657/52941657-9e2f6680-3369-11e9-91b4-10fec6e716e7.png)

Probably you have used another e-mail address in git config as the one stored in your GitHub account. Please add the e-mail address to your account and 'retrigger' the che CLA assistant check by commenting or committing to the PR.
