### ISSUE TITLE
Why does cla-assistant want `public_repo` scope?

### ISSUE THREAD

**Issue by superbrothers** [cla-assistant/cla-assistant#417]
Hi, I have a question that is why does cla-assistant want `public_repo` scope?

According to https://github.com/cla-assistant/cla-assistant/issues/78#issuecomment-150146810, @KharitonOff said "public_repo - read all public repositories in order to provide a selection of your repos to set it up", but `no scope` can also read all public repos.

- `(no scope)`: Grants read-only access to public information (includes public user profile info, public repository info, and gists)

https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

Therefore I guess cla-assistant does not need `public_repo` if the scope is only used for reading public repos.

**Comment by KharitonOff** [comment]
Thanks for pointing out! We'll check on it in our time.

**Comment by superbrothers** [comment]
Are there any updates?

**Comment by KharitonOff** [comment]
@superbrothers I've removed the scope. But the change will come with the next major release first.
