### ISSUE TITLE
Security issue: Unauthorized use of account (CVSS 7.2 - High Risk)

### ISSUE THREAD

**Issue by gregzaitsev** [cla-assistant/cla-assistant#419]
URL to the linked Repo/Org:
https://github.com/cla-assistant/

Steps to reproduce the problem:

1. Create account A on github with e-mail that has not beed used yet
2. Setup git config with existing user B's email. User B must have signed CLA agreement previously.
3. Without user's B consent, user A may commit to git and CLA bot will recognize this commit as both user's A and user's B commit. User B will effectively be obligated to whatever terms the agreement states without and possibly against user B's consent.

For example, if user B owns a patent that user A infringes on in a commit, and user A specifies user's B email in commit message, user B will be obligated to transfer his patent to the Company.

What is the expected result?

CLA bot recognizes commits by github user name only and ignores email addresses in commit message.

What happens instead?

CLA uses both email in commit message and github username. Commit messages (including user's email and name) are specified by the committer and are not enforced by git or github.

**Comment by KharitonOff** [comment]
Do you have an example of the described use case?
Generally speaking CLA assistant relies fully on the GitHub APIs. Only committers with GitHub account can sign a CLA and only committers with GitHub account can pass CLAs check. 
Now if a user (A) makes a commit with foreign email (B) GitHub will assign this commit to a user according to the email address stored in the commit (user B in our case). This means that the described use case seems possible but it is not an issue of CLA assistant but GitHub itself.
> What is the expected result?
>
> CLA bot recognizes commits by github user name only and ignores email addresses in commit message.

This is already the case.

**Comment by gregzaitsev** [comment]
Hi, thanks for a prompt response! Yes, I have an example here:

https://github.com/aragon/aragonOS/pull/486

Some (not all) commits in this PR are from user gregzaitsev with email address in commit message of gz@usetech.com that is assigned to user usetech-Jenkins that did not do any commits. Only email address associates this user with this PR.

I agree this might be an issue with github API, but signing legal agreements based on the breached code escalates the severity. 

Let me know if you need more help!

**Comment by KharitonOff** [comment]
Yes, also in your example you can see that GitHub assigns the commits, which you have done with gz@usetech.com to another user (@usetech-Jenkins). So I can't see what can be done on our side to recognize whether the committer is a real user or not.

Let's agree that the main concern of the CLA assistant bot is simply the validation whether the user A or B has signed your CLA or not. So there is no "_signing legal agreements based on the breached code_" happening.
In order to sign the CLA you have to authenticate yourself with your GitHub user. And for that your GitHub credentials are required.

**Comment by KharitonOff** [comment]
Nevertheless thank you for creating this issue and letting us know about possible security risk! We appreciate it very much.
I close this issue here since the described problem can only be solved on the GitHub side.
