### ISSUE TITLE
Consider compressing images

### ISSUE THREAD

**Issue by spadgos** [cla-assistant/cla-assistant#42]
The [logo image](https://cla-assistant.io/assets/images/logo.png) is 1.1MB. Running it through the optimiser at tinypng.com reduced it to 10kb and it looks just as nice. :)

![](https://tinypng.com/web/output/m3du5q269uuea015.png/logo.png)

**Comment by thojansen** [comment]
@KharitonOff can you make sure to reduce the images and load time for the redesign such that this is fixed? 

@spadgos :+1: for pointing this out.

**Comment by KharitonOff** [comment]
done in the new design version
