### ISSUE TITLE
cla-assistant.io is not responding to incoming webhooks

### ISSUE THREAD

**Issue by dguido** [cla-assistant/cla-assistant#422]
URL to the linked Repo/Org:
https://github.com/trailofbits/algo/pull/1351

Steps to reproduce the problem:

1. Activate a Github org in cla-assistant.io
2. Create a new pull request
3. There is no status check for the CLA on the PR

What is the expected result?
cla-assistant.io responds to Github with the required information to evaluate CLA acceptance

What happens instead?
cla-assistant.io responds with a 200 OK and does not perform the status check

The organization is linked in cla-assistant.io:
![Screen Shot 2019-03-11 at 10 58 09 PM](https://user-images.githubusercontent.com/294844/54171653-8a02f480-4451-11e9-82f9-1e8e0497d786.png)

The webhook is installed:
![Screen Shot 2019-03-11 at 10 58 27 PM](https://user-images.githubusercontent.com/294844/54171666-94bd8980-4451-11e9-94d9-6c8d0b9756b8.png)

Third-party access is allowed:
![Screen Shot 2019-03-11 at 11 01 55 PM](https://user-images.githubusercontent.com/294844/54171705-b0289480-4451-11e9-86aa-18ef43e935cd.png)

However, there is no cla-assistant check in the Github PR:
![Screen Shot 2019-03-11 at 10 59 35 PM](https://user-images.githubusercontent.com/294844/54171681-a0a94b80-4451-11e9-9140-9fe8b43b4053.png)

**Comment by KharitonOff** [comment]
Thanks @dguido for reporting this. 
Looks like a bug...

**Comment by KharitonOff** [comment]
to be honest, I can not find any trail neither in logs nor in our code 😕 
You can trigger the check via "Recheck PRs" this should create status for all open PRs
<img width="373" alt="Screen Shot 2019-03-13 at 17 52 40" src="https://user-images.githubusercontent.com/8480657/54298416-fa785580-45b8-11e9-8602-82f70cbdde64.png">

Now the question is, whether the issue persists or not. It'd be great if you'd give me a quick message if the next PR won't get CLA status.

**Comment by dguido** [comment]
I clicked "Recheck PRs" for the 3 organizations that I have linked to cla-assistant: `crytic` `osql` and `trailofbits`. Then, I opened a recent PR where this is a missing CLA check, trailofbits/algo#1345, and noted that the check from cla-assistant is still missing. Upon manual inspection, Github user `0xmilkmix`, has not signed a CLA for our organization so I would expect cla-assistant to flag on his PR.

**Comment by KharitonOff** [comment]
ok, I believe to have found the root of all evil...
Could you remove the trailing comma in the field "Exclude the following repos from the org" and click "Recheck PRs" again, please?

**Comment by dguido** [comment]
Good catch! I removed the trailing comma in the listed of repositories excluded from `trailofbits`, then pressed "Recheck PRs" on `trailofbits` `crytic` and `osql`. I waited a few minutes and then opened the same trailofbits/algo issue as above. It is still missing the cla-assistant check.

**Comment by KharitonOff** [comment]
> I waited a few minutes and then opened the same trailofbits/algo issue as above. It is still missing the cla-assistant check.

Do you mean trailofbits/algo#1345 ? I can see CLA status there. CLA assistant doesn't comment on the existing PRs but it creates a status.
Btw. GitHub has not recognized @0xmilkmix as a committer there (see gray octocat symbols near commit messages). This means that he used a different email address for the commits than he stored in his GitHub account. CLA assistant checks only committers and not an author of a PR. @0xmilkmix can add the commit email to his account then GitHub will assign all commits to his account.

**Comment by dguido** [comment]
Hooray! The status was not there when I checked. It must have taken a bit longer than I expected to show up. Thank you so much! I will check that the other PRs in my orgs have a status check from cla-assistant.

**Comment by sdht0** [comment]
Hello!

We're trying to setup cla assistant for our organization. The org-wide setup seems to be up:
![image](https://user-images.githubusercontent.com/867424/65555240-0777e900-defa-11e9-9629-3569b11373cc.png)

However, pull requests to a private repo do not show any status check from cla-assistant. We verified that the webhook are being delivered successfully.
![image](https://user-images.githubusercontent.com/867424/65555150-b7992200-def9-11e9-8723-2822cd8a51c4.png)

Is there anything else we need to do?

Thanks.

**Comment by ibakshay** [comment]
Hi @sdht0 :) , 

The CLA Assistant check will only work for the public repos but not for the private repos. This is because for private repos, we need extended scopes to access the Private repos which the CLA Assistant don't request for. 
Thank you for using CLA Assistant 😄

**Comment by sdht0** [comment]
Okay, thank you.

**Comment by BIAgents** [comment]
update_changes_cuggestion_commits

- [ ] test all changes=success

- [ ] Get Put updates 

- [ ] merge_master_file_branche

- [ ] GeT Build portfolio - true

- [ ] Get BuildConfig - all cpu
- [ ] echo booleon -true
- [ ] Push Upstream for enrichment

- [ ] OnSuccess 200ok

- [ ] GetDebug_account details

- [ ] update account

**Comment by BIAgents** [comment]
Push_upstream
