### ISSUE TITLE
Database bootstrap fails when using Amazon DocumentDB

### ISSUE THREAD

**Issue by aosman-tibco** [cla-assistant/cla-assistant#424]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Start cla-assistant pointing to Amazon DocumentDB Cluster

What is the expected result?
cla-assistant starts successfully

What happens instead?
cla-assistant fails with the following error:

```
bootstrap webhooks
✓ src/server/webhooks/ping.js
✓ src/server/webhooks/pull_request.js

✓ bootstrapped, app listening on cla.foo.com:5000
{"name":"cla.foo.com","hostname":"e7cdb76649e0","pid":19,"level":30,"msg":"✓ bootstrapped !!! App listening on cla.foo.com:443","time":"2019-03-13T19:58:20.222Z","src":{"file":"/cla-assistant/src/server/app.js","line":191},"v":0}
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: namespace name generated from index name is too long
{"name":"cla.foo.com","hostname":"e7cdb76649e0","pid":19,"level":40,"msg":"CLA collection dropAllIndexes error:  { MongoError: ns not found\n    at Function.MongoError.create (/cla-assistant/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)\n    at /cla-assistant/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:497:72\n    at authenticateStragglers (/cla-assistant/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:443:16)\n    at Connection.messageHandler (/cla-assistant/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:477:5)\n    at TLSSocket.<anonymous> (/cla-assistant/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:333:22)\n    at emitOne (events.js:96:13)\n    at TLSSocket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at TLSSocket.Readable.push (_stream_readable.js:134:10)\n    at TLSWrap.onread (net.js:548:20)\n  name: 'MongoError',\n  message: 'ns not found',\n  ok: 0,\n  errmsg: 'ns not found',\n  code: 26 }","time":"2019-03-13T19:58:20.280Z","src":{"file":"/cla-assistant/src/server/documents/cla.js","line":39},"v":0}
{"name":"cla.foo.com","hostname":"e7cdb76649e0","pid":19,"level":40,"msg":"dropAllIndexes results:  false","time":"2019-03-13T19:58:20.307Z","src":{"file":"/cla-assistant/src/server/documents/cla.js","line":40},"v":0}
```

Amazon DocumentDB is a new service that is mongodb 3.6 compatible but has some builtin limitations. It appears that we're hitting a character limit for the collection name:

https://docs.aws.amazon.com/documentdb/latest/developerguide/what-is.html
https://docs.aws.amazon.com/documentdb/latest/developerguide/limits.html

**Comment by KharitonOff** [comment]
The Problem seems to be in the long index of the cla collection. Maybe you can provide a custom name of the index using `indexOptions`
https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#options-for-all-index-types

Change this lines: https://github.com/cla-assistant/cla-assistant/blob/d4c1226aa2b980981e12a7c42f528af1683ae74b/src/server/documents/cla.js#L32-L35
to this
```
let indexOptions = {
    unique: true,
    background: true,
    name: 'cla-index'
}; 
```
P.S.: unfortunately I could not manage it to set up and connect DocumentDB to my local dev instance in reasonable time in order to test it on my own.

**Comment by Ashex** [comment]
This change worked, I was able to bring up cla-assistant with documentdb. I should be able to migrate my existing database be renaming the index considering the change sets the index name to a static value.
