### ISSUE TITLE
Release schedule/cycle

### ISSUE THREAD

**Issue by syndbg** [cla-assistant/cla-assistant#425]
Hi, @KharitonOff 

Sorry for asking here (not sure if this is the right place), but how often do you people release (github release)?

I see that there are a lot of bugfixes since last release and it's better for everyone to use a specific github release instead of deploying from your latest master (not sure how stable is that).

**Comment by KharitonOff** [comment]
@syndbg thanks for asking. We don't have any release schedule. 
Sorry for not triggering the github release function last time. I'll fix it immediately. You are very welcome to provide any further feedback.

**Comment by syndbg** [comment]
@KharitonOff I see that new releases are made now. Thank you very much :tada: 

I think the issue can be closed.
