### ISSUE TITLE
Loss of contributor signatures on config change

### ISSUE THREAD

**Issue by dpetrick** [cla-assistant/cla-assistant#426]
URL to the linked Repo/Org: https://github.com/prisma/prisma

Steps to reproduce the problem:

1. Sign into CLA dashboard.
2. Edit linked repository and add whitelist for some GitHub users.
3. Save configuration.

What is the expected result?
All currently signed contributors are still present for the linked repository, whitelist is in effect.

What happens instead?
Lost all contributor signatures.

## Optional
Any other information? (attach screenshot if possible)
- This is a critical issue for us, as an open-source company, we need those signatures for legal reasons.
- All versions of the linked repository are empty, no history whatsoever is retained. No obvious way to restore a previous state.
- Updated at remains at the original date (17th of November 2017 for us), while it should show the current date (26th of March)
- We _only_ touched the whitelist field in the form, nothing else.

Browser/version: Firefox 65.0.1 MacOS 10.14.3

**Comment by KharitonOff** [comment]
@dpetrick Sorry for the inconvenience! Changed gist url caused this issue (https://gist.github.com/timsuchanek/f86241715fd26f82512c32380c9e85c8 has changed to https://gist.github.com/f86241715fd26f82512c32380c9e85c8). Actually this bug should have been fixed already...
I've rolled back the gist url to the previous one. Now you should see all your signees again.

**Comment by KharitonOff** [comment]
The "Updated at" points to the version of the Gist file (CLA). It is correct, that it remained at the original date

**Comment by dpetrick** [comment]
@KharitonOff Thank you kindly for the fast response. I can confirm that everything is in order again.

**Comment by KharitonOff** [comment]
@dpetrick great! You should also click "Recheck PRs" button to synch all open Pull Requests and update their status
