### ISSUE TITLE
2 Contributors CLA issue

### ISSUE THREAD

**Issue by DureSameen** [cla-assistant/cla-assistant#427]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Sign in Visual Studio with hotmail or any address not associated with github
2. Push changes and create pull request
3. ClA signed but still CLA signature is required from non-github email address
4. Add and verify that email to your github Account
5. but still CLA signature is required from non-github email address

What is the expected result?

What happens instead?
if an email is added to github ... double contributor issue should be solved.

**Comment by KharitonOff** [comment]
@DureSameen can you provide the link to the PR where the issue appeared, please?

**Comment by DureSameen** [comment]
https://github.com/eventflow/EventFlow/pull/619

**Comment by KharitonOff** [comment]
There was a small "recheck" link at the end of the comment, which triggers CLA assistant to recheck the PR.
<img width="792" alt="Screen Shot 2019-04-03 at 09 43 08" src="https://user-images.githubusercontent.com/8480657/55461670-4b49ff80-55f5-11e9-8e14-f772d5f52d0a.png">
Now everything is fine again :)
