### ISSUE TITLE
Text for Slides

### ISSUE THREAD

**Issue by yaseminc** [cla-assistant/cla-assistant#43]
either quotes "what people said about CLA assistant" (but who? :stuck_out_tongue: )

-or-

short, catchy statements about the tool

**Comment by thojansen** [comment]
We could just describe the workflow again. Later we can change that to customer quotes. @KharitonOff ?

- Sign in with GitHub
- Accept CLA
- Done

**Comment by yaseminc** [comment]
Sorry about closing this, my phone tricked me.
@thojansen so you want to address the contributor rather than the repo owner?
Also just a thought, the slides start rotating not only when the user gets to the anchor, so the user might find the statement "accept CLA" or "done" first, what could be irritating?

**Comment by thojansen** [comment]
ok, but right now I have no idea for catchy statements or quotes.
@dfarr @benboeser any ideas for some rotating statments in the following section of the landing page?

![screen shot 2015-06-03 at 08 12 10](https://cloud.githubusercontent.com/assets/5912220/7963573/4c22a132-09c8-11e5-9015-c29cfb1e5ecd.png)

**Comment by KharitonOff** [comment]
easy to set up
easy to use
2 clicks from pull request to signed CLA
open source

**Comment by thojansen** [comment]
let us rather go with #75
