### ISSUE TITLE
New org is not detected

### ISSUE THREAD

**Issue by iliakan** [cla-assistant/cla-assistant#432]
1. I had several repos linked.
2. Then I created an org and moved them there. 
3. Now at cla-assistant.org I can't see any links.
4. Also I can't see the new org in the list.

I removed cla webhooks manually from my repos, but the new org is not listed, so I can't use cla-assistant any more.

**Comment by MichaelTsengLZ** [comment]
I think you need to give org permission to the CLA-Assistant. There are two ways.
- The first way:
1. You could sign out of the CLA-Assistant and Github at the same time.
2. Sign in the CLA-Assitant. It will ask org permission at that time.
- The second way:
1. Go to your Github user settings.
2. Click the `Applications` on the left.
3. Click the `Authorized OAuth Apps` on the top
4. Choose CLA Assistant app and then grant permission to the CLA-Assistant.

**Comment by 0925042781** [comment]
https://github.com/cla-assistant/cla-assistant/issues/432#issuecomment-486900373
