### ISSUE TITLE
Does not show  repository on Configure CLA

### ISSUE THREAD

**Issue by azu** [cla-assistant/cla-assistant#436]
URL to the linked Repo/Org: [asciidwango/js-primer][]

**Context of permisson**

I(@azu) have a [Owner](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) permisson for [asciidwango/js-primer][] repository.
But, I have not [Owners](https://help.github.com/en/articles/permission-levels-for-an-organization) permisson for `asciidwango` organization.

In this context, I(@azu) can not setting cla-assistant for [asciidwango/js-primer][] repository. 

![image](https://user-images.githubusercontent.com/19714/56871695-2b72f380-6a5c-11e9-9530-72ca39da028c.png)

> does not show "asciidwango/js-primer" in the list. Other repositories are shown correctly.

Steps to reproduce the problem:

1. @azu authorize cla-assistant
2. @azu **Request** a permisson of [CLA Assistant App](https://github.com/settings/connections/applications/50f062943f087ec041c6) to `asciidwango` owners from https://github.com/settings/connections/applications/50f062943f087ec041c6
3. `asciidwango`(organization) owners allow [CLA Assistant App](https://github.com/settings/connections/applications/50f062943f087ec041c6)

![image](https://user-images.githubusercontent.com/19714/56871849-6d506980-6a5d-11e9-857f-aedf9528c16e.png)

> CLA Assistant is Grant on https://github.com/settings/connections/applications/50f062943f087ec041c6

4. @azu fail to "Configure CLA" on https://cla-assistant.io/

What is the expected result?

I(@azu) can configure CLA for [asciidwango/js-primer][].

What happens instead?

I(@azu) can not configure CLA for [asciidwango/js-primer][].
[asciidwango/js-primer][] does not shown on "Choose an org or a repo" list.

## Optional

- I(@azu) am not member of `asciidwango` organization. (I have not a perssmion for other repository on this organization)
- I(@azu) have Owner permissions for [asciidwango/js-primer] repository.(It is repository permisson)
- Other orgnization's repositories is shown on "Choose an org or a repo" list. Because, I have owners permisson for these organizations.

[asciidwango/js-primer]: https://github.com/asciidwango/js-primer

**Comment by KharitonOff** [comment]
We use following API to get the repos for the list: https://developer.github.com/v3/repos/#list-your-repositories for ```affiliation``` parameter we use ```owner, organization_member```

This API seems not to consider you as an owner of asciidwango/js-primer because @asciidwango is the owner and you have 'just' the owner rights.

I suppose if you would get the membership  in this organization (with restricted rights for all other repositories except ``js-primer``) you would be able to set up CLA assistant for this repo.

**Comment by azu** [comment]
I see. Thanks.
