### ISSUE TITLE
create default entry for CLA drop down list 

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#44]
and link it to the SAP individual CLA gist file (create a .json file in order to make it possible for other companies store their CLAs a default ones)

**Comment by KharitonOff** [comment]
@yaseminc is the styling of the categories in Gist dropdown ok?

**Comment by yaseminc** [comment]
@KharitonOff maybe try it left-aligned, like in this example:
https://github.com/cla-assistant/cla-assistant/issues/32 :)
