### ISSUE TITLE
Error 524: A timeout occurred

### ISSUE THREAD

**Issue by kunzese** [cla-assistant/cla-assistant#440]
URL to the linked Repo/Org:

https://github.com/Comcast/snowdrift/pull/2

Steps to reproduce the problem:

1. Fill out the form
2. Click on `I agree`
3. Wait

What is the expected result?

That the CLA is signed.

What happens instead?

> Error 524 Ray ID: 4dbc8aee3c667e98 • 2019-05-24 04:33:34 UTC
> A timeout occurred
> You
> Browser
> Working
> Budapest
> Cloudflare
> Working
> cla-assistant.io
> Host
> Error
> What happened?
> The origin web server timed out responding to this request.

**Comment by KharitonOff** [comment]
@kunzese thanks for letting us know. Could you try to sign the CLA again and let me know whether you are successful this time, please.

**Comment by kunzese** [comment]
@KharitonOff unfortunately not, still the same issue.
