### ISSUE TITLE
CLA status showing "pending" after signing CLA w/ email address from commit

### ISSUE THREAD

**Issue by chaseadamsio** [cla-assistant/cla-assistant#441]
**URL to the linked Repo/Org:** https://github.com/webpack/webpack-cli/pull/892

**What is the expected result?**

Signing the CLA for a PR with a commit that has:

1. a single author
1. in a GitHub org (with the same email address as the user) [this PR was done in an org called `chaseadamsio-forks`]
1. with the same email address in the commit as is in the GitHub email settings 

should set the check for CLA signing to passed.

**What happens instead?**

Status is still pending.

![image](https://user-images.githubusercontent.com/1024544/58307998-2f710780-7db5-11e9-9234-bbd21606950b.png)

![image](https://user-images.githubusercontent.com/1024544/58308066-5b8c8880-7db5-11e9-8625-751ade88f27a.png)

Commit:
```
commit 91239ef5d959ab7bc2dd56843b6ec3168dffa152 (HEAD -> fixWatchOptions, origin/fixWatchOptions)
Author: Chase Adams <realchaseadams@gmail.com>
Date:   Thu May 23 22:30:25 2019 -0700

    cli: fix watch options for array config
    
    Issue #4594 points out that watch options aren't being honored when the
    Webpack config is an Array. In cases when it's an array, there may not
    be a firstOptions.watchOptions, but there will be an options.watchOptions.
    
    In the current implementation, when the Webpack compiler watch method is
    called with watchOptions and the Webpack config is an array, watchOptions
    will be `true` and not an object.
```

**Comment by KharitonOff** [comment]
@chaseadamsio sometimes the update request of the CLA assistant doesn't reach GitHub. The easiest way to let CLA assistant update the PR status is to retrigger a PR webhook by making a change on the PR (pushing a new commit or by closing and reopening the PR).

**Comment by chaseadamsio** [comment]
👍 I force pushed a rebase of w/ an empty commit and that did the trick. Thanks!
