### ISSUE TITLE
Recover list of contributors

### ISSUE THREAD

**Issue by pkfrank** [cla-assistant/cla-assistant#444]
Earlier today, we added a bot as a whitelisted user.  We did not change any other settings, nor did we adjust the CLA itself.

Upon saving that new whitelisted user, we realized that we had lost the entire list of contributors who had already signed the CLA in our project.  Even when selecting the "All Versions" option in the contributors list, we still can't recover the full list.

1) Can you please help us recover the list of contributors who have signed the CLA in our project?

2) Can you confirm that if we re-upload the list of usernames from the step above that they will not be required to re-sign the CLA?

3) Can you please explain what "Re-Check PRs" does?

**Comment by KharitonOff** [comment]
Hi Peter,
I'm sorry for the inconvenience. I've changed the gist url back to the previous one (it was overwritten because of a bug).
All signatures made before the change are still available and valid. Re-upload would work too.
On "Recheck PRs" CLA assistant starts to check all open pull requests in all repositories of your organisation and update the statuses of the PRs.

**Comment by pkfrank** [comment]
Thanks very much for your help, @KharitonOff.

To be clear, should we ever need to whitelist a new user or bit, is the expected functionality that it will trigger a "new" CLA?  Or was that the bug in question?

**Comment by KharitonOff** [comment]
This is currently the bug, if you make some changes on the linked item (repo or org) it can happen that the gist url changes from this format https://gist.github.com/<gist owner>/<gist id> to this one https://gist.github.com/<gist id>. CLA assistant considers this two as different URLs and acts like you'd have linked a new CLA.
We'll keep this issue open till we have fixed the bug and we'll notify you as soon we are done.

**Comment by pkfrank** [comment]
Understood, thanks for that explanation and for all of your hard work in maintaining this project!

**Comment by jennifer-shehane** [comment]
@KharitonOff I am also experiencing this issue. I discovered the new whitelist feature recently so I went in and added a bot to our whitelists for all of our repos. 

2 of our repos then showed as disabled. I went back to update the gist url to the correct url and now they have NO contributors. Can I recover the contributors on these repos? It was quite a lot on one of them especially.

Specifically the broken repos are:

- https://github.com/cypress-io/cypress-documentation
- https://github.com/cypress-io/cypress-example-kitchensink

**Comment by ibakshay** [comment]
Hi Jennifer, Thank you for reaching out to us. 
So you have unlinked these 2 repositories and then linked again?

If yes,  Could you please check whether the gist URL for these two repositories you have updated is in this format `https://gist.github.com/<gist id>` but not this format`https://gist.github.com/<gist owner>/<gist id>` 
![Screen Shot 2019-07-08 at 15 59 06](https://user-images.githubusercontent.com/33329946/60816237-8f6f1200-a199-11e9-99f6-a079230144d0.png)

**Comment by jennifer-shehane** [comment]
@ibakshay Yes, it does seem that the 2 repos were unlinked, albeit unintentionally. I just wanted to edit the whitelist urls and did not want to unlink them. 

I only noticed the next day that they were unlinked when the hooks in our PRs were no longer verifying users that I knew had already signed the CLA.

The gist url is currently displaying in this format: `https://gist.github.com/cf22bc6c6b55219d0f9a76d04981f7ae`, I'm not sure if the format was different prior to the editing.

**Comment by ibakshay** [comment]
The gist URL will display in this `https://gist.github.com/<gist id>` even if you linked the item(repository or org) in this format`https://gist.github.com/<gist owner>/<gist id>`. 

Hence, Now the easiest solution could be, If you can try to unlink these 2 repositories and then link again  with this URL `https://gist.github.com/cf22bc6c6b55219d0f9a76d04981f7ae`

**Comment by jennifer-shehane** [comment]
Ok, thanks @ibakshay. This did work. For others, to 'unlink' a repo:

On the repo row, click **...** (More..) and select **Edit**. From the **Select a Gist** dropdown, select **No CLA** and click **Save**. The repo should now show as **Disabled**. 

<img width="1109" alt="Screen Shot 2019-07-09 at 10 03 16 AM" src="https://user-images.githubusercontent.com/1271364/60857647-56827c00-a231-11e9-8dca-63215842d72e.png">

Click on the **...** (More..) and select **Edit** on the repo, click the **X** beside the **Select a Gist** dropdown to clear out any value already shown as selected. Paste in the gist url with the `https://gist.github.com/<gist id>` format within **Paste a URL from a Gist** and click **Save**. 

Now the repo should show the correct number of all of the contributors that previously signed the CLA.

Any PRs that are still open with CLA checks will still show up as waiting for CLA signature though, so you need to click on **...** (More..) again and select **Recheck PRs**.
