### ISSUE TITLE
Bot required to sign CLA

### ISSUE THREAD

**Issue by GregTheGreek** [cla-assistant/cla-assistant#448]
URL to the linked Repo/Org: https://github.com/ChainSafe/ssz-js/pull/112

Steps to reproduce the problem:

1. Activate any bot and the pr will be blocked by the CLA

What is the expected result?
Greenkeeper should not be required to sign CLA

**Comment by ghuntley** [comment]
This is covered in the README. Whitelist `greenkeeper[bot]`

**Comment by ibakshay** [comment]
Like [ghuntley](https://github.com/ghuntley) mentioned, just whitelist all the bots and users who don't need to sign the CLA :)
