### ISSUE TITLE
have signed the CLA already but the status is still pending

### ISSUE THREAD

**Issue by moonming** [cla-assistant/cla-assistant#449]
PR: https://github.com/iresty/apisix/pull/167
![图片](https://user-images.githubusercontent.com/26448043/60320637-ee1fd900-99ac-11e9-9256-e4af31118d5a.png)

But @xiwangzishi already signed the CLA, I confirmed in the contributors list:

![图片](https://user-images.githubusercontent.com/26448043/60320603-d47e9180-99ac-11e9-92de-3b824bc8660e.png)

URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by ghuntley** [comment]
I think there is some infrastructure problems atm as I'm having issues _installing and configuring_. https://twitter.com/GeoffreyHuntley/status/1144454752425529345

**Comment by ibakshay** [comment]
It looks like the committer  [emitle](https://github.com/emitle)  hasn't signed the CLA yet.  Could you please check if he/she has signed the CLA and then reach out to us ?. 
<img width="778" alt="Screen Shot 2019-06-28 at 10 18 59" src="https://user-images.githubusercontent.com/33329946/60328596-dfc2c480-998e-11e9-9b13-13b9256b54fc.png">

**Comment by moonming** [comment]
@ibakshay yes, fixed. thanks very much :)
