### ISSUE TITLE
View bug when site is loading

### ISSUE THREAD

**Issue by MitchK** [cla-assistant/cla-assistant#45]
Hey :) 

The site is showing the {{ }} tags for a sort period of time because Angular.js is not loaded immediately. With a fast internet connection, I think it is not a big issue. But on mobile and/or with slow internet connections, it may look a bit ugly :)

I think ```ng-cloak``` should fix it.

Cheers :)

**Comment by KharitonOff** [comment]
Thnak you, Mitch! I'll take a look on it
