### ISSUE TITLE
There is no CLA to sign for [organization]/[repository]

### ISSUE THREAD

**Issue by ghuntley** [cla-assistant/cla-assistant#450]
# background

1. cla-assistant via the account `uno-platform-robot` has been installed at https://github.com/unoplatform into the organisation with an exclusion for `uno` so that it does not run on the main repo (yet).
2. a brand new repository has been configured for testing the integration
3. a pr has been raised at https://github.com/unoplatform/cla-testing/pull/1, when I click on it....

![2019-06-28_17-12-44](https://user-images.githubusercontent.com/127353/60324442-2da7ee80-99c8-11e9-84c9-f7e719ef27f1.gif)

# error

```
Error
There is no CLA to sign for unoplatform/cla-testing

(Unexpected token Y in JSON at position 27)
```

# extra information
- org: https://github.com/unoplatform
- pr: https://github.com/unoplatform/cla-testing/pull/1
- metadata and cla: https://gist.github.com/uno-platform-robot/a7ee691cf3568efce6b19a4d1c401ddd

![image](https://user-images.githubusercontent.com/127353/60324720-db1b0200-99c8-11e9-9234-477fe39958ed.png)

![image](https://user-images.githubusercontent.com/127353/60324738-ed953b80-99c8-11e9-8f82-b3ba79715a5e.png)

![image](https://user-images.githubusercontent.com/127353/60324807-1e757080-99c9-11e9-9b1a-4c852ffd85dd.png)

**Comment by KharitonOff** [comment]
@ghuntley thank you very much for the very good described issue. The problem here seems to be with your escaped quote signs `\"You\"`. It should work if you use double backslash: `\\"You\\"`

**Comment by ghuntley** [comment]
Thanks for the fast reply @KharitonOff. `\\"You\\"` was indeed the fix.
