### ISSUE TITLE
Switch to an open source database?

### ISSUE THREAD

**Issue by fafa0803** [cla-assistant/cla-assistant#453]
Hi,

I really like what you are doing and I would like to use the cla-assistant.  
Do you have any plans to switch from mongoDB to an open source database? Since last year October, the latest versions of Mongo DB are no longer provided under an open source license, but under the server side public license.

[Daimler AG acting on behalf of Daimler TSS GmbH.](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by KharitonOff** [comment]
Hi Fabian,
it is great to hear, that you are interested in using our tool! Currently we do not have concrete plans for switching from mongoDB to any other DB. But maybe you can take a look into the issue #430. There is an ongoing discussion about possible development directions for CLA assistant, which we are going to evaluate and test. @ibakshay will take a closer look into this topic in the next few months. In case you have a proposal or just an idea, feel free to share it with us :)
