### ISSUE TITLE
org-wide CLA not configurable?

### ISSUE THREAD

**Issue by srl295** [cla-assistant/cla-assistant#457]
We switched @unicode-org to a single organization-wide CLA, however, I can't find org-wide settings to configure the whitelist, etc.

URL to the linked Repo/Org: https://github.com/unicode-org/jira-github-pr-check/pull/16#issuecomment-510656788

Steps to reproduce the problem:

1. noticed the above PR. I want to whitelist the dependabot's PR
2. went to https://cla-assistant.io and logged in

What is the expected result?

Should see a single entry with org-wide settings for whitelisting CLA contributors.

What happens instead?

Right now, cloudflare errors and a broken page.
But after many reloads, only a few individual repos under this org show up, but not including the repo https://github.com/unicode-org/jira-github-pr-check

**Comment by KharitonOff** [comment]
Hi Steven,
have you linked the whole org or separate repositories? If you link the whole org, you can make org-wide settings (click on the three dots button on the right in the org entry)
![Screen Shot 2019-07-12 at 22 30 50](https://user-images.githubusercontent.com/8480657/61156996-25d26900-a4f5-11e9-925a-fb5ab6b960fb.png)

To be able to link the whole org you need to provide further auth-scope by clicking on the link in the "Configure CLA" view
![Screen Shot 2018-09-10 at 15 14 56](https://user-images.githubusercontent.com/8480657/61157211-c6c12400-a4f5-11e9-8d65-490cd05076fb.png)

**Comment by srl295** [comment]
@KharitonOff someone else on the team (@jefgen) linked the org, but I don't see "linked repositories". I see the following:

![Captura de Pantalla 2019-07-12 a la(s) 12 57 15 p  m  (2)](https://user-images.githubusercontent.com/855219/61157316-a7e97000-a4aa-11e9-8d03-a085e49b2da4.png)

**Comment by KharitonOff** [comment]
Can you click on "Configure CLA" and follow the link I posted above? Then you should be able to see and edit the linked org too (if you have admin rights)

**Comment by srl295** [comment]
@KharitonOff That fixed it! I didn't want to click that because I didn't want to reset everything.

*edit* but now it does not show any contributors?!

**Comment by KharitonOff** [comment]
Ok, yes. Every time you link your repo/org with a new or changed CLA contributors need to sign the (changed) agreement again. In case you use the same content of the CLA, you can import the previous signatures. But this is rather a legal question, whether the agreement, signed for a repo can be imported and used / is valid for the whole organization (multiple repos).

**Comment by srl295** [comment]
Yes, it's the identical CLA and already covers all of the repos.  So, we had re-imported all the signatures when moving to the org-wide CLA.  The question is why did I need to click "configure CLA" again, and did I just wipe out the signatories once again?

**Comment by KharitonOff** [comment]
You need to click "Configure CLA" just to come to the place where you can provide an extended scope for CLA assistant, only then CLA assistant is able to access your organization information and show it in the list of Linked Orgs (usually we do not request this scope, only from users, who are willing to link also the whole org). 
It is enough to link the org only once (like @jefgen did). So you don't need to link the org again.

**Comment by srl295** [comment]
Could you find out (without scope) that I have _linked repos which themselves belong to a linked org_? 

Anyway, I think the UI can be improved.

**Comment by srl295** [comment]
@KharitonOff  Looking at https://github.com/unicode-org/jira-github-pr-check/pull/16#issuecomment-510656788 is there a reason why adding the id 'dependabot'  to the allowed list doesn't allow the CLA?  Is it something different than a github ID, being a bot?

**Comment by KharitonOff** [comment]
@srl295 sorry for the long delay. In order to whitelist the dependabot you should use its login name (which is not obvious unfortunately). We can find the login name of committers (including bots) by calling github api `https://api.github.com/repos/<repo_owner>/<repo_name>/pulls/<pull_number>/commits`.

dependabot's login name is `dependabot-preview[bot]` now (previously it was another name)
