### ISSUE TITLE
Unable to Load

### ISSUE THREAD

**Issue by unityjeffrey** [cla-assistant/cla-assistant#460]
URL to the linked Repo/Org: https://github.com/Unity-Technologies/ml-agents

Steps to reproduce the problem:

1.  Logged into cla-assistant.io via my Github login
2.  The repo is not loading the list of linked repositories
3.  Can't get to the list of users

What is the expected result?
Should be able to see a list of the linked repositories on cla-assistant.io

What happens instead?
The loading screen sits there

**Comment by rlizzo** [comment]
I'm having the same issue. Cannot verify new PRs for the repository https://github.com/tensorwerk/hangar-py

**Comment by rlizzo** [comment]
Seems to be working again?

**Comment by ibakshay** [comment]
Hi @unityjeffrey,  are you still facing the same issue ?. Are you able to see your linked repositories now?

**Comment by unityjeffrey** [comment]
hi @ibakshay - it looks to be working now

**Comment by unityjeffrey** [comment]
thank you!
