### ISSUE TITLE
Whitelist organization doesn't work

### ISSUE THREAD

**Issue by normanrz** [cla-assistant/cla-assistant#464]
### URL to the linked Repo/Org:
https://github.com/scalableminds/webknossos/pull/4200

### Steps to reproduce the problem:

1. One of our team members (member of `scalableminds` org) created a PR
2. `scalableminds` is whitelisted for that repo

### What is the expected result?
There should be no CLA request since he is a member of the whitelisted org.

### What happens instead?
There is a CLA request.

### Other info
We have been using CLA assistant for several months now. We started seeing this issue today on all PRs.

**Comment by andschwa** [comment]
Chiming in a second instance of this: also started seeing it on every PR today after having used it fine for a couple months.

**Comment by ibakshay** [comment]
Hi @normanrz @andschwa,   I just checked and I'm sorry It seems like a bug :/. 

Anyways,  I have rolled back to the previous version, So CLA Assistant should be working fine :). 
You can do `Recheck PR` now, then the comment and status will be changed.

**Comment by normanrz** [comment]
Thanks for investigating and rolling back. Appreciated!
