### ISSUE TITLE
Signed up CLA shows CLA not signed yet.

### ISSUE THREAD

**Issue by ygqygq2** [cla-assistant/cla-assistant#467]
I've signed CLA but assistant still says not signed.

In the project pr.
https://github.com/cloudnativeapp/charts/pull/45

**Comment by ygqygq2** [comment]
https://github.com/cla-assistant/cla-assistant/issues/415
the same as.

**Comment by ibakshay** [comment]
Hi @ygqygq2, The Pull request looks fine, I just checked.

**Comment by theblindprogramm3r** [comment]
I'm hitting the same problem with PR: https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/108

**Comment by ygqygq2** [comment]
![image](https://user-images.githubusercontent.com/17672440/62502395-c0d31000-b821-11e9-9731-449c3a030931.png)

@theblindprogramm3r The gitconfig email must be added into your github email.

**Comment by theblindprogramm3r** [comment]
@ygqygq2 my gitconfig e-mail is listed in the github e-mails.
