### ISSUE TITLE
Cannot view guideline documents.

### ISSUE THREAD

**Issue by pacaceres** [cla-assistant/cla-assistant#474]
URL to the linked Repo/Org:
https://github.com/SAPDocuments

Steps to reproduce the problem:

1. Open link to CLA assistant page
2. Try to view Contributing Guidelines documents:
https://github.com/SAPDocuments/Tutorial-Contribution/blob/master/contributing.md
https://github.com/SAPDocuments/How-To-Contribution/blob/master/contributing.md

What is the expected result?
Open the documents so I can read them

What happens instead?
GitHub 404 not found page

**Comment by ibakshay** [comment]
Hi @pacaceres, You can view the Guidelines of this project here in https://github.com/cla-assistant/cla-assistant/blob/master/README.md
