### ISSUE TITLE
Using two distinct CLAs

### ISSUE THREAD

**Issue by NicolasPelletier** [cla-assistant/cla-assistant#475]
Good afternoon,

My company wants me to implement two CLAs in repositories in our github.com organizations: One for individual and one for corporations.

Apparently, Apache does this ( see [ICLA](https://www.apache.org/licenses/icla.pdf) and [CCLA](https://www.apache.org/licenses/cla-corporate.pdf) ) and they want me to make our organization support this feature.

Is such a thing possible with cla-assistant ?

Thanks.

**Comment by NicolasPelletier** [comment]
I now see from your own [CONTRIBUTING.md](https://github.com/cla-assistant/cla-assistant/blob/master/CONTRIBUTING.md) that you require corporation to send you a paper copy of a signed agreement.

So, I think I expect that you do NOT support this feature in automation, otherwise you probably would have used it on your own repositories.

I will not close this question, but wait for your confirmation.

Thanks.

**Comment by ibakshay** [comment]
Hi @NicolasPelletier, Like you told our CLA Assistant automation solution is only for `ICLA` and not for `CCLA`. 

However, If any organization has signed a `Corporate CLA (CCLA)`(in paper copy) already,  then you can whitelist that organization by adding that  `organization name` in the whitelisting field in our CLA Assistant tool. 

![Screen Shot 2019-08-15 at 13 00 27](https://user-images.githubusercontent.com/33329946/63090795-b0770f80-bf5c-11e9-8e84-8c09b6ac3963.png)
 
So after whitelisting the organization, all the Pull requests coming from that whitelisted organization (forked from your repository) will be considered as **signed** and the contributors from that whitelisted organization **no need to sign the `ICLA` again in this CLA Assistant tool**. 
For this scenario, We also do a membership test to check whether all the contributors in the PR is a **member** of that whitelisted GitHub organization or just has push rights. 

If anyone is not a member then CLA Assistant tool will comment like this 
<img width="808" alt="Screen Shot 2019-08-15 at 13 19 18" src="https://user-images.githubusercontent.com/33329946/63091681-765b3d00-bf5f-11e9-94b6-3e50ed6ada0b.png">

Let me know If something is not clear to you :) .

**Comment by NicolasPelletier** [comment]
Thanks.
