### ISSUE TITLE
CLA Assistant Waiting For Status To Be Reported

### ISSUE THREAD

**Issue by dagrooms52** [cla-assistant/cla-assistant#476]
URL to the linked Repo/Org:
https://github.com/Azure/Azure-AppServices-Diagnostics

Steps to reproduce the problem:

1. Submit Pull Request

What is the expected result?
CLA Assistant check completes successfully

What happens instead?
CLA Assistant reports "Expected -- Waiting for status to be reported"
Screenshot below

Workaround:
Pushed a new commit which triggered a re-check and cleared the CLA Assistant check

![cla_assistant_waiting](https://user-images.githubusercontent.com/8743446/63291784-1aebc080-c279-11e9-8a67-e392a2b3cddf.PNG)

**Comment by ibakshay** [comment]
Hi @dagrooms52, I believe there was some problem with the network traffic and So, CLA Assistant took some time to respond. 

You can also use this API `GET https://cla-assistant.io/check/azure/Azure-AppServices-Diagnostics?pullrequest=229` for one particular Pull Request to retrigger the CLA Assistant check If CLA Assistant takes time to respond.

**Comment by SmartManoj** [comment]
It redirects https://cla-assistant.io/check/telegramdesktop/tdesktop?pullrequest=8886
