### ISSUE TITLE
All project admins should see the same CLA status

### ISSUE THREAD

**Issue by lizrice** [cla-assistant/cla-assistant#477]
**Steps to reproduce the problem:**

We have a project with more than one admin, and we'd like all admins to be able to see / administer the CLA. Admin user A links the repository in cla-assistant, and everything appears to be working fine, but for admin user B not everything is as expected

**What is the expected result?**

Both user A & B should see the same status for the repository and its CLA. 

**What happens instead?**

For User B 
* the CLA field in the table is blank (although the gist field does link to the right place)
* the status field is grey, and the hover indicates that the gist is in place but the webhook isn't
* the contributor count is missing

![Screenshot 2019-08-22 at 09 52 49](https://user-images.githubusercontent.com/458616/63500920-a6a45d80-c4c2-11e9-986f-e068d4cd273a.png)
<img width="822" alt="Screenshot 2019-08-22 at 09 55 29" src="https://user-images.githubusercontent.com/458616/63501130-04d14080-c4c3-11e9-94d1-9bdb628043e4.png">

**Comment by ibakshay** [comment]
Hi @lizrice, Could you please request the `user B` to check again? Sometimes this can happen If there is heavy network traffic on our side. 

If the `user B` is still not able to see all the fields in the table then feel free to reach to us again.

**Comment by knqyf263** [comment]
`user B` is me. Then, I'm still not able to see all the fields😔

**Comment by ibakshay** [comment]
Hi @knqyf263, oh okay. Could you please check If you have [Admin Permission](https://help.github.com/en/articles/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization) for the repo `trivy`. It can be the case where you will have `push` and `pull` permissions but not the `admin` access.

**Comment by lizrice** [comment]
Oh, that will be it. @knqyf263 you do now! Can you check if it works now? 

So sorry, I thought that was already the case. Thanks for your help @ibakshay

**Comment by knqyf263** [comment]
@ibakshay I can see it now. Thank you for your cooperation 🙏
