### ISSUE TITLE
no access after moving repo to org

### ISSUE THREAD

**Issue by hhrutter** [cla-assistant/cla-assistant#479]
CLA Assistant kind of stopped working since I moved the repo hhrutter/pdfcpu to pdfcpu/pdfcu.

Although I just merged in a PR and it seems that cla assistant was involved but
there is no way for me to doublecheck the signers of the CLA.

I am unable to add the migrated repo.

**Comment by ibakshay** [comment]
Hi @hhrutter,  
Is the repo `hhrutter/pdfcpu` still linked to CLA Assistant? 

> I am unable to add the migrated repo.

Could you please give us more details on this so that I can understand your issue better  ..

**Comment by hhrutter** [comment]
Hi!

The repo hhrutter/pdfcpu was linked to CLAAssistant.
I migrated the repo to pdfcpu/pdfcpu and now I am stuck.
I am also the admin of the pdfcpu org. 
I need  to have pdfcpu/pdfcpu linked to CLAAssistant in a way 
so I don't need anybody to sign again.

The gist I was using is still there:
https://gist.github.com/hhrutter/04f84e2276b0703f2d9c85c479534cae

Thank you

**Comment by ibakshay** [comment]
Oh okay, I got the context of your issue. Thank you for the explanation. 

So you are not able to link the organization `pdfcpu` to the CLA Assistant right ?

Are you able to view the organisation `pdfcpu`  like below screenshot when you are trying to link it to CLA Assistant ? 

![Screen Shot 2019-09-02 at 13 16 56](https://user-images.githubusercontent.com/33329946/64111118-2e704e80-cd84-11e9-8f39-766d886c5682.png)

**Comment by hhrutter** [comment]
The org/repo dropdown just shows me my repos but no organization.

**Comment by ibakshay** [comment]
`pdfcpu` organization  is not showing up in the drop-down because you need to grant further `auth-scope` permission for linking organizations.

**steps:**

1. click on **Configure CLA**
1. Then select **want to link an org** as below

<img width="451" alt="Screen Shot 2019-07-17 at 17 26 35" src="https://user-images.githubusercontent.com/33329946/64113641-2536b000-cd8b-11e9-919c-68f9a3d184c2.png">

After you provide this extra auth scope, you will be able to link `pdfcpu` 😊 .

**Comment by hhrutter** [comment]
Does not work for me. No link.
But I remember I managed to grant this access once a couple of days ago.
This is what I get now:

<img width="647" alt="Screenshot 2019-09-02 at 17 24 14" src="https://user-images.githubusercontent.com/11322155/64124231-bc5d3100-cda6-11e9-876a-c11d7aef1087.png">

**Comment by ibakshay** [comment]
Then you probably need to request an approval for CLA assistant in GitHub to access your organisation `pdfcpu` and to do so, please follow the steps described here https://help.github.com/en/articles/requesting-organization-approval-for-oauth-apps )

**Comment by hhrutter** [comment]
Excellent! Now it works! Thanks!
