### ISSUE TITLE
Service does not work

### ISSUE THREAD

**Issue by HEBOS** [cla-assistant/cla-assistant#481]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by ibakshay** [comment]
Hi @HEBOS, Could you please send the URL of the affected Pull Requests because our service seems to be working just fine !.

**Comment by ceisele-r** [comment]
@ibakshay I have the same problem, this one does not seem to be working: https://github.com/bpmn-io/tiny-svg/pull/7

I get:

> Error
> There is no CLA to sign for bpmn-io/tiny-svg

and sometimes a bunch of errors from Cloudflare when reloading the page

> The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application.

**Comment by scudette** [comment]
Service seems down at the moment - maybe overloaded? 

Navigating to https://cla-assistant.io/ times out and github web hooks seem to be mostly failing with `We couldn’t deliver this payload: Service Timeout`

**Comment by scudette** [comment]
Going to the site now shows:

```
404 Not Found: Requested route ('cla-assistant.io') does not exist.
```

It seems down.

**Comment by ibakshay** [comment]
I am sorry for the inconvenience. We have seen some performance outages and long response time in the past 3 days. I will look into it. 
@scudette Yes I believe It was overloaded. 
However, CLA Assistant service is up and running without any issue now :) .

**Comment by scudette** [comment]
Thanks @ibakshay :-). Trying to redeliver the github web hooks still times out - maybe it will get better over time :-).

**Comment by ibakshay** [comment]
😄 @scudette  Could you give us the URL of the affected pull request ?

**Comment by scudette** [comment]
When I click redeliver it spins for a while and fails with a timeout.

![image](https://user-images.githubusercontent.com/3856546/64521122-c2b95300-d33a-11e9-92b5-076048cf1b48.png)
