### ISSUE TITLE
Service not working

### ISSUE THREAD

**Issue by prestonvanloon** [cla-assistant/cla-assistant#482]
No statuses are being reported.

No linked repos are listed in cla-assistant.io.

**Comment by ibakshay** [comment]
Hi @prestonvanloon, Could you please send the URL of the affected Pull Requests, So that we can look into your issue on what exact happened ?.

**Comment by prestonvanloon** [comment]
It's working now. The pull requests were in https://github.com/prysmaticlabs/prysm.
