### ISSUE TITLE
CLA assistant check is yellow while it is signed

### ISSUE THREAD

**Issue by ThePlenkov** [cla-assistant/cla-assistant#489]
in PR https://github.com/SAP/ui5-server/pull/239 I have button like this:

CLA assistant check
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
You have signed the CLA already but the status is still pending? Let us recheck it.

The thing is - when I go inside it says _You have signed the CLA for SAP/ui5-server_ while the button stays yellow and looks like not signed.

What's the point? Thank you!

**Comment by matz3** [comment]
There are two comments of which one is already green. I guess this is caused by the fact there is a webhook on organization and repository level. I've removed the repository hook which should solve the problem.

**Comment by ThePlenkov** [comment]
i'm not sure is it important to know or not - but I also have two emails work and personal in one account.
