### ISSUE TITLE
High failure rates of webhook fires from GitHub to CLA Assistant; 'We couldn’t deliver this payload: Service Timeout'

### ISSUE THREAD

**Issue by ryanblock** [cla-assistant/cla-assistant#490]
URL to the linked Repo/Org:
- https://github.com/architect
- Screenshots below for https://github.com/architect/architect

Steps to reproduce the problem:

1. Open a PR
2. Many webhook requests from GitHub fail

What is the expected result?

Webhook requests from GitHub succeed at a rate of many nines! 📈

What happens instead?

GitHub errors with `We couldn’t deliver this payload: Service Timeout`, see screenshots below.

## Optional
Any other information? (attach screenshot if possible)

![image](https://user-images.githubusercontent.com/200964/65738455-bd783a00-e096-11e9-83f4-74a00b95590b.png)
![image](https://user-images.githubusercontent.com/200964/65738472-d7198180-e096-11e9-8be4-eb9210deff3e.png)

Configuration information:
- We are not excluding any repos
- We have whitelisted two users (dependabot and dependabot-preview)
- We are using a gist CLA
- That's it!

Thanks for your attention!

**Comment by ibakshay** [comment]
hi @ryanblock, thank you for giving us the detailed insights and reporting us. We will investigate on this issue on why some of the webhook deliveries are getting failed and I will keep you posted.

**Comment by ryanblock** [comment]
Thank you! Let me know if I can get you anything else.

**Comment by ibakshay** [comment]
Hi @ryanblock, we have done the potential fix for high  failure of webhooks. Can you check now if you are still facing the same issue ?.
