### ISSUE TITLE
Error (404 File Not Found) when clicking on "Sign in with GitHub" on the CLA page.

### ISSUE THREAD

**Issue by manoranjith** [cla-assistant/cla-assistant#496]
URL to the linked Repo/Org: (Org) https://github.com/direct-state-transfer 

Steps to reproduce the problem:

1. Go to this link : https://cla-assistant.io/direct-state-transfer/
2. Click on the "Sign in with GitHub to agree" button on the bottom of the page.
3. It leads to this page (https://cla-assistant.io/404) that displays a "404 File Not Found" error.

What is the expected result?

Dialog box to enter my github username and password for authorizing cla-assisstant app.

What happens instead?

Page with "404 File Not Found" error is shown.

**Comment by danielksan81** [comment]
Same here. Seems only to work for repositories and not for organizations.

**Comment by ibakshay** [comment]
Hi @manoranjith,  @danielksan81 Thank you for reporting. I have reproduced the same scenario, and CLA Assistant seems to be working fine for both org and repo.  Can you send the link of the affected pull request ?. I will check.

**Comment by ibakshay** [comment]
Hi @choeppler, Now i understood the problem. thank you for the details..
So, If there is a pull request from the `dst-doc` repository of your organisation `direct-state-transfer` , then the CLA Assistant bot will comment on the Pull Request with this  URL  https://cla-assistant.io/direct-state-transfer/dst-doc  to sign the CLA. Try to sign the CLA with this URL https://cla-assistant.io/direct-state-transfer/(repo-name) , then you will be able to sign the CLA :) .

**Comment by choeppler** [comment]
Hi @ibakshay, thank's for looking into the issue and for the explanation!

I assume, once the CLA is signed at https://cla-assistant.io/direct-state-transfer/dst-doc, a contributor won't have to sign it again, if she submits a pull request to another repository in the `direct-state-transfer` organisation. Is that correct?

**Comment by ibakshay** [comment]
@choeppler yes, you are absolutely right 💯.
