### ISSUE TITLE
Signed License keeps pending not signed.

### ISSUE THREAD

**Issue by mendoza-conicet** [cla-assistant/cla-assistant#497]
URL to the linked Repo/Org:
https://cla-assistant.io/librenms/librenms?pullRequest=10614

Steps to reproduce the problem:

i signed with my name and my email , not the organization. 

What is the expected result?
accepted license

What happens instead?
keep license/cla Pending — Contributor License Agreement is not signed yet.

**Comment by KharitonOff** [comment]
Thanks for reporting the issue. In your case @castorinop is the committer of the PR and CLA assistant expects him to accept the CLA. As soon he accepts the CLA too, status will become green.
