### ISSUE TITLE
Unable to allow other administrators from my GitHub org to administer the cla-assistant settings

### ISSUE THREAD

**Issue by neeraj-laad** [cla-assistant/cla-assistant#499]
URL to the linked Repo/Org: github.com/appsody

Steps to reproduce the problem:

1. When I login to cla-assistant.io I see the CLA-assistant and configured gist. 
2. When other admins from the org login to cla-assistant.io they do not see the same screen.

What is the expected result?
- All admins for the org should be able to do things like 'recheck-all-PRs'
- I woudl liek to make this capability available to all without impacitng our current list of users who have signed.

What happens instead?
- They did not see any gist or orgs configured.

**Comment by ibakshay** [comment]
Hi @neeraj-laad , thank you for reaching out to us. The other admins also need to grant further  auth `org scope` for linking an organization. I have already explained  in  this [comment](https://github.com/cla-assistant/cla-assistant/issues/479#issuecomment-527124724) on how to grant this further `org scope` to CLA Assistant. 

If something is missing, feel free to reach out to us again 😄 .

**Comment by neeraj-laad** [comment]
Thanks! That worked.
