### ISSUE TITLE
Reports both "signed" and "not signed yet"

### ISSUE THREAD

**Issue by ScottBrenner** [cla-assistant/cla-assistant#500]
Hi, ran into an odd issue with @CLAassistant in https://github.com/SAP/InfraBox/pull/363
![image](https://user-images.githubusercontent.com/416477/67327720-3bc8d000-f4cd-11e9-821b-18cf6ce453e1.png)
After I signed the CLA, it reported both "signed" and "not signed yet"! Seeing this I re-signed the CLA and clicked the "recheck" button, but nothing happens. Weird!

**Comment by KharitonOff** [comment]
Thank you for reporting this issue and sorry for this confusion.
@ibakshay I think we should remove all CLA assistant comments on update, currently we take in consideration only the first one.
