### ISSUE TITLE
pls. help to disable CLA for apache dubbo

### ISSUE THREAD

**Issue by beiwei30** [cla-assistant/cla-assistant#501]
After we transfered Dubbo project from github/alibaba/dubbo to github/apache/dubbo, recently we noticed the incoming pull request is required to sign up with the original configured CLA, for example: https://github.com/apache/dubbo/pull/5067#issuecomment-535547920, and we found no way to unlink it. 

You can find more detail from: https://issues.apache.org/jira/browse/INFRA-19007. Would you mind to help us out from this?

We cannot recall who once configured it, so pls. help.

**Comment by KharitonOff** [comment]
The best way would be to unlink repo in CLA assistant first and then transfer it to another org. 
@beiwei30 probably there is still a webhook from CLA assistant in the repo settings. You can remove it by going to Settings --> Webhooks and deleting the cla-assistant one.

**Comment by beiwei30** [comment]
@KharitonOff I see. I will take a look if I could remove webhook on my side. Thanks for pointing this out.

**Comment by beiwei30** [comment]
Replied from Apache's administrator:

> There is no cla-assistant webhook. Please see my previous reply of 26 September: There is no configuration on the Apache side that would be causing this.

**Comment by KharitonOff** [comment]
Ok. I don't see any activity from CLA assistant in the newly created Pull Requests. 

Nevertheless I have also removed the old link from the system manually. I will close the issue again. Feel free to reopen it in case you still need any further assistance from our side.

**Comment by beiwei30** [comment]
Thanks for your help, @KharitonOff.
