### ISSUE TITLE
CLA assistant saas hangs 

### ISSUE THREAD

**Issue by derberg** [cla-assistant/cla-assistant#502]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Issue visible in this PR and many others

https://github.com/kyma-project/kyma/pull/6188
Or
https://github.com/kyma-project/cli/pull/292

What is the expected result?
Not hanging CLA check on PRs

What happens instead?
Even if you signed CLA before. The cla assistant is pending. I wanted to fix it quickly and whitelisted kyma-project org to unblock at least org members, but it only turned off the PR comment while cla check is hanging

**Comment by ibakshay** [comment]
hi @derberg , I just checked and the CLA check in both the PRs look fine. I believe, the CLA status took sometime to update the CLA check status.

**Comment by derberg** [comment]
strange... it was at least few hours long problem that could by only solved by signing the CLA again
