### ISSUE TITLE
CLA Not Signed comment has random parenthesis

### ISSUE THREAD

**Issue by aeneasr** [cla-assistant/cla-assistant#503]
When a PR is made from a contributor not having signed the CLA yet, the following comment appears:

<img width="778" alt="Bildschirmfoto 2019-10-31 um 13 18 40" src="https://user-images.githubusercontent.com/3372410/67946578-edf54b80-fbe1-11e9-8baf-005191ac3461.png">

Markdown:

```md
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra?pullRequest=1623))))))))))))))))))))))))))))))))))))) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra?pullRequest=1623))))))))))))))))))))))))))))))))))))) before we can accept your contribution.<br/><hr/>**Maurizio Dominici** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra?pullRequest=1623))))))))))))))))))))))))))))))))))))) it.</sub>
```

URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Create a PR against any ory repository: https://github.com/ory/
2. Wait for the CL Assistant to generate the comment

### What is the expected result?

The comment should look normal

### What happens instead?

See above

**Comment by ibakshay** [comment]
Hi @aeneasr , Does CLA Assistant posts comment like how you mentioned for  all the PRs of the organisation `ory` or  this issue is there only for one specific Pull Request ???

**Comment by aeneasr** [comment]
I believe I've observed this on several repositories. However, I can not 100% confirm that it's all of them, maybe it's just ory/hydra.

As you can see, the bot is doing a ton of edits over time - and apparently now also all additional parenthesis are removed:

<img width="1009" alt="Bildschirmfoto 2019-10-31 um 14 39 09" src="https://user-images.githubusercontent.com/3372410/67951694-4d585900-fbec-11e9-86d0-e41c17a62eef.png">

**Comment by aeneasr** [comment]
Sorry, I misread - it's happening a lot of times when the CLA is not yet signed, not only that specific PR.

**Comment by ibakshay** [comment]
Hi @aeneasr,  Are you still facing this issue ?. We have looked into our code-base and we didn't find any issue from our side.

**Comment by aeneasr** [comment]
Hey, sorry for the late reply - yes, this is indeed still an issue!

**Comment by Shegox** [comment]
@aeneasr just to check back again as we're currently looking for issues to look into. Does this still occur? 
I spot checked a few PRs in your organization and it seems to be working correctly now?

**Comment by aeneasr** [comment]
Yes, this did not happen any more! However, sometimes the CLA bot does not leave a comment on PRs!

**Comment by Shegox** [comment]
Great to hear. Thanks for the update.

> However, sometimes the CLA bot does not leave a comment on PRs!

Yeah, that is a different problem due to GitHub rate limits. I hope that with a long-term transition to GitHub Apps (#430) we can finally fix that for good. In the mean time if it occurs you can try this: https://github.com/cla-assistant/cla-assistant/blob/master/COMMON_ISSUES.md#cla-assistant-status-or-comment-not-updated

**Comment by aeneasr** [comment]
Awesome, thank you for the tip! Closing this then as it seems resolved :)
