### ISSUE TITLE
CLA Assistant fails to handle webhook

### ISSUE THREAD

**Issue by winder** [cla-assistant/cla-assistant#512]
Every couple days the CLA Assistant check fails for a pull request. When this happens we see the "Waiting for status to be reported" message, but it never comes.

URL to the linked Repo/Org: https://github.com/algorand/go-algorand

Looking in the webhook log I can see the failed requests, they all seem to be the same:

**Headers**
```
Content-Length: 17
content-type: text/html; charset=utf-8
Date: Mon, 18 Nov 2019 15:50:03 GMT
Server: Google Frontend
set-cookie: connect.sid=s%3AfOX0clJhpPrA8mpixd5RJ77IDox36-QZ.Fpt2P260QYawY4QHcr6ejc9%2FGCHBQJ%2BJCqZzafa0Hq4; Path=/; Expires=Mon, 18 Nov 2019 16:50:02 GMT; HttpOnly
X-Cloud-Trace-Context: 61afbddf72f6f3750000f33524dc8560;o=1
x-content-type-options: nosniff
x-frame-options: Deny
x-powered-by: Express
```

**Body**
```
Unsupported event
```

From the webhook log I can click "Redeliver", and so far it has always completed the second time. Clicking the re-check option inside the CLA Assistant dashboard also fixes the problem.

**Comment by ibakshay** [comment]
Hi @winder, Thank you for reporting the issue. We will look into it. Could you please tell the Error Status Code of the failed webhook  ?.

**Comment by winder** [comment]
400

**Comment by ibakshay** [comment]
Hi @winder, This is a bug related to our application  infrastructure and we are working on it. Thank you for giving all the insights, It certainly helped us in debugging this issue 😄 .

**Comment by ibakshay** [comment]
Hi @winder, I have shipped  the potential fix for this issue. Could you please check if you are still facing the same issue and If yes, Can you also share the payload of the failed webhook ?

**Comment by denisac77** [comment]
Fix

**Comment by winder** [comment]
@ibakshay I haven't seen any failures recently. I'll close the issue and open a new one if the problem comes back. Thanks for the help this problem was really annoying for our team!!
