### ISSUE TITLE
success modal view has no header any more

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#52]
@yaseminc what do you think from design perspective?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|cc0039852364826fd8df3cd557df3d25ff0f0521|[src/client/modals/templates/linkSuccess.html#L3](https://github.com/cla-assistant/cla-assistant/blob/cc0039852364826fd8df3cd557df3d25ff0f0521/src/client/modals/templates/linkSuccess.html#L3)| #50 |[![#50](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/cla-assistant/cla-assistant/pull/50)|

**Comment by KharitonOff** [comment]
![bildschirmfoto 2015-06-03 um 10 14 29](https://cloud.githubusercontent.com/assets/8480657/7955677/7ed745a8-09da-11e5-8d25-8c96e1333dd9.png)

**Comment by yaseminc** [comment]
was there a specific reason to leave it out?

**Comment by KharitonOff** [comment]
I suppose the the header and the content were repeating each other. Maybe we can use another wording there, like "Well done" or "Success", "Congrats" ...
@yaseminc, @dfarr what do you think about it?

**Comment by yaseminc** [comment]
I thought it already said "success"?

**Comment by KharitonOff** [comment]
it was "You created a new link!"

**Comment by KharitonOff** [comment]
I'm not sure if it's better now or not. @yaseminc ?

![bildschirmfoto 2015-06-09 um 16 34 58](https://cloud.githubusercontent.com/assets/8480657/8060445/a0b09e28-0ec5-11e5-8d99-4a0bb447e369.png)

**Comment by yaseminc** [comment]
I am not sure either. First, the space above and beneath 'Success' is definitely too much... My view is first led to the illustration, then to the button, afterwards I read the text below the illustration. The headline is floating and the words double in the meaning.. @KharitonOff could you send me a shot of the very first mockup I did for this to compare, please?
