### ISSUE TITLE
Basic Auth credentials being deprecated

### ISSUE THREAD

**Issue by nycnewman** [cla-assistant/cla-assistant#525]
We have started to receive messages from Github regarding deprecation of Basic Auth against API. Looking at the code, it appears that token will never be used even if specified. The code in pullRequests.js appears to only pass the Basic Auth credentials from the global config and never passes the token. The github.js code either way will always override token with Basic Auth (latter comes later in sequence and there is not check that auth object is already set). 

Also interested to understand when the Github app is used compared to the other Auth credentials. It looks like Pull Request updates only use Basic/Token credentials. Correct?

**Comment by ibakshay** [comment]
Hi @nycnewman, Thank you once again for pointing out the depreciation notice.
We have replaced the APIs using `Basic Auth` credentials with the global config (claassistantio) token.  These changes are reflected in our latest release `v2.4.6`.

**Comment by nycnewman** [comment]
Thank you. Was thinking of submitting a fix but you got ahead of me.
