### ISSUE TITLE
Can I revoke ma agreement with an organization ?

### ISSUE THREAD

**Issue by rguichard** [cla-assistant/cla-assistant#526]
Hi,

Not sure if this is the right place for that...

Few years ago, I signed a CLA agreement with an organization for contributing at one of its repository. An organization I am now leaving. The repository have been forked into my own userspace but I'd like to prevent the organization to merge my commit into its own repository and take over ownership of the merged commits (as stated in the CLA). I'd like the organization to have to respect the licence of my forked repository if it wants to merge my commits.

How can I do that ? Is there a way to revoke my CLA with my former organization ?

Regards,

**Comment by KharitonOff** [comment]
Unfortunately there is no such functionality in CLA assistant (UI) yet. 

I would suggest to contact the organization in case you'd like to revoke your agreement or negotiate new conditions. 

From technical perspective we have an API which is preparing the revoke functionality, but the whole process is not implemented fully yet. Unfortunately we currently don't have enough capacity to finalize it.
