### ISSUE TITLE
Unable to link repository

### ISSUE THREAD

**Issue by JusteenR** [cla-assistant/cla-assistant#527]
URL to the linked Repo/Org: https://github.com/WASdev/ci.docker

Steps to reproduce the problem:

1. I logged onto https://cla-assistant.io and requested to add the organization/repo, WASdev to CLA and it appears to have been given access.
<img width="770" alt="Screen Shot 2020-01-28 at 2 33 31 PM" src="https://user-images.githubusercontent.com/37389654/73298380-33261b00-41db-11ea-9163-ac99f0b27ecb.png">

What is the expected result?

When I go to configure CLA on https://cla-assistant.io the repo WASdev/ci.docker should appear under Choose an org or a repo.

What happens instead?

When I go to configure CLA on https://cla-assistant.io to link the repo it does not appear in list as an option.

<img width="454" alt="Screen Shot 2020-01-28 at 2 38 12 PM" src="https://user-images.githubusercontent.com/37389654/73298714-d70fc680-41db-11ea-9466-73a51bc4e286.png">

**Comment by ibakshay** [comment]
Hi @JusteenR, Thank you for reaching out to us. It looks really strange to me. If you are the admin and have push rights to the organisation `WASdev` then you should be able to see this organisation's repositories in the drop-down. Could you please try once again and get back to us?. We will look into this issue 😄 .

**Comment by JusteenR** [comment]
Hi Akshay,

I logged out of CLA assistant and logged back in but the repository still
does not show up, it's the same as my screenshots attached in the issue. I
am the admin with push rights to the WASdev/ci.docker repo and a member of
WASdev, if you could look into it further it would be great.

Thanks and have a good morning,
Justeen Randev

**Comment by ibakshay** [comment]
okay, then it looks like a bug in our side. We will look into it and I will keep you updated with the developments.

 Thank you and have a great day too  😄

**Comment by ibakshay** [comment]
@JusteenR, Are you able to see the `WASdev` organisation under the `Organisations` header in the drop down something like the below screenshot ?

![Screenshot 2020-01-30 at 15 47 12](https://user-images.githubusercontent.com/33329946/73459959-f93e4b80-4377-11ea-8f16-dacc0d1502a3.png)

**Comment by JusteenR** [comment]
No I don't have the organisations heading at all, I only have the
repositories.

**Comment by ibakshay** [comment]
@JusteenR, Oh great, Then it seems like an easy fix 😄 . 

So, To be able to link the whole organization you need to provide additional auth-scope. Then you can link the whole organization. 
**Steps:**
1. click on **Configure CLA**
2. Then select **want to link an org** as below 
![image](https://user-images.githubusercontent.com/33329946/61389742-b7f1bd00-a8b9-11e9-86aa-ad8d79a5138e.png)

After you provide this extra auth scope, you will be able to link the whole organization and also link the individual repositories of an organisation separately.

**Comment by JusteenR** [comment]
Hi, I previously went through that step before and now that link does not
appear when I click Configure CLA.

Thanks and have a good morning,
Justeen Randev

**Comment by JusteenR** [comment]
Hi,

If there has been any further insight to the issue I have been having it
would be greatly appreciated.

Thanks and have a great day,
Justeen Randev

**Comment by ibakshay** [comment]
Hi @JusteenR, Thank you for your patience. We are working on it and please give us some more time as your case seems like a special one. We will soon come up with a proposal on what you have to do from your side to get the organisations listed 😄.  I will keep you posted.   
Have a great day 😄

**Comment by JusteenR** [comment]
Hi Akshay,

Thanks for your reply and have a nice day. 😊

Best regards,
Justeen Randev

**Comment by KharitonOff** [comment]
Hi @JusteenR  this looks strange for me too. 

Actually you should see the list of repositories with admin rights from all organizations (where you are a member). We use following GitHub API to collect the list of user's repositories: https://api.github.com/user/repos?affiliation=organization_member,owner&per_page=100&page=1 (for details, please refer to https://developer.github.com/v3/repos/#list-your-repositories )
The repo WASdev/ci.docker seems not to be listed in the payload of the API.

The reason, why you can not see the list of your organizations in CLA assistant is that you do not have administration/owner rights for these orgs.

**Comment by KharitonOff** [comment]
I've requested support from GitHub...

**Comment by KharitonOff** [comment]
No response from GitHub yet...

**Comment by JusteenR** [comment]
Hi Anton,

Thanks for the update and have a nice day.

Regards,
Justeen Randev

**Comment by JusteenR** [comment]
Hi Anton,

I was wondering if there has been any updates on the issue.

Thanks and have a good day,
Justeen Randev

**Comment by KharitonOff** [comment]
Hi Justeen,

no, unfortunately I didn't get any response from github yet. I'll ping them again...
If we'll get no response at all, would it be possible for you to get admin rights for the whole WASdev org? I believe this would fix the issue as well..

Have a nice day too,
Anton

**Comment by KharitonOff** [comment]
Hi Justeen,

I finally got response from GitHub, could you contact me via email please, so I would be able to loop you in to the discussion...
Regards
Anton

**Comment by Shegox** [comment]
Hi @KharitonOff, hi @JusteenR, 

just wanted to ask back if you were able to solve the issue and if you could summarize the solution here shortly please?
Otherwise I would go ahead and close this issue in the next two weeks.
