### ISSUE TITLE
license/cla check wait indefinitely

### ISSUE THREAD

**Issue by anthonyjpratti** [cla-assistant/cla-assistant#528]
URL to the linked Repo/Org: https://github.com/twitter/scoot

Steps to reproduce the problem:

1. Previously signed the CLA
2. Open new PR, namely https://github.com/twitter/scoot/pull/477

What is the expected result?
license/cla check passes

What happens instead?
license/cla check wait indefinitely 

When I go to https://cla-assistant.io/ and sign in, I see no org info.

**Comment by ibakshay** [comment]
Hi @anthonyjpratti, 
Thank you for reaching out to us. I am sorry for this and we are facing this issue (CLA status check hanging sometimes) time and time again. We are working on it and we are yet to find the root cause of the problem. 

And `twitter` Organization is not showing up in the drop-down because you need to grant further 'auth-scope' permission for linking organizations.
I already explained the steps on how to grant this permission for CLA Assistant in accessing your organization [here] (https://github.com/cla-assistant/cla-assistant/issues/459#issuecomment-512337855)

**Comment by anthonyjpratti** [comment]
Thanks for responding so fast! If there is anything else I can provide, please don't hesitate to ask.

I mentioned the missing org because I thought it might be related, but thanks for a solution to that as well!

**Comment by louiseivan** [comment]
Hola @ibakshay,

Kinda experiencing the same problem

URL to the linked Repo/Org: https://github.com/blockstack/animal-kingdom

Steps to reproduce the problem:

Previously signed the CLA
Open new PR, namely animal-kingdom/pull/716
What is the expected result?
license/cla check passes

What happens instead?
license/cla check infinity sign

When I go to https://cla-assistant.io/ and sign in, It asks me to sign again

**Comment by KharitonOff** [comment]
@louiseivan could you add the email address, used for the commit (probably l.i.payawal@student.vu.nl) to your github account please? This will solve your issue

**Comment by louiseivan** [comment]
@KharitonOff I did. Still doesn't work. [
<img width="335" alt="Screen Shot 2020-02-11 at 1 53 18 PM" src="https://user-images.githubusercontent.com/58204144/74238379-f6c3e600-4cd5-11ea-877c-be0ad4be954e.png">
](url) I even tried unlinking and linking.

**Comment by KharitonOff** [comment]
Ok, according to the api payload of your PR you seem have mixed the values of user.name and user.email in git config :) So, in this case your email is "FairyTail062394" Could you try to add this to your github account too, please?

**Comment by srl295** [comment]
We have a stuck PR also, https://github.com/unicode-org/icu/pull/1001 — user @yumaoka has signed the CLA a long time ago and has many other approved PRs.

**Comment by josesimoes** [comment]
Same on several repos under www.gitbub.com/nanoframework organization.

**Comment by t3chguy** [comment]
Still seeing this every now and then

https://github.com/element-hq/element-web/pull/28912
https://github.com/element-hq/element-web/pull/28913

**Comment by srl295** [comment]
@t3chguy and anyone: for reference, there are two workarounds I know of:
1. `https://cla-assistant.io/check/<orgname>/<reponame>?pullRequest=<prnumber>` will trigger recheck 
2. from the dashboard at https://cla-assistant.io the admin can trigger recheck
