### ISSUE TITLE
Asking same account to sign CLA?

### ISSUE THREAD

**Issue by hawkerm** [cla-assistant/cla-assistant#529]
URL to the linked Repo/Org: https://github.com/hawkerm/monaco-editor-uwp/pull/30

Steps to reproduce the problem:

1. Create a new PR on one of your own Repos linked to CLA assistant

What is the expected result? Shouldn't require a CLA for your own account contributions.

What happens instead? Lists your account as needing a CLA assigned for contribution to your own repo.

**Comment by ibakshay** [comment]
Hi @hawkerm, Thank you for reaching out to us. 
CLA Assistant has a `whitelist` feature and you can make use of it 😄.  You can whitelist your account, members of your organization and also the bots like `dependabot, greenkeeper` who doesn't have to sign the CLA. 

**Steps to do :**
1. You can click on the pencil icon (edit) in your linked item (repository or organisation) in [CLA Assistant admin view](https://cla-assistant.io/)
<img width="1393" alt="Screenshot 2020-02-07 at 09 41 40" src="https://user-images.githubusercontent.com/33329946/74014093-3add8080-498e-11ea-9fc5-79bd5ca4ad2d.png">

2. Then you can add your `github username` like the below screenshot 

<img width="558" alt="Screenshot 2020-02-07 at 09 46 30" src="https://user-images.githubusercontent.com/33329946/74014384-d7078780-498e-11ea-8731-26a942b7771c.png">

**Comment by hawkerm** [comment]
Thanks @ibakshay!
