### ISSUE TITLE
another sign-out icon

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#53]
@yaseminc which one should we take?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|cc0039852364826fd8df3cd557df3d25ff0f0521|[src/client/home.html#L53](https://github.com/cla-assistant/cla-assistant/blob/cc0039852364826fd8df3cd557df3d25ff0f0521/src/client/home.html#L53)| #50 |[![#50](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/cla-assistant/cla-assistant/pull/50)|

**Comment by KharitonOff** [comment]
![bildschirmfoto 2015-06-03 um 10 15 13](https://cloud.githubusercontent.com/assets/8480657/7955853/b78c0ff4-09db-11e5-8819-f2d59f87ba34.png)

**Comment by yaseminc** [comment]
the current one fits better to the stroke weight of the CLA logo and the other icons imo. the arrow of the shown icon for "sign out" feels too mighty. BUT a tooltip (sign out) would be nice.
![bildschirmfoto 2015-06-03 um 10 47 37](https://cloud.githubusercontent.com/assets/11296839/7956107/ffad8446-09dd-11e5-9e5a-47c3f2084e0f.png)

**Comment by yaseminc** [comment]
color for the tooltip should be a lighter grey though
