### ISSUE TITLE
Any plans for GitLab?

### ISSUE THREAD

**Issue by erlend-sh** [cla-assistant/cla-assistant#534]
I get that it’s a whole other project as it doesn’t provide the same utilities as GitHub. Just curious if it’s up for consideration. No good solution for CLAs exist for GitLab so there is a serious need for it.

They do have their own automated bot features coming together:

https://gitlab.com/gitlab-org/quality/triage-ops

**Comment by KharitonOff** [comment]
Thanks for your interest and request. Unfortunately we do not consider developing this feature for GitLab. As you noticed, this would mean a completely different line of code. Surely most parts of the project could be reused, but this development would still mean a huge investment, which we can't afford.
Nevertheless all kinds of contribution are still welcome and we would try to provide our support as good as we can.
