### ISSUE TITLE
How can I verify the CLA?

### ISSUE THREAD

**Issue by justinsb** [cla-assistant/cla-assistant#539]
As a potential signer of a CLA, how can I know what CLA I am signing?  There are some CLAs I am authorized to sign, but it would be nice to know what a CLA is.   Do I have a better option than to compare the text to the pre-approved CLAs?

It would be helpful to have a link to the source for the CLA I was signing.  Bonus points for a sha256sum, but that's likely overkill.

**Comment by KharitonOff** [comment]
The only way to see whether there is a different version of CLA in place is to check the version date
![Screen Shot 2020-02-25 at 12 43 07](https://user-images.githubusercontent.com/8480657/75244620-6359dd00-57cc-11ea-9199-ed0a808b1965.png)

But unfortunately, there is no better option to compare different versions of CLA yet.

**Comment by justinsb** [comment]
Where do we file bugs against the bot? :-)

**Comment by ibakshay** [comment]
@justinsb, you are referring to CLA bot or the stale bot ? :)
