### ISSUE TITLE
Why would the webhook fail on an org setup?

### ISSUE THREAD

**Issue by tangollama** [cla-assistant/cla-assistant#541]
URL to the linked Repo/Org: github.com/newrelic-experimental

Steps to reproduce the problem:

1. Login to CLA Assistant
2. Setup a new org and provide same config as another org
3. Want the GIST be setup but the webhook fail

What is the expected result?

Webhook configured in the org

What happens instead?

Not that

**Comment by KharitonOff** [comment]
to be honest, I don't know what could cause the issue.
Have you already tried to unlink the org and link it again (just to be sure, that the problem is not caused by github api availability)

**Comment by sygibson** [comment]
@KharitonOff - I received a fail on one of my Org's, too.  I simply re-ran the action, and it worked fine the second time.
