### ISSUE TITLE
Unable to Link Organization

### ISSUE THREAD

**Issue by adamgfraser** [cla-assistant/cla-assistant#542]
URL to the linked Repo/Org: https://github.com/zio/zio-arrow

Steps to reproduce the problem: I set up an account with CLA Assistant and gave permissions for my organization. I can now link all the individual repos in the organization but do not see an option from the drop down 

1. I set up an account with CLA Assistant.
2. I gave permissions for my organization
3. I go to the drop down menu to link an organization or repo

What is the expected result?

I expect to be able to link the entire organization.

What happens instead?

I can see and link all the individual repos in the organization but I don't see the organization itself, or any section for organizations, on the drop down menu.

**Comment by ibakshay** [comment]
hI @adamgfraser, Thank you for reaching out to us :). 
You can see all the repositories to which you have write access in the drop-down menu however,  for linking the whole organization you need to provide an additional auth-scope. Then you can link the whole organization. 
I have described the steps on how to grant this permission for CLA Assistant in accessing your organization [here](https://github.com/cla-assistant/cla-assistant/issues/459#issuecomment-512337855). 
Have you already granted this additional auth-scope but still you don't see the organization `zio` in the drop-down?

**Comment by adamgfraser** [comment]
@ibakshay Thanks for getting back to me. Yes, I believe I did that. I used to see that link for "want to link an org?" and I clicked on that. Now I no longer see the link and I received an email that the application was granted an additional scope (`admin:org_hook`). Is that the right one? Is there anything else I need to do?

**Comment by KharitonOff** [comment]
Could you also check your settings as described in this comment, please: https://github.com/cla-assistant/cla-assistant/issues/176#issuecomment-259924887 
Just to make sure, that everything is set up correctly on the github side.

**Comment by adamgfraser** [comment]
Yes it looks correct:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/20825463/75694527-a73e5d80-5c76-11ea-8c09-da6caee1d72c.png">

**Comment by KharitonOff** [comment]
Sorry for long delay in our response.
According to github api your user seems not to have administrator rights for this org. You probably should request admin rights first in order to be able to link this organization in CLA assistant.

**Comment by adamgfraser** [comment]
Thanks! That resolved it for me.
