### ISSUE TITLE
Transfer / retrieve existing CLAs after moving repo between organizations

### ISSUE THREAD

**Issue by rwedge** [cla-assistant/cla-assistant#544]
After transferring a repository to a new organization  (Featuretools/featuretools to FeatureLabs/featuretools), the CLA assistant did not remember which users had signed CLAs when the repository was under the original organization and wanted everyone to sign again.  Is there a way to transfer the list of signatories to the updated repository location?

**Comment by KharitonOff** [comment]
It looks like the whole Featuretools organization is linked and not its separate repositories. this would mean, that the signatures, you have collected for the Featuretools/featuretools repo are valid for the whole organization. I also asume, that the gist file remained the same. In this case you can export the signatures of the Featuretools org and import them into the FeatureLabs/featuretools repository.

**Comment by rwedge** [comment]
That worked, thanks!
