### ISSUE TITLE
Race condition leading to dropped webhooks

### ISSUE THREAD

**Issue by bobvawter** [cla-assistant/cla-assistant#545]
I've been running down issues similar to #528 and so on in a private installation of CLA Assistant.  What I'm seeing in our https://github.com/cockroachdb/cockroach repo is that it's possible for a `review_requested` action to be sent and received before the `opened` action.  This doesn't play nicely with the debouncing behavior in CLA assistant and leads to stalled CLA checks.

The code which attempts to debounce actions on webhooks here: https://github.com/cla-assistant/cla-assistant/blob/master/src/server/app.js#L254-L281

The code which handles the incoming pull-request notification only takes action in response to three of the possible event actions:
https://github.com/cla-assistant/cla-assistant/blob/master/src/server/webhooks/pull_request.js#L135

If the first webhook received has an action other than `opened`, `reopened`, or `synchronized`, the handler will be a no-op, responding with a 200.  If the `opened` action then lands within the 2-second window it gets logged as redundant and a 202 is returned.

I have found a pair of webhook events in the GitHub delivery log which confirm that `review_requested` received a 200, while `opened` received a 202.

One solution here would be to make the webhook handler functions return a boolean to report back to `server/app.js` as to whether or not the request should be considered handled, which would then drive the debouncing behavior.

**Comment by bobvawter** [comment]
I'll follow up with a PR implementing the above later today if nobody beats me to it.

**Comment by KharitonOff** [comment]
Great catch! I've just stumbled over the same issue in our logs. Looking forward to your PR 😃
