### ISSUE TITLE
Difficulty Whitelisting Bot

### ISSUE THREAD

**Issue by adamgfraser** [cla-assistant/cla-assistant#549]
URL to the linked Repo/Org: https://github.com/zio/zio/pull/3183

Steps to reproduce the problem:

1. I am trying to whitelist the bot that authored the PR linked above. I added `scala-steward[bot]` to the whitelist in my CLA Assistant configuration
2. I tried to recheck the CLA status
3. However, it still says the CLA needs to be signed

What is the expected result?

I would expect that now that the bot is on the whitelist the CLA no longer needs to be signed.

What happens instead?

The CLA still needs to be signed.

**Comment by KharitonOff** [comment]
The trickiest part with whitelisting bots is to get their right login name. I usually look into the api response by converting PR url `https://github.com/zio/zio/pull/3183` to a get API url "`https://`api.`github.com`/repos`/zio/zio/pull`s`/3183`/commits"
There you can see the login name of the committer `"committer": {
"login": "scala-steward",`
If you change the name from `scala-steward[bot]` to `scala-steward` then it should work well.

**Comment by adamgfraser** [comment]
Thank you! That did it.
