### ISSUE TITLE
spelling mistakes on github.io page

### ISSUE THREAD

**Issue by jeffmcaffer** [cla-assistant/cla-assistant#55]
This is the text from the main claassistant.github.io page
"Got to Gist.GitHub.com, save a CLA text file there. 
Choose the creted file or copy and paste the URL in CLA assistant. "

First word I assume is "Goto".  Then in the last sentence is should be "created" not "creted".

**Comment by KharitonOff** [comment]
Thank you for pointing this out, @jeffmcaffer. 
We asked a native speaker to look over all our texts and rewrote some texts according to his feedback. Hopefully there no typos anymore :) If you find some again, please, let us know.
