### ISSUE TITLE
Org added, exclude repo, repo has own CLA setup - order of precedence ? 

### ISSUE THREAD

**Issue by sygibson** [cla-assistant/cla-assistant#552]
**_Thank you for the great work on cla-assistant.  It has been extremely useful for us!!_**

URL to the linked Repo/Org:  
> Org is "rackn"

Steps to reproduce the problem:

> Create CLA for a repo in Org - eg "rackn/foobar", with specific CLA "foobar.md".
> Configure CLA-assistant to now add entire Org, "rackn", exclude "foobar".
> Org has "rackn.md" agreement.
> 
> QUESTION - what is the order of precedence here??   Since the Org level excludes the "foobar" Repo, will it "fall through" to the specific configuration of the "rackn/foobar" with the "foobar.md"?
> 

What is the expected result?

> My hope is that the "rackn/foobar" repo will utilize/enforce the "foobar.md" CLA, while all other Repos will use the "rackn.md" CLA.

What happens instead?

> Unsure - since my account has already accepted both CLAs, I'm not able to effectively test the behavior.

**Comment by KharitonOff** [comment]
Thanks for your feedback ☺️ 
Your assumption is right. The `foobar` repo has its own CLA and CLA assistant should request contributors to sign it, while all other repos require the org CLA.

**Comment by sygibson** [comment]
Thank you - appreciate the response.
