### ISSUE TITLE
says I have signed the CLA but the check continues to fail

### ISSUE THREAD

**Issue by e-hill** [cla-assistant/cla-assistant#553]
URL to the linked Repo/Org: https://github.com/OctopusDeploy/go-octopusdeploy/pull/27

Steps to reproduce the problem:

1. Click the link, there is a comment on the ticket that says the CLA was signed.
2. I click on details and the page that loads says the CLA was already signed.
3.

What is the expected result?

The CLA check should pass.

What happens instead?

The CLA check fails.

**Comment by KharitonOff** [comment]
The committer of the PR is @eric-at-elsevier
Has hei/she also signed the CLA?

**Comment by shaz13-socgen** [comment]
Signed CLA still error. Same for me

**Comment by KharitonOff** [comment]
@shaz13-socgen can you provide the link to your PR, please?

**Comment by shaz13-socgen** [comment]
Sure - @KharitonOff 

https://github.com/RasaHQ/NLU-training-data/pull/24#partial-pull-merging

**Comment by KharitonOff** [comment]
@shaz13-socgen your case is the same: the committer is @shaz13 and not @shaz13-socgen 
As soon you sign CLA as @shaz13 the status will change to "success"

**Comment by eric-at-elsevier** [comment]
thanks it looks like it has signed correctly now, thanks
