### ISSUE TITLE
User-wide CLA

### ISSUE THREAD

**Issue by kevincox** [cla-assistant/cla-assistant#555]
I am glad that there is now an org-wide mode. However I have a number of open-source repos that occasionally get a contributor. It would be great if I could have CLA Assistant set up for all of them. Each repo is unlikely to get a PR but in total it would save some time and effort.

**Comment by KharitonOff** [comment]
Do you mean something like linking all repos at once? Unfortunately it is not possible.

What we have though is the possibility to collect signatures for a certain CLA. If you mark the "shared gist" checkbox for each of your linked repository, then the users will need to sign the CLA only once and this signature will be valid for all other repos that "share" the same gist file.

**Comment by kevincox** [comment]
I did mean linking all repos at once (basically the same as the organization linking but for users). 

it's a shame that isn't possible 😔
