### ISSUE TITLE
Failed webhook on org setup, HTTP 404 error in JS for https://cla-assistant.io/api/webhook/get

### ISSUE THREAD

**Issue by tangollama** [cla-assistant/cla-assistant#556]
I found issue #386, and I'm experiencing the same issue.

URL to the linked Repo/Org: https://github.com/newrelic-experimental

Steps to reproduce the problem:

1. Login to CLA Assistant
2. Setting up CLA for a new organization

What is the expected result?

- Webhook is created and shown in the org settings -> webhooks
- CLA Assistant shows organization in list of linked orgs
- CLA Assistant reacts to PRs in that org

What happens instead?

CLA Assistant indicates in UI that linking was successful, however after reloading the page the repository is not shown anymore.

<img width="551" alt="Screen Shot 2020-04-07 at 4 02 20 PM" src="https://user-images.githubusercontent.com/929261/78719766-7a730b00-78f2-11ea-9b95-2d1e5646404a.png">

## Optional
Any other information? (attach screenshot if possible)

1. It doesn't matter if choosing a predefined CLA or a gist, both don't work
2. The UI popup indicates linking was successful
3. The new org shows up an in the list of linked orgs, however only the checkmark for gist is given but not for webhook. 

<img width="1176" alt="Screen Shot 2020-04-07 at 5 12 14 PM" src="https://user-images.githubusercontent.com/929261/78720048-fcfbca80-78f2-11ea-8046-d17ea6edb081.png">

4. Retrying after log out / login in both Github and CLA assistant doesn't work
5. I have the required rights to the org

Browser/version: Chrome

**Comment by KharitonOff** [comment]
Thank you very much for detailed report. It sounds like a bug. We will look into it as soon as possible. 
Could you please also confirm, that the access to the organisation is granted (see #506)

**Comment by stephenfuqua** [comment]
I am able to reproduce this running release 2.7.0 locally. I've confirmed that the Application has been granted access to my repo, and I've confirmed that the API token in use has public_repo acess. Going to try a previous release next.

**Comment by tangollama** [comment]
@KharitonOff thanks for the follow up. It turns out that 3rd party access was restricted. I had to shut that off to get this working. It is connected now. 

Follow up question: how do we restrict 3rd party access but still allow this to work?

cc: melissaklein24

**Comment by KharitonOff** [comment]
> Follow up question: how do we restrict 3rd party access but still allow this to work?

This is a good question. I don't know how to do it yet. So far I know, you can reactivate the 3rd party restriction after the org was set up. We should investigate on it how to provide a better linking experience without manual switching of 3rd party restrictions.
