### ISSUE TITLE
Cannot sign CLA

### ISSUE THREAD

**Issue by benmaoer** [cla-assistant/cla-assistant#557]
URL to the linked Repo/Org:  
https://cla-assistant.io/pingcap/docs-tidb-operator?pullRequest=170

Steps to reproduce the problem:

1.  click url link to approve CLA
2.  there is no button in the page, it redirect to github
<img width="601" alt="image" src="https://user-images.githubusercontent.com/24819510/78742216-00905f80-798e-11ea-8aab-56f2ad860833.png">

What is the expected result? 
sign CLA

What happens instead?
Still Pending for CLA .  Browser/version: Safari/Version 13.0.5 (15608.5.11)
<img width="676" alt="image" src="https://user-images.githubusercontent.com/24819510/78742422-91ffd180-798e-11ea-8d82-9f7f986be82d.png">

**Comment by KharitonOff** [comment]
please check the solution in #548

**Comment by benmaoer** [comment]
> please check the solution in #548
It has nothing to do with the issue #548, it is solved after logging in https://cla-assistant.io through the github account
