### ISSUE TITLE
Github apps can't sign the CLA

### ISSUE THREAD

**Issue by iphydf** [cla-assistant/cla-assistant#559]
Example: https://github.com/TokTok/c-toxcore/pull/1441

I tried to add "imgbot" directly to the list, but github.com/imgbot is a different thing than github.com/marketplace/imgbot, so that didn't work.

**Comment by iphydf** [comment]
Also: how do I now delete IMGBOT from my list? It seems the (fake) signature is now stored forever.

**Comment by michael-spengler** [comment]
Hi @iphydf. 

I just looked into this issue and I saw the PR was already merged in the meantime. Did you already figure out a solution by your own?

Just to be sure: Did you use the following field for whitelisting IMGBOT resp. IMGBOTAPP ?

![Screen Shot 2020-04-27 at 13 45 32](https://user-images.githubusercontent.com/43786652/80369467-9e40c580-888e-11ea-95d4-466d83f056ed.png)

**Comment by iphydf** [comment]
Yeah, I found and used the whitelist field after a while, thanks. I still can't remove the signature, which I guess is a feature. The only way I could remove it, it seems, is by updating the CLA with a no-op and then importing everyone's signatures again, except for the bot.

**Comment by khareyash05** [comment]
Hi @iphydf @michael-spengler , i have a github app which is failing CLA due to invalid github user which is true, how did you solve this?

**Comment by khareyash05** [comment]
unstale
