### ISSUE TITLE
Unable to unlink cla-assistant

### ISSUE THREAD

**Issue by arnog** [cla-assistant/cla-assistant#561]
URL to the linked Repo/Org: https://github.com/arnog/mathlive

### Steps to reproduce the problem:

I have:
1/ removed the depot in cla-assistant.io
2/ verified there are no webhooks for cla-assistant in my depot
3/ verifier there are no installed GitHub Apps for cla-assistant in my depot

### What is the expected result?

That when PR is submitted, a CLA is not required.

### What happens instead?

The PR integration check fails for lack of a signed CLA.

<img width="846" alt="Screen Shot 2020-04-25 at 7 07 40 AM" src="https://user-images.githubusercontent.com/760798/80281941-77826380-86c3-11ea-8385-2bb0f0c0e2ea.png">

**Comment by michael-spengler** [comment]
Hi @arnog. I just looked into this issue - on CLA side it seems there is no entry for the repository https://github.com/arnog/mathlive.

As soon as you unlink the repository from the Contributor License Agreement the webhook is normally deleted immediately. I can imagine there were some network issues at the time of unlinking.

Solution proposal.
Relink the CLA with the repository https://github.com/arnog/mathlive and unlink it shortly after.

If this does not solve the issue please feel free to reach out to us again.

**Comment by KharitonOff** [comment]
@arnog could you also remove the cla-assistant status from the list of "required" statuses, please. I believe this will solve your issue.

**Comment by arnog** [comment]
@KharitonOff That was it! 

Settings > Branches > Branch Protection Rules : Edit.

Thanks!
