### ISSUE TITLE
sign to CLA is not working

### ISSUE THREAD

**Issue by elvisdukaj** [cla-assistant/cla-assistant#564]
URL to the linked Repo/Org: https://github.com/espressif/esp-idf/pull/5191

Steps to reproduce the problem:

1. I sign in with GitHub account to the CLA
2. A message that confirms the registration appears
3. When I try go back to the pull request page the CLA seems not signed

What is the expected result?
I expect that all the checks will be passed

What happens instead?
Checks are still not passed

Browser/version:
Opera 68

**Comment by michael-spengler** [comment]
Hi @elvisdukaj. This looks like a duplicate to: https://github.com/cla-assistant/cla-assistant/issues/562#issuecomment-619914668

If this does not solve your issue please let me know. I will take a deeper look into it then.

Kind regards
Michael

**Comment by elvisdukaj** [comment]
Yes it solved the case! Thank you very much :smile:
