### ISSUE TITLE
Private repo connects but is missing CLA

### ISSUE THREAD

**Issue by derekherman** [cla-assistant/cla-assistant#565]
I spun up an instance of this project on Cloud Run and MongoDB Atlas without any issues. However, in order to get a private repository to show up I needed to add the `repo` scope to the `src/config.js` `admin_scope` option and then the private repo was showing up in the list of repositories to choose from.

Anyhow, everything got connected and I tested a PR and it asked for me to sign the CLA.

![Screen Shot 2020-04-30 at 6 23 59 AM](https://user-images.githubusercontent.com/1715811/80715467-3fa46300-8aab-11ea-86db-c7470c009132.png)

However, when I click on the `details` link I get `There is no CLA to sign for xwp/private-repo` even though it shows up as being connected with the gist and webhook in the admin. Anyone have some ideas what's happening?

**Comment by KharitonOff** [comment]
Does the CLA Github user have access rights to your repository? All api calls on the CLA page (not the admin view) are done with CLA Github user token. I can imagine that something goes wrong there.

**Comment by derekherman** [comment]
Are you saying that the token needs repo permissions to work correctly? That’s an extremely elevated set of permissions for a token.

**Comment by KharitonOff** [comment]
Yes, this is just a guess, which I would try out... And I am talking about the 'technical' user, which usually comments on the PRs, the token which you provide via environmental variables `.env`. 

One of the calls, which needs to be done is getting the repo information from github. You can usually do this without any privileges for public repos, but if you want access information about a private repository you need appropriate rights to do so...
