### ISSUE TITLE
General Troubleshooting

### ISSUE THREAD

**Issue by michael-spengler** [cla-assistant/cla-assistant#567]
Provide a diagram for typical symptoms and solutions.

Roles
Contributor
Admin

Typical example symptoms & solutions: 
1. Contributor can not sign CLA --> check this link to see how to configure git: git config ...
2. CLA Status seems wrong --> Contributor should retrigger the CLA check vie "Recheck" Button or via API

**Comment by ibakshay** [comment]
## most common issues and solutions flow chart 
---
![CLA-Issue-tracking-flow-chart](https://user-images.githubusercontent.com/33329946/81485376-e081e380-924c-11ea-866a-abc243cd4a03.png)

[Link 1](https://github.com/cla-assistant/cla-assistant/issues/539)
[Link 2](https://github.com/cla-assistant/cla-assistant/issues/520#issuecomment-571590565)
[Link 3](https://github.com/cla-assistant/cla-assistant/issues/549)
[Link 4](https://github.com/cla-assistant/cla-assistant/issues/542)

**Comment by ibakshay** [comment]
If the above `issue tracking flow chart` helps in solving your issue then please kindly give 👍 reaction to this comment. We will try to automate our technical support as much as possible for all the commonly occurring issues, FAQ  :)

**Comment by ohsayan** [comment]
We're having an odd issue with our self-hosted CLA assistant here: https://cla.skybasedb.com. Like you can see, the styles.css never loads and fails with a 'MIME type error' (reading off a chrome inspection tab). FWIW, we're running cla-assistant off the v2.8.5 tag
