### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by stagg54** [cla-assistant/cla-assistant#573]
URL to the linked Repo/Org:
https://cla-assistant.io/JKISoftware/
Steps to reproduce the problem:

1. goto page above
2. click on Sign in with Github to agree
3. Get 404 regardless of whether already signed in to Github or not.  Happens in Opera and Edge on latest version of Windows, even after clearing caches.

What is the expected result?
 Should allow me to sign it. Never used cla-assistant before but imagine that some sort of success or failure page should show up.

What happens instead?
I get a 404

Browser/version:
Opera 68.0.3618.125
Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763
Windows 10 Pro 10.0.17763 Build 17763
Any other tested browsers/devices(OK/FAIL):

**Comment by stagg54** [comment]
perhaps better described in #574

**Comment by KharitonOff** [comment]
I will close this issue, since it is related to the #574 
See my comment there :)
