### ISSUE TITLE
CLA assistant hangs, unable to sign

### ISSUE THREAD

**Issue by hork71** [cla-assistant/cla-assistant#577]
URL to the linked Repo/Org:
https://github.com/denoland/deno/pull/6064

Steps to reproduce the problem:

1. Click Contributor License Agreement

What is the expected result?
Signed agreement

What happens instead?

Redirected to https://cla-assistant.io/accept/denoland/deno?pullRequest=6064

Clicked button 'Sign in with GitHub to agree'

Page hangs until the message 'Service Unavaliable' appears

<!--

## Optional
Any other information? (attach screenshot if possible)

Browser/version:
Chrome Version 83.0.4103.61

**Comment by ibakshay** [comment]
Hi @hork71,  Thank you for reporting the issue. We will look into it. Could you please send us the screenshot of the error message ?? :)

**Comment by hork71** [comment]
Hello @ibakshay ,

Thank you for the quick response. 
<img width="601" alt="cla_service_unavailable" src="https://user-images.githubusercontent.com/66360109/83686857-3dbe4a00-a5eb-11ea-9ee4-bb3297681c4c.png">

**Comment by ibakshay** [comment]
Thank you very much. This looks very strange to me. Give us some time. We will look into our logs and will get to you ..

**Comment by hork71** [comment]
Using FireFox 77.0.1 yields the same results

**Comment by hork71** [comment]
@ibakshay any ideas yet?

**Comment by ibakshay** [comment]
Hi @hork71, sorry for the delayed response. I did some changes to our backend. Hopefully, it works now. 
Can you please revoke the access for `CLA assistant` before you try again (Then CLA assistant will automatically ask for necessary permissions when you are signing in). 
## Steps to do so: 
`settings -> applications -> Authorized OAuth Apps -> CLA Assistant -> revoke Access`

Let us know if it works :)

**Comment by hork71** [comment]
Hi @ibakshay , 

Your solution worked, thank you very much 👍

**Comment by ibakshay** [comment]
@hork71 awesome. Have a great weekend 😄
