### ISSUE TITLE
CLA Assistant Not Working

### ISSUE THREAD

**Issue by adamgfraser** [cla-assistant/cla-assistant#578]
URL to the linked Repo/Org: https://github.com/zio/zio

Steps to reproduce the problem:

1. Go to an issue like this one (https://github.com/zio/zio/pull/3754)
2. There is no message from the CLA Assistant
3. When I click on the link I get a message

```
Error
There is no CLA to sign for zio/zio

(Bad credentials)
```

What is the expected result?

I expect the CLA Assistant to generate a message for every PR to our organization and to be able to access the data on everyone who has signed the CLA through the CLA assistant site.

What happens instead?

CLA Assistant is not generating messages and bad credentials error is displayed when trying to access.

**Comment by KharitonOff** [comment]
This looks like an invalid token. Probably the user, who has linked the org in cla-assistant has revoked his permissions for CLA assistant app or doesn't have enough rights anymore. Anyways you (an owner of the organization) can solve this problem by logging into the cla-assistant.io and clicking "Recheck PRs" button.

**Comment by adamgfraser** [comment]
Hi! Thanks for your help. I'm not seeing any button to do that. Here is what I see when I log in now? I used to see the CLA for the organization with the ability to view signers and take other actions but now I don't see anything.

<img width="1252" alt="Screen Shot 2020-06-05 at 5 50 56 AM" src="https://user-images.githubusercontent.com/20825463/83878149-8ad81400-a6f0-11ea-92d7-8ffb4c5a4fc5.png">

**Comment by KharitonOff** [comment]
Hi Adam, do you have admin rights for the org? Can you check your settings please, whether you has granted CLA assistant access to the org: https://github.com/settings/connections/applications/50f062943f087ec041c6

**Comment by adamgfraser** [comment]
Hmmm, I had to reset my Github password and now I not seeing it on the list of authorized Apps.

<img width="1248" alt="Screen Shot 2020-06-05 at 6 38 17 AM" src="https://user-images.githubusercontent.com/20825463/83882558-266c8300-a6f7-11ea-9bf9-f5056f74c0a6.png">

**Comment by KharitonOff** [comment]
You can logout from the old session via https://cla-assistant.io/logout and sign in again.

**Comment by adamgfraser** [comment]
Okay, so now I think am back to the prior situation. It looks like access is correctly set up but I'm still not able to manage our activities when I log in. Thank you again for your help with this by the way!

<img width="1249" alt="Screen Shot 2020-06-05 at 8 33 08 AM" src="https://user-images.githubusercontent.com/20825463/83895171-312f1400-a707-11ea-8535-aed0f7df104a.png">

<img width="1006" alt="Screen Shot 2020-06-05 at 8 33 28 AM" src="https://user-images.githubusercontent.com/20825463/83895208-3d1ad600-a707-11ea-97f6-fb94ca136bcf.png">

**Comment by KharitonOff** [comment]
Hi Adam, when you click on the button "Configure CLA" do you see this link there?
![Screen Shot 2020-06-08 at 11 54 11](https://user-images.githubusercontent.com/8480657/84017398-e0c1eb80-a97e-11ea-8025-3daa7c390442.png)

**Comment by adamgfraser** [comment]
@KharitonOff I do see that link, but it looks like when I click on that I have to grant permissions for the organization again. Should I go ahead and do that?

**Comment by KharitonOff** [comment]
Yes, right. You need to grant CLA assistant right to access your orgs in order to get it listed in the UI.

**Comment by adamgfraser** [comment]
Got it! And then Recheck PRs?

**Comment by adamgfraser** [comment]
All working now! Thank you for your help!
