### ISSUE TITLE
Support: recover already signed users from lost GitHub user credentials

### ISSUE THREAD

**Issue by fauust** [cla-assistant/cla-assistant#581]
Hi!
Is there a way to recover already signed information from a lost GitHub credential account linked to CLA-assistant?

Ideally, we would like to do a CSV export/import from the old account to a new account.

Thanks for your help!

**Comment by KharitonOff** [comment]
What do you mean with lost GitHub user credentials? You have linked a repo with a user, whose credentials are lost now and you can not access the cla-assistant with this user anymore, is this the problem? Or have you signed multiple CLAs with the account and you don't want to sign all theese documents again with a new user?

**Comment by fauust** [comment]
> What do you mean with lost GitHub user credentials? You have linked a repo with a user, whose credentials are lost now and you can not access the cla-assistant with this user anymore, is this the problem?

This is the exact problem

**Comment by KharitonOff** [comment]
Ok then I believe, the new user has become an owner/admin of the repo now. The signatures are not connected to a user, but to the linked repository/organization and gist file. This means, that you can just log into the CLA assistant with the new user (who has admin right on the repository) and you should see all linked repos and signatures there.

**Comment by fauust** [comment]
Will try this, thanks!

**Comment by fauust** [comment]
Hi!
Sorry for not closing this issue. I finally regain access through another account on the repo.
Thanks!
