### ISSUE TITLE
Creating an Org signature flow?

### ISSUE THREAD

**Issue by byjrack** [cla-assistant/cla-assistant#583]
So I may be a bit dull this morning, but could use some help on how to implement an Org signature flow natively (if possible).  Basically in my head we would have independent Gists on the same Repo prompting the user for two paths Individual or Corp. And if you follow the Corp it would add for the Org and not the user using the whitelist feature.  Currently it seems like you can only have one link and that is tied to the user automatically.

From testing I could do a wet signature by email process where I manually add the Org to the link record, but didn't know if I was just missing some doc somewhere on doing a branching type authorization.  I don't think we can customize the PR comment yet either so I think I would need to add a header to the ICLA text to try and direct them to the manual process for a CCLA.

**Comment by KharitonOff** [comment]
Actually we do not support CCLAs but only iCLAs. There are some workarounds though, which are pretty limited:
- you can not link multiple CLAs with one repo or with an org, but you can consider using "custom fields" for this, where user can let you know whether he accepts the CLA in his own name or in the name of his organisation
- there is a possibility to whitelist an org, which would mean that all contributions coming from this GitHub org get green check. You can only manually add an org to the whitelist.

There is no possibility to customize a PR comment. But in case you are going to host your own CLA assistant instance, you can fork the repo and change the text in the source code.

**Comment by byjrack** [comment]
Got it @KharitonOff thanks for the reply.  I wasn't sure if I was just missing how to update the whitelist through features like custom fields so appreciate the clarification.  I am sure there are others who would love to get that supported natively, but the ICLA works great and we can handle the CCLA using a wet signature process and the whitelist today.
