### ISSUE TITLE
Enabling multiple CLAs to be associated with an org

### ISSUE THREAD

**Issue by vbasem** [cla-assistant/cla-assistant#586]
Another specific suggestion to my use is the follow:

under an organization afew companies might be active which will require their own variation of the CLA.

A possible solution would be to link multiple CLAs to an org and have CLA-Assistant chose the right one based on a label/tag/file originating from a particular repo in that org.

I understand this might be a bit more involved than a quick feature, but certainly a viable problem for bigger corporations.

Please let me know what you think.

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by KharitonOff** [comment]
> I understand this might be a bit more involved than a quick feature, but certainly a viable problem for bigger corporations.

It sounds like a viable problem, but you are the first person, who brings it up... So I believe that this is rather an edge case. With the current state of code you can link separate repos with different CLAs.

**Comment by vbasem** [comment]
Indeed, and that is what I have started to do. As you mentioned, it might be an edge case and this is what it looks like:

- 1 single org for multiple business units with different CLAs
- each unit will have to manage its own repositories under the ORG by knowing which repo + cla is the correct choice
- decentralized approach, to avoid central foss office bottle necks, require the business units that they take care of their own repos

Now a manual approach is error prone and throws a wrench into my ambitions of automating everything. 

Hence I was hoping to tag repos or include a file indicating their business unit origin and map that to the correct CLA in the assistant. 

The work flow could for example be:
```
CLA Assistant ---> add org --> add multiple CLAs and map them to labels:
CLA1 -> BU1
CLA2 -> BU2
```
And the webhook would then be handled via the following workflow:
```
Incoming webhook event -> get repo labels ->  find mapped CLA to the label 
-> check signature status....
```

I am open to any other proposal on how I can automate the aforementioned setup.

p.s. I am unable to  influence the org / CLA/  BU structure itself sadly

**Comment by KharitonOff** [comment]
I see your point :) 
Here are some thoughts from my side:
Your idea is for sure doable, but there is a certain amount of work required to implement your proposal. The main part would be redesigning current database model, which doesn't consider linkage of multiple CLAs with one org. 
From my point of view the desire to automate everything doesn't justify the workload these changes would require and possible errors, they would generate...

I also don't see a big difference in the manual work. Whether you go to GitHub and
>  tag repos or include a file indicating their business unit origin

or you go to CLA assistant and separate the business units by linking different repos with different CLA files, both sounds to me like a comparable amount of work.

Please, don't understand me wrong. If you want to go forward with your idea and implement it you can still count on our support. We will help you as much as possible by guiding you through the code or pointing you to the right places in the codebase.

**Comment by vbasem** [comment]
Perhaps I didnt mention that there are templates for different BUs and github actions that take care of adding required tags/copyright/legal footers.

> Please, don't understand me wrong. If you want to go forward with your idea and implement it you can still count on our support. We will help you as much as possible by guiding you through the code or pointing you to the right places in the codebase.

thanks @KharitonOff , much appreciated.

Still trying to see if we can simplify the process, and if I cant succeed, I will definitely  take you up on your offer.

Thank you, I guess this issue can be closed.
