### ISSUE TITLE
Small issues in ToU / legal.md

### ISSUE THREAD

**Issue by silverhook** [cla-assistant/cla-assistant#588]
URL to the linked Repo/Org: https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30

Steps to reproduce the problem:

1. read the ToU
2. notice a few typos and inconsistencies

What is the expected result?

No typos and inconsistencies :)

What happens instead?

A few typos and inconsistencies ;)

- § 9, sentence 3 – `s/qthat/that/`
- § 12 mentions “deleting Your profile”, while not mentioning a profile anywhere else – everywhere else there is only talk about “your account”
- § 16 – title should be in CAPS with a trailing newline, to be consistent with the rest of the document’s styling
- app. A, under _Who are the recepients of your Personal Data […]_, bullet point 3, the first sentence is missing a dot at the end – `s/and investigations/and investigations./`

**Comment by KharitonOff** [comment]
Thank you very much for your feedback!
