### ISSUE TITLE
Says I signed it successfully but isn't recognized on my pull request as being signed.

### ISSUE THREAD

**Issue by petre247** [cla-assistant/cla-assistant#593]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Go to https://github.com/connamara/quickfixn/pull/625 and click on details next to sign license/cla
2.Press sign at the bottom
3.

What is the expected result?
Should remove that I still need to sign the license from my pull request

What happens instead?
Does not recognize that I signed the document and still says it is pending

![image](https://user-images.githubusercontent.com/37818784/86544290-4dcb9100-beeb-11ea-89c9-c629d16f45a5.png)
![image](https://user-images.githubusercontent.com/37818784/86544296-5ae88000-beeb-11ea-8a74-2edcd5041559.png)

**Comment by KharitonOff** [comment]
Probably you had to add the email address, which you have used for your commit. It looks, like you've done it already. I've clicked "recheck CLA" in the comment and now everything looks good 👍
