### ISSUE TITLE
bors-ng compatibility?

### ISSUE THREAD

**Issue by adaszko** [cla-assistant/cla-assistant#595]
Hi!

I've been trying to set up cla-assistant to work with [bors-ng](https://github.com/bors-ng/bors-ng/) and it times out.  The problem lies in specifying the exact GitHub job name for bors to wait on.  Is it `license/cla`, `cla`?  None of these work.  Any other names I can try?

## Required

URL to the linked Repo/Org: https://github.com/sigp/lighthouse/pull/1341

Steps to reproduce the problem:

1. Comment `bors try` on a pull request that has `status = [..., "license/cla"]` in `bors.toml`

What is the expected result?

Bors succeeds like at https://github.com/sigp/lighthouse/pull/1341#issuecomment-654791725

What happens instead?

Bors times out like at https://github.com/sigp/lighthouse/pull/1341#issuecomment-654721588

## Optional

Other checks pass, so the other job names should be correct.

**Comment by KharitonOff** [comment]
Is this question related to https://github.com/cla-assistant/github-action ?

**Comment by adaszko** [comment]
Leaving the solution here for the record:

Thanks to @michaelsproul's help, the timeouts were fixed by moving `"license/cla"` from `status` to `pr_status` in `bors.toml`, because `"license/cla"` turns out to be a GitHub "check" that's pull request-specific, not branch-specific.
