### ISSUE TITLE
I have signed the CLA, but the tag keeps "not signed yet" 

### ISSUE THREAD

**Issue by runningdata** [cla-assistant/cla-assistant#596]
https://cla-assistant.io/wechaty/wechaty.github.io?pullRequest=323 

Why?

**Comment by KharitonOff** [comment]
Because @WillCup committed to this PR and you sign CLA as @runningdata

**Comment by runningdata** [comment]
> Because @WillCup committed to this PR and you sign CLA as @runningdata

Yes. My fault.
