### ISSUE TITLE
"Sign in" broken on cla-assistant.io 

### ISSUE THREAD

**Issue by DenisGorbachev** [cla-assistant/cla-assistant#60]
Hey, first off, thanks for the service — that's exactly what I need!

However, here's what happens when you click "Sign in":
![sign-in](https://cloud.githubusercontent.com/assets/829578/8616610/6cdebc80-2705-11e5-805e-7c6173e80d46.png)

I have removed the "?admin=true", and signed in, but was greeted with a blank page: 
![empty](https://cloud.githubusercontent.com/assets/829578/8616638/97bbc196-2705-11e5-93ca-bc6e77856b07.png)

Could you please fix it? Thanks in advance!

**Comment by KharitonOff** [comment]
Hi Denis, 
thank you very much for reporting the issue!
The Problem should be solved now.

**Comment by DenisGorbachev** [comment]
@KharitonOff Thanks you for a quick response! I confirm, the site is working now.
