### ISSUE TITLE
CLA check not present on private repo PRs

### ISSUE THREAD

**Issue by triclambert** [cla-assistant/cla-assistant#600]
**URL to the linked Repo/Org:**  `opstrace/opstrace`

**What is the expected result?**

I expect to see the CLA check on a PR.  I expect to be able to block PRs without that check.

**What happens instead?**

I have our org wired up to CLA Assistant, and the webhook is working.  However, the checks do not show up on the PR.  

There are a couple of other issues that may address this issue, but it's not 100% clear to me that they do.  Hoping someone can give me some pointers here to get things working fully.

**Comment by ibakshay** [comment]
Hi @triclambert, thank you for reaching out to us. 
Is `opstrace` a public repository?

**Comment by triclambert** [comment]
Ah gotcha.  I must have missed that in the documentation.  We do plan to open this in the not-too-distant future, so I'll revisit CLA Assistant then.  Thanks.
