### ISSUE TITLE
Bug: lost list of allowed usernames

### ISSUE THREAD

**Issue by pkfrank** [cla-assistant/cla-assistant#601]
## Required

**URL to the linked Repo/Org**: https://github.com/forem/forem

**Steps to reproduce the problem**:

1. Open CLA-Assistant.io
2. Log in to account
3. Click pencil "Edit" icon

**What is the expected result?**
- List of allowed-list usernames is preserved

**What happens instead?**
- (This just happened, not necessarily a persistent problem)
- The list of allowed-list usernames was blank
- This was blocking PRs due to the CLA check
- After re-adding, it was unblocked

## Optional
Any other information? (attach screenshot if possible)
- This was not a browser issue, as it was verified to be blocking PRs
- This impacted our other repos as well

**Comment by KharitonOff** [comment]
Thank you very much for the issue. This was our fault. The old lists should be back again, if you have recreated the list, then the new version stays in place. We are very sorry for the inconvenience!

**Comment by pkfrank** [comment]
@KharitonOff thanks for confirming.  Things appear to be back to normal now.
