### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by srl295** [cla-assistant/cla-assistant#602]
## Required

URL to the linked Repo/Org: https://cla-assistant.io/accept/unicode-org/cldr?pullRequest=570

Steps to reproduce the problem:

1. go to https://cla-assistant.io/accept/unicode-org/cldr?pullRequest=570
2. Attempt to sign CLA

What is the expected result?

cla gets signed

What happens instead?

```
Service Unavailable                                                                            
```

## Optional

Browser/version:

Chrome mac Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by KharitonOff** [comment]
This url works for me. Why do you have the url with `accept` in it? Have you tried to go to the  https://cla-assistant.io/unicode-org/cldr?pullRequest=570 ?

**Comment by srl295** [comment]
> This url works for me. Why do you have the url with `accept` in it? 

I clicked what the automated github comment said to click. I merely captured the URL that reported "Service Unavailable"

Have you tried to go to the https://cla-assistant.io/unicode-org/cldr?pullRequest=570 ?

I'll try.

**Comment by srl295** [comment]
> This url works for me. Why do you have the url with `accept` in it? Have you tried to go to the https://cla-assistant.io/unicode-org/cldr?pullRequest=570 ?

Clicking that URL gives me the CLA, but when I sign it, it redirects ot https://cla-assistant.io/accept/unicode-org/cldr?pullRequest=570 which times out after a while with Service Unavailable.
