### ISSUE TITLE
license/cla Pending — Contributor License Agreement is not signed yet.

### ISSUE THREAD

**Issue by yeongseon** [cla-assistant/cla-assistant#604]
URL to the linked Repo/Org:
https://github.com/SAP/sqlalchemy-hana/pull/67
I don't know why this license/cla is pending.

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by KharitonOff** [comment]
it is pending because @jarus has also committed to this PR and hasn't accepted the CLA yet. He should accept the CLA as well in order to make the status successful.
