### ISSUE TITLE
Wrong URL in default CLA template

### ISSUE THREAD

**Issue by silverhook** [cla-assistant/cla-assistant#605]
I just took CLA-Assistant for a quick spin on a testing repo of mine, and found a bug in the default CLA template.

URL to the linked Repo/Org: https://cla-assistant.io/silverhook/tutorial-test

Steps to reproduce the problem:

1. set up CLA-Assistant
2. use the default CLA template (i.e. don’t change anything)
3. click on the URL at the bottom of the CLA text

What is the expected result?

It should have opened the following URL (or similar, working one):

http://contributoragreements.org/ca-cla-chooser/?beneficiary-name=&project-name=&project-website=&project-email=&process-url=&project-jurisdiction=&agreement-exclusivity=exclusive&fsfe-compliance=&fsfe-fla=&outbound-option=fsfe&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=

What happens instead?

The link in the default CLA text instead points to a 404 error here:

http://contributoragreements.org/chooser/?beneficiary-name=bce&project-name=dniae&project-website=&project-email=&process-url=&project-jurisdiction=&agreement-exclusivity=exclusive&outbound-option=fsf&outboundlist=&outboundlist-custom=&medialist=____________________&patent-option=Traditional&your-date=&your-name=&your-title=&your-address=&your-patents=&pos=apply&action=

If you need any help on the ContributorAgreement.org side, I’m happy to help, as I’m one of the co-authors of said CLA :smile_cat:

**Comment by KharitonOff** [comment]
Great, than you very much for your help offer! And this is a nice tool for generating a CLA 👍
The issue with the url seems to be in your gist file: https://gist.github.com/silverhook/1b42e716fe0ab0360a07
If you fix it there, the changes will be reflected also in your linked repo 😏

**Comment by silverhook** [comment]
@KharitonOff I did not create any Gist myself …CLA-assistant created this Gist in my stead, it seems. That is why I opened an issue :)

**Comment by KharitonOff** [comment]
@silverhook CLA-assistant doesn't create any gist at all. Nevertheless only you can edit the content of your gist file, so unfortunately we can not help you here further. If you follow the link, I've shared with you before and edit this file everything will be fine. Be aware, that all contributors, who has accepted your CLA will need to do it again on their next contribution. But if you just linked it with your testing repo, this probably shouldn't be a big deal.

**Comment by silverhook** [comment]
Hmm, I tried it again, and while I can find that Gist in the drop-down menu, it did not use it as default.

I’m confused now …I could swear I did not create that Gist that I remember of.

**Comment by KharitonOff** [comment]
You can not do it in CLA assistant. You should change your document on gist.github.com:
 1. go to https://gist.github.com/silverhook/1b42e716fe0ab0360a07
 2. click on the edit button 
![Screen Shot 2020-08-07 at 17 49 23](https://user-images.githubusercontent.com/8480657/89663800-678b3a00-d8d6-11ea-9c9a-51e6acdca266.png)
3. scroll down in the document and replace **all wrong urls** with correct ones (take care, there are more than two, which you see on the screenshot)
![Screen Shot 2020-08-07 at 17 51 34](https://user-images.githubusercontent.com/8480657/89663938-a9b47b80-d8d6-11ea-84e3-331da8c5cde7.png)
4. When done, click "Update public gist"

This should do the trick :) 
BTW. according to github, this document was created in 2015, chances are that you just forgot doing it ;)

**Comment by silverhook** [comment]
> BTW. according to github, this document was created in 2015, chances are that you just forgot doing it ;)

Might be, but that did baffle me quite a bit. I apologise for the false alarm. I’ll close this issue now.
