### ISSUE TITLE
'CLA assistant' page does not have any interactable elements

### ISSUE THREAD

**Issue by rpherbig** [cla-assistant/cla-assistant#607]
URL to the linked Repo/Org: https://github.com/stripe/scala-interview-prep/pull/1

Steps to reproduce the problem:

1. I created a PR: https://github.com/stripe/scala-interview-prep/pull/1
2. The CLAassistant bot posted I needed to sign an agreement
3. I followed the bot's link to https://cla-assistant.io/stripe/scala-interview-prep?pullRequest=1

What is the expected result?

I see some interface with which I can interact

What happens instead?

I only see a page with `Version` and no way to proceed.

## Optional
Any other information? (attach screenshot if possible)

![chrome_vLC8HGE4GE](https://user-images.githubusercontent.com/1181607/89536583-21df4c00-d7c6-11ea-8cba-3cd42a96a684.png)

Browser/version:  Desktop Chrome Version 84.0.4147.89

**Comment by rpherbig** [comment]
I inspected the page with Dev Tools and forced a number of elements to be visible. I at least saw the elements I would expect (`Sign In`, `Sign In With GitHub`, `I Accept`, etc.), but trying to click anything gave me an error.

**Comment by KharitonOff** [comment]
Thanks, for reporting this issue! Can you test it again, please? I suppose the issue was in the configuration on our side... it should be fixed now.

**Comment by rpherbig** [comment]
@KharitonOff it looks like it's working now, thank you
