### ISSUE TITLE
Don't ask repository owners to sign a CLA ?

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#61]
should we differentiate between repository owners and "external" committers?

pro: 
 - there is actually no need to sign a CLA from side of the repository owner(s)
 - teams, which work with pull requests, are not "bothered" about signing CLA

contra: 
 - it is hard to test/validate for newcomers, whether CLA assistant work properly
 - each person have to sign a CLA only once (until it changes) - shouldn't be a big deal for repository owners

**Comment by KharitonOff** [comment]
@thojansen , @mierschp , @yaseminc any thoughts on this?

**Comment by thojansen** [comment]
No, would not change this behaviour. I think any pull request should be checked and even project members can very easily sign the CLA via one click. We cannot assume that every contributor or owner is legally allowed to contribute. Maintaining another list is not easier that just clicking two buttons, so I would opt for sticking with the current flow.
