### ISSUE TITLE
Can we add a second CLA admin to a project who is not an organization owner?

### ISSUE THREAD

**Issue by gbirchmeier** [cla-assistant/cla-assistant#611]
URL to the linked Repo/Org: github.com/connamara/quickfixn

I am the lead maintainer of the QuickFIX/n project, but I am not a github owner/admin of Connamara.

One of the Connamara org owners set up the CLA for QuickFIX/n, but we are unable to figure out how to add a second CLA admin.  Is it possible for him to give me the rights to manage the CLA of connamara/quickfixn without me being an owner of the Connamara org?

**Comment by KharitonOff** [comment]
Unfortunately it is not possible to "give admin rights" to another user because we fully rely on GitHub's user/auth management. We do not have any other way to identify users role other than access GitHub's data. Sorry about it.

**Comment by gbirchmeier** [comment]
Ok, thanks.
