### ISSUE TITLE
[UX] Radio button labels for custom fields are not clickable

### ISSUE THREAD

**Issue by ygra** [cla-assistant/cla-assistant#613]
URL to the linked Repo/Org:

Steps to reproduce the problem:

CLAs with custom fields of enum type show those additional fields as radio buttons. Since the text associated with each radio button is not within a `label` element for the respective `input` element, one has to pixel-hunt the radio button instead of just being able to click on the text.

What is the expected result?

Clicking on the text should activate the radio button, as usual in desktop and properly-written web applications.

What happens instead?

Clicking the text does nothing.

If I had to guess, the following change should make it work, but I can't really test this at the moment, especially whether it's okay from a styling perspective:

```diff
diff --git a/src/client/templates/customField.html b/src/client/templates/customField.html
index afae7bf..ff97579 100644
--- a/src/client/templates/customField.html
+++ b/src/client/templates/customField.html
@@ -20,8 +20,10 @@
 <div ng-if="type.enum" title="{{description}}">
     <label ng-class="{'required': required}" title="{{description}}">{{title || name}}</label>
     <div class="checkbox" ng-repeat="prop in type.enum">
-        <input ng-disabled="!logged || signed" ng-model="value[name]" name="{{name}}" title="{{description}}" type="radio" value="{{prop}}"
+        <label>
+            <input ng-disabled="!logged || signed" ng-model="value[name]" name="{{name}}" title="{{description}}" type="radio" value="{{prop}}"
         /> {{prop}}
+        </label>
     </div>
 </div>
 <div ng-if="type === 'readonly'">
```

Apparently checkboxes are already handled properly.

**Comment by KharitonOff** [comment]
Thank you very much for your proposal! I've changed UI accordingly. With the next release, this change will be available on the running system.
