### ISSUE TITLE
Missing Repos from Configure CLA

### ISSUE THREAD

**Issue by kareem-DA** [cla-assistant/cla-assistant#616]
We are running a private install of CLA assistant.  I upgrade to the latest version last week.  We recently add a new org  in Github.  We would like to add some of the repos from the new org to CLA, but I am not seeing them in drop down list.  I can see the original 2 orgs, but not the new one.  I am owner on the Org, so I should be able to see them, right?

What settings are required in the new org to ensure it shows up in the list?

Steps to reproduce the problem:

1. Setup CLA
2. Login with github cred
3. select Configure CLA
4. select choose a repo

What is the expected result?
Get a list of all repos that I have admin permission
What happens instead?
I get the original 2 orgs, but I don't get my new one.

**Comment by KharitonOff** [comment]
Could you check your GitHub settings as described in this comment, please: [# 176 comment](https://github.com/cla-assistant/cla-assistant/issues/176#issuecomment-259924887)

**Comment by kareem-DA** [comment]
I did see this.  I think that I have this correctly set.  The new org is the last one on the list and is authorized for this application. 

![image](https://user-images.githubusercontent.com/59445682/92744291-5c04b600-f34f-11ea-8ddc-27c9c8e6955a.png)

**Comment by KharitonOff** [comment]
Ok, can you check also the Third-Party Access policy in the settings of your org, please?
![Screen Shot 2020-09-14 at 11 14 54](https://user-images.githubusercontent.com/8480657/93067668-cb461700-f67b-11ea-8a03-8d02c728653e.png)

**Comment by kareem-DA** [comment]
Closing this issue.  Looks like this was stupid user.  Didn't realize that this only pulled in public repos.
