### ISSUE TITLE
UI stopped showing the list of signees

### ISSUE THREAD

**Issue by eyalbe4** [cla-assistant/cla-assistant#618]
We've been using CLA Assistant for a few months already.
I have just noticed that the list of signees is not available in the UI anymore. We use "Shared Gist". We used to be able to export the CSV by clicking on the link under the "Contributors" column. It used to take 2-3 minutes for this link to become visible in the UI though. Now it does not appear even though we wait.

URL to the linked Repo/Org:
https://github.com/jfrog/jfrog-idea-plugin

As I mentioned, we use "Shared Gist", so there are other repos under the same GitHub org which are connected and use the same CLA.

Thanks in advanced for your assistance.

**Comment by eyalbe4** [comment]
We really need your help with this...
Any idea how to resolve this issue?

**Comment by KharitonOff** [comment]
It would be helpful for us if you could send us a screenshot of the problem, you have described and time when the screenshot is made.

**Comment by eyalbe4** [comment]
Sure @kborchers,
See the following two screenshots. They cover the entire screen (I couldn't fir everything into one image).
I took both of them now (12.20.47 GMT +2)
Please let me know if you need addition information.
Thanks!

![image](https://user-images.githubusercontent.com/7830056/93318751-bbfbd080-f817-11ea-91c0-35ae8e69d849.png)
![image](https://user-images.githubusercontent.com/7830056/93318826-d170fa80-f817-11ea-926a-bf77f77f0770.png)

**Comment by kborchers** [comment]
@eyalbe4 I think you meant to mention @KharitonOff 😄

**Comment by eyalbe4** [comment]
Indeed! My apologies @kborchers!
I meant to mention @KharitonOff :)

**Comment by KharitonOff** [comment]
@eyalbe4 unfortunately I do not have a solution for the problem yet...
But looking at your list I think it would make sense for you to link the whole org once instead of linking each repository separately. Are there any reasons not to do so?

**Comment by eyalbe4** [comment]
@KharitonOff - I think we'll do so.
Is this only a UI issue? Can you please retrieve the signees CSV for me?

**Comment by eyalbe4** [comment]
@KharitonOff,
Sorry for nagging about this, but we really need the CSV export. If the UI issue cannot be resolved for now, that's fine, we'll come up with a different approach that does not rely on it, but all we need is to receive the stored CSV export.
I'd rally appreciate your quick assistance with this!

**Comment by eyalbe4** [comment]
@KharitonOff - the issue is resolved! Thanks!!
![image](https://user-images.githubusercontent.com/7830056/93435536-4274e880-f8d2-11ea-9099-bf11ccf1cf0c.png)

**Comment by KharitonOff** [comment]
I am glad, that the issue is resolved for you now, thanks for letting us know. It seems to be a UI issue, I could not find anything in our server logs... I would suggest to link the whole org and import the signatures there. You can easily unlink current repos, the list of signatures doesn't get lost.
