### ISSUE TITLE
Link multiple repos in one flow

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#62]
Although the process of linking a repo doesn't require too much effort it might be helpful to have the possibility to select multiple repos in step `(2) Choose a repository` as you have to select the CLA over and over again when adding a bunch of repos.
An option to pre-select all repos of one Org/User might also be cool when starting to use CLA-assistant and activating all your repositories for it.

What do you think?

**Comment by KharitonOff** [comment]
Good idea!
We should find a better way of linking CLA and repos from the UX perspective:
selecting multiple repos and/or preselecting the CLA (let user select a CLA only once and not on each link action)

**Comment by matz3** [comment]
@KharitonOff I would like to share my feedback (based on https://github.com/cla-assistant/cla-assistant/issues/64#issuecomment-236180650):

The preview-version doesn't really solve this issue like I've described it (linking multiple repos without having to link the whole org).

In case you want to link ALL repos this is fine and even better than my suggestion.

But it might be the case that one wants to only enable it for a bunch of repos or wants to enable it for all repos with some exceptions.
So I could actually think of two different ways to enable this.

1. Replace dropdown with list of checkboxes to select multiple repos (like in my initial description).<br>I think this would come handy in case you would like to enable CLA for quite a number of repos (maybe add a "check all" button) but not for some (e.g. private repos?) and don't want to have CLA active by default for new repos.<br>
  (2) Choose your repositories<br>
  - [x] project-a
  - [ ] project-b
  - [x] project-c

2. In case an organization is linked, provide a way to exclude specific repos. I am not sure if this would be a good solution as in case a repo is created you have to actively opt-out before the first PR is created. Otherwise CLA assistant is already handling it. Maybe even a way to exclude a repo before it is created?

This is nothing I actually really need to have. Just some thoughts and ideas to improve 👍

**Comment by thojansen** [comment]
We tried to keep it simple, so now it is either per org or per repo which also reflects how GitHub sends events. And I will suggest to link the SAP org completly.

**Comment by matz3** [comment]
Exactly. That's what I meant. As I don't really need it I see no reason to add this unless other people would like to have it.

**Comment by thojansen** [comment]
closing this for now and waiting for more requests. v1.4 is released now to production
