### ISSUE TITLE
Web commits from GitHub for accounts with email privacy enabled can't be accepted in CLA-guarded PRs

### ISSUE THREAD

**Issue by cbowns** [cla-assistant/cla-assistant#620]
## URL to the linked Repo/Org:

https://github.com/square/workflow-swift/pull/69

## Steps to reproduce the problem:

1. Enable "email privacy" for your GitHub account: see https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-on-github for more info and background
2. In the GitHub web UI, select any file in a CLA-guarded repo: edit and commit the change.
3. Open a PR for your change.

## What is the expected result?

CLA recognizes me via my GitHub account and if I've signed the CLA, approves the CLA check.

## What happens instead?

"Christopher Bowns", 474+cbowns@users.noreply.github.com, has not, and I can't log into that account to accept it, and so my PR is not mergeable.

## Optional

This is viewable in the commit history for https://github.com/square/workflow-swift/pull/69

"cbowns" authored a commit on my machine under my work email address, but my browser-based edit is from "Christopher Bowns", 474+cbowns@users.noreply.github.com and is being rejected.

**Comment by KharitonOff** [comment]
You seem to have solved this issue on your own by adding the email address to your account :) The only step was missing - to click on the "recheck PR" link in CLA assistant's comment. I close this issue, since your problem seems to be solved now.

**Comment by cbowns** [comment]
I have no idea how I did that, but apparently yes, I did. Was that the issue, that actually my web commit was passing the CLA, but my CLI one wasn't?

**Comment by KharitonOff** [comment]
Yes, GitHub assigns commits coming from CLI based on the email you have setup in your git config. If you have added the email to your GitHub account then GitHub (and CLA assistant accordingly) recognises you as the author of the commit.
