### ISSUE TITLE
Unable to see repo for organization, even though the organization has allowed CLAAssistant

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [cla-assistant/cla-assistant#625]
URL to the linked Repo/Org: https://github.com/Tinder/bazel-diff

Steps to reproduce the problem: 

1. Go to CLA Assistant
2. Log In
3. Attempt to add bazel-diff as a repository 

What is the expected result?

To add bazel-diff

What happens instead?

I cannot see it listed, even thought my organization has allowed access

**Comment by tinder-maxwellelliott** [comment]
<img width="435" alt="Screen Shot 2020-09-25 at 8 27 23 PM" src="https://user-images.githubusercontent.com/56700854/94325672-94baa700-ff6d-11ea-9472-b51d26540c30.png">

**Comment by KharitonOff** [comment]
You are unable to see the repo in CLA assistant because you do not have admin rights for the organization. 
Your problem is similar to #436
