### ISSUE TITLE
CLA assistant not able to validate GitHub account

### ISSUE THREAD

**Issue by samarabbas** [cla-assistant/cla-assistant#626]
URL to the linked Repo/Org: https://github.com/temporalio/java-samples/pull/46

Steps to reproduce the problem:

1.  Here is the [PR](https://github.com/temporalio/java-samples/pull/46) which is stuck on CLA step

What is the expected result?  
CLA check passes as the user has already signed CLA

What happens instead? 
CLA check shows up as not successful

**Comment by KharitonOff** [comment]
Please, read the comment of the cla assistant:

> If you have already a GitHub account, **please add the email address used for this commit to your account**.

This will solve the problem (GitHub can not recognise the committer of the PR)

**Comment by samarabbas** [comment]
Thanks @KharitonOff.  I have notified the user.
