### ISSUE TITLE
Signed CLA and reran checks in PR, but still shows CLA is not signed

### ISSUE THREAD

**Issue by saranyaeu2987** [cla-assistant/cla-assistant#628]
With reference to Link2 of https://github.com/cla-assistant/cla-assistant/issues/567#issuecomment-626237815
I signed CLA certificate and reran PR checks. Still says the certificate is unsigned.

PR - https://github.com/argoproj/argo/pull/4224.
Any suggestions?

**Comment by KharitonOff** [comment]
please add the email address used for this commit to your account. see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by saranyaeu2987** [comment]
@KharitonOff 
It was already added it and reran PR checks. Unsure why it still says the same.

**Comment by KharitonOff** [comment]
@saranyaeu2987 Is this email address "elumalai.saranya@heb.com" stored in your github account? Maybe there is a typo in this address or in your GitHub account? CLA assistant reads only GitHub information, provided via api, if GitHub can not recognise you as committer, the CLA assistant can't do it either.

**Comment by saranyaeu2987** [comment]
@KharitonOff 
elumalai.saranya@heb.com is my professional email id and I accidentally used that email for personal project check. 
Thats why this caused issue. I added elumalai.saranya@heb.com email to github personal account and that resolved this issue. We can close this.
