### ISSUE TITLE
Issue with bot account thats whitelisted but halts PRs

### ISSUE THREAD

**Issue by joshuafernandes** [cla-assistant/cla-assistant#637]
URL to the linked Repo/Org:
https://github.com/ConsenSys/tessera/pull/1175

Steps to reproduce the problem:

1. `quorumbot` is in the list of users that have signed the CLA on the repo 
Any other information? (attach screenshot if possible)
![Screenshot_20201104_202259](https://user-images.githubusercontent.com/3722503/98100551-c0ba3800-1edc-11eb-93e4-2a70afe72a39.png)
2. Raise a PR where quorumbot is a user and merges are halted at the CLA check. Ref https://github.com/ConsenSys/tessera/pull/1175 
3. PR's cannot be merged because the CLA check fails

What is the expected result?
PRs are not halted on the CLA check with qurourmbot (or any other user in the whitelist)

What happens instead?
PRs are halted on the CLA check with qurourmbot

**Comment by KharitonOff** [comment]
@joshuafernandes the PR, which you have linked here seems to be ok. Have you solved this issue on your own or do you still need help?

**Comment by joshuafernandes** [comment]
Looks good now, thankyou
