### ISSUE TITLE
Unclear way to withdraw consent

### ISSUE THREAD

**Issue by NiklasBr** [cla-assistant/cla-assistant#648]
I'm attempting to withdraw/cancel my consent to a repository but I find no way to do so. This use case should be clarified.

**Comment by michael-spengler** [comment]
Hi @NiklasBr. 

Currently this feature is only accessible for repo owners & admins. So we recommend you to raise an issue within the repo for which you signed the CLA asking the owner / admin to terminate your CLA subscription for this repo.

We see that it would be a good feature to have in the CLA also for contributors - however we do no longer invest in enhancing this CLA solution as we recommend the new - GitHub Action based - CLA Handling: 
https://github.com/cla-assistant/github-action#handling-clas-and-dcos-via-github-action-alpha

In case of any difficulties around that feel free to contact us again.

Kind regards
Michael
