### ISSUE TITLE
Write access to Gists?

### ISSUE THREAD

**Issue by ferventcoder** [cla-assistant/cla-assistant#65]
Is this the only way to get read access to gists? 

![image](https://cloud.githubusercontent.com/assets/63502/9443213/75521ec6-4a45-11e5-8518-8122fc17e81b.png)

**Comment by KharitonOff** [comment]
unfortunately there is no read-only access scope for gists (public and secret). So we have to choose between read-only public gists or read and write access to be able to read also "secret" gists.
As there are lot of CLA assistant users, who uses secret gists, we need this permission.

**Comment by matz3** [comment]
What about letting the user decide between public and private like [Huboard](https://huboard.com/login) does?

**Comment by thojansen** [comment]
@matz3 actually this does not make too much sense for gists.. secret gists are visible to anyone having the URL so there is no real distinction for public and private usage. Currently around 50% of our users are using secret gists, so we would also rather not change this.

**Comment by matz3** [comment]
Didn't know that. Makes sense.

**Comment by ferventcoder** [comment]
No worries, answers my question about GitHub permissions, which are sometimes wonky. :)

**Comment by thojansen** [comment]
:+1:

**Comment by samlaf** [comment]
Isn't there a way to pressure github to include read-only access to private gists...? I can't believe it's still in this state after 5 years.
