### ISSUE TITLE
Today `tikv/tikv` recheck and ask for sign CLA when this repo is not using CLA

### ISSUE THREAD

**Issue by zhouqiang-cl** [cla-assistant/cla-assistant#652]
# URL to the linked Repo/Org:
`github.com/tikv/tikv`

# What is the expected result?

The repo `tikv/tikv` is not using cla for a long time, but today it notify all contributors to sign cla, May I know why?

A long time ago, TiKV is using CLA but later using DCO, but we do not disable webhook and not delete from cla-assistant.io.
But today it recheck all the PRs

# What happens instead?

All contributors notify to sign CLA in a not using tikv repo like https://github.com/tikv/tikv/pull/9273#issuecomment-745738220. Is that normal?

**Comment by KharitonOff** [comment]
Probably somebody with admin rights has linked your repository in CLA assistant again. But according to the statuses of the new PRs this is not an issue anymore, correct? Can we close this issue?

**Comment by zhouqiang-cl** [comment]
> Probably somebody with admin rights has linked your repository in CLA assistant again. But according to the statuses of the new PRs this is not an issue anymore, correct? Can we close this issue?

@KharitonOff Thank you for your quick reply.  I ask all admins that no one linked in CLA assistant. Is there are any service incidents today? I am afraid that someone do something bad 😑

Yes. It is not a problem for our repo anymore. Just want to make sure how it happends 

Thank you again, Anton❤️
