### ISSUE TITLE
Signed in cla-assistant.io, not signed in github (pending)

### ISSUE THREAD

**Issue by johnnyrun** [cla-assistant/cla-assistant#659]
URL to the linked Repo/Org:
https://github.com/Comcast/kuberhealthy

Steps to reproduce the problem:

1. open pull request (https://github.com/Comcast/kuberhealthy/pull/784)
2. sign CLA
3. tried to update using "refresh button"
4. tried to update using empty git commit
5. tried to update status using API via curl. I receved "Found. Redirecting to https://github.com"

What is the expected result?
CLA signed on github

What happens instead?
CLA is signed on cla-assistant.io, but status is "Pending"

Browser/version:
chrome 87.0.4280.88-1 linux

**Comment by KharitonOff** [comment]
Sorry for late response. CLA assistant checks signatures of all PR **committers**. This means in your case that @giannicarabelli has to sign the CLA in order to get a green status on your PR.

**Comment by johnnyrun** [comment]
thanks. The *committers* point was not clear to me.
