### ISSUE TITLE
multiple repos, same CLA

### ISSUE THREAD

**Issue by jdanyow** [cla-assistant/cla-assistant#66]
Thanks for your work on this project!

We're evaluating using using CLA assistant with [Aurelia](http://aurelia.io).  Aurelia's design partitions each module in separate GitHub repository.

We would like potential contributers to be prompted to sign the CLA only once for all repos in the [Aurelia github organization](https://github.com/aurelia).  

For example, if I'm a new contributer and create a PR for aurelia/binding, I'm prompted to sign the CLA.  When I later create a PR for aurelia/dependency-injection, I'm not prompted a second time.

cc @EisenbergEffect

**Comment by KharitonOff** [comment]
We had the same requirement from SAP. After some discussion we came to the point that it's clearer for the contributor (and from the legal perspective) to sign a CLA per repository.

**Comment by ejsmith** [comment]
Yeah, I really don't want people to have to sign the CLA a bunch of times. We have several repositories as well. Would love to have this feature.

**Comment by niemyjski** [comment]
I agree with @ejsmith, we could really use this

**Comment by thojansen** [comment]
v1.4 is released now to production with the option to link orgs :shipit: instead of repos. Let us know in case you face any issues.
