### ISSUE TITLE
Unable to  sign CLA

### ISSUE THREAD

**Issue by Alphasaurs** [cla-assistant/cla-assistant#661]
URL to the linked Repo/Org: https://github.com/percona/pmm

Steps to reproduce the problem:

1. Make a pull request to this organization.
2. you will be prompted to sign CLA
3. Sign in with Github to CLA

What is the expected result?
You should have successfully signed the CLA.

What happens instead?
It is not signing the CLA even after signed in with Github

Screenshot attached 
![Screenshot (1331)](https://user-images.githubusercontent.com/50196057/107065782-2df2a780-6803-11eb-9b96-a31727b6d137.png)
![Screenshot (1332)](https://user-images.githubusercontent.com/50196057/107065791-2fbc6b00-6803-11eb-85d7-5d8c7771b87c.png)

Browser/version: chrome and firefox

**Comment by KharitonOff** [comment]
According to your screenshot you have signed the CLA and the system recognises it, stating "You have signed the CLA for percona/pmm"
Also the comment and status of the PR are both green. 
Now you see the second comment, which says, that you haven't sign the CLA. This is a bug. CLA assistant doesn't expect two comments, that's why it updates only the first one.

**Comment by caupolicandiaz** [comment]
I'm having a similar issue with a PR. Like the user in the existing the thread above I get acknowledgment that the CLA has been signed but the comment does not update and continues to indicate that it has not been signed. Unlike the example above there is only one comment regarding the CLA.

**Comment by Shegox** [comment]
@caupolicandiaz can you please link the PR and I can check the logs?

**Comment by caupolicandiaz** [comment]
[https://github.com/Codecademy/docs/pull/133](url)

**Comment by Shegox** [comment]
@caupolicandiaz the problem with your pull request is/was that the commits weren't associated with your GitHub account. 
When we look into the commits (https://github.com/Codecademy/docs/commit/6123b4a82f520d75acabd2e5b8059c6bd510ea01.patch) we can see that they were authored by `Caupolican Diaz <caupolicandiaz@Caupolicans-MacBook-Pro.local>`, which is probably not the email associated with your GitHub account. Therefore CLA-assistant shows that the CLA is not signed. 
You could fix this with ammending your last commit and redoing it with the proper email address: https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by Shegox** [comment]
Hi  @caupolicandiaz, 

I'm going ahead and close this issue for now. If you have open questions, please feel free to let us know through a new issue.

**Comment by james-deee** [comment]
I also am having this issue @Shegox . 

As far as I can tell it's all the same user with the commit and signing the CLA.

https://github.com/grafana/grafana/pull/47290
