### ISSUE TITLE
Can't submit form

### ISSUE THREAD

**Issue by atielking** [cla-assistant/cla-assistant#667]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by ibakshay** [comment]
Could you please send the link of the affected Pull Request ?

**Comment by Shegox** [comment]
Hi @atielking, I'm going a head and close this Issue. If your issue still persists please open a new Issue with a link to the affected pull request. Thanks.
