### ISSUE TITLE
Resign the CLA - Internal Server Error

### ISSUE THREAD

**Issue by bagajjal** [cla-assistant/cla-assistant#672]
Resigning the CLA failed with internal server error.
Please refer to https://github.com/PowerShell/openssh-portable/pull/362

Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/23668037/111364254-3df57680-864e-11eb-92a9-78cb0ed4eb12.png)

- user (yan4321) needs to resign the CLA 
- To be able to resign we first need to terminate the existing signature (per this comment)
- As an admin of the repo, I am trying to use the terminateSignature API, but consistently encountering the internal server error shown below. 
- Expected result: Signature terminated. Actual result: internal server error.

**Comment by bagajjal** [comment]
x-token is my github token.

**Comment by KharitonOff** [comment]
@bagajjal you are calling the API of cla-assistant.io but your signature is on the Microsoft's instance: https://cla.opensource.microsoft.com/ 😏

**Comment by bagajjal** [comment]
@KharitonOff - Thanks for your reply. 

is this right? If yes, why am I getting "Incorrect token credentials"? I have a valid git token passed to x-token.
![image](https://user-images.githubusercontent.com/23668037/111673262-06b2d100-87d8-11eb-80c2-b898692e7716.png)

**Comment by KharitonOff** [comment]
@bagajjal yes, this looks better :) 
Now if we search for the error message, we see that your call lands in the method "authenticateForAdminOnlyApi" (see line 16). I would say, only an admin of the linked repository or organisation can terminate the signature.
https://github.com/cla-assistant/cla-assistant/blob/0dc73fab0a644b397833fa5d7f7d330939c53980/src/server/middleware/authenticated.js#L5-L16

This API like many others was not restricted some time ago. Now we have a strict check to avoid a misuse. I agree that we should leave this api open to everyone, who would like to terminate their own signature. Here we would need a small contribution or maybe someone from our team will find some spare time to improve.  But at the moment it seems to be possible to do the change only with admin rights.

**Comment by bagajjal** [comment]
@KharitonOff - I am an admin for "powershell/openssh-portable" repo. I created a new admin token with all the privileges but I still get the "Incorrect token credentials" error.

![image](https://user-images.githubusercontent.com/23668037/112878322-a431be80-907c-11eb-9efc-9adb671d50ce.png)


![image](https://user-images.githubusercontent.com/23668037/112877756-fde5b900-907b-11eb-9521-5cec051b6e7a.png)

**Comment by KharitonOff** [comment]
@bagajjal I am sorry for confusion here... As I was referring to admin rights, I meant the rights in CLA assistant and not in GitHub. You can check whether you have admin rights in CLA assistant, by accessing https://cla.opensource.microsoft.com/ and following the link "Administrator Sign In". If you land on the view, where you can see your repository or organisation there, then you have admin rights there as well...

**Comment by bagajjal** [comment]
Hi,

I’m confused if I have the admin right in the CLA assistant.
I accessed https://cla.opensource.microsoft.com/. After I sign in with my credentials, I see “PowerShell team” organization.
I click on “Authorize” and then I see Contributor license agreement page.

Does it mean I have admin right in CLA assistant? If yes then why my request to resign CLA fails with “incorrect token credentials”?
If not then is there a way to know who has the admin rights in CLA assistant?
Fyi, my manager tried but there is no luck.

 
![image](https://user-images.githubusercontent.com/23668037/114789929-b6785180-9d38-11eb-9953-cba5b901dfce.png)

![image](https://user-images.githubusercontent.com/23668037/114789943-bd9f5f80-9d38-11eb-865f-d9c12464db78.png)

**Comment by KharitonOff** [comment]
Hi, I am sorry for the confusion but now I am at the end of my expertise with regards to this instance :) It looks to me that you do not have admin rights there...
The point is that this is an instance from Microsoft, they operate it and adjust according to their needs and policies. I am part of SAP and we host another Instance (cla-assistant.io). So all changes and adjustments in the Microsoft's instance besides the "standard" ones are not known to me. 
If you are an employee of Microsoft, you should probably approach your Open Source Office to clarify the issue further.
Sorry that I could not help you here.

**Comment by bagajjal** [comment]
Worked offline with Microsoft opensourceEngineeringSupport team and got it resolved.
