### ISSUE TITLE
I have signed the CLA, but pr tracking says `cla not signed yet`

### ISSUE THREAD

**Issue by aak7912** [cla-assistant/cla-assistant#679]
I have signed the CLA but the error says `aparna_kesarkar seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.` 

The user `aparna_kesarkar` is from another version control service provider. How to I change this commit to my github user? Also I wasn't allowed to create the same user on github since github doesn't allow '_' in usernames. 

<img width="763" alt="Screen Shot 2021-04-22 at 2 35 41 AM" src="https://user-images.githubusercontent.com/74846270/115692030-73f3dd80-a313-11eb-9fa8-9421858592b4.png">

**Comment by KharitonOff** [comment]
There is no need to create a new user. Please, follow the instruction as proposed in the comment and after adding the email address to your account hit the "recheck" link again.

**Comment by Shegox** [comment]
Closing this issue for now, as the problem seems to be addressed. 
@aak7912, if you have further issues please open a new issue.
