### ISSUE TITLE
CLA Assistant 'Sign in with GitHub' Returns 404 Error Page

### ISSUE THREAD

**Issue by celanthe** [cla-assistant/cla-assistant#680]
URL to the linked Repo/Org: https://cla-assistant.io/camunda-community-hub/

Steps to reproduce the problem:

1. Clicked https://cla-assistant.io/camunda-community-hub/
2. Clicked 'Sign in with GitHub to Agree'
3. Received https://cla-assistant.io/404 error page

What is the expected result? Should be taken to GitHub to authorize CLA assistant on multiple repos and complete signing.

What happens instead? I get a 404 error page.

**Comment by KharitonOff** [comment]
There is repository name missing in this url. I know, the url works to some extent, but it shouldn't be the case, you have to put a repo name at the end of the url as well: https://cla-assistant.io/camunda/<repo name>

**Comment by celanthe** [comment]
> There is repository name missing in this url. I know, the url works to some extent, but it shouldn't be the case, you have to put a repo name at the end of the url as well: https://cla-assistant.io/camunda/ `<repo-name>`

I've done this and unfortunately it's still 404-ing out for us :(

**Comment by mrpalide** [comment]
I have same problem.
I get `Service Unavailable` error.

**Comment by KharitonOff** [comment]
Can you provide a specific link, which doesn't work for you, please?

**Comment by celanthe** [comment]
Update: We have resolved this issue for now. I will close this issue!
