### ISSUE TITLE
Unable to accept CLA

### ISSUE THREAD

**Issue by rajkamal-cv** [cla-assistant/cla-assistant#683]
URL to the linked Repo/Org:  https://github.com/rdkcentral/rtRemote
Pull request: https://github.com/rdkcentral/rtRemote/pull/3
Steps to reproduce the problem:

1. Click "CLA not signed" button. 
2. It will navigate to https://cla-assistant.io/rdkcentral/rtRemote?pullRequest=3

What is the expected result?
At the end of the page , Accept checkbox is enabled, and "I Agree" button should be present

What happens instead?
At the end of the page , Accept checkbox is disabled, and "I Agree" button is not present

Any other information? (attach screenshot if possible)
![image](https://user-images.githubusercontent.com/72071311/117123148-4b102580-adb4-11eb-8aff-4cbfc935e9b9.png)
Browser/version: Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by KharitonOff** [comment]
@rajkamal-cv you have already accepted the CLA. Please, read the second part of the comment from CLA assistant in the PR and follow the proposed steps there.

**Comment by rajkamal-cv** [comment]
@KharitonOff , Okay. So the commits are done with the user 'raj'. In the .gitconfig file, it has an invalid email address like <raj@mail.com>. In that case, how do I proceed. Can you please help?

**Comment by KharitonOff** [comment]
Sure, you just add this email to your account. It doesn't matter whether the address is valid or not, GitHub just checks the entries in your account.

**Comment by rajkamal-cv** [comment]
This is the email ID used to commit the changes.

![image](https://user-images.githubusercontent.com/72071311/117135858-2bcdc400-adc5-11eb-90b8-96260daad15a.png)

As you suggested, I added the mail to my github account. But, do I need to verify this mail? Since this is an invalid e-mail ID, I dont think I can get any verification mails from github for this mail ID - raj@mail.com

![image](https://user-images.githubusercontent.com/72071311/117136018-6a637e80-adc5-11eb-88e7-34ec64eeba05.png)

**Comment by KharitonOff** [comment]
Yes, that's ok. Now you just need to hit the small "recheck" link at the end of the CLA assistant comment.

**Comment by rajkamal-cv** [comment]
Thanks a lot !!! It worked.
