### ISSUE TITLE
Guideline to deploy to vercel

### ISSUE THREAD

**Issue by softmarshmallow** [cla-assistant/cla-assistant#687]
Vercel deployment will be nice to have feature. I'm sorry i haven't take a deep look into the code & structure, but it seems like to be able to run with vercel or other easy setup hosting environment.

**Comment by KharitonOff** [comment]
Sounds interesting. Never tried vercel though...

**Comment by Shegox** [comment]
CLA-assistant offers as well a container image (Dockerfile) and with this and a serverless storage backend (like mlab) you can run a quite easy self-hosted setup. 
cla-assistant.io for example runs on Google Cloud Platform Cloud Run (their serverless container runtime) in combination with a hosted mongodb from mlab. 
In my opinion vercel and other platforms are too opinionated for cla-assistant and the generic approach with just requiring as a node app + mongodb (or docker containers) allows people a wide variety of deployments.

I'm going ahead and close this issue for now, if you like you can however feel free to try a vercel deployment out and comment your experience here.
