### ISSUE TITLE
license/cla Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by daohu527** [cla-assistant/cla-assistant#692]
My PR is stuck in license/cla, and I close the PR and reopen a new one, the problem is still.

Could you give me some advice? https://github.com/ApolloAuto/apollo/pull/13803

I have signed the CA certificate before

**Comment by KharitonOff** [comment]
Sorry for late response. The issue seems to be solved... Your PR is merged. Let us know if you still need help.
