### ISSUE TITLE
Audit policy metadata-only rule should include `serviceaccounts/token` resource

### ISSUE THREAD

**Issue by liggitt** [cla-assistant/cla-assistant#694]
The following files reference a metadata-only audit policy in order to prevent logging request/response contents for sensitive resources:

* https://github.com/cla-assistant/cla-assistant/blob/master/.actions/gardener/ansible-playbook/roles/gardener/defaults/audit_policy.yaml

A recent Kubernetes [bugfix](https://github.com/kubernetes/kubernetes/pull/102040) means that audit-logging of subresource requests which previously failed will now log successfully. The `serviceaccounts/token` subresource responds to `TokenRequest` API calls with a newly minted service account token.

The `serviceaccounts/token` resource should also be included in the metadata-only audit policy if credentials are not intended to appear in the audit log:

```yaml
- group: "" # core
  resources: ["secrets", "configmaps", "serviceaccounts/token"]
```

**Comment by Shegox** [comment]
Hi @liggitt, 

thanks a lot for pointing that out. 
We will in an iteration remove the whole kubernetes part of the project. So far as well only some staging services where running it. I'm going ahead and close this and again thanks for pointing this out.
