### ISSUE TITLE
Unable to sign in cla with github

### ISSUE THREAD

**Issue by liuarui** [cla-assistant/cla-assistant#696]
## URL to the linked Repo/Org:
https://github.com/JSFoundation/cla-assistant/issues/23
https://github.com/webpack/webpack-cli/pull/2776

## Steps to reproduce the problem:

1. open https://cla.js.foundation/
2. click `sign in with github`
3. authentication successful

## What is the expected result?
sign in successful

## What happens instead?
can not sign in

**Comment by KharitonOff** [comment]
To accept the CLA there is no need to sign in on the page, you have mentioned. This is only for administrators. You should normally use the link from the CLA assistant's comment or from the status in your PR. Now the PR doesn't received any status for whatever reasons. It looks like something went wrong with the webhooks on GitHub... Maybe you can retrigger the webhook on your pull request by committing to it an insignificant change.

**Comment by liuarui** [comment]
THX, I will try

**Comment by liuarui** [comment]
cla.js.foundation server error , done
