### ISSUE TITLE
CLA Assistant Status is not updated

### ISSUE THREAD

**Issue by MikyungKim** [cla-assistant/cla-assistant#697]
URL to the linked Repo/Org: https://github.com/enactjs/agate

Steps to reproduce the problem:

1. Make a branch
2. Create a commit and push
3. Make a PR (ex. https://github.com/enactjs/agate/pull/602)

What is the expected result? CLA Assistant status should be passed.

What happens instead? CLA Assistant status is not updated and it blocks the merge.

~Other members don't have this issue. I'm wondering what's wrong with my account.~
update: We've found other members have the same problem. Does our repo have an issue?

I've already done https://github.com/cla-assistant/cla-assistant/issues/520#issuecomment-571590565 but it's not resolving the issue.
Please let me know what should I do.
Thank you.

![image](https://user-images.githubusercontent.com/5037429/121975444-973f8400-cdbc-11eb-8ccb-481dd473918b.png)

**Comment by KharitonOff** [comment]
Thanks for your patience @MikyungKim . @ryanjduffy has linked your organisation with CLA assistant. Can you confirm that he still has admin rights on your repository? It looks to me like CLA assistant can not set the status due to outdated/invalid token.

**Comment by ryanjduffy** [comment]
I was re-added to the org and was able to download the contributors and unlink CLA assistant so @MikyungKim + the team should be able to set up CLA assistant again and import the existing contributors if they choose to.

**Comment by MikyungKim** [comment]
Thank you @ryanjduffy and @KharitonOff!
We will follow up soon. I'm closing this issue.
