### ISSUE TITLE
Use separate repo for CLA + list of signees

### ISSUE THREAD

**Issue by stuartpb** [cla-assistant/cla-assistant#70]
As described in [this comment](https://github.com/jonsneyers/FLIF/issues/14#issuecomment-145230848).

**Comment by KharitonOff** [comment]
from my point of view it would make the contribution process more complicated (comparing to few clicks needed to be done in CLA assistant).
And the biggest problem I see here is that the personal information should be stored in a public repository, that could be a reason for some developers not to sign the CLA.
