### ISSUE TITLE
i did sign the CLA and stil lstatus pending

### ISSUE THREAD

**Issue by Lil-Moon** [cla-assistant/cla-assistant#700]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by johanfol** [comment]
Hey @Lil-Moon - do you have the same symptoms as per this issue?
https://github.com/cla-assistant/cla-assistant/issues/701

Have you signed a CLA before, or is it your first time signing?

**Comment by johanfol** [comment]
Furthermore, if either of these is the PR you're referring to, both of them is picking up that it is signed now... 
https://github.com/openmultiplayer/web/pull/357
https://github.com/openmultiplayer/web/pull/356

**Comment by Shegox** [comment]
Hi @Lil-Moon, 

I'm going ahead and close the issue. If you still experience issues, please feel free to open a new issue and include the link to the affected Pull-Request and we can dig into that.
