### ISSUE TITLE
Request to sign CLA from new computer - never succeeds

### ISSUE THREAD

**Issue by johanfol** [cla-assistant/cla-assistant#701]
https://github.com/mojaloop/fraud_risk_management

Steps to reproduce the problem:
1. Sign the CLA
2. Commit and merge code a few times
3. Use a new computer
4. Requested to sign the CLA again - but it doesn't pick up:
![image](https://user-images.githubusercontent.com/36838637/125054691-c6d56980-e0a6-11eb-945c-875daed50ac2.png)

What is the expected result?
1. Not sure why I am requested to sign the CLA again after I have already done so from a different computer. 
2. Upon signing a second time, it must still work. 

What happens instead?
1. No matter how many times I sign the CLA (and clicking "recheck") it doesn't pick up that I have signed it. 

Any other information? (attach screenshot if possible)
1. Related PR: https://github.com/mojaloop/fraud_risk_management/pull/198

Browser/version:
Google Chrome is up to date
Version 91.0.4472.124 (Official Build) (64-bit)

Any other tested browsers/devices(FAIL):
Microsoft Edge
Version 91.0.864.64 (Official build) (64-bit)

**Comment by elnyry-sam-k** [comment]
@johanfol - any chance your other machine is using a different GitHub ID (or isn't configured to use one)?

**Comment by johanfol** [comment]
Same GitHub ID - if you click on my UserID you should see all my previous PR's to the same repository, with this GitHub ID.

**Comment by KharitonOff** [comment]
In the related PR @Messulethe92 is the sole committer of the PR, so this user needs to sign the CLA, not the author of the PR.

**Comment by johanfol** [comment]
Thanks, that was the problem.
