### ISSUE TITLE
Issue Resolved

### ISSUE THREAD

**Issue by aldringames** [cla-assistant/cla-assistant#703]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Valet can use iOS
2. Fish Rod contains forms
3. Kpopian Theme at stable

What is the expected result?

What happens instead?

**Comment by Shegox** [comment]
Hi there, 
it looks like this issue is not related to CLA-assistant. I'm going ahead and closing it. 
Please feel free to open a new issue with further information, if you think we can help you.
