### ISSUE TITLE
CLA disappeared for cockroachdb/cockroach

### ISSUE THREAD

**Issue by bdarnell** [cla-assistant/cla-assistant#71]
The CLA for `cockroachdb/cockroach` no longer appears when I visit cla-assistant.io, and cla-assistant is no longer doing anything on our pull requests (even though we still have the web hook configured for https://cla-assistant.io/github/webhook/cockroach). It looks like this stopped working on or around Oct 1. Any idea what's going on, and whether this can be recovered?

**Comment by bdarnell** [comment]
Not sure if you changed anything, but it's back now.

**Comment by KharitonOff** [comment]
Ok, glad to hear, that it works for you again. Please let us know if you notice any disfunction again.
