### ISSUE TITLE
CLA Commiter's List Not Updated After Rebase/Force Push

### ISSUE THREAD

**Issue by casche** [cla-assistant/cla-assistant#74]
I created a PR with one commit on RN, https://github.com/reviewninja/review.ninja/pull/989. I then noticed that my author details were not set correctly. 

I rebased the branch with the right authors and removed the original commit. Then force pushed to master. 

CLA assistant still lists both commiters :cry:

**Comment by KharitonOff** [comment]
solved.
I'l add a "recheck" functionality in CLA assistant for repo owners soon, so they'll be able to resolve such kind of problems :)
