### ISSUE TITLE
Trying to sign, but there is no agreement and no submit

### ISSUE THREAD

**Issue by TJM** [cla-assistant/cla-assistant#745]
https://cla-assistant.io/puppetlabs/go-pe-client?pullRequest=61

<img width="1152" alt="Screen Shot 2021-09-01 at 1 18 16 PM" src="https://user-images.githubusercontent.com/1641316/131730838-dc698a6a-915d-4221-9a95-df0351b6ab1b.png">

**Comment by Shegox** [comment]
@TJM for me it works (although it takes a second to load the tex).

Can you try opening the browser developer tools and look under "network" if there are any errors? 

Also can you potentially try a different browser/incognito tab to see if that might be a browser side issue?

**Comment by TJM** [comment]
Cool, glad it was able to be reproduced. :)

**Comment by TJM** [comment]
I left it alone, and it eventually shows an error apparently...
<img width="400" alt="Screen Shot 2021-09-01 at 2 11 05 PM" src="https://user-images.githubusercontent.com/1641316/131737829-d9ad3ea0-5729-4a24-816b-8edbb7c82cb0.png">

**Comment by Shegox** [comment]
```
{hostname: localhost, level: 30, msg: Request quota exhausted for request GET /gists/:gist_id, name: cla-assistant.io, pid: 13, src: {…}, v: 0}
{hostname: localhost, level: 30, msg: Retrying after 821 seconds!, name: cla-assistant.io, pid: 13, src: {…}, v: 0}
```

From the request logs it seems that we got quite a bit of requests just now. I assume that in 20min or so when the rate limit resets everything works well again. 

This is a bigger underlaying problem that some of the rate limits can be exhausted by other and  I hope in the next weeks to build something which will completely solve the root issue for that.

**Comment by TJM** [comment]
The initial issue is resolved, @Shegox mentioned that there was a larger issue that was the cause of this one, which may already be resolved. I don't know, as I *rarely* use this tool. I would suggest that it can just be closed.

**Comment by Shegox** [comment]
@TJM thanks for confirming that, indeed I hope that our work towards #430 will solve this permanently, but this is bigger activity.
