### ISSUE TITLE
cla status not reported on PR rebase/merge commit?

### ISSUE THREAD

**Issue by larshp** [cla-assistant/cla-assistant#750]
## URL to the linked Repository or Organization
https://github.com/SAP/abap-file-formats

## Steps to reproduce the problem

1. Create a PR
2. push changes to main branch
3. rebase/merge branch into the PR

Example, https://github.com/SAP/abap-file-formats/pull/206, no status is reported for commit `3cb84acafdacc4468d67c6c034d7cb3398cbff5c`
![image](https://user-images.githubusercontent.com/5888506/131850153-a7de5423-2119-44f9-a2da-4b1a58b01627.png)

Another example: https://github.com/SAP/abap-file-formats/pull/211, status is not reported for commit `b0720ff3ad7f71aeacce158f151d5bf0a801acbf`

![image](https://user-images.githubusercontent.com/5888506/131850434-6caef2e7-75b5-4e3e-a7f6-d65861131ae8.png)

## What is the expected result?
Expect status to be reported for any commits added to a branch/PR, this seems to happen only for merge commits

## What happens instead?
No status reported, giving a yellow status for the PR, signaling that the CI is still running

## Any other information? (attach screenshot if possible)
N/A

## Used browser and browser version?
Chrome 92

## Any other tested browsers/devices(OK/FAIL):
No

FYI @albertmink

**Comment by Shegox** [comment]
Thanks for the report @larshp.

We have some problems with running into rate limits, causing the status not to be reported. 
Either manually triggering the check via (I just did that): 
https://cla-assistant.io/check/SAP/abap-file-formats?pullRequest=206
https://cla-assistant.io/check/SAP/abap-file-formats?pullRequest=211

or pushing a dummy commit should fix this quickly. 

In the long term we have planned to add some more resilience to avoid this.

**Comment by larshp** [comment]
thanks, yea, I did push a dummy commit to https://github.com/SAP/abap-file-formats/pull/211

status for a merge commit was reported in https://github.com/SAP/abap-file-formats/pull/209, so I guess it was just random that the other merged failed 😁 

thanks for the fast feedback, I'll close the issue
