### ISSUE TITLE
Badge for CLA assistant

### ISSUE THREAD

**Issue by benboeser** [cla-assistant/cla-assistant#76]
Would it be helpful to have a badge which indicates how many contributors already signed a CLA?
It shows how big of a community is working on the repo. 

@thojansen @KharitonOff @dfarr - what do you think?

**Comment by thojansen** [comment]
i think something like

![badge](https://img.shields.io/badge/CLAs_signed-137-0594c6.svg) 

would be pretty cool :+1:

**Comment by dfarr** [comment]
:+1:

**Comment by OmgImAlexis** [comment]
:+1:

**Comment by mquandalle** [comment]
I think relying on [shields.io](http://shields.io/) would be a good idea. For instance using @thojansen’s example: https://img.shields.io/badge/CLAs%20signed-137-blue.svg

**Comment by mquandalle** [comment]
Thank you @KharitonOff!
