### ISSUE TITLE
{"meetingURL":"https://usdolevents.webex.com/wbxmjs/joinservice/sites/usdolevents/meeting/download/relaunch/7acf0701939dc328db0edf5cf940a31b","meetingName":"Briefing on the 2014-2018 Equal Employment Opportunity Tabulation Data","meetingSaveTime":1631556624071}

### ISSUE THREAD

**Issue by Mint-6263** [cla-assistant/cla-assistant#769]
## URL to the linked Repository or Organization

https://github.com/
## Steps to reproduce the problem

1.
2.
3.

**Comment by Shegox** [comment]
Hi there, 
this doesn't look like a valid issue therefore I'm going to close it. 
If you have a problem, please make sure to provide sufficient information about how you encounter it. :) 

Many thanks!
