### ISSUE TITLE
CLA status reporting not working

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#77]
It seems that CLA-assistant is not reporting a success status for several PRs in the SAP/openui5 repo:
https://github.com/SAP/openui5/pull/653
https://github.com/SAP/openui5/pull/654
https://github.com/SAP/openui5/pull/655

It just says "Waiting for status to be reported", but on https://cla-assistant.io/ I can see that the CLA has been signed.

The WebHook is active and I already tried to deactivate and activate it again and also to redeliver an event without any success.

Thanks in advance!

**Comment by KharitonOff** [comment]
It is solved now at least for the openui5 repository. The problem was caused by a "wrong" access token stored in our DB.

**Comment by matz3** [comment]
Thanks :+1:

**Comment by c0ze** [comment]
Hello there,

We have a similar issue at iron

https://github.com/iron-io/functions/pull/637

what could be the cause ?

**Comment by crufter** [comment]
I'm having the same https://github.com/1backend/1backend/pull/1

**Comment by KharitonOff** [comment]
@crufter  please add the email address used for this commit to your account as described here: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user
