### ISSUE TITLE
Error: There is no CLA to sign for mochajs/mocha

### ISSUE THREAD

**Issue by juergba** [cla-assistant/cla-assistant#776]
## URL to the linked Repository or Organization
https://github.com/mochajs/mocha

## Steps to reproduce the problem

1. already signed CLA's are not available anymore, e.g. [#4737](https://cla.js.foundation/mochajs/mocha?pullRequest=4737)
![image](https://user-images.githubusercontent.com/44573692/134541150-6beda0e2-8e55-4aaa-8f65-e161b9bfd714.png)

2. in our last PR [#4746](https://github.com/mochajs/mocha/pull/4746) there is no licence/cla at all, neither as a comment nor as a record in the GH actions list.
The CLA has stopped working approx. one week ago.

**Comment by Shegox** [comment]
Hi @juergba, 

it looks like you  have your instance of cla-asssistant deployed `https://cla.js.foundation` and are not using our central instance (cla-assistant.io). Do you by chance know who runs this instance (if not maybe your organization owner knows)? 
Most likely that runs an outdated version and they need to update to a newer version of cla-assistant. 

Infortunately there is nothing which I can do for you here. If there are no hard legal requirements to use your own instance, you are of course more than welcome to use [cla-assistant.io](https://cla-assistant.io).

**Comment by juergba** [comment]
@Shegox thank you for your quick reply.

It suppose it must be run by the OpenJsFoundation with its GH user https://github.com/JSFOwner. They are one of Mocha's owner.

@jorydotcom can you have a look at this, please. I suppose this `https://cla.js.foundation` is run by your foundation?

**Comment by juergba** [comment]
@Shegox thank you for your help.
