### ISSUE TITLE
need to show all signers for any version, not just the last one

### ISSUE THREAD

**Issue by spf13** [cla-assistant/cla-assistant#79]
For the CLA-assistant to be usable it needs to capture and show all contributors and when they signed and for what version of the CLA. As it is currently written any modification to the CLA virtually resets a record of all signers rather than showing the list of users who accepted a CLA for their contributions and what the version of the CLA that they accepted. 

The readme states "You as repository owner can review the list of users who signed your CLA for each version of it." Perhaps there is a way to do it but with the current UI I only see the latest CLA signatures. I went from a list of 141 to 1 after making a small change to the CLA and have no way of getting the list of the previous 141 anymore. 

I'm happy to help with this if I can.

**Comment by KharitonOff** [comment]
Good point! :+1:
We have had this functionality in an older version of CLA assistant, but it was skipped later on by redesign.
Your request is absolutely valid, let's bring it back...

**Comment by KharitonOff** [comment]
@spf13 , could you check the new version, please? Does it work for you as expected?

**Comment by spf13** [comment]
Yes, this works... but it's a bit weird to have to export the list multiple times.. I can see why some may want this, but it would be great to have an export of all signings in one file as well.

**Comment by KharitonOff** [comment]
Ok, I see... Would you expect a list with user name as a unique key or username + gist version as a unique key?

Name | Version
--------|------------
User A | 1
User B | 2
User C | 2

or

Name | Version
--------|------------
User A | 1
User B | 2
User B | 1
User C | 2

**Comment by spf13** [comment]
I think the latter is better. I can filter it on my end if I need to.
