### ISSUE TITLE
Issues when there are more than 100 repositories / gists

### ISSUE THREAD

**Issue by matz3** [cla-assistant/cla-assistant#80]
I am currently not able to see all the activated repositories as there are more than 100 repos available to me on GitHub.
The same applies to linking new repos and I guess also to gists.

I guess the paging feature of the GitHub API needs to be used / enabled to read further entries.

See
https://github.com/cla-assistant/cla-assistant/blob/4bd0ec5095298a7aad7aa5f8fb30f3ed86644648/src/client/controller/home.js#L27-L28

**Comment by KharitonOff** [comment]
thank you very much, for pointing to this. Now it should work fine. Could check it, please?

**Comment by matz3** [comment]
Wow, that was fast!
Works for the repos, thanks! :+1:
