### ISSUE TITLE
Unable to recover list of contributors

### ISSUE THREAD

**Issue by yamashi** [cla-assistant/cla-assistant#812]
## URL to the linked Repository or Organization

https://github.com/tiltedphoques/tiltedonline
## Steps to reproduce the problem

1. Unlink a repo
2. Link it again
3. Website says 0 contributors and downloading gives 0 

## What is the expected result?

Previously signed CLAs show up.

## What happens instead?

Nothing shows up.

Seems related to #444 but they workaround doesn't seem to be working.

**Comment by yamashi** [comment]
For future reference I had to add my username in the gist url.

**Comment by Shegox** [comment]
Thanks for putting the solution in here. I guess this related to #806 and that we treat the "same" gist with different urls (full url vs url without name) as different gists.
