### ISSUE TITLE
CLA Assistant is "fishing" bot due to NO way to resign it from repo

### ISSUE THREAD

**Issue by Symbian9** [cla-assistant/cla-assistant#822]
## URL to the linked Repository or Organization

https://github.com/solvespace/solvespace
## Steps to reproduce the problem

- https://github.com/cla-assistant/cla-assistant/issues/561

## What is the expected result?

- https://github.com/solvespace/solvespace/issues/1098

## What happens instead?

- https://github.com/cla-assistant/cla-assistant/issues/691

## Any other information? (attach screenshot if possible)

I **reported** CLA Assistant *to GitHub Support Team* as "fishing app/bot" due to NOT solving critical bug where GitHub repo owners has no way to resign CLA Assistant Checker from managed repos.

![Screenshot_2022-01-10_11-34-42](https://user-images.githubusercontent.com/13188580/148744413-b596ba7c-0974-43e8-8065-52cf1f9e858f.png)

**Comment by Shegox** [comment]
As noted in https://github.com/solvespace/solvespace/issues/1098#issuecomment-1009065835 and https://github.com/solvespace/solvespace/issues/1098#issuecomment-1008696674 they were able to remove CLA-assistant, which was set up by a former team member through revoking the third-party OAuth Access and removing the webhook.

https://github.com/cla-assistant/cla-assistant/issues/691 seems to be not related in this specific case, as this more about that already posted status/comments aren't removed after disabling CLA-Assistant.
