### ISSUE TITLE
Merging of PRs without signing CLAs

### ISSUE THREAD

**Issue by je-hal** [cla-assistant/cla-assistant#824]
Is there a way to enforce that pull requests cannot be merged if there are still contributors who haven't signed the CLA?

Lately, one of our colleagues merged a pull request before the CLA was signed by an external contributor by mistake. The colleague does not have an admin role, so I would have assumed that merging is not possible without a signed CLA. 

## URL to the linked Repository or Organization

https://github.com/SAP-docs/btp-cloud-platform/pull/27

## Any other information? (attach screenshot if possible)

![image](https://user-images.githubusercontent.com/34343894/150354343-c3910c69-a2ea-4245-b0b9-aa62522a8355.png)

**Comment by Shegox** [comment]
Hi @je-hal, 

there is an option for this called "required status checks". 
You will need to create branch protection rule and then set `license/cla` as a required status check. 
The GitHub docs on "[Creating a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)" can walk you through it.

**Comment by je-hal** [comment]
Hi @Shegox,

thank you - however, we have a machine user [ditaccms-bot](https://github.com/ditaccms-bot) that needs to push to the main branch directly according to our workflow (for the next documentation update). 

I assume if we enable the branch protection rule as you describe above our workflow would fail, because the bot hasn't signed the CLA yet. Any ideas how the bot could sign the CLA? 😄
We could open a dummy PR in all repos to do that, but I was wondering if there is a better way...

**Comment by Shegox** [comment]
When you enable the branch protection rule, each commit needs to be checked before it can be pushed to the matching branch. So even if you sign the CLA as the bot (or better exclude it in the CLA-Assistant settings) you will need to first open a PR, let the check run and can merge it. 
![image](https://user-images.githubusercontent.com/16856448/150757548-76c81cc6-cc94-448e-bdde-cae0b501c7c1.png)


If your bot has admin permission on the repository (and your users don't) you can disable "Include administrators" for your branch protection rule to allow the bot user to bypass the checks, while enforcing it for your colleagues/PR reviewers. 
![image](https://user-images.githubusercontent.com/16856448/150757631-3c047263-cc07-4116-bc76-af264794de10.png)

**Comment by je-hal** [comment]
Thanks - I think the GitHub documentation is not 100% clear about whether a PR is needed or not:
![image](https://user-images.githubusercontent.com/34343894/150939770-00c65ddb-6b77-4605-87fe-9424a00425e9.png)

Since there is a separate rule to require pull requests (_Require a pull request before merging_), I still would have hope that the bot doesn't need to open a PR during the workflow execution if we enable the check. 

Anyway - could you point me to information about the "CLA settings"? I checked the README file in this repo. We don't run our own CLA instance.

**Comment by Shegox** [comment]
Depending if you have the CLA configured on organization or repository level, you need either repository admin or organization owner and then can login to https://cla-assistant.io and then use the three dots to exclude users/bots from signing the CLA.

**Comment by Shegox** [comment]
I'm going ahead to close this issue as Jens and I followed up via mail on this.
