### ISSUE TITLE
No longer able to call api/cla/getAll to backup website data

### ISSUE THREAD

**Issue by enzbang** [cla-assistant/cla-assistant#825]
Hello,

We started using cla-assistant 5 years ago and this has been a very useful tool for us. Thank you for providing such a tool to the community!

We have been performing backups of all registered contributors by following instructions given at
https://github.com/cla-assistant/cla-assistant/issues/166#issuecomment-256642858

This is unfortunately no longer working (we get an "Unauthorized" answer). Can you point us to an alternative method if one exists?

Thank you

**Comment by Shegox** [comment]
I will take a look on why that happens. 
Do you try to get the contributors for a single repository or a for a full organization?
In the meantime can you please try doing a manual curl request and enable response headers (e.g. with `curl -v`)? In there should be some trace identifier, please share that with me. With this I can cross check more easily our logs.

**Comment by enzbang** [comment]
We get the list of contributors for a single repository.

The trace is 'x-cloud-trace-context': 'f12ae8d20ab99c6125e7b5bd3a118768/4618082281102965823;o=1'

Thank you for your help!

**Comment by Shegox** [comment]
@enzbang thanks a lot. I found the problem, this is indeed an issue on our side and I got a fix ready (#826). 
Probably I can deploy that on Monday/starting of next week to cla-assistant.io. 

Out of curiosity, did the problem just started to occur or do you have a rough timeframe when it started? I'm asking because I think I actually broke that part as part of some refactoring a couple of months back already.

**Comment by enzbang** [comment]
That's a few months ago, it was reported internally mid November. Given that we had many ongoing changes on our side, I wanted to double check before reporting. Next time I'll try to report such issue sooner.

**Comment by Shegox** [comment]
Okay perfect, if you need them now, you should be able to still download them via the UI.

**Comment by Shegox** [comment]
@enzbang patch is now live and the API should be working again. 
Thanks again for the report!

**Comment by enzbang** [comment]
I confirm this is working as expected. Thank you!
