### ISSUE TITLE
Link Based CLA Signing

### ISSUE THREAD

**Issue by bkerensa** [cla-assistant/cla-assistant#83]
It would be nice if there was someway to link to a CLA in our contributing.md instead of notifying people upon PR. The use case for this would be getting previous contributors to sign the CLA and CLA Hub actually does this.

so something like https://cla-assistant.io/cla/[githuborg/reponame] could be the URL and then projects could link to the CLA on their websites or contributing.md's etc

This would be super useful!

**Comment by KharitonOff** [comment]
This is already given: `https://cla-assistant.io/<githubOrg>/<githubRepo>` is the pattern e.g.:
https://cla-assistant.io/cla-assistant/cla-assistant
