### ISSUE TITLE
GitHub API connection seems broken

### ISSUE THREAD

**Issue by teozkr** [cla-assistant/cla-assistant#830]
## URL to the linked Repository or Organization
https://github.com/stackabletech

## Steps to reproduce the problem

1. Open a new PR in a @stackabletech repository (for example: https://github.com/stackabletech/operator-rs/pull/300 or https://github.com/stackabletech/regorule-operator/pull/181)
2. Note that no CLA status is applied to the PR
3. Go to the dashboard (https://cla-assistant.io/)
4. Log in to the dashboard
5. Request PR rechecks

## What is the expected result?

Ideally, the status should be applied automatically (as it is normally). Failing that, the backup workflow should pick back up and set the statuses afterwards.

## What happens instead?

The status is never applied, even when requested manually.

## Any other information? (attach screenshot if possible)

The GitHub webhook times out for what looks like any hooks with `action` set to `opened`, `reopened`, or `synchronize`.

The login to the dashboard gets stuck for minutes loading the OAuth callback (`https://cla-assistant.io/auth/github/callback?code=[snip]`). After that eventually goes through, the same happens for https://cla-assistant.io/api/org/getGHOrgsForUser.

The recheck API endpoint itself (https://cla-assistant.io/api/cla/validateOrgPullRequests) returns 200 pretty much immediately, but I'm assuming that it just adds it to a queue somewhere?

Curiously, both https://cla-assistant.io/api/github/call and https://cla-assistant.io/api/repo/getAll also succeed nearly instantly.

https://cla-assistant.io/api/cla/get also took a bit over a minute to load (guessing this is #829, while this issue seems to have started this morning), while https://cla-assistant.io/api/cla/getAll loaded in under a second.

## Used browser and browser version?

Firefox 96.0.2-1 from the Arch Linux repositories.

## Any other tested browsers/devices(OK/FAIL):

**Comment by teozkr** [comment]
Manual dashboard rechecks now seem to work again, but otherwise the site still seems tired, and webhooks are still timing out.

**Comment by teozkr** [comment]
The dashboard is now usable again (if a bit slow), and the webhooks seem to work again (although GH still reports them as timed out). Thanks!

**Comment by Shegox** [comment]
Hi @teozkr, 

thanks for detailed report. I assume this is related to some API rate limits by GitHub and CLA-assistant then slows done the requests. 

The current long-term plan is to move more and more to GitHub Apps (#430) as this should hopefully ease the rate limit problems and make it way more stable.
