### ISSUE TITLE
Already Signed CLA, but stills show cla not signed yet in pull request

### ISSUE THREAD

**Issue by carlisliu** [cla-assistant/cla-assistant#856]
in this pr: https://github.com/alibaba/rax/pull/2307
As a committer, I have already signed cla, but stills show `cla not signed yet ` in the pull request
Re-check it just redirect to this pr.

![image](https://user-images.githubusercontent.com/2157653/160547258-e6046620-8ac3-4ad8-8836-87bd695006d2.png)
After I click the Detail link, shows "You have agreed to the CLA for alibaba/rax"

**Comment by Shegox** [comment]
Hi @carlisliu, 

just to be sure: It seems like the initial PR and commits are done with a different account called @chenjun1011. If that is your account as well, you need to sign it using that account to CLA-Assistant and sign the CLA with that account. Only in that way CLA-Assistant can verify that the creator of the PR as well as the commits agreed to the CLA.

If you no longer have access to that account, you might need to recreate the commits as well as open a new PR using your current account and associated commit email.

**Comment by carlisliu** [comment]
> Hi @carlisliu,
> 
> just to be sure: It seems like the initial PR and commits are done with a different account called @chenjun1011. If that is your account as well, you need to sign it using that account to CLA-Assistant and sign the CLA with that account. Only in that way CLA-Assistant can verify that the creator of the PR as well as the commits agreed to the CLA.
> 
> If you no longer have access to that account, you might need to recreate the commits as well as open a new PR using your current account and associated commit email.
