### ISSUE TITLE
PR check not green although all contributors signed

### ISSUE THREAD

**Issue by jstoiko** [cla-assistant/cla-assistant#86]
It's happening here: https://github.com/brandicted/nefertari/pull/125

We're trying to figure out why - despite the fact that all 3 participants have signed - the CLA check is still not green.

Update: seems like some of the commits attached to the PR have a "co-commiter": https://github.com/brandicted/nefertari/pull/125/commits could that be the reason?

**Comment by KharitonOff** [comment]
there is a function in CLA assistant which rechecks open pull requests and updates their statuses. Could you trigger it please?
![bildschirmfoto 2015-11-26 um 16 31 26](https://cloud.githubusercontent.com/assets/8480657/11426280/382c2be4-945b-11e5-83a4-d331124a5206.png)

ok, but abyssusj and postatum should also sign the cla.
