### ISSUE TITLE
Not possible to specify certificate when using HTTPS protocol?

### ISSUE THREAD

**Issue by zhangyangyu** [cla-assistant/cla-assistant#869]
Just as the title tell. Doesn't find any way to specify certificate  when using HTTPS protocol.

**Comment by Shegox** [comment]
Hi @zhangyangyu, 

the `PROTOCOL` flag is just to indicate the protocol for constructing links. CLA-Assistant currently doesn't handle HTTP*s* on it's own and is relying on a TLS-termination service in front (e.g. something like an nginx, or ingress controller in kubernetes). For cla-assistant.io we e.g. use Google Cloud Platforms Cloud Run (their managed knative) and part of the service is TLS-termination, so our service doesn't have to care about that.

**Comment by zhangyangyu** [comment]
Ahh, just as what I thought. Never mind, not hard to make it possible, just use https lib and add certificate :-)
