### ISSUE TITLE
CLA changed out of the blue => contributors are gone?

### ISSUE THREAD

**Issue by daKmoR** [cla-assistant/cla-assistant#882]
## URL to the linked Repository or Organization

https://github.com/ing-bank/lion

## Issue

For the last 3-4 year? we had a custom CLA and we had ~100 contributors... 

not sure when but I guess sometime in the last few weeks/months/years? it switched the CLA to the default SAP one and most contributers are gone?

Any clue what happened? and why? can we get a list of the "old" contributors?

**Comment by Shegox** [comment]
Quick response: 

I'm currently on vacation without any proper internet access, but should be able to check on this maybe by the end of this week or early next week. Generally we do have backups and I strongly assume that the data is not lost.

**Comment by Shegox** [comment]
Quick response: 

I'm currently on vacation without any proper internet access, but should be able to check on this maybe by the end of this week or early next week. Generally we do have backups and I strongly assume that the data is not lost.

**Comment by Shegox** [comment]
@daKmoR sorry for the long wait. I got something last week and started working today again. 

I checked and I can see that the signatures are still existing, but for whatever reason the CLA currently points to `null`. Looks like it got disabled. 

If you want to recover the status again, following should do the trick: 
1. Go into https://cla-assistant.io and sign in
2. Check if there is already the `lion` repo enabled.
    1. If yes, then click on edit and update the `gist url` to the original gist URL `https://gist.github.com/spockz/e2e991b5d2c3f27087b50199e1acad86`(make sure to use exactly that URL) .
    2. If no, then go to `Configure CLA` for the `lion` repo using the gist url `https://gist.github.com/spockz/e2e991b5d2c3f27087b50199e1acad86` (make sure to use exactly that URL). 
3. Now it should show again and all past signatures should be shown again. 

Please do let me know if that worked for you or if not, where problems occur. Sorry again for the long wait on this.

**Comment by daKmoR** [comment]
sweet 👌

that worked - thxx 🙇‍♂️
