### ISSUE TITLE
when I open the class assistant for https://cla-assistant.io/SAP-samples/sap-iot-samples?pullRequest=13 the drop down for versions is empty

### ISSUE THREAD

**Issue by marcuscbehrens** [cla-assistant/cla-assistant#883]
I cannot continue

**Comment by KharitonOff** [comment]
Hi Marcus, your issue is most probably related to the #866

**Comment by marcuscbehrens** [comment]
Today it showed up (in safari on Mac) after waiting a few seconds. Yesterday it did not work even after 30 seconds with no wait indicator.
