### ISSUE TITLE
Sprite can't be written in relative path("sprite": "css/sprite").

### ISSUE THREAD

**Issue by zjp369** [cla-assistant/cla-assistant#884]
Sprite can't be written in relative path("sprite": "css/sprite").

**Comment by Shegox** [comment]
Hi @zjp369, 

it seems that you opened the issue in the wrong project. I assume you wanted to open this in a different repository? 

If this indeed related to CLA-assistant, please do open a new issue and include information where exactly you encounter this issue. Thanks a lot.
