### ISSUE TITLE
option to disable the comment on PRs when the author has signed already

### ISSUE THREAD

**Issue by fommil** [cla-assistant/cla-assistant#91]
It looks like we always get a comment on our PRs, is that right? According to the documentation:

* Comments on *each* opened pull request to ask the contributor to sign the CLA

Is it possible to **not** comment on a PR if the contributor has already signed it? It could get rather noisy and annoying (many people get emailed with comments on PRs).

BTW, I'm talking at http://scalasphere.org next month about licenses and CLAs, so I'm hoping to get this setup on all our ensime repositories as an example to the community, thank you for making this a gratis service and for releasing the sources under a free software license!

**Comment by mquandalle** [comment]
In my experience users that previously signed the CLA don’t receive the cla-assistant comment on further PRs. One of such example: https://github.com/wekan/wekan/pull/458

**Comment by fommil** [comment]
OK cool! I must have not signed it for the test repo. We have many projects and I could easily have lost count.
