### ISSUE TITLE
Retroactively requiring users to sign CLA?

### ISSUE THREAD

**Issue by opcfoundation-org** [cla-assistant/cla-assistant#93]
Hello,
First, this is a GREAT tool!
I have just incorporated cla-assistant to an already-live repository which has pending pull-requests.
In my testing I can see how new pull requests trigger the cla-assist.
I have several pending pull requests; how can I associate those to a cla-assist so those users sign the CLA?
Thank you.

**Comment by thojansen** [comment]
Yes, this is possible. In the list of linked repositories you can **Recheck PRs**.

![screen shot 2016-01-21 at 09 20 45](https://cloud.githubusercontent.com/assets/5912220/12475142/0875b6f8-c021-11e5-95ed-f8308eee47c9.png)

![screen shot 2016-01-21 at 09 29 27](https://cloud.githubusercontent.com/assets/5912220/12475198/7e6df0aa-c021-11e5-8ecb-d229f82abeb7.png)

**Comment by opcfoundation-org** [comment]
Ah, yes you can. Thank you for that tip; most helpful.
There is one very minor issue... when clicking the "..." button the 2 buttons do not fully display, for me, the "Recheck" button actually says "Rech". It seems to be because of the magnification setting of Firefox.
I agree this issue is resolved. Thank you.

**Comment by thojansen** [comment]
agreed.. i have created a separate issue for that .. #94
