### ISSUE TITLE
I have signed the CLA already but the github status is still pending

### ISSUE THREAD

**Issue by Kway99** [cla-assistant/cla-assistant#942]
## URL to the linked Repository or Organization
https://github.com/TheThingsNetwork/lorawan-devices/pull/552
## Steps to reproduce the problem

1.I have signed the CLA already but the github status is still pending
## What is the expected result?
The status gets updated.
## What happens instead?
The CLA status is not updated

## Any other information? (attach screenshot if possible)
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/108512334/203005121-a2734057-388e-45d5-a146-c038f41c8d13.png">
<img width="923" alt="image" src="https://user-images.githubusercontent.com/108512334/202959001-0a8bb8bf-f489-4aa4-af4b-c4b6595f9842.png">

**Comment by KharitonOff** [comment]
Hi @Kway99 , 
you have made a commit in this PR with an email address, that is not assigned to your GH account. See https://api.github.com/repos/TheThingsNetwork/lorawan-devices/pulls/552/commits
To fix the issue, please follow the description on how to [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by Kway99** [comment]
> Hi @Kway99 , you have made a commit in this PR with an email address, that is not assigned to your GH account. See https://api.github.com/repos/TheThingsNetwork/lorawan-devices/pulls/552/commits To fix the issue, please follow the description on how to [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Really Thanks for your reply,

But I have set a email address to my account :kewei.li@seeed.cc. And my local git configuration email is also this one.
They are consistent.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/108512334/203208988-180c4b91-b04e-424c-926c-ee85d25f1089.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/108512334/203209054-e49bb1ad-cd15-4a25-8f5d-dd79d1e0cf68.png">

**Comment by KharitonOff** [comment]
@Kway99 I understand, but there is one commit with the following e-mail: "kewei.liseeed.cc@KevinLeedeMacBook-Air.local"
GitHub cannot assign this commit to any account; therefore, the CLA assistant reports a missing signature from one of the committers.

**Comment by Kway99** [comment]
@KharitonOff Thanks for your comments. It helps me a lot. Solved the issue.
