### ISSUE TITLE
CLA Assistant doesn't register agreement correctly

### ISSUE THREAD

**Issue by blueglyph** [cla-assistant/cla-assistant#959]
## URL to the linked Repository or Organization

https://github.com/tldr-pages/tldr/

## Steps to reproduce the problem

1. Read information about contributing to the project: https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md
2. Click on `sign` (1st paragraph of page linked above): https://cla-assistant.io/tldr-pages/tldr
3. Submit pull request: https://github.com/tldr-pages/tldr/pull/9749
4. Verify status

## What is the expected result?

CLA shown as signed.

## What happens instead?

CLA is shown as pending:

![image](https://user-images.githubusercontent.com/31706195/217270915-dfd2d66e-be26-4df2-809c-642b3753df12.png)

## Any other information? (attach screenshot if possible)

I can sign and have signed several times. 
- The first time I sign, I get a page with a button to sign, and after clicking I see a brief message "Thank you blueglyph for signing the CLA!" that redirects to the main repo page.
- If I try shortly after, the `sign` page shows "You have agreed to the CLA for tldr-pages/tldr"
- If I wait long enough (I don't know how long - one day maybe), I can sign again.

The status hasn't been updated since the creation of  the pull request, 8 January 2023 (despite GitHub showing that as "last year"...).

See the PR that I initially created on their repository for this issue: https://github.com/tldr-pages/tldr/issues/9821

## Used browser and browser version?

Chrome, latest version (Version 109.0.5414.120 (Official Build) (64-bit))

**Comment by KharitonOff** [comment]
Thanks for the detailed issue description. The problem here is that you have used your local git user for some commits and neither GitHub nor CLA assistant can recognise to whom do these commits belong, thus the message from CLA assistant:
`redglyph seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).`

CLA assistant requires every committer of the PR to sign the CLA in order to set the status to green/success

**Comment by KharitonOff** [comment]
once you have added the email address of your local git user to your GitHub account, you can hit the "recheck" link at the end of the CLA assistant's comment.

**Comment by blueglyph** [comment]
I see, that's surprising, I thought it would use the account of the GitHub repo the request was coming from.

There's nothing I can do unfortunately, I'm not giving my actual email address for privacy reasons so I'm using "redglyph@localhost" which is a common pattern. This address is not accepted by GitHub when I try to add it in the settings. Maybe I'll change it to another fake address in case I happen to participate to another project using CLA.

Not a big problem in this specific case though, someone has vetoed the modification with a fake request for change, so it has little chance of going further.

**Comment by blueglyph** [comment]
Anyway, thanks for clarifying that to me, @KharitonOff, I see I missed that message from CLA assistant in the pull request.
