### ISSUE TITLE
Transferring repositories to a new organization

### ISSUE THREAD

**Issue by jstoiko** [cla-assistant/cla-assistant#96]
We transferred a bunch of repositories to a new github org that were linked to cla-assistant. Re-linked the repositories but now we lost our signatures. (we're using cla-assistant.io) Any way we can get them back?

**Comment by KharitonOff** [comment]
Thanks for pointing it out. CLA assistant doesn't support repository transfer yet. But it should be for sure implemented. I've done some preparation for that. Could you check the list of signed CLAs in CLA assistant again, please?

**Comment by jstoiko** [comment]
It looks good. Thanks for that!

**Comment by thojansen** [comment]
The workflow is now to add a renamed/ transferred repository again to CLA assistant.
