### ISSUE TITLE
CLA is not requested to be signed

### ISSUE THREAD

**Issue by nklhtv** [cla-assistant/cla-assistant#960]
## URL to the linked Repository or Organization

https://github.com/stremio/stremio-web

## Steps to reproduce the problem

1. Open this PR https://github.com/Stremio/stremio-web/pull/342
2. The user is marked as `First-time contributor`, CLA is not requested to be signed but marked as signed. The username does not appear in the CLA Contributors List.

## What is the expected result?

Request the user to sign the CLA.

## What happens instead?

CLA is marked as signed.

## Used browser and browser version?

unrelated

## Any other tested browsers/devices(OK/FAIL):

unrelated

**Comment by KharitonOff** [comment]
The status of the CLA assistant check states "All CLA requirements met". It looks like you have selected an optional setting that ignores minor changes (e.g. "Minimum Line Number Changes" is set to "5") or maybe the user was exempted from signing the CLA.

**Comment by nklhtv** [comment]
Thank you for the quick response!
