### ISSUE TITLE
Too wide GH API permissions required just to sign a CLA

### ISSUE THREAD

**Issue by dolmen** [cla-assistant/cla-assistant#97]
CLA Assitant requires too wide permissions when I'm using it just to sign a CLA.
For example, why does it want to be able to write to my repos?

**Comment by KharitonOff** [comment]
this question is already answered in https://github.com/cla-assistant/cla-assistant/issues/78
To sign a CLA you access CLA assistant via a specific link `https://cla-assistant.io/<org_or_user>/<repository_name>`

**Comment by dolmen** [comment]
It appears that despistes I arrived on CLA assistant via a such link, the authentication process failed in some way (probably because I have cookies disabled by default for all sites), so I have probably been redirected to the home page where I clicked on the "sign up with GitHub", and that's probably the reason why I have been asked so many perms.

So I think that you track more the users coming using a "sign link", to avoid such failures. Signing a CLA  should either work without cookies (not even session cookies) enabled, or detect the issue (and report to the user) if they are required.

**Comment by jn64** [comment]
This issue still exists. Accessing CLAassistant via a specific link (not homepage), with cookies disabled, appears to work with no indication to the user. The only clue is that the user is confusingly redirected to the homepage and asked for more permissions.

**Comment by Olf0** [comment]
@KharitonOff and @thojansen, [as denoted](https://github.com/cla-assistant/cla-assistant/issues/78#issuecomment-1146954486) closing this was premature.  It enforced users to create duplicate issue reports, see #78, #566 etc.

I suggest to deal with this at issue #566, until it has been fully resolved: I.e., until the [CLA assistant](https://cla-assistant.io/) works properly with cookies disabled in the web-browser.
