### ISSUE TITLE
Support GitHub merge queues

### ISSUE THREAD

**Issue by viceice** [cla-assistant/cla-assistant#972]
We are using the CLA assistant on [renovate](https://github.com/renovatebot/renovate) and had the CLA check as required.
But the check isn't added to the queue, so the queue didn't merge because of the missing check.
We like to have the passing check on merge queue too.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by Shegox** [comment]
Looking at it, it seems that we need to listen on the webhook for `merge_group.checks_requested`: 
```json
{
  "action": "checks_requested",
  "merge_group": {
    "head_sha": "d402f95b1d8796e686cbf2731508c9267ab66c67",
    "head_ref": "refs/heads/gh-readonly-queue/main/pr-2-8379b2aef14df9b97ecca3781a25200530118670",
    "base_sha": "8379b2aef14df9b97ecca3781a25200530118670",
    "base_ref": "refs/heads/main",
    "head_commit": {
      "id": "d402f95b1d8796e686cbf2731508c9267ab66c67",
      "tree_id": "170e487e7f59c4f7062b3d42be05da8f8ea49325",
      "message": "Merge pull request #2 from tobias-something-something/Shegox-patch-2\n\nUpdate README.md",
      "timestamp": "2023-02-15T11:50:16Z",
      "author": {
        "name": "Tobias",
        "email": "github@tobiasgabriel.de"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com"
      }
    }
  },
  ...
```



Some question we need to make our minds up about: 
- Do we actually need to perform a CLA check, or do we just need to green-light the merge_group? Assumption is that you can't enqueue a PR into the merge group if the CLA haven't been signed. So the status is only relevant for the merge_group to merge, but don't actually need to check that everyone signed the CLA (again).
- We currently only listen on `pull_request` events in the webhook and need to adjust that to include `merge_group`. We need to make sure how we can get the webhook events. 


Test repo: https://github.com/tobias-something-something/merge-queue

**Comment by Shegox** [comment]
I run some tests yesterday and indeed if you have the `license/cla` as required status check you can only enqueue the Pull Request into the merge queue after it passed once. 

After the check passed on the pull request level I think it's save to just green light the merge queue from CLA assistant without performing the CLA check again (as the PR couldn't have been enqueued without the CLA being signed and greenlight on the PR level and integrating other PRs or upstream changes doesn't have an affect on the CLA status). 

I would then propose to add a hook to react to `merge_group` webhooks and from CLA-Assistant side immediately add a `success` status with description: `'Dummy status to green light merge group. CLA checks only happen on Pull Requests.'`.

@viceice do you think this is reasonable?

**Comment by viceice** [comment]
yes, that would be enough for us.

**Comment by viceice** [comment]
can you please comment, when this is gone live? so we can make the check mandatory again.

**Comment by Shegox** [comment]
Deployment should be as of _now_ live and I tested it as well in https://github.com/tobias-something-something/merge-queue/commits/main

<img width="823" alt="image" src="https://user-images.githubusercontent.com/16856448/219367589-29990da1-ed63-4735-a87c-7e121ffcf7e8.png">


You need however to change one of these two things: 
- Inside your repository -> settings -> Webhooks -> "The CLA hook" -> make sure to enable "Merge Group" events.

\- or - 

- Enable this GitHub App on your repository (https://github.com/apps/cla-assistant). Then you need to manually delete the hook under repository -> settings -> webhooks -> CLA hook. The advantage of the GitHub App is that it uses the App identity instead of the configured users token for interactions with GitHub. Notice: This will change the username which creates the comments to `cla-assistant[bot]`

**Comment by rarkins** [comment]
We use the app I believe. Haven't needed to edit webhooks directly before (for any app) as I thought GitHub handles that automatically

**Comment by viceice** [comment]
@rarkins can you make the cla mandatory again

**Comment by rarkins** [comment]
Done
