### ISSUE TITLE
Can't sign the CLA

### ISSUE THREAD

**Issue by ELV-Elektronik-AG** [cla-assistant/cla-assistant#987]
Hello,

i tried to sign the CLA for a PR (https://github.com/TheThingsNetwork/lorawan-devices/pull/594) multiple times but it does not work. I set the email address
in the console with git config --global user.email "development@elv.com" before the commit and also checked the commit in the Web Inteface. The output says:

From 41b8666481b2ae535512ba1f6ad172d1195ddc30 Mon Sep 17 00:00:00 2001
From: ELV-Elektronik-AG <development@elv.com>
Date: Wed, 15 Mar 2023 08:58:53 +0100

I also cheked the profile settigs regarding the email address and for me it seems to be correct. Our company wants to keep contributing to the LoRaWAN Device Repository in the
future, so it would be great if anybody has an idea how to solve this.

![image](https://user-images.githubusercontent.com/115455579/228465986-2d7048cd-f3a5-4b7a-8031-c19f9c0a5661.png)

**Comment by KharitonOff** [comment]
Hello,
maybe you can try adding this email to your account as well: "root@EQ3-53792.elv.lan"

**Comment by ELV-Elektronik-AG** [comment]
Hi, also analysed my commit history and the problem is, that the address you mentioned is not a real email address but just the default Username of my machine. Do you think there is a way to change the author without any complex git operations?

**Comment by KharitonOff** [comment]
Even though it is not a real e-mail address, you should be able to add it to your GH account. This is the easiest way to solve the issue.

**Comment by ELV-Elektronik-AG** [comment]
Thanks a lot, it's working
