### ISSUE TITLE
Error There is no CLA to sign for X  (API rate limit exceeded for user ID XYZ.)

### ISSUE THREAD

**Issue by 4pz** [cla-assistant/cla-assistant#988]
Not sure why I'm unable to sign the CLA for my latest PR. How do I get past this rate limit? I haven't done anything.

**Comment by Coder-256** [comment]
This is [thanks to Twitter](https://github.com/twitter/the-algorithm/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)...

**Comment by srl295** [comment]
I'm seeing this again.
