### ISSUE TITLE
Is there a way to give another user access to see who has signed the CLA create links etc.

### ISSUE THREAD

**Issue by dmodoomsirius** [cla-assistant/cla-assistant#99]
I am apart of a org with 2 owners we want to be able to set up the cla-assistant for each repo but have the same amount of access.

**Comment by thojansen** [comment]
All owners can see the list of **linked CLAs** and perform actions (see all signed users per version, export, import, ..). Owners just need to authorise/ log in to CLA assistant at https://cla-assistant.io.
