### ISSUE TITLE
CLA assistant asking me to sign when I've already signed

### ISSUE THREAD

**Issue by Grryum** [cla-assistant/cla-assistant#996]
I tried to sign CLA in my MR https://github.com/zio/zio/pull/8150
I successfully signed it after clicking on link, but nothing happen than.
Also I could not see any signed CLAs, just empty page:

https://cla-assistant.io/my-cla

Could you please help me with this issue?

**Comment by Grryum** [comment]
I tried almost everything - adding and deleting to account all my emails, changing account settings, manually authorizing to CLA assistant - nothing helped.. Could you at least suggest how and where see logs of this check if it possible for me?

**Comment by Grryum** [comment]
Everything seems to be ok:
- correct email and name in commit patch https://github.com/zio/zio/commit/342ff36428de4049590f9568158beb60eeda8b5b.patch
- this email is my primary email
- email is public and available via github api

No ideas at all...

**Comment by Shegox** [comment]
The two commits you created are done from the email `“vlad.ugrum@gmail.com”` including the quotes and the quotes are the problem. This is not a valid email. 

- https://github.com/zio/zio/commit/7e4ee0d5cf2f7a3e9b2bfa29b3323a4e46e22c21.patch
- https://github.com/zio/zio/commit/342ff36428de4049590f9568158beb60eeda8b5b.patch

You need to rewrite the two commits to use your proper email (I assume `vlad.ugrum@gmail.com`) then following commands should fix it locally: 
- `git config --show-scope user.email` determine where it is set (e.g. global/local/system)
- `git config --global user.email vlad.ugrum@gmail.com`: set the email, make sure to use the same flag as you saw previously
- `git config --show-scope user.email` should now show your email without quotes

After fixing the email in your local setup, you need to redo the last two commits and force push the branch.

**Comment by Grryum** [comment]
thank you so much!
